### ISSUE TITLE
Question about Developer Anki

### ISSUE THREAD

**Issue by OcileCollection** [open-spaced-repetition/fsrs4anki#1]
How did you get access to Anki 2.1.55? I can't seem to find a download anywhere.

**Comment by L-M-Sherlock** [comment]
> How did you get access to Anki 2.1.55? I can't seem to find a download anywhere.

Clone the code from the repo of Anki at: https://github.com/ankitects/anki, and build it from source in local.

**Comment by OcileCollection** [comment]
Thanks!
