### ISSUE TITLE
[QUESTION] Is it possible to use this now with PC + IOS?

### ISSUE THREAD

**Issue by Viterkim** [open-spaced-repetition/fsrs4anki#100]
Is it possible to use this with the PC anki beta and the current version of IOS or will scheduling conflicts occur?
IOS does have the custom scheduling box.

Or is it possible to schedule from PC and then do the reviews etc?

**Comment by L-M-Sherlock** [comment]
Of course, you can do the review in phone and sync to PC, then use FSRS4Anki helper to reschedule the review.

**Comment by L-M-Sherlock** [comment]
For detail, please see: https://ankiweb.net/shared/info/759844606

**Comment by Viterkim** [comment]
Wait, so do you need to run this scheduler all the time, or couldn't you run into IOS overwriting the schedule?
Or is the new schedule after a card is reviewed?
Also thanks!

**Comment by L-M-Sherlock** [comment]
Maybe next version of Anki mobile will support the FSRS4Anki. Before its support, you can review cards in iOS and sync them to PC, then use helper to reschedule them.

**Comment by Viterkim** [comment]
So do a reschedule after every review?

**Comment by L-M-Sherlock** [comment]
> So do a reschedule after every review?

I think one time a day is enough.

**Comment by Viterkim** [comment]
Thanks!
Do you still think it's beneficial to use this if you only use "Good" and "Again"? reviewing twice a day, and using learning steps like `1m 3m 6h 10h` -> graduate at 3 days, to brute force the new cards a bit? (or would it be better to let the algorithm work with graduating the card earlier)

**Comment by L-M-Sherlock** [comment]
I don't recommend using long learning steps. I prefer the default steps.

**Comment by Viterkim** [comment]
Cool thanks

**Comment by Viterkim** [comment]
It seems like the IOS version of Anki has been updated with some stuff about the v3 scheduler.
Would it work now? And should you just use the QT6 version in the deck?
Thank you :D

**Comment by L-M-Sherlock** [comment]
Of course, you can use FSRS in iOS AnkiMobile now.

**Comment by Viterkim** [comment]
Great thanks!
