### ISSUE TITLE
[question] FSRS4Anki suggested retention quite low?

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki#101]
I started using FSRS4Anki some time ago, seems to produce better results than standard Anki algorithm, especially in the early learning stages.
I am using Anki mainly for languages learning, so keeping good retention of material over a long period of time is significant factor for me.
For now I used FSRS4Anki with retention set to 0.9. However the optimizer is suggesting me that "the optimal retention to minimize the repetitions for long-term memory consolidation" for my deck is 0.83.
I am little hesitant to lower the target retention as I have a gut feeling, that in such case I will have more cards that I already forgot but are not yet due.
Any opinions on this?

**Comment by L-M-Sherlock** [comment]
It is just a suggestion aiming at minimum repetitions. If you prioritize the retention over the burden, it's no problem to set a higher retention.
