### ISSUE TITLE
[Question] Intervals for new cards

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#103]
Hi. My Anki settings for new cards are default. When I use default scheduler, my intervals for new cards are mostly 1 day. When I use your scheduler, my intervals are mostly 4 day, sometimes 3 and hardly ever 2. I prefer mostly 1 day because they're new cards. Is it any way to change it?

**Comment by L-M-Sherlock** [comment]
To replace the default weights with the following weights:

```javascript
var w = [1, 0, 5, -1, -1, 0.1, 1.5, -0.2, 0.8, 2, -0.2, 0.2, 1];
```

**Comment by kurkasr** [comment]
> To replace the default weights with the following weights:
> 
> ```js
> var w = [1, 0, 5, -1, -1, 0.1, 1.5, -0.2, 0.8, 2, -0.2, 0.2, 1];
> ```

Thanks!

**Comment by kurkasr** [comment]
When I use optimizer, for example, in a month to train my model, will 'var w = [1, 0, 5, -1, -1, 0.1, 1.5, -0.2, 0.8, 2, -0.2, 0.2, 1]' be irrelevant?

**Comment by L-M-Sherlock** [comment]
The optimizer will generate a new set of weights relied on your review logs. You also can modify the weights by yourself. The function of each weight is introduced here: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler
