### ISSUE TITLE
[Feature Request?] Adding a variable to the custom scheduler without interfering with FSRS scheduling

### ISSUE THREAD

**Issue by Ceynou** [open-spaced-repetition/fsrs4anki#105]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
I'm trying to add the following variable so I can change the display of the template depending on the interval of the card.
```js
globalThis.intervalTest = states.current.normal.review.elapsedDays;
```
But then the easy button interval for example, goes from 7 days to 2 days.

**Describe the solution you'd like**
A way to use the card's current interval value in the template without affecting FSRS scheduling.

**Describe alternatives you've considered**
Using additional card fields addon
or every X days, selecting cards with interval > Ydays and bulk filling a field that I will use with conditional replacement

**Additional context**
The point is to review sentence cards until they have a certain interval, let's say the mature interval(21days), then they become vocab cards, this way I can internalize the context and the reviewing time is back to normal(faster) after 21 days.
If you think this is stupid or just less efficient, please tell me, I'll forget about this idea.

**Comment by L-M-Sherlock** [comment]
Could you give me your full code? I can debug it.

**Comment by L-M-Sherlock** [comment]
I guess this line of code is nearly your need.

https://github.com/open-spaced-repetition/fsrs4anki/blob/87e1e24d1930799c06e9bcb73aedf0ec664b7587/fsrs4anki_scheduler.js#L89

You can add a new line below it:

```javascript
globalThis.intervalTest = interval
```

**Comment by Ceynou** [comment]
Yep seems to work thank you!
But is there any reason as to why this variable would affect the new card easy interval? you can close the issue

**Comment by L-M-Sherlock** [comment]
> But is there any reason as to why this variable would affect the new card easy interval?

Maybe you added the code in a wrong place that blocked the scheduler.
