### ISSUE TITLE
[Feature Request] Optimizer: Ignoring "Good" as first learning step if "Again" has been pressed in the same day.

### ISSUE THREAD

**Issue by 1over137** [open-spaced-repetition/fsrs4anki#114]
**Is your feature request related to a problem? Please describe.**
I often use Anki to study new material, such as previously unseen vocabulary in a foreign language. This means that I definitely cannot answer the card when I first see it. However, If I press "Again" in this case, Anki will show me the card again very soon (after a few more cards), which is annoying and increases learning cards too much. Therefore, I often press "Good" instead when encountering these cards when the interval is 10m on the Good button. I think the optimizer misinterprets this action as me already knowing the card, and gives put them far away into the future when they really shouldn't be. I will not do this anymore now that I know it affects the scheduling, but I can't change past review logs easily.
**Describe the solution you'd like**
An option so that, when "Again" is detected on a day, the grading record from that day should be "Again", instead of the first grade. For example, for a new card that I fail to recall on the second learning step, the day's reviews might look like:
`3,1,1,3`. Currently, this will record a `3` in the dataset as the first grade, but it really should be a `1`.

Maybe this point that the first grade is of great importance should be noted on the FAQ.

**Comment by galantra** [comment]
You could change your learning steps from ´1, 10´ to sth. like `10, 30`

**Comment by L-M-Sherlock** [comment]
I guess this case is not very common. So you can modify the code of the optimizer for yourself.

**Comment by 1over137** [comment]
Well, for anyone else that might want this:
replace
```py
df.drop_duplicates(['cid', 'real_days'], keep='first', inplace=True)
```
with
```py
df.sort_values('r', inplace=True, ignore_index=True)
df.drop_duplicates(['cid', 'real_days'], keep='first', inplace=True)
df.sort_values(by=['cid', 'id'], inplace=True, ignore_index=True)
```
