### ISSUE TITLE
Intervals on overdue cards are much shorter than with the vanilla scheduler

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki#115]
### Describe the bug
After a long study break (or after the card had been suspended for a long time), a successful review will yield an interval that is much shorter than expected. In the example below, fsrs4anki resulted in a 2 year interval after I successfully reviewed the card after a 2.5 yrs break.

It seems like fsrs4anki's scheduler doesn't take into account the break at all.

### **To Reproduce**
1. Have a card that is very overdue
2. Review it
3. Open the card's info (Ctrl + Shift + I in the browser)
4. Observe that the latest interval is too short.

### **Expected behavior**
The scheduler should take the true interval of the card (scheduled interval plus overdue days) as the card's interval.

### **Screenshots**
![image](https://user-images.githubusercontent.com/52420923/210355848-e0b3fe82-52c4-4201-a9ad-e38e44b722e1.png)
(The ease value of 386% is from _Auto Ease Factor_.)
I was using my optimized `var w` values when this review was made.

### **Environment**
 - Anki version: Version ⁨2.1.55 (01caec2a)⁩  
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
 - OS: Windows 10 
 - Scheduler version: FSRS4Anki v3.9.6 Scheduler Qt5

### **Additional context**
I observed this on a filtered deck as I was going through some leeches.

The vanilla Anki behavior: https://faqs.ankiweb.net/due-times-after-a-break.html

> This is because Anki considers the actual time the card was unseen, not just the time it was scheduled for. Thus if the card was scheduled for 5 days but you didn’t study for a month, the next interval will be closer to 60 days than 10 days.

**Comment by L-M-Sherlock** [comment]
The scheduler has accounted for overdue days. But it doesn't mean the new interval is larger than the overdue days. You can check it through the following guideline: https://github.com/open-spaced-repetition/fsrs4anki/wiki/How-does-the-scheduler-work%3F

**Comment by L-M-Sherlock** [comment]
Or share me with your collection files. I will check it on my device.

**Comment by galantra** [comment]
Here are a couple of very overdue cards. I renamed the extension from .apkg to .zip so that I can upload it here. 

**[fsrs4anki scheduler overdue.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/10341958/fsrs4anki.scheduler.overdue.zip)**

Please let me know if this was enough to check and hopefully reproduce it.

PS: Take for example card [1552818477569](http://127.0.0.1:53802/_anki/legacyPageData?id=2857698337264#) (Q: North Macedonia A: Skopje).

![image](https://user-images.githubusercontent.com/52420923/210498441-e62adcd9-6f05-4d10-9e9c-8f0b81b50219.png)

This is with the default fsrs4anki_scheduler_qt5.js, no changes made to it.

**Comment by L-M-Sherlock** [comment]
> Shouldn't the last scheduled interval be much larger than 2.87 months?

But the scheduled interval before your break is 7 days. 2.87 month is twelve times as many as 7 days.

**Comment by L-M-Sherlock** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/32575846/210504717-8e381fd9-abdb-4340-835c-506cc63e66b2.png">

Based on the scheduled interval of the card, the last stability is 6.7. The real interval is 884 days. If we don't consider the overdue days, the new stability is 12 days. But FSRS has considered the overdue days, so the new stability is 83 days.

**Comment by L-M-Sherlock** [comment]
> My subjective feeling (as a 5 years SRS user) is that fsrs4anki should weigh overdue days more than it currently does.

It depends on the parameters. FSRS considers the overdue days via retrievability. For details, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler

<img width="926" alt="image" src="https://user-images.githubusercontent.com/32575846/210535204-7f944428-b939-4939-9c41-fe1c546618f8.png">

**Comment by L-M-Sherlock** [comment]
There is an upper limit on SInc. So the new interval would not increase linearly with overdue days.
