### ISSUE TITLE
[Feature Request] Allow configurable fuzz around pre-defined days

### ISSUE THREAD

**Issue by connwork** [open-spaced-repetition/fsrs4anki#117]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
The FSRS scheduler conflicts with many scheduling solutions that implement fuzz over specified days for specified cards (such as eliminating weekend reviews for mature cards, etc).

**Describe the solution you'd like**
A configurable parameter built in for weekends, holidays, etc to allow a reduction (or elimination depending on user parameter/card maturity) of reviews for that day. It would be nice but not necessary to build this into the optimizer as well. 

**Describe alternatives you've considered**
A workaround is to manually every Friday use previous addons (such as the AnKing "weekends and holidays" addon) to reschedule cards, then reschedule again with the FSRS4Anki helper on Monday morning. This is fairly cumbersome, and **I don't think it would work** although I haven't tried.

**Additional context**
You may want to reach out to the AnKing to collaborate on this (I am not affiliated) since they have already done some work here.

Some screenshots of AnKing's current solution
![image](https://user-images.githubusercontent.com/77240181/213517680-cd72cb0c-7b21-49ab-ac57-775ca24faa0b.png)
![image](https://user-images.githubusercontent.com/77240181/213517766-bdd1d2f3-4506-4f4e-9d50-b1cf555e9eac.png)
![image](https://user-images.githubusercontent.com/77240181/213518029-1ad92220-6128-4d8f-97f8-05ed61224217.png)

**Comment by L-M-Sherlock** [comment]
Do you mean that let FSRS4Anki scheduler postpone specified cards in specified days?

**Comment by L-M-Sherlock** [comment]
Could you share the link of AnKing's "weekends and holidays" addon with me? It's interesting to me.

**Comment by connwork** [comment]
> Do you mean that let FSRS4Anki scheduler postpone specified cards in specified days?

Yes, but more like take classes of cards (by age for example) and distribute them a couple of days prior to and a couple of days after the break, so that they don't all bunch up on the day back or the day before the break. If someone was not reviewing over the weekend for example, they would probably have more daily reviews Monday-Friday to maintain the same retention rate while skipping two days from the weekend before and the next weekend. Could build this into the optimizer too I think, though not sure of the benefit there.   

> Could you share the link of AnKing's "weekends and holidays" addon with me? It's interesting to me.

Hmmm, actually on second look, this addon just seems to be a re-scheduler. It doesn't actually change the intervals. In this case, it probably would work to just sync Friday night, but still something I would rather have built into the algo. It's behind a $5 paywall at the ankipalace website. Happy to send over a donation if you think it will help your project. 

Here's the link: https://courses.ankipalace.com/products/anking-membership-bronze-tier/categories/4374320/posts/2153301549

**Comment by L-M-Sherlock** [comment]
> A workaround is to manually every Friday use previous addons (such as the AnKing "weekends and holidays" addon) to reschedule cards, then reschedule again with the FSRS4Anki helper on Monday morning. This is fairly cumbersome, and **I don't think it would work** although I haven't tried.

Could you try it? I do not think it is the responsibility of FSRS to implement this feature. I avoid making FSRS too complicated.

**Comment by connwork** [comment]
I tried it. It does work, but every time I do reviews over the scheduled off day on mobile, I need to reschedule using the helper, then reschedule again using the weekends Addon.

Again, even if it makes it complicated, it would be a huge value add for this to be integrated. If it was, all concerns about the effect of taking a day off on retention would be mitigated, since training the optimizer could account for this. 

This is a problem that has plauged anki since day 1 and you could solve it.

**Comment by connwork** [comment]
> I tried it. It does work, but every time I do reviews over the scheduled off day on mobile, I need to reschedule using the helper, then reschedule again using the weekends Addon.
> 
> Again, even if it makes it complicated, it would be a huge value add for this to be integrated. If it was, all concerns about the effect of taking a day off on retention would be mitigated, since training the optimizer could account for this.
> 
> This is a problem that has plauged anki since day 1 and you could solve it.

Also, it has some strange effects. For example, after I reschedule with this addon and reschedule with the helper, there is some persistence. Very strange.

**Comment by L-M-Sherlock** [comment]
> Also, it has some strange effects. For example, after I reschedule with this addon and reschedule with the helper, there is some persistence. Very strange.

Maybe you need to use the Helper to reschedule before using the Weekend add-on.

**Comment by L-M-Sherlock** [comment]
> Again, even if it makes it complicated, it would be a huge value add for this to be integrated. If it was, all concerns about the effect of taking a day off on retention would be mitigated, since training the optimizer could account for this.

I find that it is infeasible to integrate this feature into Scheduler because Scheduler doesn't know the number of reviews each day. It could only schedule cards to avoid weekends, which could induce backlogs on Mondays.

**Comment by connwork** [comment]
> Maybe you need to use the Helper to reschedule before using the Weekend add-on.

Tried this too, still getting some weird results. Like, when I reschedule via the helper at any time during the weekend, the rescheduling from the weekends addon is still persisting. I need to do this to review non-mature cards on the weekend. 

> I find that it is infeasible to integrate this feature into Scheduler because Scheduler doesn't know the number of reviews each day. It could only schedule cards to avoid weekends, which could induce backlogs on Mondays.

It is totally fine if it doesn't know the number of reviews. You've already implemented a fuzz. All you would have to do is identify if the card is mature, and if it is, use that fuzz to schedule cards **before or after** the weekend. I'm fairly sure this is how the weekend and holidays re-scheduler works. This would obviously increase reviews before and after the break. You could spread it out more evenly by scheduling 1-2 days before and after. There are obviously more sophisticated ways to do this but keeping it simple would be possible as well.

**Comment by L-M-Sherlock** [comment]
I have implemented the load balance. The free weekend is in the plan.
