### ISSUE TITLE
[Feature Request] Combine the Scheduler and Helper into one configurable addon

### ISSUE THREAD

**Issue by connwork** [open-spaced-repetition/fsrs4anki#118]
**Which module is related to your feature request?**
Scheduler, Helper

**Is your feature request related to a problem? Please describe.**
There is a disconnect between the Scheduler and Helper that I've commented on before, and it can be frustrating when they don't line up. A concrete example is when I finish my reviews for the day on mobile, come back to reschedule them with the Helper, and ~30ish reviews are added to my already completed daily count. There are also many features that are not as user friendly in the Scheduler that can be implemented more seamlessly in an addon (specifically referring to using different optimization parameters for different decks where I can't change the note type to include the deck name in the header- such as auto syncing cards/notetypes with Ankihub). 

**Describe the solution you'd like**
A single Anki addon where I can paste in optimization parameters on a per-deck basis, configure other features such as reduced reviews on weekends, etc (See other feature request "Allow configurable fuzz around pre-defined days"), that shows correct intervals when pressing "good", etc but that also auto-reschedules on sync and anki-opening in a consistent way.

**Describe alternatives you've considered**
None

**Additional context**
I know this is a big request, but it is necessary to encourage wide-spread adoption of FSRS4Anki. 

In terms of the difference between Scheduler and Helper algorithms, reviewing other addons and looking at the code, I think it is possible to preserve the more accurate Helper addon that (correct me if I am wrong) schedules intervals based on the whole review history of the card. 

in terms of mobile versions of Anki that may one day support custom scheduling, this addon could push the scheduler to the mobile version when that occurs, and then reschedule on desktop sync using the card's full review history. 

In terms of feasibility questions, I highly recommend you reach out to the AnKing team (I am not affiliated, but I could try to reach out to them if you are interested) and explore the work they have already done around custom scheduling with their "weekends and holidays" addon. I'll repost pictures of their GUI, etc below just as I did in another related feature request. 
![image](https://user-images.githubusercontent.com/77240181/213528021-b0cd228a-151a-4cd7-89d0-5968c040ceb3.png)
![image](https://user-images.githubusercontent.com/77240181/213528056-aee94f34-7946-4473-82c0-d31470daf0c0.png)
![image](https://user-images.githubusercontent.com/77240181/213528080-634af962-7d0a-46fe-abda-ef7f6d84d3da.png)
![image](https://user-images.githubusercontent.com/77240181/213528221-d7bec832-3176-4a23-b087-209ff48c739a.png)

**Comment by L-M-Sherlock** [comment]
I am waiting for support for FSRS4Anki from iOS and Android. The helper add-on will be removed when the scheduler works on all platforms. Because it would be infeasible to implement the scheduler via add-on because it requires the custom scheduling feature.

By the way, does "weekends and holidays" work compatibly with the V3 scheduler?

**Comment by connwork** [comment]
> I am waiting for support for FSRS4Anki from iOS and Android. The helper add-on will be removed when the scheduler works on all platforms. It would be infeasible to implement the scheduler via add-on because it requires the custom scheduling feature.
> 
> By the way, does "weekends and holidays" work compatibly with the V3 scheduler?

It does, but as I mentioned in my other comment, I think it is just a re-scheduler that is set to reschedule on every sync. 



> It would be infeasible to implement the scheduler via add-on because it requires the custom scheduling feature.

Do you have any plans on making the per-deck scheduling more compatible then? Is your plan just to wait until anki implements that feature?

**Comment by galantra** [comment]
> The helper add-on will be removed when the scheduler works on all platforms

I would suggest leaving it on ankiweb, with a [DEPRECATED] tag in title if you don't want to maintain it; because it will still be useful, especially for old vanilla-scheduled cards.

**Comment by connwork** [comment]
> > Do you have any plans on making the per-deck scheduling more compatible then? Is your plan just to wait until anki implements that feature?
> 
> FSRS4Anki's scheduler and helper both have supported per-deck scheduling.

The issue with the scheduler's implementation of per deck scheduling is that it requires a first line deck name call on the individual note type.

Two main issues with this:
1) Updating cards is incredibly hard with edited note types, even more so with ankihub syncing. Without ankihub, updating cards would create duplicates with edited note types instead of updating the card information. With ankihub syncing on a daily basis, it is so far impossible to use your workaround for per-deck scheduling (although I have submitted a request to them to create a workaround that will make your original workaround viable).
2) It isn't user friendly at all. I'm trying to convince all of my colleagues to implement this, but even when I create video showing them exactly how to do it, they're afraid of anything without a gui. 

If I'm not mistaken, when you asked anki web if they were implementing per deck scheduling, they responded with the workaround and didn't really say if they were working on it.

**Comment by L-M-Sherlock** [comment]
> The issue with the scheduler's implementation of per deck scheduling is that it requires a first line deck name call on the individual note type.

It is a suggestion from Dae (the leading developer of Anki). For details, please see: https://forums.ankiweb.net/t/feature-request-set-anki-custom-scheduling-per-deck-option/23315/

I also think it is inconvenient. But I need help from Dae to pass the deck name without modifying the template. But he seems not to want to support it.

**Comment by L-M-Sherlock** [comment]
> I would suggest leaving it on ankiweb, because it will still be useful, especially for old vanilla-scheduled cards. With a [DEPRECATED] tag in title if you don't want to maintain it.

Thanks to your suggestion. I will keep it on ankiweb.

**Comment by connwork** [comment]
> > The issue with the scheduler's implementation of per deck scheduling is that it requires a first line deck name call on the individual note type.
> 
> It is a suggestion from Dae (the leading developer of Anki). For details, please see: https://forums.ankiweb.net/t/feature-request-set-anki-custom-scheduling-per-deck-option/23315/
> 
> I also think it is inconvenient. But I need help from Dae to pass the deck name without modifying the template. But he seems not to want to support it.

I understand this and have read the conversation with Dae when I was looking for a solution. My understanding is that Dae considered the problem resolved with this workaround. I'm presenting two specific and widespread cases where it will not work: updating decks and syncing with ankihub. 

Here is the post I made on the ankihub community asking for their dev team to build a workaround: https://community.ankihub.net/t/implementing-custom-scheduler-fsrs-on-a-per-deck-basis-with-ankihub-syncing/35

However, their current goal system still wouldn't allow the first line of the deck to call the deck name, but I figured it was better than nothing and I might be able to work it out anyway.

**Comment by L-M-Sherlock** [comment]
I appreciate your suggestion. I will close this issue because the latest several discussions are off-topic. I don't have the plan to develop an add-on to modify the schedule. The current implementation based on Anki's custom scheduling is enough and simple. If you want to discuss the deck-specific scheduling, please open a new issue. And it needs support from Dae.

**Comment by connwork** [comment]
> > > The issue with the scheduler's implementation of per deck scheduling is that it requires a first line deck name call on the individual note type.
> > 
> > 
> > It is a suggestion from Dae (the leading developer of Anki). For details, please see: https://forums.ankiweb.net/t/feature-request-set-anki-custom-scheduling-per-deck-option/23315/
> > I also think it is inconvenient. But I need help from Dae to pass the deck name without modifying the template. But he seems not to want to support it.
> 
> I understand this and have read the conversation with Dae when I was looking for a solution. My understanding is that Dae considered the problem resolved with this workaround. I'm presenting two specific and widespread cases where it will not work: updating decks and syncing with ankihub.
> 
> Here is the post I made on the ankihub community asking for their dev team to build a workaround: https://community.ankihub.net/t/implementing-custom-scheduler-fsrs-on-a-per-deck-basis-with-ankihub-syncing/35
> 
> However, their current goal system still wouldn't allow the first line of the deck to call the deck name, but I figured it was better than nothing and I might be able to work it out anyway.

Just wanted to mention that the devs over at Ankihub implemented a fix just so we can run FSRS for ankihub, for anyone reading this in the future. See link in this comment.
