### ISSUE TITLE
[Question] Should the new scheduler act only after leaving learning mode?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#119]
**Describe the bug**
Should the new scheduler act only after leaving learning mode?

I have the following settings for new cards:
![image](https://user-images.githubusercontent.com/42243532/214249166-6d11bd15-e3e3-4bbd-9372-5c4d5ae4a710.png)

If I don't know the card when I read it for the first time, I always mark that I don't know so he can only come back the next day (1d).

In the 1 day return, if I remember the content of the card, I mark "GOOD".

Without using the new scheduler, it returns in a fuzz of 3 days (2, 3 or 4).

But using the new scheduler, ALL cards are returning in 1 day.

Shouldn't it be using the deck settings (3-day fuzz) and only on the next return start using the spacing of the new algorithm?

**Comment by L-M-Sherlock** [comment]
It couldn't. It calculated the initial stability for your first rating. And I don't know why the intervals are all one day. Could your give me the parameters?

**Comment by cjdduarte** [comment]
> It couldn't. It calculated the initial stability for your first rating. And I don't know why the intervals are all one day. Could your give me the parameters?

It shouldn't, because the first "again" leaves the card in learning.

![image](https://user-images.githubusercontent.com/42243532/214395442-e7d3af1d-8f9a-4605-a5df-cefa81374082.png)

**Comment by L-M-Sherlock** [comment]
> It shouldn't, because the first "again" leaves the card in learning.

If all first ratings are "again", the stabilities of all cards are the same.

**Comment by L-M-Sherlock** [comment]
I mean the parameters your FSRS used.

**Comment by cjdduarte** [comment]
> > It shouldn't, because the first "again" leaves the card in learning.
> 
> If all first ratings are "again", the stabilities of all cards are the same.

Do not. I did a test before opening the issues.
After 1 day, when they return, if I click GOOD on all, they return in 1, 2 or 3 days (fuzz).

![image](https://user-images.githubusercontent.com/42243532/214515198-3ea6346a-89e8-4e7a-80a2-900b5a6cf4f4.png)

With fsrs4anki, after 1 day, when they return, if I click GOOD on all cards, they return in 1 day only.

**Comment by L-M-Sherlock** [comment]
> it ignores the graduating interval

Of course, I have mentioned it in FAQ.

Q7: Once FSRS is running, which Anki settings will become irrelevant (in the sense that changing them won't affect scheduling anymore) and which won't?

A7: FSRS only modifies the long-term scheduling. So Learning steps and Relearning steps work as usual. And I recommend using the default Learning steps and Relearning steps. It is best not to set a step of more than one day.

In the latest version of FSRS4Anki, maximum interval,  easy bonus, and hard interval have been supported. You can modify them in fsrs4anki_scheduler.js.

The graduating interval, easy interval, new interval, starting ease, and interval modifier become irrelevant. The requestRetention of FSRS4Anki is equivalent to interval modifier.

**Comment by cjdduarte** [comment]
Where exactly could I change this in the code?

I understood that I must adapt to the way fsrs4anki
 it works because my first answer is conceptual.

But maybe changing some parameter is better.

**Comment by L-M-Sherlock** [comment]
> Where exactly could I change this in the code?
> 
> 
> 
> I understood that I must adapt to the way fsrs4anki
> 
>  it works because my first answer is conceptual.
> 
> 
> 
> But maybe changing some parameter is better.

If you want to change the parameters, please read this page: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler

And you can test your parameters in the optimizer.

**Comment by cjdduarte** [comment]
Tanks. we can close this one.
