### ISSUE TITLE
[Question] How specific should I get with my decks to gain the most benefits from the optimizer? 

### ISSUE THREAD

**Issue by Vitorvlv** [open-spaced-repetition/fsrs4anki#121]
Right now I have one 'Medicine' deck and all my cards go in there, my cards organization workflow uses a lot of tags instead of decks.

My question is, is it good enough to just feed this deck into the optimizer. Or would I get way better values if I sub-divided the Medicine deck into 'Anatomy, Immunology, Physiology...", and then feed each of these into the optimizer and get a value for each?

Is it worth the trouble? Or is the first approach good enough?

**Comment by Ceynou** [comment]
Check the stats, if you have very similar results in all these decks don't bother with optimizing for each subdeck, otherwise do bother
