### ISSUE TITLE
[BUG] Index out of bounds in optimizer

### ISSUE THREAD

**Issue by Blauelf** [open-spaced-repetition/fsrs4anki#123]
**Describe the bug**
Once I reach the "Calculate the optimal retention to minimize the repetitions for long-term memory consolidation.", the next block crashes at the end of execution

**To Reproduce**
1. Load my data
2. Follow all the steps in the notebook

**Expected behavior**
No error message (obviously). Some graph at the end.

**Screenshots**
```
IndexError                                Traceback (most recent call last)
[<ipython-input-13-e7c94e47fd97>](https://localhost:8080/#) in <module>
     58                 forget_s_index = max(stability2index(forget_s), 0)
     59                 recall_repetitions = repetitions_list[d - 1][recall_s_index] + r_repetitions
---> 60                 forget_repetitions = repetitions_list[forget_d - 1][forget_s_index] + f_repetitions
     61                 exp_repetitions = p_recall * recall_repetitions + (1.0 - p_recall) * forget_repetitions
     62                 if exp_repetitions < repetitions_list[d - 1][s_index]:

IndexError: index 801 is out of bounds for axis 0 with size 800
```

**Environment**
 - Anki version: (2.1.56)
 - OS: (Windows)
 - Scheduler version: (v3.9.6 Qt6)
 - Optimizer version: v3.9.10
 - Simulator version: (v3.8.3)

**Additional context**

**Comment by L-M-Sherlock** [comment]
What are the parameters generated by the optimizer for you? I need them to solve related problems.

**Comment by Blauelf** [comment]
Do you mean the `w` vector?
```
var w = [0.826, 1.4373, 4.5608, -0.868, -1.2271, 0.0, 1.7429, -0.1494, 1.0813, 1.6569, -0.5394, 0.9351, 1.1447];
```

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/blob/v3.10.1/fsrs4anki_optimizer.ipynb
