### ISSUE TITLE
[Feature Request] Populate "Due" property on cards

### ISSUE THREAD

**Issue by patrickellis** [open-spaced-repetition/fsrs4anki#125]
**Which module is related to your feature request?**
Scheduler?

**Is your feature request related to a problem? Please describe.**
The due column in the browser isn't populated by any numbers **for new cards**,  is this caused by the fsrs4anki scheduler's behaviour?
It makes it impossible to sort by due for **new** cards that haven't been studied yet. I have many thousands of new cards that I'm trying to place into a sensible order, and it's impossible to reposition these cards without the due number to see their upcoming orders. (If I'm doing something wrong, please do tell me and I'll close this issue)

N.B the initial order is correct, but if I reposition any cards and give them new queue positions they do not update to display in the correct order. 

**Describe the solution you'd like**
Populate the due column for new cards with a number that indicates the order in which they will appear in future, so they can be repositioned before being studied. 

![image](https://user-images.githubusercontent.com/74929696/215287971-c57df4a7-0166-45bb-935b-4d6799afa0e2.png)

**Comment by patrickellis** [comment]
Sanity test: moved all Anki configuration files to a backup folder, re-launched the App to trigger a fresh state of Anki 2.1.55 and enabled the V3 scheduler, the cards produced have "New #1" identifiers in the due column, which makes me think the fsrs algo is responsible

**Comment by L-M-Sherlock** [comment]
FSRS4Anki scheduler doesn't affect new cards if you haven't studied them via FSRS.

**Comment by L-M-Sherlock** [comment]
I found that your question has been solved here: https://forums.ankiweb.net/t/new-cards-have-no-due-date-help-please/26940, So I closed this issue.

**Comment by patrickellis** [comment]
Yep, thanks for your help and apologies for opening a non-fsrs related issue
