### ISSUE TITLE
[BUG] AnkiDroid v3 scheduler and Anki desktop scheduler with FSRS causing different intervals

### ISSUE THREAD

**Issue by connwork** [open-spaced-repetition/fsrs4anki#126]
**Describe the bug**
Intervals on the Ankidroid beta and desktop with FSRS enabled are different and seem to ignore reviews from ankidroid

**To Reproduce**
1. Download beta ankidroid with v3 scheduler
2. Use the fsrs scheduler
3. Complete Anki Cards
4. Review updated intervals and how they differ between desktop and ankidroid

**Expected behavior**
Intervals should be the same between desktop and ankidroid

**Screenshots**
![image](https://user-images.githubusercontent.com/77240181/215309945-4ad25752-cf0f-40e0-ac92-ad03f4aeec06.png)

**Environment**
 - Anki version: 2.1.56
 - OS: Android
 - Scheduler version: Latest

**Additional context**
I saw this issue posted on the Ankihub community page [here](https://community.ankihub.net/t/fsrs-anki-ankidroid-issue-discussion/433), know that you respond very quickly here, and wanted to make you aware ASAP.

**Comment by L-M-Sherlock** [comment]
The beta ankidroid with v3 scheduler doesn't support FSRS.

**Comment by L-M-Sherlock** [comment]
Related issue: https://github.com/ankidroid/Anki-Android/issues/12620

**Comment by L-M-Sherlock** [comment]
I recommend using FSRS4Anki Helper to reschedule those reviews synced from AnkiDroid with FSRS.

FSRS4Anki Helper add-on: https://ankiweb.net/shared/info/759844606
