### ISSUE TITLE
[Feature Request] Disable message

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#129]
How to disable this message? Or change its color?

![Screenshot_2](https://user-images.githubusercontent.com/42243532/215453921-ec040f3d-7b7d-4623-8ec6-fe978af21cb4.png)

**Comment by L-M-Sherlock** [comment]
Remove these codes:

![image](https://user-images.githubusercontent.com/32575846/215455847-d1e8c1ec-96a8-4e98-a84c-9966cfbd575f.png)

**Comment by cjdduarte** [comment]
> Remove these codes:
> 
> ![image](https://user-images.githubusercontent.com/32575846/215455847-d1e8c1ec-96a8-4e98-a84c-9966cfbd575f.png)

Thanks.

I take the opportunity to make a suggestion. Change so that this text appears on the bottom borders and not below the card.

**Comment by cjdduarte** [comment]
SUGESTION

![image](https://user-images.githubusercontent.com/42243532/215461745-4c76a3d6-6267-45c4-8ee3-9480b46772d4.png)

![image](https://user-images.githubusercontent.com/42243532/215461857-df256b06-a96f-4b8a-84f0-1737aff679d2.png)

**Comment by L-M-Sherlock** [comment]
Thanks for suggestion! I will update it in next patch version.
