### ISSUE TITLE
[BUG]scheduler ignores the 'Maximum interval' setting of the deck's options

### ISSUE THREAD

**Issue by MNastri** [open-spaced-repetition/fsrs4anki#131]
I have a deck with cards that I want to appear every six months, so I set the maximum interval of the deck to 180 days. These cards are just interesting quotes/ideas that I like to see from time to time and I generally just press good on those cards.
The cards stopped showing after I started using the scheduler.
I checked what's happened and the scheduler just changed their interval from 6 months to 5, 6 years etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/87741282/216453498-3f9ce41a-cd62-4a2e-a8d7-186f752dea3f.png)

**Environment**
    
    Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-02-01 13:57:51
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['slackers_delight', 0, 'None', '']
    Advanced Browser ['874215009', 2022-09-26T21:28, 'None', '']
    Auto Ease Factor ['1672712021', 2021-03-21T15:11, 'None', mod]
    Autosync 21 ['1726633659', 2019-03-08T20:58, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2023-01-13T00:54, 'None', '']
    Deck name in title 21 ['699175524', 2019-05-31T22:05, 'None', '']
    FSRS4Anki Helper ['759844606', 2023-01-28T03:12, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T14:06, 'None', '']
    Load Balanced Scheduler ['208879074', 2018-10-04T21:06, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T14:45, 'None', '']
    Minimize to tray ['85158043', 2022-04-30T14:57, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T09:05, 'None', '']
    MorphMan for Anki 21 ['900801631', 2023-01-10T17:01, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T04:22, 'None', mod]
    Syntax Highlighting for Code ['1463041493', 2018-10-06T22:31, 'None', '']
    Transfer scheduling data from one card to another ['94685914', 2020-09-18T06:23, 'None', '']
    autoLapseNewInterval  automatically adjust the new interval after a lapse ['372281481', 2022-09-28T04:26, 'None', mod]
    avgEase for Anki  2141 ['1129477042', 2021-06-27T08:58, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1129477042 1436550454 1463041493 1556734708 1672712021 1726633659 1771074083 1781298089 208879074 225180905 295889520 372281481 699175524 759844606 85158043 874215009 900801631 94685914
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Auto Advance automatically show answer  flip card  audio play repeat  speed ['1747534155', 2019-11-22T01:57, 'None', '']
    Incremental Reading v4103 ['935264945', 2019-04-21T09:54, 'None', '']
    load balancer ['1417170896', 2020-08-05T20:58, 'None', '']

thank you in advance

**Comment by L-M-Sherlock** [comment]
You need to set 'Maximum interval' in the scheduler: 

![image](https://user-images.githubusercontent.com/32575846/216490647-3ddf6dda-3ac7-468e-a29f-a50398b169f5.png)

**Comment by MNastri** [comment]
OK. That works, thank you, but shouldn't the addon be able to check and get the decks' configuration automatically?

**Comment by L-M-Sherlock** [comment]
If Anki custom scheduling could give API to get the decks' configuration, I will improve FSRS to get it automatically.
