### ISSUE TITLE
Setting different parameters  for decks

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#133]
I want to set some parameters for some decks. For example, I have 4 decks and 3 sub-decks. Is my code right?

// get the name of the card's deck
// need to add <div id=deck deck_name="{{Deck}}"></div> to your card's front template's first line
if (document.getElementById("deck") !== null) {
  const deck_name = document.getElementById("deck").getAttribute("deck_name");
  // parameters for a specific deck
  if (deck_name == "DECK 1") {
    var w = [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451];
    // User's custom parameters for the specific deck
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
    // parameters for a deck's all sub-decks
  } 
if (deck_name == "DECK 2") {
    var w = [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451];
    // User's custom parameters for the specific deck
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
    // parameters for a deck's all sub-decks
  } 
if (deck_name == "DECK 3") {
    var w = [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451];
    // User's custom parameters for the specific deck
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
    // parameters for a deck's all sub-decks
  } 
if (deck_name == "DECK 4") {
    var w = [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451];
    // User's custom parameters for the specific deck
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
    // parameters for a deck's all sub-decks
  } 
else if (deck_name.startsWith("DECK 5::Archive")) {
    var w = [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517];
    // User's custom parameters for sub-decks
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
  }
else if (deck_name.startsWith("DECK 6::Archive")) {
    var w = [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517];
    // User's custom parameters for sub-decks
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
  }
else if (deck_name.startsWith("DECK 7::Archive")) {
    var w = [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517];
    // User's custom parameters for sub-decks
    requestRetention = 0.9;
    maximumInterval = 36500;
    easyBonus = 1.3;
    hardInterval = 1.2;
  }

**Comment by L-M-Sherlock** [comment]
I need your deck names. Could you share the screenshot of your Anki?

**Comment by L-M-Sherlock** [comment]
Oh, your code doesn't match your deck names.

**Comment by L-M-Sherlock** [comment]
It's right and remember to add <div id=deck deck_name="{{Deck}}"></div> to your card's front template's first line.

**Comment by L-M-Sherlock** [comment]
You don't need to do that. Maybe you need to check the template of different card templates of the same note type.
