### ISSUE TITLE
[Question] Would FSRS work correctly for cards with copied scheduling data?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#136]
I have a question about whether FSRS would work for me correctly. But, before I ask my question, here is some background:

While working through my cards, I often discover old cards that I think should not be a single card but must be split into multiple cards. Then, I split those cards and based on my assessment of my memory of those answers, I copy the scheduling data from the old card to the new cards using [this add-on](https://ankiweb.net/shared/info/94685914). However, this add-on doesn't copy the complete review history. Here are the card infos of two such cards:

<img src="https://user-images.githubusercontent.com/92206575/217216146-7217a908-4294-47cd-afa9-2f27f3e266a2.jpg" width=75%>
<img src="https://user-images.githubusercontent.com/92206575/217217766-440f0c34-beba-4888-a30a-9f35d597cf78.jpg" width=75%>

All the reviews seen in the review history are those that were done after the splitting.

Now, since the Optimizer and the Helper use the complete review history of the card, would they work correctly with these cards?

I don't know how much of my collection consists of such cards, but I guess it should be close to 10%.

**Comment by L-M-Sherlock** [comment]
It will cause problems 😫. In my view, these logs are invalid.

**Comment by user1823** [comment]
How serious could it be?
Do I need to do something to minimize it?
Are you planning to do something to fix it?

**Comment by MNastri** [comment]
Here's what I think:
-The addon that transfers scheduling information needs to actually transfer them correctly. 
-Fsrs4anki should assume that the received scheduling info is right.
That's just my opinion of course.

I'm curious about what fraction of your cards had their scheduling transfered, I suspect it's a really small number and that would have little effect on your optimized weights.

**Comment by L-M-Sherlock** [comment]
> How serious could it be?

FSRS helper needs the first rating (corresponding to the learning type of review) to initiate the rescheduling of the card.

**Comment by user1823** [comment]
> FSRS helper needs the first rating (corresponding to the learning type of review) to initiate the rescheduling of the card.

Ok. But, what would the helper do in the case of these cards? 
Also, what would be the effect on the optimized w values (considering the number of such cards to be 5-10% of my total cards)?

Also, my other two questions remain unanswered.
1. Is there something I can do to resolve the issue (at least partially)?
2. Are you planning to do something to resolve the issue?

**Comment by L-M-Sherlock** [comment]
It would cause unknown bugs, because I haven't tested this case.

5% data doesn't affect the parameters too much. And maybe I need to use the add-on and check the effect.

**Comment by L-M-Sherlock** [comment]
It's not the responsibility of FSRS. In my opinion, the history of reviews shouldn't be mutable.

**Comment by user1823** [comment]
> It's not the responsibility of FSRS. In my opinion, the history of reviews shouldn't be mutable.

I agree that it's not the responsibility of FSRS.

However, for the benefit of the users, I think a small check could be added to look for such cases.

If such a case is found, the helper can use only the later parts of the review history to set the  difficulty and other factors. These factors would then adjust as more reviews are done.

> 5% data doesn't affect the parameters too much.

So, this would mean that there is no need to tweak the optimizer.

> And maybe I need to use the add-on and check the effect.

I would wait for the results.

**Comment by L-M-Sherlock** [comment]
> If such a case is found, the helper can use only the later parts of the review history to set the difficulty and other factors. These factors would then adjust as more reviews are done.

I prefer to skip these cards, because the helper can't create the first rating out of nothing.

**Comment by L-M-Sherlock** [comment]
> I would wait for the results.

Could you share the deck file with scheduling information with me? It will speed the check.

**Comment by user1823** [comment]
Here is the file: [Selected Notes.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/10676442/Selected.Notes.zip)

Note 1: I have changed the file extension to .zip because GitHub wouldn't allow me to upload .apkg file. Please change the extension to .apkg before using it.

Note 2: I have only shared some of those cards which were affected, not my whole collection. Also, I have deliberately replaced the contents of the fields in the note because I don't want to share the contents online.

**Comment by user1823** [comment]
Actually, I ended up testing it myself. The helper increased the interval of the card, but not as much as the other cards. I don't know what it did to the difficulty (because I can't see it, I guess).

However, I discovered another issue. For most of the normal cards, the intervals of the cards were increased greatly. For example, in the below screenshot, the interval increased from 1.5 months to 5.3 months!! After I recall a card after 20 days (which was the previous interval), it can't be sure of being able to recall it after 5.3 months.
![Untitled2](https://user-images.githubusercontent.com/92206575/217300417-50966edf-d05a-4f30-a2b8-4f27990fe858.jpg)

I used the scheduler version v3.12.1

The values I used are as follows:

> var w = [1.0667, 1.5311, 5.074, -1.1417, -1.1723, 0.0084, 1.6441, -0.0156, 1.0239, 1.7457, -0.4718, 0.8922, 0.6602];
> let requestRetention = 0.9;
> let maximumInterval = 36500;
> let easyBonus = 1.3;
> let hardInterval = 1.2;

**Comment by L-M-Sherlock** [comment]
> However, I discovered another issue. For most of the normal cards, the intervals of the cards were increased greatly. For example, in the below screenshot, the interval increased from 1.5 months to 5.3 months!! After I recall a card after 20 days (which was the previous interval), it can't be sure of being able to recall it after 5.3 months.

I guess your retention before is higher than 90%. Could you paste the analysis generated by the optimizer here? Like this:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/32575846/217409175-83ed581f-d7e2-4976-abe6-3c91af3c546b.png">

**Comment by L-M-Sherlock** [comment]
I have tested these selected notes with the helper add-on. The helper skipped those two reviews because the card didn't contain the learning stage. It will be fixed in the next update of the FSRS4Anki helper add-on.

![image](https://user-images.githubusercontent.com/32575846/217423308-d1c8d833-d50c-4fa2-b716-d30b203641f4.png)

**Comment by user1823** [comment]
> Could you paste the analysis generated by the optimizer here?

Here is the analysis:
![image](https://user-images.githubusercontent.com/92206575/217440127-affcb752-d80e-416c-883a-c7cf396b50ce.jpg)

**Comment by L-M-Sherlock** [comment]
I noted that the retention is extremely high when the first rating of the `r_history` is 3 (good). So the interval increased hugely when your target retention is 90%.

**Comment by L-M-Sherlock** [comment]
By the way, I recommend using learning steps shorter than one day. Let FSRS control the long term schedule.

**Comment by user1823** [comment]
> I noted that the retention is extremely high when the first rating of the `r_history` is 3 (good). So the interval increased hugely when your target retention is 90%.

What should I do then? Should I increase the target retention to something like 96%?

**Comment by user1823** [comment]
> By the way, I recommend using learning steps shorter than one day. Let FSRS control the long term schedule.

I will set learning steps shorter than one day when I start using FSRS. These logs are from my previous reviews.

**Comment by L-M-Sherlock** [comment]
> What should I do then? Should I increase the target retention to something like 96%?

It depends on your goals. Higher retention or less reviews. You could check the stats given by Anki to see the retention in the past.

**Comment by user1823** [comment]
> You could check the stats given by Anki to see the retention in the past.

Is this what you are talking about?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/92206575/217445298-b163461f-f83d-468d-9bcd-f0bdb799b70b.png">

> It depends on your goals. Higher retention or less reviews.

I would want similar (if not greater) retention to that achieved by standard Anki algorithm. 

So, if I use a retention like 95%, would FSRS reduce the number of reviews as compared to standard Anki algorithm? Or would I be fine with using the standard algorithm and not bother about FSRS?

**Comment by L-M-Sherlock** [comment]
> So, if I use a retention like 95%, would FSRS reduce the number of reviews as compared to standard Anki algorithm? 

You could simulate the comparison via the fsrs4anki simulator: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb

**Comment by L-M-Sherlock** [comment]
> So, if I use a retention like 95%, would FSRS reduce the number of reviews as compared to standard Anki algorithm? 

You could simulate the comparison via the fsrs4anki simulator: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb

**Comment by user1823** [comment]
So, I simulated the comparison. Here are my results for 94%, 95% and 96% retention respectively.
[simulation 94%.pdf](https://github.com/open-spaced-repetition/fsrs4anki/files/10682660/simulation.94.pdf)
[simulation 95%.pdf](https://github.com/open-spaced-repetition/fsrs4anki/files/10682663/simulation.95.pdf)
[simulation 96%.pdf](https://github.com/open-spaced-repetition/fsrs4anki/files/10682662/simulation.96.pdf)

Based on this analysis, I think 95% retention reduces my review time (slightly) as compared to standard Anki algorithm but gives the maximum number of remembered cards (5906).

So, I think 95% retention would be best for me. What do you think?

**Comment by user1823** [comment]
Sorry for being too inquisitive. I am just trying to ensure that FSRS gives me the most optimal results possible.

**Comment by L-M-Sherlock** [comment]
I prefer 94% because its time per remembered card is the least (i.e., efficient).

**Comment by user1823** [comment]
This seems good.
However, I have one question:
With 94% retention, though number of remembered cards is greater than standard Anki, the retention per day is lower than Anki. Why is it so?

**Comment by L-M-Sherlock** [comment]
> With 94% retention, though number of remembered cards is greater than standard Anki, the retention per day (in graph) is lower than Anki. Why is it so?

The retention per day doesn't equal the retention of all cards. For example, the retention of mature cards is often lower than young cards in Anki, because Anki gives a longer interval to those mature cards. The lower retention of mature cards could not be included in the daily retention until they were due.

**Comment by user1823** [comment]
Thanks. I think you should include an explanation of the values generated by the simulator in the simulator's description.
