### ISSUE TITLE
[Question] Do optimizer and helper use review history before manual reset of a card?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#137]
Whenever I find a card that hasn't been framed in a way that is optimal for learning, I edit it and then reset it using the "Forget" option.

In my opinion, the review history before the reset is not of any value because at that time, I was just cramming the card instead of learning the information.

Now, my question is: Do the optimizer and the helper use the review history prior to the manual reset?

**Comment by L-M-Sherlock** [comment]
The helper has considered the manual reset.

**Comment by user1823** [comment]
What exactly does this mean?

I suppose this means that reviews before the reset are considered null and void and not used at all. Am I right?

And what about the optimizer?

**Comment by L-M-Sherlock** [comment]
You can see the source code of the helper add-on here: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/8f979c1eb6171a1a563dd08355974e5f74ccda04/reschedule.py#L92

The rating equal 0 when you manually reset the card.

**Comment by user1823** [comment]
Sorry. I am not that technical to understand the code.

Please state clearly whether the helper and the optimizer completely ignore the reviews done before the reset.

**Comment by L-M-Sherlock** [comment]
The helper will reset the memory state when it meets the the "forget" action.

**Comment by user1823** [comment]
Ok. Thanks

**Comment by L-M-Sherlock** [comment]
I don't know how anki to store the manual reset in the review logs, so I can't answer the question about the optimizer.

**Comment by cjdduarte** [comment]
> The helper will reset the memory state when it meets the the "forget" action.

@L-M-Sherlock when we use the forget function, Anki does not clear the revlog. Can't it be a problem?

**Comment by L-M-Sherlock** [comment]
> Can't it be a problem?

The helper will use the review logs before reset to generate memory state. But it doesn't affect the memory state after reset.
