### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#138]
**Data file**
If you use FSRS4Anki optimizer, it will extract the data of your review and save it as `revlog.csv`. You can download it from Colab. Then drag and drop the `revlog.csv` file here:
[revlog.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/10674197/revlog.csv)

**Additional context**
- Timezone: Asia/Calcutta
- The next day starts at: 4

**Comment by L-M-Sherlock** [comment]
Thanks for your contribution to the spaced repetition research!
