### ISSUE TITLE
[Feature Request] optimize new interval setting

### ISSUE THREAD

**Issue by MNastri** [open-spaced-repetition/fsrs4anki#142]
### **Which module is related to your feature request?**
Optimizer

### **Is your feature request related to a problem? Please describe.**
I'd like to request an optimizer for the 'New Interval' setting in the deck options. 
Is it possible to guess/optimize this setting within FSRS4Anki? Or does it already do that?

#### What 'New Interval' does in Anki?
This setting represents by how much the current interval of a forgotten/failed card will get multiplied.
Anki defaults this setting to 0 but respects the 'Minimum interval' setting (default is 1 day, I think)  when calculating the new interval after a lapse.
And the new interval is only set after all lapse steps are completed after a failed review. 

#### The problem with 'New Interval' default value
Anki's default is 0, meaning that after a failed review, a card that had an interval of 300 days (as an example) will now have an interval of 1 day after it has gone trough the relearning queue. 
Obviously this can't be correct since the successful recalls before failure increased the memory half-life/stability and setting the new interval to 1 day is not optimal.

#### Workarounds
As a fix for this issue I changed the setting in my default deck to 70% so any new decks I create inherit this automatically. That's better but it ignores the fact that different decks have different difficulties.

An even better solution has been using the [autoLapseNewInterval addon](https://ankiweb.net/shared/info/372281481). 
It keeps track of the retention of the cards reviewed after lapses until some count of reviews is reached and them applies an algorithm. 
It checks cards that share the same deck options for their retention and then adjust the new interval if the retention is above/below the desired retention.

The explanation for the algorithm comes from [eshapard's post](https://eshapard.github.io/anki/anki-auto-adjust-new-interval-after-a-lapse.html):
"If your current success rate is 20% higher, than the target rate (85%), we make the Lapse New Interval 20% longer; if our success rate is 20% lower, we make the Lapse New Interval 20% shorter". (recently the addon changed the desired retention to 95%)

### **Describe the solution you'd like**
When using the optimizer it could output the retention of cards after a lapse.

-My naive solution:
You calculate the number of success and total reviews in a revision history of a card by counting the ones after the first failure only.
Calculate some "average" of retention after a lapse.

-Not so simple solution:
Use your model somehow to calculate the best retention after a lapse

### **Describe alternatives you've considered**
The autoLapseNewInterval keeps track of how many reviews after a lapse you have done and when a certain count of cards is reached it runs the algorithm to recalculate the New Interval setting.
This makes the setting work more like a "rolling average" of retenttion after a lapse and is useful...

### **Additional context**
![image](https://user-images.githubusercontent.com/87741282/216986137-a9413352-d8d0-4759-9b2d-dadc04f6dfb5.png)

**Comment by L-M-Sherlock** [comment]
You can see the formula of stability after forgetting (i.e., post-lapse stability).

https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler

In DSR model, the relation between the post-lapse stability and the pre-lapse stability is not a constant.

**Comment by MNastri** [comment]
If I'm understanding this right, after a failed review you reschedule the card interval with the value from the formula, right? 
If that's the case I'm not sure what is the interaction of the scheduler with this setting. 
Is this 'New Interval' setting affecting the schedule of failed cards or not?
In other words, if I leave the setting at 70%, or whatever other value, will it have any effect in the way lapsed cards are being rescheduled?

Question 7 of the FAQ (Which Anki settings will become irrelevant, and which won't?) doesn't mention this setting.

**Comment by kuroahna** [comment]
@MNastri you should check out the anki docs on the new interval setting https://docs.ankiweb.net/deck-options.html#new-interval

> While preserving part of the interval may seem to make sense, **SuperMemo has observed that preserving part of the delay can actually be counter-productive.** For this reason, we recommend you leave it on the default setting

From supermemo https://supermemo.guru/wiki/Post-lapse_stability

> Some competitive spaced repetition software, as well as SuperMemo in its first years, experimented with re-learning hypotheses based on ancient wisdoms of psychology, e.g. **by halving intervals after a memory lapse. Current data shows clearly that this approach is harmful, as it slows down the identification of leeches. Such an approach to handling forgotten items is a form of irrational procrastination.**

And
> It has been shown long ago that the length of the first post-lapse optimum [[interval] is best correlated with the number of memory lapses recorded for the item. **Even then, post-lapse interval usually oscillates in the range of 1-4 days for the default forgetting index of 10%.**

This is why anki sets the interval back to 1 after a memory relapse. You're slowing down the identification of leeches by trying to set new interval anything beyond 1 to 4 days. It's really not a big deal. If the card is easy, you can press the easy button and push it further. Or just keep pressing good. You should be able to pass the card within 1 to 3 seconds if you actually know the card really well. Otherwise you needed the extra practice

It'll be interesting to see if FSRS has different results, but supermemo already did some research on it and setting new interval to 50 percent for example was detrimental

**Comment by MNastri** [comment]
Right! Thank you very much!
@kuroahna, feel free to send me any other stuff you think is relevant. I'm always open to changing my understanding when faced with new evidence.

I'll leave this issue open in case LMSherlock wants to do anything with it, but feel free to close it.

**Comment by L-M-Sherlock** [comment]
> If that's the case I'm not sure what is the interaction of the scheduler with this setting.

The `new interval` setting is ignored by FSRS.

**Comment by L-M-Sherlock** [comment]
> Question 7 of the FAQ (Which Anki settings will become irrelevant, and which won't?) doesn't mention this setting.

It mentioned:

> The `graduating interval`, `easy interval`, **`new interval`**, `starting ease`, and `interval modifier` become irrelevant.

**Comment by MNastri** [comment]
Oof, my bad. Ty anyway.
