### ISSUE TITLE
[BUG] Real interval is wrong when setting revlog_start_date

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki#144]
Oh, seems like I need to reduce the minimum counts
here it is:
```
r_history  avg_interval  avg_retention  stability  factor  group_cnt
        1           7.9          0.700        2.4     inf        345
      1,3          14.0          0.833        8.1    3.38         30
        2           9.0          0.843        5.6     inf         51
        3           9.0          0.898        8.9     inf        353
```
I have no idea why the first row says average interval is 7.9 days. I believe the first interval if i pressed 1 should be 2 days.

_Originally posted by @1over137 in https://github.com/open-spaced-repetition/fsrs4anki/issues/113#issuecomment-1416696411_

**Comment by 1over137** [comment]
I think the way to fix this is just to still go through the whole history in order to eliminate cards first seen before revlog_start_date, then use the data after revlog_start_date.

**Comment by L-M-Sherlock** [comment]
Yep, I'm fixing it. The old history will be removed after time-series feature extraction.

**Comment by L-M-Sherlock** [comment]
I have fixed it. Could you help me test it?

https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Fix/wrong-inteval-when-setting-revlog_start_date/fsrs4anki_optimizer.ipynb

**Comment by 1over137** [comment]
Appears to have the same results
```
1:again, 2:hard, 3:good, 4:easy

r_history  avg_interval  avg_retention  stability  factor  group_cnt
        1           7.9          0.700        2.4     inf        303
        3           9.0          0.897        8.7     inf        336
```

**Comment by L-M-Sherlock** [comment]
> Appears to have the same results

Could share the new revlog.csv and revlog_history.tsv with me? I need it to locate problem.

**Comment by 1over137** [comment]
[revlog.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/10702068/revlog.csv)
[revlog_history.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/10702072/revlog_history.csv)
(github doesn't let me upload tsv, so you need to change it back)

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/217977084-2dddf77f-d035-41ff-b958-75db0f3c58bb.png)

The result is expected. Did you use the optimizer via my link?

https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Fix/wrong-inteval-when-setting-revlog_start_date/fsrs4anki_optimizer.ipynb

**Comment by L-M-Sherlock** [comment]
I figure out the problem. Some intervals of the cards whose first rating is 1 (again) are wrong. It is due to a bug in the helper add-on. The bug has been fixed since 2023-02-03.
