### ISSUE TITLE
[Question] Is fuzz applied evenly?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#145]
In standard Anki, fuzz applied to the cards is in proportion to their interval.

Is it the same with FSRS scheduler? Also, does FSRS have its own fuzz implementation or it just asks Anki to apply fuzz as Anki usually does?

What about the case when I review my cards on AnkiDroid and then reschedule them with the Helper? Is the fuzz applied in this case? Is this fuzz proportional to the card interval?

**Comment by L-M-Sherlock** [comment]
FSRS scheduler implements the fuzz, and enables it in default. The helper doesn’t support fuzz.

**Comment by L-M-Sherlock** [comment]
For details about the fuzz feature of FSRS, please see: https://github.com/open-spaced-repetition/fsrs4anki/pull/73

**Comment by user1823** [comment]
> The helper doesn’t support fuzz.

So, I think adding fuzz support to the helper would be a good idea.

**Comment by L-M-Sherlock** [comment]
You could propose the feature request in a new issue.
