### ISSUE TITLE
[Question] Using additional custom scheduling along with FSRS

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#146]
I want to use the following code along with FSRS scheduler so that if I ever want to switch back to standard Anki scheduling, I won't be stuck in Ease Hell.

```
if (
  states.good.normal &&
  states.good.normal.review &&
  states.current.normal.review
) {
  let oldEase = states.good.normal.review.easeFactor;
  let diff = 2.5 - oldEase;
  states.good.normal.review.easeFactor +=
    Math.sign(diff) * Math.min(0.05, Math.abs(diff));
}
```

Source: https://forums.ankiweb.net/t/i-love-v3-custom-scheduling/16301

Is this possible?
- If yes, where should I insert this code so that FSRS can continue to work correctly?
- If no, can some slight changes make it possible to use both of them together?

**Comment by L-M-Sherlock** [comment]
I will test it and answer you in tomorrow.

**Comment by L-M-Sherlock** [comment]
It works well. Please add them above FSRS's code.
