### ISSUE TITLE
Make it possible to use another learning step only for cards rated Again or Hard

### ISSUE THREAD

**Issue by 1over137** [open-spaced-repetition/fsrs4anki#148]
I think one of the important differences that contributes to my reduced workload with FSRS is that cards I already know at the time of first learning step is now getting a bigger interval that accounts for prior knowledge. Wouldn't it make more sense to have only a single learning step? If I succeeded in keeping this information in my memory between the time I first learned it and the first learning step, there is no real point in seeing the card again in 10 minutes. It only makes sense to have extra learning steps for either new information or cards I failed to remember between its creation and the first appearance in Anki.

Though, this also affects cards rated "Again", where it would normally show two learning steps. It would be great to have the ability to still show two learning steps for cards with the initial rating of Again or Hard, but those rated Good should be given the new interval directly (just like with Easy). Can this be implemented in FSRS?

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ

A7:  FSRS only modifies the long-term scheduling. So Learning steps and Relearning steps work as usual. And I recommend not setting a step of more than one day. For example, if your current steps are 10m 1h 1d 2d, you had better remove the 1d 2d from the steps.
