### ISSUE TITLE
[Feature Request] improve adding decks to custom scheduler

### ISSUE THREAD

**Issue by MNastri** [open-spaced-repetition/fsrs4anki#149]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
The current process for adding deck parameters to the custom scheduler is somewhat cumbersom and prone to errors. 
I believe it would be more efficient and reduce the risk of mistakes if the deck parameters were decoupled from the scheduler logic.
To address this, I made a modification to the code by including a dictionary to specify the deck parameters the user wants to include/change.
I included in the dictionary the global parameters for the scheduler because it made sense, but it could easily be undone too.
I placed the dictionary at the beginning and outside of any code so that users have an easier time adding parameters even if they don't have any coding experience.
And since they won't need to fiddle in the code there's no chance they will inadvertdly change the code. 
Although I  tested the change I'm proposing (below), I am not familiar with JavaScript, I made it very quickly, and may have missed some errors.

**Describe the solution you'd like**
```
const deckParams = [
  {
    "deckName": "global config for FSRS4Anki",
    "w": [0.816, 2.3557, 4.6962, -1.9418, -1.852, 0.0214, 1.9571, -0.1892, 1.2709, 1.8373, -0.5185, 0.6747, 1.4451],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2
  },
  {
    "deckName": "ALL::Learning::English::Reading",
    "w": [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
    "includeSubdecks?": false
  },
  {
    "deckName": "ALL::Archive",
    "w": [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
    "includeSubdecks?": true
  }
];

if (document.getElementById("deck") !== null) {
  const deck_name = document.getElementById("deck").getAttribute("deck_name");
  let params = {};
  
  for (let i = 0; i < deckParams.length; i++) {
	if (deckParams[i]["includeSubdecks?"] === true) {
	  if (deck_name.startsWith(deckParams[i]["deckName"])) {
	  	params = deckParams[i];
		break;
	  }
	} else {
      if (deck_name === deckParams[i]["deckName"]) {
        params = deckParams[i];
        break;
      }
	}
  }
  if (Object.keys(params).length === 0) {
    params = deckParams.find(deck => deck["deckName"] === "global config for FSRS4Anki");
  }
  var w = params["w"];
  var requestRetention = params["requestRetention"];
  var maximumInterval = params["maximumInterval"];
  var easyBonus = params["easyBonus"];
  var hardInterval = params["hardInterval"];
}
```

**Comment by L-M-Sherlock** [comment]
The helper add-on also extracts parameters from the scheduler’s code. Do you test it?

**Comment by MNastri** [comment]
I had not tested it before. It's giving a fatal error when I try to reschedule, but I can't check what happened right now.
 
I have made a pull request with the code I proposed above, if you could review it until then it would be awesome...

**Comment by L-M-Sherlock** [comment]
I am busy developing a new feature of the helper add-on today. I will check the PR in a few days.

**Comment by MNastri** [comment]
No problem, I'll review it later then 😉

**Comment by L-M-Sherlock** [comment]
Do we need `includeSubdecks?` ? In which case, the user could apply the parameters to a deck but not to its subdecks?

**Comment by L-M-Sherlock** [comment]
By the way, we may need to develop a config generator GUI to solve the problem of adding deck parameters. For example, the [fsrs4anki_app](https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app) is a GUI version for the optimizer.

**Comment by MNastri** [comment]
Last night I learned regex and started changing the helper addon for the new code I've proposed. 

Sorry for taking so long to answer, but I'm in the middle of a vacation with family and only have a few hours at night to study/improve the code. OK?
I'll try to finish it today.

If I have a deck tree like this 
A
A::B

If A has deck parameters with includesubdecks=false
Now when we review A::B fsrs will use the global parameters

**Comment by MNastri** [comment]
I updated the pull request. I'm sorry for the delay, I feel like there's LOTs of improvements on the table for the Regexp (which I just learned) but I decided to just use the basics that works and deal with issues as they appear... I created a PR for the helper  too, please check it out.

**Comment by MNastri** [comment]
> By the way, we may need to develop a config generator GUI to solve the problem of adding deck parameters. For example, the [fsrs4anki_app](https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app) is a GUI version for the optimizer.

This seems like the best approach, after fiddling with regex I thought of several simple changes a user can make that could break the logic of the helper addon...

**Comment by user1823** [comment]
> By the way, we may need to develop a config generator GUI to solve the problem of adding deck parameters. For example, the [fsrs4anki_app](https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app) is a GUI version for the optimizer.

It is a good idea to develop a GUI version.

But, even then, any suggestion to make it easier to edit the code itself should be encouraged (including the PR https://github.com/open-spaced-repetition/fsrs4anki/pull/150 linked to this issue).

**Comment by MNastri** [comment]
Updated #150 to work with older code, please review it when you can

**Comment by L-M-Sherlock** [comment]
I will review your code in this weekend. Thanks for your contribution!

**Comment by L-M-Sherlock** [comment]
> In regards to your question, yes I think we need it. If I have a deck tree like this A A::B
> 
> If A has deck parameters with includesubdecks=false when we review A::B fsrs will use the global parameters instead of A's parameters

It means that some cards of A are not in A::B, and the parameters of A only apply to these cards. Those cards in A::B are not affected. But this case is rare, in my option. Should we support it?

**Comment by L-M-Sherlock** [comment]
Actually, the rescheduling doesn't consider this case. The `include_subdecks` is not used.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/87022eb0f095db5fce3b39c74e8fdf241da27ef7/reschedule.py#L132

**Comment by MNastri** [comment]
> It means that some cards of A are not in A::B, and the parameters of A only apply to these cards. Those cards in A::B are not affected. But this case is rare, in my option. Should we support it?

I too think that this case will be less common and we may not need it... I'm sorry for adding unnecessary stuff to the code before discussing with you.

Will you remove these changes or should I do it?

.
.
.
In regards to your other reply 
> In fact, the rescheduling doesn't consider this case. The `include_subdecks` is not used.

It does consider this case, see: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/87022eb0f095db5fce3b39c74e8fdf241da27ef7/reschedule.py#L129-L130
In these lines 'i' is the parameter 'includeSubdecks?' from the deckParams in the custom scheduler.

This in pseudo code/natural language is the same as:
If parameter 'includeSubdecks?' is True and deck 'name' starts with the parameter name or parameter 'includeSubdecks?' is False and deck 'name' is exactly the parameter name then load the parameters.
This works because subdecks will not match exactly when includeSubdecks? is false

An practical example might explain better:
Let a deck with name AAA have includeSubdecks?=true in the custom scheduler. 
_1st case_: When we study from AAA it will be true for the first condition and load the parameters.
_2nd case_: When we study from AAA::BBB it will be true for the first condition and load the parameters.

Let a deck with name CCC have includeSubdeks?=false in the custom scheduler.
_3rd case_: When we study from CCC it will be false for the first condition, and true for the second condition and load the parameters
_4th case_: When we study from CCC::DDD it will be false for the first condition, and false for the second condition and we do not load the parameters (pre-loaded global parameter will be used then).

**Comment by L-M-Sherlock** [comment]
> Will you remove these changes or should I do it?

I will switch to FSRS4ANKI tomorrow, and modify the code by myself. I'm busy teaching chatgpt to create this week, so I delayed the review of code. I'm sorry for that.

**Comment by MNastri** [comment]
I don't know if I should post this here or open a new issue, but I developed a small code to read a config file (using toml) and output the string that can be pasted in the custom scheduler.
see it [here](https://github.com/MNastri/fsrs4Anki_config_gui)

**Comment by L-M-Sherlock** [comment]
I make a pre-release: https://github.com/open-spaced-repetition/fsrs4anki/releases/tag/v3.14.0

**Comment by L-M-Sherlock** [comment]
This feature has been released.
