### ISSUE TITLE
[Question] requestRetention vs optimizer.ipynb

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#152]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

What is the relationship between Retention % (85% or 90%) and Optimizer?

I went to test the optimizer, and from what I understood it evaluates all my history, but I didn't see in the optimizer where to put the retention percentage.

Or do you not need to inform this number in the optimizer?

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/218261917-7e01fc1e-b518-489d-b861-5188df6b21aa.png)

The optimizer provides detailed retention grouped by history.

**Comment by cjdduarte** [comment]
What I'm trying to test:

In 200 days I will do a test. and I have a deck with 3,000 new cards.

What is better?

Study up to 1,000 with 90% retention (learned 900 cards) or study 3,000 with 85% retention (learned 2,550) in the same amount of time.

I'm trying to find an optimal solution based on my history.

**Comment by cjdduarte** [comment]
using the optimizer it returned me this:

`var w = [0.9762, 0.9768, 5.03, -0.5159, -0.5532, 0.1656, 1.3986, -0.0638, 0.7986, 1.9511, -0.249, 0.1775, 0.9508];`

but I don't understand if this suggestion is for a 90% retention or is it indifferent?
and just change it later?

**Comment by L-M-Sherlock** [comment]
The parameters are optimized to fit your memory. Retention depends on your goal for SRS.

**Comment by L-M-Sherlock** [comment]
> In 100 days I will do a test. and I have a deck with 3,000 new cards.
> 
> What is better?

You can use the simulator.

**Comment by cjdduarte** [comment]
Tanks
