### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by zxhd863943427** [open-spaced-repetition/fsrs4anki#153]
**Data file**
If you use FSRS4Anki optimizer, it will extract the data of your review and save it as `revlog.csv`. You can download it from Colab. Then drag and drop the `revlog.csv` file here:
[revlog.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/10715721/revlog.csv)

**Additional context**
- Timezone:Asia/Shanghai
- The next day starts at:4

**Comment by L-M-Sherlock** [comment]
Thanks for your contribution!
