### ISSUE TITLE
[Question] Difference between helper addon and fsrs optimizer ?

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#154]
If I have a new profile and it doesn't have any reviews, do I need to use helper addon? What is the difference between helper addon and fsrs optimizer? I use only Anki PC with FSRS. Can I use load balancer in the helper addon or it only when I reschedule cards with it?
"It could reschedule the card with the new parameters of FSRS4Anki if you used the optimizer to generate personalized parameters for yourself. The interval given by the Helper is more accurate than the Scheduler." Does it mean that it is better to use the Helper to reschedule cards?

The second question is how can I set up 1d for relearn cards if "For example, if your current steps are 10m 1h 1d 2d, you had better remove the 1d 2d from the steps." Now when I hit Again after learning phase I have 2d?

**Comment by L-M-Sherlock** [comment]
> If I have a new profile and it doesn't have any reviews, do I need to use helper addon? 

Not need.

**Comment by L-M-Sherlock** [comment]
> What is the difference between helper addon and fsrs optimizer?

The optimizer is used to generate parameters. The helper uses the parameters to reschedule cards.

**Comment by L-M-Sherlock** [comment]
> Can I use load balancer in the helper addon or it only when I reschedule cards with it?

Load Balance only works when rescheduling.

**Comment by L-M-Sherlock** [comment]
> Does it mean that it is better to use the Helper to reschedule cards?

If you don't have old cards with review history, the helper will be consistent with the scheduler.

**Comment by L-M-Sherlock** [comment]
> Now when I hit Again after learning phase I have 2d?

You could set 1d in the relearning steps. The recommendation assumes that FSRS’s interval is accurate in long term.

**Comment by L-M-Sherlock** [comment]
> It's sad the Load Balance only works when rescheduling. It would be great to work for scheduler too.

Due to technical limitations, it's impossible to implement the Load Balance in scheduler with V3 Scheduler.

**Comment by L-M-Sherlock** [comment]
> So, for me as a new profile the helper add-on makes no sense, right?

Yep, except that you need the postpone & advance features.
