### ISSUE TITLE
Is there any way to avoid the custom scheduler code being removed after every AnkiDroid sync?

### ISSUE THREAD

**Issue by johtso** [open-spaced-repetition/fsrs4anki#155]
Every time I sync from AnkiDroid, the custom scheduler code for the deck ends up empty.

Is there any way to prevent this from happening?

**Comment by L-M-Sherlock** [comment]
Refer to https://github.com/ankidroid/Anki-Android/issues/13009

It has been fixed in the 2.16 version.
