### ISSUE TITLE
Auto rescheduling to ensure consistent state and improve compatibility with AnkiDroid

### ISSUE THREAD

**Issue by 1over137** [open-spaced-repetition/fsrs4anki#156]
It seems to me that the helper and the scheduler tend to produce differing results. In another thread, you mentioned that we should the helper should be better when rescheduling. Would it be possible to use the helper regularly auto-reschedule all cards? In other words, basically just adding a series of options to choose when to trigger auto-rescheduling. Ideas: - On launch, on sync, on closing, on finishing reviewing deck. This would allow compatibility with AnkiDroid, which doesn't seem to be getting proper support of this any time soon.

**Comment by Ceynou** [comment]
I tried doing that copying the FieldReporter addon for the activation on launch but I couldn't get it to work, is on closing even possible?

**Comment by L-M-Sherlock** [comment]
> The [Straight Reward add-on](https://github.com/hgiesel/anki_straight_reward) changes the ease of the reviewed cards that are synced to Anki Desktop from AnkiWeb. Possibly, some of the code from that add-on can be used to implement auto-rescheduling in the FSRS helper add-on.

Thanks for your valuable information. I developed this feature here: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/20156ec71b5a5486bcabc6988b6882fa88c7a59a.

Could anyone help me to test it? The patch file: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/10933224/fsrs4anki-helper.zip)

**Comment by L-M-Sherlock** [comment]
> I think that the rescheduling should only occur when changes are synced from AnkiWeb to Anki Desktop (i.e. a download) and not when changes are uploaded to AnkiWeb.

I don't know how to implement it. Maybe someone could help me. I will open a new issue.
