### ISSUE TITLE
[Question] Inconsistency between scheduler, helper, advance, and postpone

### ISSUE THREAD

**Issue by 1over137** [open-spaced-repetition/fsrs4anki#157]
Lately with the addition of these new options I tried to use them after reviewing, only to find that it sent many cards to my review queue, which disappears after I postpone and advance old cards. Rescheduling this morning gave me over 100 cards in one deck, and advancing + postponing moved them to the future again. In all cases I have set the same retention value (0.86, 86%). Can you explain where this inconsistency is coming from?

**Comment by 1over137** [comment]
I think I solved at least a part of this problem by changing the code to log things. The inconsistency between the rescheduler (helper) and postpone is due to the fact that the rescheduler takes into account hard interval (default = 1.2), while the postpone feature does not, so the rescheduler spits out an interval that is not proportional to the current stability.  I'm not so sure what should be done here. It seems that hard_interval is overriding FSRS predictions by applying a fixed factor here. I don't understand why there is a need for hard_factor though, because the hard_s prediction in FSRS should mean something, just like how the new stability after again is used. Would you just remove this option, so everything would become consistent? To this end, I'm not sure what good `easy_bonus` is supposed to do either. If the model is working properly as trained, there shouldn't be a need for either of these and everything should work according to the formulas.

**Comment by 1over137** [comment]
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/0fedcf289a04c58574569215737621a249dfa6a4/reschedule.py#L139
`hard_ivl = next_interval(last_s * hard_ivl, retention, max_ivl)`
Changing `last_s * hard_ivl` to `hard_s` removes the inconsistency between rescheduler and postpone.

**Comment by L-M-Sherlock** [comment]
> `hard_ivl = next_interval(last_s * hard_ivl, retention, max_ivl)`
> Changing `last_s * hard_ivl` to `hard_s` removes the inconsistency between rescheduler and postpone.

The current code is consistent with scheduler:

https://github.com/open-spaced-repetition/fsrs4anki/blob/b0c2bb3b65b961f4a0d21d2a85a24bdf92828829/fsrs4anki_scheduler.js#L137

**Comment by 1over137** [comment]
I'm mostly wondering why there is this hard interval factor. It isn't described anywhere in the model, and overrides it, also affecting future behavior (you would see the card before the model thinks it's the time, and then model calculates a new stability based on a much higher retrievability, which needlessly slows down stabilization as SInc would be quite a bit lower.

**Comment by L-M-Sherlock** [comment]
I add the hard interval factor to imitate Anki's built-in algorithm. In pure FSRS, only `again` and `good` exist. If we remove the hard interval factor from FSRS, the difference in intervals between `hard` and `good` will reduce.

**Comment by 1over137** [comment]
So, do you think postpone/advance should be changed to ignore cards whose last rating is `hard`?

**Comment by L-M-Sherlock** [comment]
I think the inconsistency is negligible. Most people only use `again` and `good`.

**Comment by L-M-Sherlock** [comment]
By the way, the inconsistency exists in cards whose latest rating is `easy`, too. I have no plan to ignore those cards when postponing and advancing.
