### ISSUE TITLE
[BUG] Error using the latest optimizer v3.13.3

### ISSUE THREAD

**Issue by Farinata** [open-spaced-repetition/fsrs4anki#158]
**Describe the bug**
fails on `1.2 Create time-series feature & analysis`

```
NonExistentTimeError                      Traceback (most recent call last)
[<ipython-input-3-841ae64ab12c>](https://localhost:8080/#) in <module>
     33 df = df[(df['type'] == 0) | (df['type'] == 1)].copy()
     34 df['real_days'] = df['review_date'] - timedelta(hours=next_day_starts_at)
---> 35 df['real_days'] = pd.DatetimeIndex(df['real_days'].dt.floor('D')).to_julian_date()
     36 df.drop_duplicates(['cid', 'real_days'], keep='first', inplace=True)
     37 df['delta_t'] = df.real_days.diff()

7 frames
/usr/local/lib/python3.8/dist-packages/pandas/_libs/tslibs/tzconversion.pyx in pandas._libs.tslibs.tzconversion.tz_localize_to_utc()

NonExistentTimeError: 2022-03-22 00:00:00
```

**Comment by Farinata** [comment]
Don't know why it is mentioning 2022-03-22. I tried before and after dates with same problem.

My deck:
[BA.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/10766001/BA.zip)

**Comment by galantra** [comment]
The error seems to be related to the time zone

https://stackoverflow.com/questions/25266675/nonexistenttimeerror-when-localizing-pandas-datetime-index

Did you make sure to replace `timezone = 'Asia/Shanghai'
` with your own time zone?

**Comment by Farinata** [comment]
> Did you make sure to replace `timezone = 'Asia/Shanghai' ` with your own time zone?

Yes. And when I tried different time zone, same error appears but with a different date "NonExistentTimeError: 2022-03-28 00:00:00"

**Comment by Farinata** [comment]
Note that I use VPN a lot. But even after stopping the VPN and using my time zone same error

**Comment by Farinata** [comment]
I tried deactivating the "Legacy timezone handling" in preferences --> review, then exporting the deck. Nothing changed.

**Comment by Farinata** [comment]
Interestingly, when I keep Asia/Shanghai it is working. But I don't know how much my parameters will be affected.

**Comment by Farinata** [comment]
Update: using the UTC±0.00 format is working fine.

**Comment by L-M-Sherlock** [comment]
I have fixed it. Could you help me to test the patch?

https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Fix/NonExistentTimeError/fsrs4anki_optimizer.ipynb

**Comment by Farinata** [comment]
I can confirm now it is working like a charm.

Note that "var w =" is now appearing twice behind each other. Dunno if it means anything.
Thanks.

**Comment by L-M-Sherlock** [comment]
> Note that "var w =" is now appearing twice behind each other

Could you share the screenshot with me?
