### ISSUE TITLE
Request to review my code for the GUI for the custom scheduler config

### ISSUE THREAD

**Issue by MNastri** [open-spaced-repetition/fsrs4anki#163]
I developed some code to generate the custom scheduler code automatically. It isn't complete yet but it resembles how I think it should work.
Can you check it out and share your thoughts?
[repo](https://github.com/MNastri/fsrs4Anki_config_gui)

**Comment by MNastri** [comment]
by the way, I do not know PyQt5 nor how Anki uses Qt5. I'm just reading docs and googling my way to get the UI the way I want.

**Comment by L-M-Sherlock** [comment]
Could we deploy it on a website? I'm afraid few people would have a Python environment on their devices.

**Comment by MNastri** [comment]
Good idea, I'll do it as soon as I can.

**Comment by MNastri** [comment]
[update](https://github.com/MNastri/fsrs4Anki_config_gui/blob/master/fsrs4anki_create_deck_config_through_gui.ipynb). 

Your feedback is appreciated!

**Comment by L-M-Sherlock** [comment]
I will test it in this week.

**Comment by L-M-Sherlock** [comment]
Sorry for this late reply. I would not support this feature because we plan to integrate the optimizer into Anki: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/91, which will generate the custom scheduler config, too.
