### ISSUE TITLE
"skip_decks list" not working

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4anki#165]
In FSRS v3.14.0 Scheduler Qt5, the decks set to be skipped are not being skipped.

**Comment by L-M-Sherlock** [comment]
You need add `<div id=deck deck_name="{{Deck}}"></div>` to your card's front template. The skip deck feature needs the deck name of cards.

**Comment by hugomarins** [comment]
Thanks for explaining, I missed that orientation. Sorry! Now it is working as expected.
