### ISSUE TITLE
[BUG] rescheduling still works even if the numbers of parameters and other configs unmatch.

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki#166]
**Describe the bug**

The helper add-on doesn't warn users even if the configs are incomplete, because assert doesn't work in Anki.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/8936508ac4847c115643fd0b13e5992dc62d906b/utils.py#L122-L124

@MNastri 

I plan to wrap a warning function.

**To Reproduce**
1. Remove a hardInterval from the scheduler code.
2. Reschedule all cards
3. The rescheduling works

**Expected behavior**
The helper add-on doesn't warn users even if the configs are incomplete, because assert doesn't work in Anki.

**Comment by MNastri** [comment]
Good idea! Something like "Making changes to any part of the code besides your custom deck configuration/data may render the scheduler useless or reduce its functionality. Please do NOT change any part of the code past the user/deck data section" then add some clear distinction to the scheduler code as to where this section ends. What do you think?

But this is one of those issues that could be solved if the config/custom scheduler code was created through some GUI. 
If the user just copy and paste the config as generated that would avoid a lot of user 'mistakes'.

I wonder if this GUI can be implemented directly in Anki as an addon, but I've had trouble understanding how to create addons for Anki in the past. Maybe you could point me to some good primer (or something) so I can learn that?

**Comment by L-M-Sherlock** [comment]
> I wonder if this GUI can be implemented directly in Anki as an addon, but I've had trouble understanding how to create addons for Anki in the past. Maybe you could point me to some good primer (or something) so I can learn that?

I plan to generate parameters for specific decks in the optimizer, then users could get the final scheduler code with the optimized parameters.

But it requires anki package in colab or other online platforms. I need to learn more about it.
