### ISSUE TITLE
[BUG] Adjustment in the outputs of the weights

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#167]
**Describe the bug**

just a small detail. With the weight format change, the optimizer output still shows the old one.

![image](https://user-images.githubusercontent.com/42243532/221206569-5c61e168-6348-41d7-932d-7151da1bf3a2.png)

**Optimizer**
![image](https://user-images.githubusercontent.com/42243532/221206268-6b0fdafc-9546-4a59-a517-cbc79471a00b.png)

![image](https://user-images.githubusercontent.com/42243532/221206472-332c31bd-50fa-4313-a581-b309ee85c06c.png)

**Comment by L-M-Sherlock** [comment]
Should it only output `[1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1]`?

**Comment by cjdduarte** [comment]
> Should it only output `[1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1]`?

Exactly.
Remove the "w=" as it is no longer used in this new update.
