### ISSUE TITLE
[BUG] Scheduler is not taking sub-deck specific parameters into account

### ISSUE THREAD

**Issue by Vitorvlv** [open-spaced-repetition/fsrs4anki#168]
I have a main deck and a sub-deck.
The main deck has parameters specific for and so does the sub-deck.

```
    "deckName": "Medicina",
    "w": [0.291, 1.0092, 5.1177, -0.6635, -0.5622, 0.0496, 1.3686, -0.1768, 0.7569, 1.6634, -0.5266, 0.7515, 0.5999],
    "requestRetention": 0.84,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
  },
  {
    // Example 2: User's custom parameters for this deck and its sub-decks.
    // Don't omit any keys.
    "deckName": "Medicina::Atual",
    "w": [0.8392, 1.0148, 5.2615, -0.7854, -0.7471, 0.0055, 1.2835, -0.1306, 0.6806, 1.6346, -0.5602, 0.2927, 0.6559],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
  }
```
This worked fine in the previous way of setting deck-specific parameters, but with this new one I see on the inspector that the scheduler is only taking into account the first one. The second one never gets applied. 

**Environment**
 - Anki version: 2.1.58
 - OS: Fedora 37
 - Scheduler version: 3.14.1

```
  for (let i = 0; i < deckParams.length; i++) {
    if (deck_name.startsWith(deckParams[i]["deckName"])) {
      params = deckParams[i];
      break;
    }
```

looking at the inspector it seems this is the issue? It's only taking into account what the name starts with. So the part where it sees that it's a different deck gets ignored. I'm not a developer though, so idk. ~I'll downgrade to the previous version of the scheduler for now.~

Actually, putting "Medicina::Atual" before "Medicina" works around the issue, it seems to be behaving as expected now. 

![image](https://user-images.githubusercontent.com/26132870/221332462-8dfae88b-c3a5-41bb-9263-ca0989f81efb.png)

**Comment by L-M-Sherlock** [comment]
Oh, the loop of setting params break before it reaches "Medicina::Atual". @MNastri, do you have any idea to fix it?

An alternative method is placing the subdeck params before their parent decks. @Vitorvlv

**Comment by MNastri** [comment]
> Oh, the loop of setting params break before it reaches "Medicina::Atual". @MNastri, do you have any idea to fix it?
> 
> An alternative method is placing the subdeck params above their parent decks. @Vitorvlv

Sort the dict in reverse order before looping?

This would put the longest deckName before the shortest one and should solve this kind of issues (parent and child decks with custom params). 

I thought of this when I was writing the code but I might've forgotten to actually implement it.... I'm going to take a look at it and revert back to you

**Comment by L-M-Sherlock** [comment]
@Vitorvlv Have a try to this patch: https://github.com/open-spaced-repetition/fsrs4anki/releases/tag/v3.14.2

**Comment by L-M-Sherlock** [comment]
I think this bug has been fixed.
