### ISSUE TITLE
[Feature Request] Need more instruction about how to tell if the algorithm is working

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#17]
I was aware of this exact same question/answer in the Wike FAQ. I installed the `AnkiWebView Inspector` Anki add-on yesterday, however, I still didn't know what to look for as the interface appeared very messy to me probably because my web development knowledge was very limited, and therefore I was probably missing a lot of context. So I think it would be very helpful if @L-M-Sherlock  could provide more details in documentation about how to confirm if the algorithm is working. I'm especially interested in this because I really couldn't tell the difference when I put this algorithm in use yesterday as it appeared to me that the scheduling was pretty much the same as if it was done by Anki's algorithm.

By the way, I noticed that @L-M-Sherlock  had some new fixes or improvements regarding the `filtered deck`, because most of my reviews are performed in `filtered deck`, I'm not sure if I was affected.

**Comment by L-M-Sherlock** [comment]
It is 11:59 PM in China. I’m going to bed, and will reply you in tomorrow.

**Comment by YorkZ** [comment]
Oh, yep we are in different time zone (12 hours difference). Don't bother replying, sleep is definitely the highest priority, and hope you have nice dreams.

**Comment by L-M-Sherlock** [comment]
I'm back. You can open the inspector via right-clicking interface and clicking inspect:

![Snipaste_2022-09-23_09-32-33](https://user-images.githubusercontent.com/32575846/191877514-ad7fca6d-053d-406a-843f-a20ddb04be17.png)

Then start your deck and use `step over`:

![image](https://user-images.githubusercontent.com/32575846/191877577-86442393-2b07-4003-80bd-87e1004dc8a6.png)

The highlighted line is the code running currently:

![image](https://user-images.githubusercontent.com/32575846/191877706-13609f78-072e-4340-bdef-bd239d1afdd6.png)

**Comment by YorkZ** [comment]
Thank you for the help, but I'm still confused. Attached is my screenshot where I wasn't able to find anything similar to yours.
![2022-09-23_17-24](https://user-images.githubusercontent.com/742238/192023666-acd4a17d-c2de-49fb-b2f2-0127a5d2c553.png)

**Comment by L-M-Sherlock** [comment]
I need a gif or screen recorder to know each step of your Anki. Or wait me to open my Anki in tomorrow because I leave my computer in company.

**Comment by YorkZ** [comment]
OK, finally! Looks like I have to open the `AnkiWebView Inspector` before clicking the `Study now` button instead of after clicking that button. Thanks for the help.

**Comment by L-M-Sherlock** [comment]
> OK, finally! Looks like I have to open the `AnkiWebView Inspector` before clicking the `Study Now` button instead of after clicking that button. Thanks for the help.

Right, the scheduler code calculates the interval for each rating before you click `show answer`.

**Comment by YorkZ** [comment]
Probably not before clicking `show answer` but before clicking `Study Now`.

**Comment by L-M-Sherlock** [comment]
More accurately, before Anki loading the front of a card.

**Comment by YorkZ** [comment]
By the way, I think the intervals showing on the buttons `Again`, `Hard`, `Good` and `Easy` are already calculated by your custom scheduler, am I right?

**Comment by L-M-Sherlock** [comment]
Of cause, the intervals shown on button are given by the custom scheduling.

**Comment by L-M-Sherlock** [comment]
I write the instruction on this wiki page: [How does the scheduler work?](https://github.com/open-spaced-repetition/fsrs4anki/wiki/How-does-the-scheduler-work%3F)

**Comment by YorkZ** [comment]
Nice work!
