### ISSUE TITLE
[BUG] Deck name not found (randomly?)

### ISSUE THREAD

**Issue by tkozybski** [open-spaced-repetition/fsrs4anki#172]
**Describe the bug**
At random, cards appear as "Deck name not found" when display_memory_state is set to true. Usually it happens on the first card of the deck, or if I study on a parent deck and anki jumps between the children decks, but it's not a rule. The deck is set up properly in the config, the proper div object is also present in the card. 

It looks like a race condition, when FSRS4Anki loads before the card finishes loading. It might be a bug in Anki itself. I see there was an [attempt](https://github.com/open-spaced-repetition/fsrs4anki/commit/4c480405d7bb9416b9dfa49d418bb75a045f3ce2) to make it wait for the card to render, but it has been reverted.

**Environment**
 - Anki version: 2.1.60 QT6
 - OS: Linux (Arch)
 - Scheduler version: v3.14.3
 
**Screenshoots**
![image](https://user-images.githubusercontent.com/5121875/221770937-159a799b-cef5-42a8-a5e3-4c77195f6867.png)
After going back to main screen and back to study
![image](https://user-images.githubusercontent.com/5121875/221771393-3e0020f3-fa9a-4952-9475-fadc89615d8d.png)

The position of the div doesn't seem to matter. I've had it on top of the card and the issue was also present.

**Comment by L-M-Sherlock** [comment]
I need help from dae. I report it in the Anki forum: https://forums.ankiweb.net/t/enhancement-block-review-js-until-the-cards-front-is-rendered/27984

**Comment by L-M-Sherlock** [comment]
Related issue at Anki: https://github.com/ankitects/anki/pull/2421

**Comment by tkozybski** [comment]
What if the state mutator would provide that deck name, not just customData? There would be no need to modify decks for them to work with FSRS4Anki, making it more user-friendly. 

It could also provide note and card types. That would allow even more granular control o FSRS settings besides deck name.

**Comment by L-M-Sherlock** [comment]
Anki 2.1.61 Beta 2 has solved this issue: https://betas.ankiweb.net/anki2.1.61.html#beta-2

**Comment by tkozybski** [comment]
Great! I see it in the release notes of 2.1.61. This bug can now get fixed.

**Comment by L-M-Sherlock** [comment]
2.1.61 has been released, so I closed this issue.

**Comment by tkozybski** [comment]
> 2.1.61 has been released, so I closed this issue.

@L-M-Sherlock 2.1.61 only exposed the deck name and the seed in the context, but it still needs to be implemented in FSRS, right?

**Comment by L-M-Sherlock** [comment]
Oh, you remind me. I will update the scheduler to get the deck name automatically after 2.1.61.
