### ISSUE TITLE
[BUG] Seems like a lot of variables are missing now (deckName, w, requestRetention, etc.)

### ISSUE THREAD

**Issue by kylegoetz** [open-spaced-repetition/fsrs4anki#173]
**Describe the bug**
When I try to run reschedule now, I get the error message:

"The number of deckName, w, requestRetention, maximumInterval, easyBonus, or hardInterval unmatch.
Please confirm each item of deckParams have deckName, w, requestRetention, maximumInterval, easyBonus, and hardInterval."

This used to work. Anki has auto-updated the plugin a couple times since I got the plugin to work a few weeks ago. This is the first time I'm trying it again.

**Environment**
 - Anki version: 2.1.56
 - OS: MacOS 12.0.1
 - Scheduler version: The JS code pasted into options is "FSRS4Anki v3.9.6 Scheduler Qt6"
 - Plugin? I suppose whatever the latest is since when Anki prompted me to update my plugins I said OK.

**Comment by L-M-Sherlock** [comment]
I recommend updating to the latest scheduler. Or you should check whether you omit these variables in the red box:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/32575846/221948631-efd4e7d6-d495-4694-b548-58733e03dd83.png">

**Comment by kylegoetz** [comment]
Nope, those variables are all there, and the plugin just updated in Anki this morning, same issue. Right at the top of my options:

```javascript
// FSRS4Anki v3.9.6 Scheduler Qt6
set_version();
// The latest version will be released on https://github.com/open-spaced-repetition/fsrs4anki

// Default parameters of FSRS4Anki for global
//var w = [1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1];
var w = [0.3475, 0.744, 5.5054, -0.9453, -1.0023, 0.0151, 1.1452, -0.163, 0.5697, 1.6265, -0.5263, 0.7607, 0.9741];

// The above parameters can be optimized via FSRS4Anki optimizer.

// User's custom parameters for global
let requestRetention = 0.9; // recommended setting: 0.8 ~ 0.9
let maximumInterval = 36500;
let easyBonus = 1.3;
let hardInterval = 1.2;
```

**Comment by MNastri** [comment]
Those you mentioned are the global parameters.  

The ones in the red box are for specific decks and are further down the code.

Please check if the specified decks there are missing any of their parameters

**Comment by kylegoetz** [comment]
I see. So if the plugin updates you have to manually replace old JavaScript code in the options with new stuff, and copy and paste the custom data from one to the other.

Since Anki auto-updates my plugins, I had no idea this had happened. Also it looks like this kicked in a while back and the scheduler might have been silently failing the whole time? Because I just applied the rescheduler after fixing this and 700+ new cards just showed up due beyond the 200 I already had.

**Comment by MNastri** [comment]
> I see. So if the plugin updates you have to manually replace old JavaScript code in the options with new stuff, and copy and paste the custom data from one to the other.

The plug-in is backward compatible with the old Javascript code and, as far as I know, it doesn't change your custom scheduler, it just reads from it.
If you changed the code to add specific decks you may have deleted/not copied some of the code.

> Since Anki auto-updates my plugins, I had no idea this had happened. Also it looks like this kicked in a while back and the scheduler might have been silently failing the whole time? Because I just applied the rescheduler after fixing this and 700+ new cards just showed up due beyond the 200 I already had.

I'm not sure that this is what happened, but I'll check if the code is missing any obvious warning later when I get home.

**Comment by kylegoetz** [comment]
I've never updated the JS since the first time I configured the `w`. It worked and rescheduled when I did the "reschedule cards" feature for my deck -> options. That was I guess January at some point. Then I never did anything manually again until yesterday or day before, when I tried the exact same procedure and got the error message I mentioned above.

The only change was allowing Anki to update the plugin itself. I never touched the JS.

And then like I said, when I tried the manual deck -> options reschedule thing, 700+ cards showed up due that weren't before I did that. Reverted to a backup after the hospital revived me from my heart attack :)

**Comment by kylegoetz** [comment]
FWIW i looked through the commits to the scheduler JS file since the first commit in Jan to the file, and I didn't see anything that jumped out at me. Looks like there was the extraction of user's config data (w, deck name, etc) to an object instead of independent variables, and the ability to enable some sort of info on your cards. (I also saw some comment about needing to add some code to the front of your card template, which I haven't done but seems like it's for deck-specific rather than global config).

I guess I should take a look at the Python for the plugin next myself.

**Comment by L-M-Sherlock** [comment]
> ```js
> //var w = [1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1];
> ```

This comment caused the problem. The add-on uses regex to extract parameters from the scheduler code. This line was extracted, too.

**Comment by kylegoetz** [comment]
You've got to be kidding me.

**Comment by kylegoetz** [comment]
@L-M-Sherlock OK so in this case, the JS has been correctly scheduling the whole time, but it's just when I run the Python a couple days ago, the advancement of 700-ish cards to be immediately due is the incorrect behavior?

**Comment by L-M-Sherlock** [comment]
> OK so in this case, the JS has been correctly scheduling the whole time, but it's just when I run the Python a couple days ago, the advancement of 700-ish cards to be immediately due is the incorrect behavior?

The rescheduling a couple days ago could use the wrong parameters.
