### ISSUE TITLE
[Question] New Stability after Recall formula

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4anki#178]
I noted that the formula for the new Stability after recall shown in https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler#formula differs from that shown in https://github.com/open-spaced-repetition/fsrs4anki/wiki/Auto-migrate-from-SM-2-to-FSRS (the difficult term changes).

Which one is currently in use?

**Comment by L-M-Sherlock** [comment]
The first.  I will update the second document.
