### ISSUE TITLE
[Question] -----suggested retention (experimental): 0.92-----

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#181]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I've been optimizing my deck every 15 days and I've always seen this message: "suggested retention (experimental)".
It always returned a value of 0.90.

But this time it returned 0.92.

![image](https://user-images.githubusercontent.com/42243532/223401737-9096115e-d53e-4a72-b39a-632c8f99451e.png)

In practice, what changes if I leave it at 0.90 or change 0.92 with respect to the new weights?
And why does he now recommend 0.92?

What "changed" in my study?

**Comment by L-M-Sherlock** [comment]
The optimizer would suggest high retention for easier cards. Maybe the number of easy cards increased in your collection.

**Comment by cjdduarte** [comment]
But what changes if I change to 0.92?
Will the cards come more or less frequent?

**Comment by user1823** [comment]
The cards will become **more frequent**. But you will forget less of them. So, overall, it _might_ decrease the total time spent doing the cards. Though, the total time spent can also increase.

**Comment by cjdduarte** [comment]
Tanks
