### ISSUE TITLE
[Feature Request] helper & custom scheduler: Do not increase difficulty if review fails during (re-)learning phase (learning steps)

### ISSUE THREAD

**Issue by fredsilon** [open-spaced-repetition/fsrs4anki#183]
I wouldn't expect the helper / custom scheduler to treat the following example (see picture below) as a difficult card. However, it seems fsrs4anki treats fails during learning or relearning the same as during review to increase the difficulty.

I suggest that fails during learning or relearning do not increase the difficulty.

Maybe make the related behaviour configurabile: something like *Modify difficulty (d) during (re-)learning: yes / no*

(See example below: This behaviour led to the reduction of the interval from 9.3 years (Anki sched.) to 1.8 years (helper))
![Screenshot_20230308_225307](https://user-images.githubusercontent.com/1548138/223860198-e9c40c51-f4ca-4d5a-84c0-42af715ad40c.png)

**Comment by fredsilon** [comment]
I also used the optimizer to retrieve custom w parameters …
```
[1.2039, 1.57, 5.0212, -1.0422, -1.222, 0.0112, 1.6529, -0.1446, 1.0232, 1.9466, -0.2239, 0.526, 1.2608]
```

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/223894659-e97d9df9-b846-47c5-87fb-d96d344eee19.png)

FSRS has ignored these reviews because FSRS would ignore the reviews with elapsed days shorter than one day.

**Comment by fredsilon** [comment]
I guess I have to review the code to learn more in detail how FSRS behaves. I think this issue is a misconception from my side. --> I close it for now.

thanks :)

**Comment by fredsilon** [comment]
Maybe this needs to be revisited? I think the very first review will set the initial d and s, regardless of elapsed time < 1d.
(not a bug, but a feature maybe) … however I would like to have the first *graduating step* as defining regarding d and s


e. g.

with
```
    "w": [1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1]
```

**I would expect: d=5, s=3 … (with first graduating step with grade = 3)**

Actually it behaves like:

## As expected
![grafik](https://user-images.githubusercontent.com/1548138/223968591-5fef8b32-e127-4df8-837b-a12ece1c6415.png)

![grafik](https://user-images.githubusercontent.com/1548138/223967619-b5dcc3b5-d999-4cfe-af5e-e9f693319473.png)

## Not as expected
![grafik](https://user-images.githubusercontent.com/1548138/223967838-c9e7989b-5784-475a-ae01-cdd89f47f6bc.png)

![grafik](https://user-images.githubusercontent.com/1548138/223968118-91aa4570-44c5-437b-8149-715540050748.png)

![grafik](https://user-images.githubusercontent.com/1548138/223968787-a63fd771-b8e6-4432-9837-6562633ecb7a.png)

![grafik](https://user-images.githubusercontent.com/1548138/223971893-31beeac3-4e69-40f2-9129-1cf7663d8dda.png)

## Remark
I used
![grafik](https://user-images.githubusercontent.com/1548138/223970220-b151156d-b9d1-4f8a-be5c-5900bc314a15.png)
to quickly generate the test data.

**Comment by L-M-Sherlock** [comment]
> Maybe this needs to be revisited (maybe with a different issue?) I think the very first review will set the initial d and s, regardless of elapsed time < 1d.
> (not a bug, but a feature maybe) … however I would like to have the first _graduating step_ as defining regarding d and s

According to my paper, the first review is very important. So FSRS is deliberately designed to set the initial d and s at the first rating.

By the way, he first graduating step's ratings only could be 'good' and 'easy'.
