### ISSUE TITLE
[Question] Isn't the Fuzz formula making the "max" value too long?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#184]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Carrying out the tests here I noticed a tendency, mainly with the load balancer activated, of the cards tending to the "right" (farther).

Reading the implemented formula, it is similar to the one in v2:

**FRSR:**
![image](https://user-images.githubusercontent.com/42243532/223885550-84745b38-21db-478e-bb27-7f4f211e13cd.png)

Note that max_ivl has no limit, while min_ivl has a maximum limit of 2.

Reading the function in Anki's V2 found at: **Link**: [V2.py](https://github.com/ankitects/anki/blob/ankidroid-2.1.55/pylib/anki/scheduler/v2.py)

![image](https://user-images.githubusercontent.com/42243532/223885963-be255d0f-fd57-488f-b888-cf0b98ff0406.png)

It limits both min_ivl and max_ivl.

What I evaluated is that the FSRS max_ivl has no size limit.

**Wouldn't it be an opportunity to change to this other?**

**Comment by L-M-Sherlock** [comment]
The fuzz formula is implemented in V3 differently from V2. I don't see the limit.

https://github.com/ankitects/anki/blob/a32c7a8e63019da73be0e36d9f8e1553922bd6d1/rslib/src/scheduler/states/fuzz.rs#L35-L42
```rust
pub(crate) fn with_review_fuzz(&self, interval: f32, minimum: u32, maximum: u32) -> u32 {
    if let Some(fuzz_factor) = self.fuzz_factor {
        let (lower, upper) = constrained_fuzz_bounds(interval, minimum, maximum);
        (lower as f32 + fuzz_factor * ((1 + upper - lower) as f32)).floor() as u32
    } else {
        (interval.round() as u32).clamp(minimum, maximum)
    }
}
```

```rust
fn constrained_fuzz_bounds(interval: f32, minimum: u32, maximum: u32) -> (u32, u32) {
    let (mut lower, mut upper) = fuzz_bounds(interval);


    // minimum <= maximum and lower <= upper are assumed
    // now ensure minimum <= lower <= upper <= maximum
    lower = lower.clamp(minimum, maximum);
    upper = upper.clamp(minimum, maximum);


    if upper == lower && upper > 2 && upper < maximum {
        upper = lower + 1;
    };


    (lower, upper)
}


fn fuzz_bounds(interval: f32) -> (u32, u32) {
    let delta = fuzz_delta(interval);
    (
        (interval - delta).round() as u32,
        (interval + delta).round() as u32,
    )
}


/// Return the amount of fuzz to apply to the interval in both directions.
/// Short intervals do not get fuzzed. All other intervals get fuzzed by 1 day
/// plus the number of its days in each defined fuzz range multiplied with the
/// given factor.
fn fuzz_delta(interval: f32) -> f32 {
    if interval < 2.5 {
        0.0
    } else {
        FUZZ_RANGES.iter().fold(1.0, |delta, range| {
            delta + range.factor * (interval.min(range.end) - range.start).max(0.0)
        })
    }
}
```

**Comment by cjdduarte** [comment]
Sorry, I believe I simulated the wrong calculation.
I'll follow up and if that's the case, I'll open another question.

Thanks again.
![image](https://user-images.githubusercontent.com/42243532/223983020-6b4897cf-94fe-4378-a6e8-07b0baa30c2c.png)
