### ISSUE TITLE
[Question] Why review Intervals have some super long intervals after rescheduling

### ISSUE THREAD

**Issue by tempura-shrimp** [open-spaced-repetition/fsrs4anki#186]
**Research**

I have followed the guide to trained the optimizer and rescheduled the deck with helper. And I noticed my review interevals becomes super long, I have almost 50% of the cards have intervals more than 150days:

![image](https://user-images.githubusercontent.com/4588539/224563400-8080cab2-c97c-4424-b21a-d7a11f0bd456.png)

I tried with default parameter, and the intervals graph is similar.

**Question**
Is this normal or I messed something up?

**Comment by tempura-shrimp** [comment]
I also tried to set `"maximumInterval": 150,`

The intervals graphs becomes:

![image](https://user-images.githubusercontent.com/4588539/224563558-88bc8256-bdad-4543-a4f2-f7086a0d27c5.png)


Which doesnt make sense to me as well

**Comment by L-M-Sherlock** [comment]
> I have followed the guide to trained the optimizer and rescheduled the deck with helper. And I noticed my review interevals becomes super long, I have almost 50% of the cards have intervals more than 150days:

Could you share the analysis generated in the optimizer?

**Comment by L-M-Sherlock** [comment]
Does this issue solve your problem?

https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/49
