### ISSUE TITLE
[Feature Request] Allow preserving deck options scheduler on sync

### ISSUE THREAD

**Issue by johtso** [open-spaced-repetition/fsrs4anki#192]
Currently every time I sync from Ankidroid, it overrides my scheduler with an old version.

I'm sure at some point Ankidroid's handling of v3 scheduler stuff will improve, but until then it would save me so much hassle to be able to define my scheduler somewhere that fsrs can override the options scheduler with after every sync.

Currently I have to copy and paste my scheduler code into the deck options _after every sync_ and do a reschedule.

It's _highly_ unlikely you'll actually want to modify the scheduler on your phone (not sure if you even can?) so it would be great if fsrs could prevent it from happening.

I guess in theory you might be using it or more than one computer, but it could be optional.

Any other ideas appreciated!

**Comment by user1823** [comment]
I am using the latest alpha of AnkiDroid and I don't face this issue. Probably, the issue occurs only with the older versions of AnkiDroid.

The latest version of AnkiDroid (v2.16alpha94) can be downloaded here: https://github.com/ankidroid/Anki-Android/releases

**Comment by johtso** [comment]
@user1823 thanks for the heads up. I think I had some problem with the latest alpha so had to revert a couple of versions (2.16alpha92). I'll try that alpha out again and see what the deal was.

**Comment by L-M-Sherlock** [comment]
Same issue like: https://github.com/ankidroid/Anki-Android/issues/12866
