### ISSUE TITLE
 [Question] I want to know why the new card's first graduation interval is 5 Days? 

### ISSUE THREAD

**Issue by MJRT** [open-spaced-repetition/fsrs4anki#194]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**
I used fsrs4anki_optimizer.ipynb to generate parameter, and then some cards' first  graduation was put long to 5D.
I don't think that is a proper interval, but I can't know where is bug.
By the way, not all cards' first graduation interval is 5D, some cards remained 1D.

 "w": [0.9078, 1.0309, 5.2646, -0.7951, -0.6906, 0.0365, 1.2011, -0.1963, 0.5943, 1.7241, -0.4764, 0.2114, 0.7848]
![Snipaste_2023-03-26_23-15-04](https://user-images.githubusercontent.com/17826582/227785397-cbf42b64-d025-4d78-b37f-65c77155a8d9.png)
![Snipaste_2023-03-26_23-12-59](https://user-images.githubusercontent.com/17826582/227785269-847e620f-6ca7-4495-aa19-777162928fb0.png)

**Comment by Whitesttax** [comment]
I just installed and I had new cards going to 3 days, which is too much I need 1 day. I don't understand much about it but I changed my w following the answer here, maybe it helps you
https://github.com/open-spaced-repetition/fsrs4anki/issues/103

**Comment by L-M-Sherlock** [comment]
The initial stability is `w[0] + (rating - 1) * w[1]`. In your case, `w[0] = 0.9078` and `w[1] = 1.0309`. So the stability of `good` is 0.9078 + (3 - 1) * 1.0309 ≈ 3. And the interval depends on the initial stability and the requested retention, which you have not shown here.

**Comment by MJRT** [comment]
> The initial stability is `w[0] + (rating - 1) * w[1]`. In your case, `w[0] = 0.9078` and `w[1] = 1.0309`. So the stability of `good` is 0.9078 + (3 - 1) * 1.0309 ≈ 3. And the interval depends on the initial stability and the requested retention, which you have not shown here.

Ok, its explicable, the requested retention of my set that is 0.85. 

But I still think this time is not expected and too long, so I had rollback to anki default scheduler.

Thank you for @Whitesttax  and @L-M-Sherlock .

**Comment by galantra** [comment]
You could add a learning step of 1d
