### ISSUE TITLE
Overshooting retention rate by a large amount

### ISSUE THREAD

**Issue by mttr01** [open-spaced-repetition/fsrs4anki#197]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Been using the scheduler since January. Previously, I had a retention rate of 90%, and coming off of a period of using Anki a lot, I did about 50-80 reviews a day (declining). I followed the guide in the forum on how to implement the scheduler (that had a targeted retention of 90% by standard), and for the first week or so, I saw a great reduction in cards. That soon changed though, when the amount of reviews slowly began to creep up, along with my actual retention rate. I now do 150-180 reviews a day with a retention rate of 93% (going up) and it just seems to pile on more cards. I review on pc in the weekends and usually on Ankidroid (syncing and rescheduling using the add-on every day). I also believe that I've experienced a combination of issue open-spaced-repetition/fsrs4anki#192 and open-spaced-repetition/fsrs4anki-helper#116 before, although it seems like open-spaced-repetition/fsrs4anki#192 is resolved for me. I changed the target retention to 0.89 (which was my original plan too) and it has helped on the reviews a tiny bit, but 1) I don't know if it is the inconsistency of the scheduler, which sometimes gives me a bunch of cards, and 2) it seems like "symptomatic treatment".

**Comment by mttr01** [comment]
Revlogs = review logs, which I assume is the cut-off date right? I input "2022-07-01", which I believe to be 1st July

**Comment by L-M-Sherlock** [comment]
You can use the latest optimizer to generate parameters and evaluation:

![image](https://user-images.githubusercontent.com/32575846/235909689-a20ecfe9-9841-4f56-a8ad-4814198924a3.png)

This graph could help you check whether FSRS underestimated your retention and give you more reviews.

**Comment by mttr01** [comment]
![image](https://user-images.githubusercontent.com/22281511/236298444-75a8c405-b8e5-4556-9557-682cd93a70c6.png)
 
The cutoff date for the revlogs is the same as the above-mentioned. Looking my graph, the retention underestimated around the 90% mark. What does that mean I should do concretely? Do I purposely enter a lower retention rate?

**Comment by L-M-Sherlock** [comment]
Does this problem still preserve?

**Comment by L-M-Sherlock** [comment]
Inactive issue will be closed.
