### ISSUE TITLE
[Feature Request] Discriminate New from Learn

### ISSUE THREAD

**Issue by JeremiaWilliams** [open-spaced-repetition/fsrs4anki#198]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
I have cards set up so that I see them twice on the first day which they are new. I find that, if I get a new card immediately correct, the second time does not benefit me. If I get the new card wrong, then I need to see it twice that day before graduating it.

**Describe the solution you'd like**
Could you make it an option to discriminate interval options for new cards from the learning cards?

I would like "Good" on new cards to be 1 day, and all other intervals to be normal.

**Additional context**
I have tried implementing this myself by forcing `good_interval` to 1 day, but it didn't work:

```
if (is_new()) {
  init_states();
  const good_interval = 1;
```

**Comment by L-M-Sherlock** [comment]
> I have cards set up so that I see them twice on the first day which they are new. I find that, if I get a new card immediately correct, the second time does not benefit me. If I get the new card wrong, then I need to see it twice that day before graduating it.
> 
> 

Why not just use one learning step?

**Comment by L-M-Sherlock** [comment]
OK. I know your case. But FSRS cannot control the learning stage. Maybe you need to propose this issue at the Anki forum.
