### ISSUE TITLE
[Feature Request] Added functionality of reminding the user to do the optimiser via FSRS4Anki Helper addon

### ISSUE THREAD

**Issue by ufo12413** [open-spaced-repetition/fsrs4anki#199]
**Which module is related to your feature request?**
Scheduler, Optimizer, or Simulator?
Optimizer

**Is your feature request related to a problem? Please describe.**
The algorithm has been phenomenal but I am consistently forgetting that it is best for me to do the optimiser once a month.

**Describe the solution you'd like**
Is there any chance that the FSRS4Anki Helper addon would add the functionality of reminding the user to do the optimizer in a set interval?

**Describe alternatives you've considered**
I tried external reminders but does not seem intuitive enough.

**Additional context**
None

**Comment by L-M-Sherlock** [comment]
Why not just use the calendar app to remind you? Embedding this feature to the add-on would be annoying to someone.
