### ISSUE TITLE
[Feature Request] Optimize parameters on data after a certain date/time

### ISSUE THREAD

**Issue by kuroahna** [open-spaced-repetition/fsrs4anki#2]
When exporting the anki collection and using fsrs4anki_optimizer to optimize the parameters on the revlog, the optimizer will use all time series data in the revlog. I think this is good since we need lots of data to get accurate results. However, I have used Anki wrong in the past where my retention rate would be really low, like 60-70%. Only recently I have fixed the issue and my retention rate in Anki is around 80-85%. However, since fsrs4anki_optimizer uses the whole revlog, it will include the data from when I reviewed cards poorly, meaning the parameters returned will be skewed, and hence there will be a bias to give short intervals

It would be nice if we can optionally specify a certain date for when the optimizer will start processing the data, such as

```
revlog_start_date = "2022-04-01"
```

Otherwise, if not specified (such as a default value of `None`), it will use the whole revlog data

**Comment by L-M-Sherlock** [comment]
The latest version has supported it.
