### ISSUE TITLE
[Feature Request] Add some useful stats

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#202]
**Which module is related to your feature request?**
Scheduler.

**Describe the solution you'd like**
For all cards that have been reviewed multiple times (and FSRS kicked in) calculate predicted R, then calculate the average of those Rs. This will give the user an estimate of how much knowledge he currently has. For example, if average R is 85%, this means that the algorithm is expecting the user to know about 85% of all cards at this given moment in time. 

Another idea (which I stole from Supermemo) - **Burden**, the sum of reciprocals of all intervals, in days (aka the sum of 1/interval, like 1/I1 + 1/I2 + 1/I3...+ 1/In). If a card's interval is 100 days, it means that, on average, the user will see it 1/100 times per day. So **Burden** is an estimate of how many reviews user needs to do per day, on average. By multiplying it by the average time spent per review (**Average Review Time**), you can obtain **Expected Workload**, an estimate of the average amount of time needed to study per day. If Burden=300 cards per day and Average Review Time=12 seconds, that means that on average user needs 300*12=3600 seconds per day to finish all reviews, that's his Expected Workload. I don't know if Anki keeps track of all review times (it's necessary to calculate Average Review Time), if it doesn't - well, just implement the Burden alone then.
EDIT: now that I think about, Burden has a problem - since cards can have very short (for example, 5 minutes) intervals, if you convert that to days and take a reciprocal, you will end up with a very large number, and I'm pretty sure. I'm not sure if it's better to cap the value of the reciprocal (for example, make it so that it cannot be larger than 2), or to just exclude cards with intervals shorter than 1 day entirely. SuperMemo wiki page doesn't say anything about this. After thinking about it, I think capping the reciprocal at 1 is the most reasonable approach. So like:
if 1/interval > 1:
    1/interval = 1

**Comment by L-M-Sherlock** [comment]
This feature would be related to the add-on. And I guess what you need is something like True Retention add-on.

**Comment by Expertium** [comment]
Yeah, I know. Since you haven't closed this yet, I'm assuming you plan to implement the stats that I suggested?

**Comment by L-M-Sherlock** [comment]
Yep, I'm looking at the code of True Retention.

**Comment by L-M-Sherlock** [comment]
> For all cards that have been reviewed multiple times (and FSRS kicked in) calculate predicted R, then calculate the average of those Rs.

Should it include the suspended cards?

**Comment by L-M-Sherlock** [comment]
My current progress: ![image](https://user-images.githubusercontent.com/32575846/231799852-9ef96eb3-81ea-417f-a8bd-387484b50e07.png)

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/232191212-5c81c286-8ea1-4517-8a4f-5ea7f4130a66.png)

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/11238584/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
I tried this and got the following stats:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/92206575/232223804-e29689a4-7ea0-429b-bfe5-0d3224e9adf8.png">

This seems to be good. But, I have the following points to share:
- There should be units for all the stats.
- The stats are not shown when the "True Retention" add-on is enabled.
- An explanation should be added for each of the stats shown.

**Comment by L-M-Sherlock** [comment]
> * Currently, the stats are not shown when the "True Retention" add-on is enabled. This should be fixed.

I can't reproduce this bug.

![image](https://user-images.githubusercontent.com/32575846/232234243-fa24e571-884c-4ecf-a772-4a1561e2066a.png)

**Comment by user1823** [comment]
Sorry for the confusion. I am using a newer version of the add-on.

Link: https://ankiweb.net/shared/info/923360400

**Comment by Expertium** [comment]
1. Is stability measured in days? Isn't it 1/time (so like day^-1), since r=e^-t/S, so the units of S should be the inverse of the units of t, so they cancel out?
2. Burden is measured in reviews/day. Btw, it would be nice if you added Expected Workload (seconds or minutes per day) as well.
3. I looked at the code at https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/cd0af7f230c35f9aa31f96fe2133e7a5bdb7e9f6, and while I am no code wizard, I don't see the part that would be responsible for limiting 1/interval to 1 max.
4. I'm assuming "Count" is the number of all cards that have been reviewed at least once?

**Comment by user1823** [comment]
> since r=e^-t/S, so the units of S should be the inverse of the units of t, so they cancel out?

If r = e^(-t/S), the units of t and S should be the same!!

> Burden is measured in reviews/day. 

I agree.

**Comment by L-M-Sherlock** [comment]
> * An explanation should be added for each of the stats shown.

![image](https://user-images.githubusercontent.com/32575846/232235312-26e16a10-4528-411e-924a-ab281cf5eee3.png)

**Comment by L-M-Sherlock** [comment]
> Sorry for the confusion. I am using a newer version of the add-on.
> 
> Link: https://ankiweb.net/shared/info/923360400

I read the code of this add-on. This add-on overwrites the stats instead of appending new info. So I can't fix it in my code.

**Comment by L-M-Sherlock** [comment]
> Sorry for the confusion. I am using a newer version of the add-on.
> 
> Link: https://ankiweb.net/shared/info/923360400

I read the code of this add-on. This add-on overwrites the stats instead of appending new info. So I can't fix it in my code.

**Comment by L-M-Sherlock** [comment]
> Sorry for the confusion. I am using a newer version of the add-on.
> 
> Link: https://ankiweb.net/shared/info/923360400

I read the code of this add-on. This add-on overwrites the stats instead of appending new info. So I can't fix it in my code.

**Comment by Expertium** [comment]
> If r = e^(-t/S), the units of t and S should be the same!!

Oh wait, you're right, I had a brain fart.

**Comment by user1823** [comment]
> > * An explanation should be added for each of the stats shown.
> 
> ![image](https://user-images.githubusercontent.com/32575846/232235312-26e16a10-4528-411e-924a-ab281cf5eee3.png)

Not like that. I think that a more detailed explanation should be added, probably as separate paragraphs.

**Comment by user1823** [comment]
> I read the code of this add-on. This add-on overwrites the stats instead of appending new info. So I can't fix it in my code.

Ok. Can you suggest me a change that I can make in the True Retention add-on myself to fix the issue?

**Comment by L-M-Sherlock** [comment]
The code is a little complicated. I will do more research tomorrow.

**Comment by L-M-Sherlock** [comment]
> Anyway, cap 1/interval at 1.

When the card is in review queue, its interval is always bigger than one day. So it is unnecessary to cap it.

**Comment by user1823** [comment]
> The code is a little complicated. I will do more research tomorrow.

Leave it. I fixed it myself.

Just suggest me how can I convert the folder containing the add-on files into a .ankiaddon file. Just zipping the folder using Windows File Explorer and changing the extension from .zip to .ankiaddon didn't work because Anki showed the message "Invalid add-on manifest".

**Comment by Expertium** [comment]
> When the card is in review queue, its interval is always bigger than one day. So it is unnecessary to cap it.

Sorry, I don't understand. You can make learning steps smaller than 1 day, FSRS doesn't affect learning steps. So how then are intervals never shorter than 1 day? Or does it only work for cards that are in the "mature" stage (after learning steps)? If so, then it will severely underestimate the burden.

**Comment by user1823** [comment]
> If so, then it will severely underestimate the burden.

I don't think so. How many cards in your collection are currently in the "learn" stage? There are none in mine. (I have already with the cards due today).

**Comment by L-M-Sherlock** [comment]
> Sorry, I don't understand. You can make learning steps smaller than 1 day, FSRS doesn't affect learning steps.

These cards are in learn queue or relearn queue. They have been excluded in the stats.

**Comment by Expertium** [comment]
Well, as I said, if they are not included burden will be underestimated.

**Comment by L-M-Sherlock** [comment]
> Just suggest me how can I convert the folder containing the add-on files into a .ankiaddon file. Just zipping the folder using Windows File Explorer and changing the extension from .zip to .ankiaddon didn't work because Anki showed the message "Invalid add-on manifest".

You need to create a file like this: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/main/manifest.json

**Comment by L-M-Sherlock** [comment]
> Well, as I said, if they are not included burden will be underestimated.

I will add the number of (re)learning cards to the burden.

**Comment by Expertium** [comment]
Ok, just cap them, otherwise cards with intervals like 5m or 15m will inflate burden too much. I mean, nobody is going to be reviewing a card EVERY 5 minutes for 24 hours straight.

**Comment by L-M-Sherlock** [comment]
Current progress:

![image](https://user-images.githubusercontent.com/32575846/232266234-4436141a-b080-488a-b321-381654ace9a6.png)

**Comment by user1823** [comment]
The correct units for burden should be `reviews/day`.

Also, add bullet points in the interpretation section to make it easier to read.

**Comment by Expertium** [comment]
Good job! 

So my question is - does Anki store all info about review times (how many seconds the user took to review a card)?  If it does, then there are 2 more useful stats to add.

**Comment by L-M-Sherlock** [comment]
> So my question is - does Anki store all info about review times (how many seconds the user took to review a card)? If it does, then there are 2 more useful stats to add.

Anki stores the review time per repetition in `revlog` table. The current FSRS stats only query the `card` table.

**Comment by user1823** [comment]
@Expertium

How is Burden different from Anki's Average Reviews per day?
I know that they are calculated differently. But, which one is a better indicator of the average number of reviews you will need to do per day? And why?

**Comment by Expertium** [comment]
I'm not sure what you mean by "Average reviews per day" here, and I can't use my desktop version right now, so I would appreciate it if you screenshot this stat.

If it is what I think it is, a an average based on your *past* reviews, then it won't change if you reschedule cards in any way. Meanwhile Burden will change. For example, if you change your desired retention in FSRS.

**Comment by user1823** [comment]
I am talking about the "Average" stat below the graph.

<img width="434" src="https://user-images.githubusercontent.com/92206575/232308826-5a884ba6-4430-4a55-bdd7-d336fecbe1be.png">

**Comment by user1823** [comment]
My FSRS stats are as follows:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/92206575/232309041-d8fe6ea0-2456-4c38-9fa4-305db4e36a3c.png">

I also found an issue with the FSRS stats. They don't consider the deck selected. That is, all decks have the same FSRS stats.

**Comment by Expertium** [comment]
Check Anki stats and FSRS stats for your entire collection, is Average in Future Due (select "all", not "1 month") significantly different than Burden? Show me both.

> That is, all decks have the same FSRS stats.

You might want to open a new issue then.

**Comment by user1823** [comment]
Here are the Anki stats and the FSRS stats for the same deck:
<img width="434" src="https://user-images.githubusercontent.com/92206575/232308826-5a884ba6-4430-4a55-bdd7-d336fecbe1be.png">
<img width="237" alt="image" src="https://user-images.githubusercontent.com/92206575/232310142-e786a4f4-9ba8-47fa-9f2c-a4f27130ee70.png">

(I obtained these by exporting the deck and importing in a new profile.)

As you can see, the burden is roughly the double of the Anki's average number of reviews per day.

**Comment by Expertium** [comment]
Please select "all" and screenshot again.
![Uploading 20230416_153627.png…]()

**Comment by user1823** [comment]
> Please select "all" and screenshot again.

Here you go:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/92206575/232312007-94fa48e2-20af-41c4-8ed5-eb0b08f9bb9a.png">

"All" gives poor results because it doesn't consider that I will someday review a card and it will become due again sometime later.

**Comment by Expertium** [comment]
Huh. Ok, I have no idea how it's calculated then, so I can't compare it to Burden.

**Comment by L-M-Sherlock** [comment]
> in the [Statistics window](https://help.supermemo.org/wiki/Statistics), a number which estimates the average number of [elements](https://help.supermemo.org/wiki/Glossary:Element) that have to be repeated daily (this statistic may overestimate the workload in [collections](https://help.supermemo.org/wiki/Glossary:Collection) where [Postpone](https://help.supermemo.org/wiki/Postpone) is used often):

https://help.supermemo.org/wiki/Glossary:Burden

**Comment by L-M-Sherlock** [comment]
Only Woz know what it means (lol).

**Comment by Expertium** [comment]
No, the meaning of Burden is pretty clear (I mean, just look at the formula), the question is whether Burden is better than average in Future Due.

**Comment by user1823** [comment]
> Huh. Ok, I have no idea how it's calculated then, so I can't compare it to Burden.

I can explain how that Anki's stat works.

It takes all cards and sees how many are due in the next month, 3 months, next 1 year, etc.

It then divides the number of cards by the number of days to obtain the average.

**Comment by user1823** [comment]
For the above example, 2912 reviews ÷ 31 days ≈ 94 reviews/day.

**Comment by Expertium** [comment]
Ok, so Anki stat assumes that after you review a card you will never see it again, otherwise I can't explain why it would give such a low number. Burden assumes that you will keep seeing that card, but with the same interval.

Yeah, I guess neither is very accurate, you'd have to make a proper simulator to get an accurate number.

**Comment by Expertium** [comment]
But that one doesn't use FSRS.

Meanwhile this obviously does: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb

Is it possible to run your simulator and then pass the results to the stats window?

**Comment by user1823** [comment]
> Ok, so Anki stat assumes that after you review a card you will never see it again, otherwise I can't explain why it would give such a low number when you select "all". Burden assumes that you will keep seeing that card, but with the same interval.

So, I think that the average between the two stats is a reasonably good estimate of the number of reviews you will need to do.

> Is it possible to run your simulator and then pass the results to the stats window?

I don't think that it is possible. Also, even if it was possible, it would be too slow.

**Comment by Expertium** [comment]
> So, I think that the average between the two stats is a reasonably good estimate of the number of reviews you will need to do.

Nah, the errors would have to cancel out *miraculously* well for such a trick to be accurate.

> I don't think that it is possible. Also, even if it was possible, it would be too slow.

Oh well, that's unfortunate. I don't know whether Burden should be removed or no. I mean, it's still somewhat useful, but it could also confuse people.

**Comment by user1823** [comment]
> > So, I think that the average between the two stats is a reasonably good estimate of the number of reviews you will need to do.
> 
> Nah, the errors would have to cancel out _miraculously_ well for such a trick to be accurate.

I don't say that it is an accurate estimate. I say that it is reasonably good.

> > I don't think that it is possible. Also, even if it was possible, it would be too slow.
> 
> Oh well, that's unfortunate. I don't know whether Burden should be removed or no. I mean, it's still somewhat useful, but it could also confuse people.

I don't think that it should be removed. Probably we can add an explanation that it might slightly overestimate the review burden.

**Comment by L-M-Sherlock** [comment]
> I mean, it's still somewhat useful, but it could also confuse people.

Few people could find this feature.
