### ISSUE TITLE
[Feature Request] I propose a modification to the FSRS algorithm

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#203]
**Which module is related to your feature request?**
Scheduler and Optimizer

**Describe the solution you'd like**
Currently, FSRS uses the good old formula: R=e^(-t/S). Here is a new formula that I propose: R'=B*R+(1-R)*A, 0 ≤ A < B ≤ 1.
B is the maximum value that probability of recall can reach, you can call it the upper limit, A is the minimum value (lower limit). A and B will be optimized the same way as the other parameters, and the calculation of S will be unaffected.
I made a short video where I show what this new function looks like and explain a few things: https://i.imgur.com/yb2Vb6o.mp4
I could write my speculations as to why I think this will be an improvement, but the good thing about machine learning is that you don't really have to speculate, you can just try it and see how it affects the loss.
1. Optimize FSRS parameters on whatever dataset you want and record the value of the loss function afterwards.
2. Implement this new formula (R' will be used as the output), optimize FSRS parameters plus these 2 new parameters and record the value of the loss function afterwards.
3. Compare the values of the loss function. If this modification results in lower loss - great!
It's a pretty simple and straightforward modification that is easy to understand, easy to implement and easy to test against the original FSRS.

EDIT: oh, I forgot, here is the inverse function in case you need to find t (interval) knowing R', S, A and B. The inverse is t=S*ln((A-B)/(A-R'))

**Comment by L-M-Sherlock** [comment]
I argue that retention is 100% when the elapsed time is 0.

![image](https://user-images.githubusercontent.com/32575846/230367679-afb15e1e-efa9-4140-a570-0e0777324833.png)

Using  R=e^(-t/S) to fit the forgetting curve is good enough.

The data is from the open-source dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VAGUL0
