### ISSUE TITLE
[Feature Request] Optimizer Addon

### ISSUE THREAD

**Issue by spartandrew18** [open-spaced-repetition/fsrs4anki#204]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Will you ever consider incorporating the optimizer into an addon for anki? It would be ideal to have everything packed into 1 addon. Is this possible? Or is the code too large to run in anki?

**Comment by L-M-Sherlock** [comment]
The optimizer requires PyTorch, which is a large package in Python. And it could induce many compatible problems in cross-platform.

Maybe I will implement the optimizer into Anki. But it would be developed after we integrate FSRS into Anki: https://github.com/ankitects/anki/issues/2443
