### ISSUE TITLE
Rerunning optimizer [Question]

### ISSUE THREAD

**Issue by shmuelsash** [open-spaced-repetition/fsrs4anki#208]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I see online that you suggest rerunning the optimiser about 1x per month. Is there any reason not to run it more often?

Also, when rerunning it, which date do we put it? The original date we chose or the last time we ran the optimiser?

**Comment by L-M-Sherlock** [comment]
No, it's just for illustration. By the way, the parameters would be stable if the size of data is large enough. So the frequency would be not very important.

**Comment by shmuelsash** [comment]
Ok great

I find that FSRS makes the # of reviews per day decease but the cards are
much harder for me to remember (which I feel is a good thing, instead of
showing me easy cards it's focusing me on material I have a harder time
with)

Ideally I'd want to do as few reviews as necessary so if that means running
the optimizer each week I'm ok with that. Just don't want it to hurt me
