### ISSUE TITLE
[BUG] Read deck name and seed from ctx will recognize the filtered deck as the deck name.

### ISSUE THREAD

**Issue by Vitorvlv** [open-spaced-repetition/fsrs4anki#213]
When using filtered decks the new behavior will recognized the filtered decks name as the deck name, instead of the original deck the card was pulled from.

**Comment by L-M-Sherlock** [comment]
Oh, it is inconsistent with the old behavior. I need help from Dae. I will report it in [Anki Forums](https://forums.ankiweb.net/).

**Comment by L-M-Sherlock** [comment]
You can track this issue here: https://forums.ankiweb.net/t/inconsistent-read-deck-name-and-seed-from-ctx-will-recognize-the-filtered-deck-as-the-deck-name/29327

**Comment by L-M-Sherlock** [comment]
Anki 2.1.62 has solved this issue.

https://github.com/ankitects/anki/releases/tag/2.1.62
