### ISSUE TITLE
[Question] Ridiculously large "to Review" size after rescheduling & Expected time (10^5s), are they normal?

### ISSUE THREAD

**Issue by SolarBlaze** [open-spaced-repetition/fsrs4anki#214]
Is this normal? 
I've been playing with fsrs4anki, changing target retention within the recommended range, exporting my full collection, the specific vocab deck I am repping as deckpkg (which doesn't work) vs colpkg (which gives me the same results as exporting the entire thing, etc etc. 

Every time I get these huge expected time and when I apply it to my Anki end up having like 2k cards in reviews.

I would consider myself a quick repper, and while my retention is nothing great and even quite low by some people standards (hovering between 70-85% depending of the season) I typically decide if I know a card in less than 2 seconds making my review times pretty short. 
I've been repping this deck for over a year.

The fsrs4anki concept seems really interesting and I'd love to try it, but I don't think I am ready to review more than 10x my review load for the foreseeable future.

PS: I pass or fail all my cards, and been doing so for as far as I can remember, easy and hard basically don't exist to me. 
PS2: Well that's embarassing, I read a bit more and postponed cards. Still about double my usual load, but should be manageable, but the question still stands especially for the expected time.

[0.1088, 0.1031, 5.4702, -0.3355, -0.719, 0.0656, 1.0534, -0.1763, 0.4615, 1.5753, -0.5334, 0.5812, 0.6101]

<img width="525" alt="anki_8OliaO8IwD" src="https://user-images.githubusercontent.com/37492126/231539033-924b9b18-70d3-4a13-9264-dc34ab4c9d09.png">

![image](https://user-images.githubusercontent.com/37492126/231535241-814e0a1a-a46b-4665-93e2-1cc5966cb344.png)
![image](https://user-images.githubusercontent.com/37492126/231535347-f8425a7c-a3ec-4e2f-9882-2d83be59d814.png)
![image](https://user-images.githubusercontent.com/37492126/231537295-63cfbff5-1b95-47ff-a427-c32b84afd9dd.png)

**Comment by Vitorvlv** [comment]
> The fsrs4anki concept seems really interesting and I'd love to try it, but I don't think I am ready to review that more than 10x my review load for the next few days for the foreseeable future.

Then don't.  No need to reschedule all your cards. You can just reschedule the ones you did in the last 7 days. Or don't reschedule at all, just let FSRS start doing it's thing.

**Comment by SolarBlaze** [comment]
> > The fsrs4anki concept seems really interesting and I'd love to try it, but I don't think I am ready to review that more than 10x my review load for the next few days for the foreseeable future.
> 
> Then don't. No need to reschedule all your cards. You can just reschedule the ones you did in the last 7 days. Or don't reschedule at all, just let FSRS start doing it's thing.

Makes perfect sense and I am probably going to use FSRS using that method or something similar, if you don't mind me asking did you have an expected time similar to that? (Referring to the graph)

**Comment by L-M-Sherlock** [comment]
Could you share the analysis generated in section 1.2 `Create time-series feature & analysis` of the optimizer?

**Comment by kieranlblack** [comment]
@SolarBlaze you set the `requestRetention` in `deckParams` to be your desired retention, correct?

**Comment by SolarBlaze** [comment]
> @SolarBlaze you set the `requestRetention` in `deckParams` to be your desired retention, correct?

yep

**Comment by L-M-Sherlock** [comment]
The analysis shows that your retention is low during the initial few repetitions.

**Comment by L-M-Sherlock** [comment]
> If you mean the revlog I can send that too.

If you are willing to share it with me, I will do more research on your data.

**Comment by L-M-Sherlock** [comment]
I try to train your data in the latest optimizer:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/32575846/231920002-da8a002c-cb7c-49bc-bd7e-815a3f8eac58.png">

**Comment by SolarBlaze** [comment]
> I try to train your data in the latest optimizer:
> 
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/32575846/231920002-da8a002c-cb7c-49bc-bd7e-815a3f8eac58.png">

I see, this looks interesting but I hav to admit I have no idea what this is saying.
If you don't mind, could you explain what this graph means?

**Comment by L-M-Sherlock** [comment]
> If you don't mind, could you explain what this graph means?

According to the bar graph, in the prediction of FSRS, your retention of cards are mainly distributed between 0.6 and 0.9. 

The blue line plot (predicted retention, actual retention). Ideally, the blue line is align with orange line which means the prediction is perfectly accurate.

**Comment by L-M-Sherlock** [comment]
According to the prediction of FSRS, the predicted retention of your cards is lower than your requested retention. So these card intervals are shortened, which induces the ridiculously large "to Review" size after rescheduling.

**Comment by SolarBlaze** [comment]
> According to the prediction of FSRS, the predicted retention of your cards is lower than your requested retention. So these card intervals are shortened, which induces the ridiculously large "to Review" size after rescheduling.

Oh I see, sorry past week was really busy and I forgot to answer. Thanks a lot for your help!
