### ISSUE TITLE
[Feature Request] Add a button to reschedule only cards that have been reschedule within the last N days

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#216]
**Which module is related to your feature request?**
Helper add-on/Scheduler

**Is your feature request related to a problem? Please describe.**
FSRS doesn't work on AnkiDroid, so if I want to do reviews on my smartphone but still get the benefits of FSRS, I need a button to reschedule what has been reviewed in AnkiDroid.

**Describe the solution you'd like**
I really doubt that Anki keeps track of which reviews have been done in the desktop version, and which reviews have been done in AnkiDroid. However, if I know that I only used AnkiDroid, for example, today, that means I only need to reschedule cards that have been reviewed today. So here's what I want:
1. A button that says something like "Reschedule recently reviewed cards".
2. Once pressed, a window pops up and asks the user to enter a number (0=today, 1=yesterday, etc.).
3. Then only cards that have been reviewed within that number of days will be rescheduled using FSRS algorithm.

Or just automatically reschedule cards after sync each time ¯\\\_(ツ)_/¯

**Comment by L-M-Sherlock** [comment]
> * A button that says something like "Reschedule recently reviewed cards".

FSRS has supported this feature:

![image](https://user-images.githubusercontent.com/32575846/232304198-f96ada13-ec5f-41ed-9944-def4ae0d3353.png)

![image](https://user-images.githubusercontent.com/32575846/232304410-a74533c7-a957-4315-ba8d-f280f525b208.png)

**Comment by Expertium** [comment]
Wait, does it automatically reschedule cards after sync already? If so, then close this issue (I haven't used the desktop version in the last couple of days)

**Comment by L-M-Sherlock** [comment]
> Wait, does it automatically reschedule cards after sync already?

Of course.
