### ISSUE TITLE
To update the scheduler do I have to copy paste the new scheduler code and replace the old every time?

### ISSUE THREAD

**Issue by kimo-supremo** [open-spaced-repetition/fsrs4anki#218]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ ] I have searched for similar existing questions here

**Question**

**Comment by L-M-Sherlock** [comment]
After 3.14.0, you can keep the Configuration piece and replace the remaining part.

The configuration starts with `// Configuration Start` and ends with `// Configuration End`.

**Comment by kimo-supremo** [comment]
would be cool if the addon reminded me that an update for the scheduler is released and i should copy paste it

**Comment by user1823** [comment]
> would be cool if the addon reminded me that an update for the scheduler is released and i should copy paste it

To be notified of new releases, you can set a "Watch" on this GitHub repository.

![Screenshot_20230420-170734~2](https://user-images.githubusercontent.com/92206575/233355239-c40273a4-4e61-4ae0-99d3-46ba8081d626.png)
