### ISSUE TITLE
Long interval after only a few reviews [Question]

### ISSUE THREAD

**Issue by shmuelsash** [open-spaced-repetition/fsrs4anki#219]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
![image](https://user-images.githubusercontent.com/35056305/232352906-830875df-d978-4437-a795-0da47a383553.png)
Does it make sense that this card is due in so long after so few reviews? Because there's no way I'm gonna remember that in so long. If this is the intended effect of the scheduler how does it make sense?

P.S. This card was an overdue card after rescheduling with FSRS could it be that the "bonus" anki gives for overdue cards is what messed this up?

**Comment by L-M-Sherlock** [comment]
FSRS also gives overdue card "bonus". 

$$R(t,S) = 0.9^{\frac{t}{S}},$$

According to the above formula, the retrievability (R) is low when the delay is long.

$$S^\prime_r(D,S,R) = S\cdot(e^{w_6}\cdot (11-D)\cdot S^{w_7}\cdot(e^{w_8\cdot(1-R)}-1)+1).$$

The next stability increases when the retrievability decreases.

**Comment by L-M-Sherlock** [comment]
For more details about the memory model of FSRS, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler

**Comment by L-M-Sherlock** [comment]
You can increase your requested retention.
