### ISSUE TITLE
[BUG] Running optimizer falied with no clue

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#22]
**Describe the bug**

As subject
**To Reproduce**
1. Upload exported anki deck `linux-kernel.apkg`
2. Change the file name and timezone
3. Click on "Run all"
4. Program stopped at `2.2 Train the model`

**Screenshots**
![2022-09-23_16-28](https://user-images.githubusercontent.com/742238/192009369-c1f6fd16-0d0f-4170-b1bf-373f8c7bc94f.png)

**Environment**
 - Anki version: Dev version 2.1.55
 - OS: Arch Linux
 - Optimizer version: v1.0.3 on Google Colab

**Comment by L-M-Sherlock** [comment]
Can you use the latest version?

**Comment by YorkZ** [comment]
Correct me if I'm missing anything, but I thought the page on Google Colab is the one I'm supposed to use, and should be the latest one?

**Comment by L-M-Sherlock** [comment]
The latest version of optimizer is v1.4.0, and you can find it in current main branch.
![image](https://user-images.githubusercontent.com/32575846/192024676-85e2cee5-4e5d-40ee-bdc7-e21110e3aca1.png)

**Comment by YorkZ** [comment]
Sorry so did you mean that you haven't deployed it to Google Colab?

**Comment by L-M-Sherlock** [comment]
https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb

**Comment by L-M-Sherlock** [comment]
> Sorry so did you mean that you haven't deployed it to Google Colab?

You can click the button `Open in Colab` to deploy it.

**Comment by YorkZ** [comment]
Sorry this is my first time using Google Colab, and therefore I'm so confused. So what optimizer was I running, and where did it come from?

**Comment by L-M-Sherlock** [comment]
> Sorry this is my first time using Google Colab, and therefore I'm so confused. So what optimizer was I running, and where did it come from? 

You can paste the link of your colab page, or the version in the first cell of notebook.

**Comment by YorkZ** [comment]
I can't find the `Open in Colab` button.

**Comment by YorkZ** [comment]
Never mind found it.

**Comment by L-M-Sherlock** [comment]
Open this link,

https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb

In my screen, there is a `open in Colab` button.

![image](https://user-images.githubusercontent.com/32575846/192027953-ebb89bf8-d22d-415b-88f9-d57ed7ee0dd9.jpeg)

**Comment by YorkZ** [comment]
Yep, I finally found it before you posted this screenshot, but still, thanks a lot. So I guess I'd better to re-generate all my parameters right in v1.4.0 right?

**Comment by L-M-Sherlock** [comment]
> Never mind found it.

😂, there's high ping in Chinese network. I have just seen this comment.

**Comment by L-M-Sherlock** [comment]
> Yep, I finally found it before you posted this screenshot, but still, thanks a lot. So I guess I'd better to re-generate all my parameters right in v1.4.0 right?

Yes, it's improved. And you need use it with the newest FSRS4Anki scheduler.

**Comment by YorkZ** [comment]
Running version 1.4.0 with the same file still failed, please check the screenshot.

![2022-09-23_19-12](https://user-images.githubusercontent.com/742238/192040901-1ef9e3e6-971c-4457-8ee3-68187e7325a6.png)

**Comment by L-M-Sherlock** [comment]
Are there only nine review logs？

You can set `print_len` = 1. But I think it need more logs.

**Comment by YorkZ** [comment]
There were only there cards in this deck with 16 review history in total.

**Comment by L-M-Sherlock** [comment]
You can fix it by replacing `print_len = dataset.shape[0] // 10` with `print_len = max(dataset.shape[0] // 10, 1)`.

**Comment by YorkZ** [comment]
After your suggested change, it didn't fail out, but the parameters didn't get printed out.

**Comment by YorkZ** [comment]
It's so late in China now man, you are so diligent!

**Comment by YorkZ** [comment]
I really appreciate your help, but sleep is very important. Please don't worry about this thing, it's not emergency.

**Comment by L-M-Sherlock** [comment]
Can you test it?
https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v1.4.3/fsrs4anki_optimizer.ipynb

**Comment by YorkZ** [comment]
Seemed to be working, thanks.
