### ISSUE TITLE
[Question] No-code version and local version give different w values

### ISSUE THREAD

**Issue by Roxiun** [open-spaced-repetition/fsrs4anki#220]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
[No-code version](https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app) and locally running the jupyter notebook give different w values. Is this just because its run on different computers?

I can provide more information if that would help

**Comment by L-M-Sherlock** [comment]
The no-code version is behind the jupyter notebook version. Nobody maintained the no-code version recently. I will update the no-code version.
