### ISSUE TITLE
希望有撤销上一步reschedule的功能

### ISSUE THREAD

**Issue by Kitsuta-le** [open-spaced-repetition/fsrs4anki#221]
一旦误reschedule就需要从其他端强制同步重新覆盖，非常麻烦。而且不了解的人一误旦reschedule之后就只能再学一遍，非常劝退。。。望考虑

**Comment by L-M-Sherlock** [comment]
理论上是可以 undo 的，但是 reschedule 的卡片太多可能失效，具体原因我也不清楚，可能这需要 Anki 本体修复。

**Comment by L-M-Sherlock** [comment]
reschedule 是 helper 的主要功能，使用者应该了解其效果吧。实在不行我可以加一个确认键。

**Comment by Kitsuta-le** [comment]
> reschedule 是 helper 的主要功能，使用者应该了解其效果吧。实在不行我可以加一个确认键。

undo的效果不是恢复到本次reschedule前的状态，而是全部重排了一遍。。。我主要是有时候学完忘同步了，reschedule完才想起来只能强制同步了。。

**Comment by Kitsuta-le** [comment]
对了我想请教下load balance和fuzz是什么意思？我没有找到相关的说明。。。。

**Comment by L-M-Sherlock** [comment]
Load balance 就是平衡压力，让每天的复习量尽可能平滑。
Fuzz 是随机分散，在原有间隔的基础上进行小变动，防止复习都堆在一起。

**Comment by L-M-Sherlock** [comment]
> undo的效果不是恢复到本次reschedule前的状态，而是全部重排了一遍。。。我主要是有时候学完忘同步了，reschedule完才想起来只能强制同步了。。

你可以具体说一下情况吗？undo 后不是恢复 reschedule 前的间隔和复习日期吗？

**Comment by L-M-Sherlock** [comment]
你 undo 的时候，Anki 左下角有没有提示 undo 了？

**Comment by Kitsuta-le** [comment]
嗯？不是helper里头的undo吗？ anki我用的是2.16版目前reschedule是undo不了的

**Comment by L-M-Sherlock** [comment]
> 嗯？不是helper里头的undo吗？

那个是 reset，重置卡片回到所有 reschedule 之前。出于技术问题，目前做不了单次的。
