### ISSUE TITLE
[Question] What is R2 in calibration graph of the optimizer?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#222]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
What is the R^2 in the calibration graph produced by the optimizer?

I read the following comment by @Expertium.

> Add R-squared (coefficient of determination), like in the very first picture I posted in this issue, the one from Supermemo wiki. This way we can quantify calibration instead of just saying "Hmmm, I think these two lines don't quite align".

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki/issues/151#issuecomment-1505502578_

It tells me that R^2 refers to the coefficient of determination. But, what does this actually mean? Also, how should a user interpret this value? Is it better to have a larger value or a smaller value?

**Comment by Expertium** [comment]
https://en.wikipedia.org/wiki/Coefficient_of_determination

Loosely speaking, it tells us whether a change of one of the values (let's call them A and B) will affect the other one. R-squared is always between 1 and 0. R^2=1 means that if we change A, B will always change proportionally. If R^2=0 then that means that if we change A, B can go up, or down, or stay the same, or whatever. In our case, with calibration, higher R^2 is better.

**Comment by user1823** [comment]
Thanks for the explanation. It makes sense to me.

I think that a brief explanation about the R^2 should also be added to the optimizer.
