### ISSUE TITLE
[Question] Is average retention in FSRS stats calculated using subdeck parameters or just parent deck parameters?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#223]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
So suppose there is a deck A, and it has 2 subdecks - A1 and A2, each with it's own unique parameters (obtained by using the optimizer), and A has it's own parameters too. I click on deck A and see the average retention. Is it calculated using parameters of A1 and A2, or just A?

**Comment by L-M-Sherlock** [comment]
The calculation of retention doesn't use parameters. It relies on the stability stored in the custom data of each card and the elapsed days.
