### ISSUE TITLE
[BUG] "Deck name not found" despite having <div id=deck deck_name="{{Deck}}"></div> in the card template

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#224]
**Describe the bug**
FSRS seems to be working fine on all but one card templates. Here is the deck with problematic cards, if you want to take a look.
https://drive.google.com/file/d/1svCz--KFHKXVB5pGxX4-_22g5QQgc5VW/view?usp=share_link
When I review them I see this: 
![image](https://user-images.githubusercontent.com/83031600/234044820-779c5f21-8162-43d6-bb8a-72c903ae5952.png)
despite the fact that I put `<div id=deck deck_name="{{Deck}}"></div>` in the template:
![image](https://user-images.githubusercontent.com/83031600/234044975-4ae33445-3dfa-4086-abf1-da7be51a98fb.png)
What's even more strange is that if I remove `<div id=deck deck_name="{{Deck}}"></div>` and then add it again, it fixes the issue...
![image](https://user-images.githubusercontent.com/83031600/234045158-68cc3bf5-6e6c-4ee7-a18e-d04db580b489.png)
...and then the issue comes back once I move onto the next card.

**To Reproduce**
1. Try to review a card with "IO Card" type
2. See "Deck name not found" message
3. Additionally, remove `<div id=deck deck_name="{{Deck}}"></div>` and immediately paste it again, it should fix the issue for this one card
4. See the same "Deck name not found" message again when you review the next card

**Expected behavior**
FSRS should be able to read deck name.

**Environment**
 - Anki version: 2.1.60, Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
 - OS: Windows 10
 - Scheduler version: v3.15.1

**Additional context**
This isn't the first time I'm having issues with Image Occlusion cards + FSRS, no idea why this specific card template breaks FSRS.

EDIT: ok, nevermind, this isn't the only card type that has this issue, it affects other card types as well.

**Comment by L-M-Sherlock** [comment]
This issue has been solved in #172.

**Comment by Expertium** [comment]
I updated Anki to 2.1.61 and this issue seems to be gone, thank you!
