### ISSUE TITLE
[Question] What happens when you force "set due date" with ! ?

### ISSUE THREAD

**Issue by Diego-BR** [open-spaced-repetition/fsrs4anki#226]
**Research**

*Enter an [x] character to confirm the points below:*

- [X ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X ] I have searched for similar existing questions here

**Question**

How does the scheduling (and also the helper addon) work when you force "set due date" with ! (altering manually the next interval and due date)? Ex.: What happens if a card has an interval of 7 months and I force it for the next week with a new interval of 10 days. 

And in the case that I just set the due date for tomorrow but with no modification to the next interval? 

Also, does a filtered deck with the "reschedule cards" ticked (and not ticket) influence the FSRS in anyway?

**Comment by Diego-BR** [comment]
As far as I can tell for the first question, even if I force the due date for tomorrow with a new interval set for 1 (1!), the next interval is going to be above 7 months. 

In other words, it is not possible to force the card to have a smaller interval definitively.

Am I wrong?

**Comment by Diego-BR** [comment]
> > As far as I can tell for the first question, even if I force the due date for tomorrow with a new interval set for 1 (1!), the next interval is going to be above 7 months.
> 
> Did you check the due date?

Sorry, opened an issue when intended to quote only. Closed it. 

As for the question, just got the due date for today, with interval of 1 (0!). 
Good got me with the old interval back (3+ months in this card).

**Comment by L-M-Sherlock** [comment]
Is it unexpected for you? Maybe you need `forget` the card.

**Comment by Diego-BR** [comment]
> Is it unexpected for you? Maybe you need `forget` the card.

I don't think this is the case. 

After some time off, my intervals got too long (I know FSRS tend to increase by a large amount the interval when it is due for quite some time) and I wanted to have my cards distributed between 30-45 days from now only and so on. 

You see... there is no need to start from scratch, but have them with the intervals set to 4 to 7 months from now is quite excessive. 

And after reviewing in those 30-45 days, I'll have the same problem again (4-7+ months intervals).

**Comment by L-M-Sherlock** [comment]
How about forget the card and then set due date?

**Comment by Diego-BR** [comment]
> How about forget the card and then set due date?

This is something I don't know how to test lol (If I forget and set the due date + interval to 30 days, only when the day comes I'll be able to check for the next interval.. i think). 

Anyway, If I forget and set due date + interval to 40 days. The next interval will be as expected from FSRS? 

Would it be a good practice?

**Comment by L-M-Sherlock** [comment]
I don't recommend controlling the interval manually too much. FSRS could deal with most cases if you use the optimizer to generate personal parameters from your own data.

**Comment by Diego-BR** [comment]
I see. Tks for your help and for the algo!
