### ISSUE TITLE
[BUG] Scheduled interval is not the same as what "Good" button says

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#23]
**Describe the bug**
As subject

**To Reproduce**
1. Click the filtered deck which was filtered with `deck:Python is:due is:learn`
2. Click the `Study Now`
3. After reviewing, click `Good`, and the button suggested the next review would be in 4 days.
4. Open the card browser, find the card just got reviewed to check the interval, but it says `1 day`

**Expected behavior**
The interval should be the same as the `Good` button says, i.e., 4 days in this case.

**Screenshots**
![2022-09-23_20-01](https://user-images.githubusercontent.com/742238/192048958-14115e96-c416-4c5a-b086-557b88a1fc50.png)

**Environment**
 - Anki version: Dev version 2.1.55
 - OS: Arch Linux
 - Scheduler version: 1.4.2
 - Optimizer version: 1.4.0

**Comment by YorkZ** [comment]
Just got another one, still in the same filtered deck. The `Easy` button says `6` days, but what actually scheduled was `2` days. Guess I'll have to stop using the scheduler until this issue get addressed.

**Comment by YorkZ** [comment]
Don't worry about this thing, I can wait for as long as you get enough sleep. :)

**Comment by L-M-Sherlock** [comment]
Are you opening the inspector during the review? It could block the scheduler.

**Comment by YorkZ** [comment]
No.

**Comment by L-M-Sherlock** [comment]
I didn't reproduce this bug. Could you give more details?

**Comment by YorkZ** [comment]
Did you test it by creating a filtered deck with `deck:Python is:due is:learn`?

**Comment by L-M-Sherlock** [comment]
![Snipaste_2022-09-24_23-28-59](https://user-images.githubusercontent.com/32575846/192106191-b0aded00-3137-4959-aece-025c8379f412.png)

![image](https://user-images.githubusercontent.com/32575846/192106207-35f7c343-9871-44d7-87ca-4cf280160416.png)

![image](https://user-images.githubusercontent.com/32575846/192106253-69052a2d-4fac-4b70-9de7-d019f1440a9e.png)

**Comment by YorkZ** [comment]
Then maybe it's deck related? Can you download the `Python` deck I used from `AnkiWeb` and test on that deck?

**Comment by L-M-Sherlock** [comment]
There are so many decks named `Python`. Could you give me the link?

**Comment by L-M-Sherlock** [comment]
And do you install other add-ons? Maybe it is related.

**Comment by YorkZ** [comment]
Yep that's possible, these are all the addons I'm using. 

![2022-09-24_15-46](https://user-images.githubusercontent.com/742238/192107018-dfffc1d6-9f9c-4d0d-8109-7c0d08304c2a.png)

**Comment by YorkZ** [comment]
> There are so many decks named Python. Could you give me the link?

Sorry I forgot this. It's this one https://ankiweb.net/shared/info/51975584. It was the top rated shared deck when I searched `Python`.

**Comment by L-M-Sherlock** [comment]
I find the source of the bug. Disable `Advanced Review Bottom Bar` and try again.

**Comment by L-M-Sherlock** [comment]
I figure it out! `Advanced Review Bottom Bar` show the interval given by Anki's built-in scheduler.

**Comment by L-M-Sherlock** [comment]
I record it in [Compatibility](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Compatibility) and will report it to the author of `Advanced Review Bottom Bar`.

**Comment by YorkZ** [comment]
Oh, thank you for tracking this down. But I need this addon, I need the `info` button to show the info, and the `skip ` button` to skip the current card. Also, It would be helpful if there's a way to show the interval from both the builtin and the custom algorithm. Any idea?

**Comment by YorkZ** [comment]
So in this case there were very big difference between the interval calculated from the builtin and your algorithm. It feels like you algorithm is probably too aggressive as I don't feel I need to see those two cards in 1 day and 2 days.

**Comment by L-M-Sherlock** [comment]
> Also, It would be helpful if there's a way to show the interval from both the builtin and the custom algorithm. Any idea?

It is not a problem that can be solved by myself.

**Comment by L-M-Sherlock** [comment]
> I don't feel I need to see those two cards in 1 day and 2 days

You rate `hard` in first learning, which my algorithm considers an important behavior.

**Comment by L-M-Sherlock** [comment]
And the default parameters are generated from my review logs. So it may not be adaptive to you. I improved the simulator today. Maybe it could give some reference for you to fine-tune the parameters for yourself.

**Comment by YorkZ** [comment]
I think I used the parameters optimized for this deck. I think I compared the my parameters with the default ones, the `difficulty` was higher and 'stability` was lower than the default values.

**Comment by L-M-Sherlock** [comment]
Or you can set requestRetention = 0.8, which will increase the interval.
