### ISSUE TITLE
[Feature Request] GPU accelerate

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki#231]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
I have the suspicion that maybe it is possible to use GPU acceleration / CUDA might make the Optimizer notebook run faster.

**Describe the solution you'd like**
The user changes [runtime to GPU](https://www.tutorialspoint.com/google_colab/google_colab_using_free_gpu.htm). Then the notebook uses the GPU.

And hopefully, this would be faster than the current Optimizer.

~~**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
I don't know enough to assess whether this is viable and effective. My research suggests that the training steps may be done on a GPU.

**Comment by L-M-Sherlock** [comment]
Unfortunately, FSRS doesn't use the built-in neural network and doesn't have matrix operations. So the GPU would not make the Optimizer notebook run faster. I test it with my macbook with the `mps` device. It is slower than before. But you can test it in other device.

**Comment by galantra** [comment]
Thanks for the explanation!

Sorry about the issue's title, BTW. I created it too quickly.
