### ISSUE TITLE
[BUG] Errors while running optimizer

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#233]
**Describe the bug**
When running the optimizer (the version on the main branch), some error messages are seen. Screenshots are shared below.

**Screenshots**
<img width="810" alt="image" src="https://user-images.githubusercontent.com/92206575/234861907-484474b5-a326-4a99-adfc-69bbba73b37f.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/92206575/234865171-8745e0b8-22de-41e0-8b90-8a4bb1894c43.png">

**Environment**
 - Optimizer version: v3.17.1

**Comment by Expertium** [comment]
I could be wrong, but it's probably because some bins are empty, so you get a division by 0 error when trying to calculate `prediction / counts` and `correct / counts`.
