### ISSUE TITLE
[BUG] No-code version: Unexpected build error

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki#236]
**Describe the bug**

> ### build error
> Unexpected build error
> 
> #### Build logs:
>	
> `===== Build Queued at 2023-04-25 16:06:48 / Commit SHA: 48f4086 =====`

**To Reproduce**
1. Go to https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52420923/235197860-c83fd2e6-0c68-484d-913f-06accb7a25ea.png)

**Environment**

 - OS: Windows 10 Home 22H2 19045.2846
 - Browser: Firefox and Edge

**Comment by L-M-Sherlock** [comment]
I restart the space. You can try it again.
