### ISSUE TITLE
custom deck parameters not working

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki#237]
**Describe the bug**
When using a filtered deck, the deck name used by FSRS is that of the filtered deck, not the original deck. As a result, custom deck parameters do not apply. This happen regardless of whether <div id=deck deck_name="{{Deck}}"></div> is in the front template

**To Reproduce**
1. turn on debugger
2. set custom parameters for a deck (set a low maximuminterval)
4. move cards from that deck to a filtered deck
5. note the maximuminterval is not being honored 

**Environment**
 - Anki version: [e.g. 2.1.61]
 - OS: [MacOS Ventura]
 - Scheduler version: [e.g. v3.15.1]

**Comment by L-M-Sherlock** [comment]
This is issue is duplicate with #232. I recommend using Anki 2.1.60 or using the scheduler v3.14.3 until Anki fixes this bug.
