### ISSUE TITLE
Optimizer ignore fail more than X Seconds

### ISSUE THREAD

**Issue by BEST8OY** [open-spaced-repetition/fsrs4anki#238]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
Well, sometimes when I fail a card, I tend to research about the card in internet to learn it and then hit on [Again] button thus the average fail time is a bit high, and I'm concerned if it affects my results in optimizer.

**Describe the solution you'd like**
Ignore fail more than X Seconds (X=n)

**Comment by L-M-Sherlock** [comment]
Anki has truncated the time of review: 

![image](https://user-images.githubusercontent.com/32575846/235421123-cde4efe9-2d33-4643-a7ea-fb49b57083ea.png)

**Comment by BEST8OY** [comment]
> Anki has truncated the time of review:

Does it affect my previous answered cards?
If not, I guess I have to get new answer history from now on!

**Comment by L-M-Sherlock** [comment]
> Well, sometimes when I fail a card, I tend to research about the card in internet to learn it and then hit on [Again] button thus the average fail time is a bit high, and I'm concerned if it affects my results in optimizer.

It doesn't affect the training of parameters, so it is unnecessary to ignore them.
