### ISSUE TITLE
AttributeError: module 'tqdm' has no attribute 'notebook'

### ISSUE THREAD

**Issue by eyests** [open-spaced-repetition/fsrs4anki#240]
I was able to use optimizer fine a month ago, but have been getting this error recently. I haven't upgraded anki. Same error whether I use .apkg or .colpkg. 

I have Anki Version 2.1.60

revlog.csv saved.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-3-0ae3437af148>](https://localhost:8080/#) in <cell line: 58>()
     56     return x
     57 
---> 58 tqdm.notebook.tqdm.pandas()
     59 df = df.groupby('cid', as_index=False, group_keys=False).progress_apply(get_feature)
     60 df = df[df['id'] >= time.mktime(datetime.strptime(revlog_start_date, "%Y-%m-%d").timetuple()) * 1000]

AttributeError: module 'tqdm' has no attribute 'notebook'

**Comment by L-M-Sherlock** [comment]
Please use the latest optimizer in the releases page.

**Comment by L-M-Sherlock** [comment]
Has been solved by #201.
