### ISSUE TITLE
[Question] How to keep original V3 scheduler in some deck/card type?

### ISSUE THREAD

**Issue by chieh0958** [open-spaced-repetition/fsrs4anki#243]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

How to keep original V3 scheduler in some deck/card type?

**Comment by L-M-Sherlock** [comment]
You can add the name of decks that you want to use the original algorithm to `skip_decks` in the scheduler code.

**Comment by L-M-Sherlock** [comment]
And I recommend using the latest Anki (2.1.62) and FSRS4Anki scheduler, which could fetch the deck name of your card automatically.
