### ISSUE TITLE
Free Anki On Certain Days

### ISSUE THREAD

**Issue by ArcticBlack23** [open-spaced-repetition/fsrs4anki#244]
I have been using this addon for a while now and I can’t seem to get the Free Anki on certain days to work. I have it checked, and I’ve already rescheduled the cards but there are still over 200 cards due on the day I want to free up (Saturday). It would make sense if these were learning cards but even reviews are present on that day.

**Comment by L-M-Sherlock** [comment]
Are these cards' intervals are too short? The `Free Anki` respects the fuzz range of cards, which is -5% ~ +5% of the interval.

**Comment by L-M-Sherlock** [comment]
Inactive.
