### ISSUE TITLE
Make it easier to share data for SRS research

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#247]
@L-M-Sherlock, you once created the following Google Form to allow users to share data for SRS research: https://docs.google.com/forms/d/e/1FAIpQLSekiv2g00goXKZnRd7AokIq9GFyI9eq2Ne48TfLWluIQwYoxQ/viewform

This was a good initiative because data is everything and the more diverse data we collect, the better SRS algorithm we can develop.

But, there are some problems. Here, I highlight those problems and suggest some solutions.
- The form link was not widely circulated. So, only some users could get to know about it. I suggest putting the link to the form on
    - the readme of the GitHub repo of FSRS4Anki
    - the readme of the GitHub repo of FSRS4Anki helper
    - the add-on page of the FSRS4Anki helper on AnkiWeb
    - reddit
- The first section of the form asks the user to upload their collection in the .colpkg form. But an average user may not know how to get a .colpkg form of their collection. A brief explanation of how to export the collection as .colpkg would be great.
- The next section of the form just says "Next day starts at __ hours past midnight (e.g., 5)". An average user might not understand what it means. It would be great if the form also says that this value can be seen by going to Preferences → Review.
- The next section of the form asks for the timezone in an unusual format and most users won't be able to understand what to fill in it. So, is it possible to change the format of the timezone? Otherwise, include a link to the following (or a better) gist in the form: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568

The idea is to design the form while assuming that the target audience has no technical background. This way, we can maximize the number of people who can share their data with us.

**Comment by L-M-Sherlock** [comment]
<img width="814" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/b0b596e1-dc87-4820-bf3c-4c2d20d383d5">
<img width="805" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/37475e9f-b9e2-4ce0-a55b-8331ed6e0e6d">
<img width="835" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/9b0c97ad-b8a1-4616-a66e-b510657ce465">

I update the form. It would be more user-friendly.
