### ISSUE TITLE
Ensure that minimum new interval with fuzz is always greater than the previous interval 

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#249]
> I found that sometimes, even if I answered a card correctly, the new interval would stay the same, or even get reduced (!).
>
> I thought about what might be causing it, and I realised that it is probably the implementation of fuzz. Since the difficulty of most of my cards is extremely high, each time I answer a card correctly its interval would only increase by 1 or 2 days. But, since fuzz adds or subtracts a couple of days to each new interval, this would effectively mean that there would be a reasonably high chance that the new intervals would actually be lower/the same than the previous ones.
>
> I set fuzz to 'false' in my deck settings, rescheduled all my cards, and it seems like this has alleviated the problem quite a lot, there being less reviews in the upcoming days, and it seems like the amount of reviews I'll have to do over the next few days will actually start going down (slowly, but still). It's too early to assess how big of a difference removing fuzz will bring in the long run, but at least now I have hope that I might make my way out of this ~~ease~~/~~difficulty~~/interval (?) hell.

_Originally posted by @Leocadion in https://github.com/open-spaced-repetition/fsrs4anki/issues/189#issuecomment-1527314489_

I think the best way to solve this problem is to constrain the minimum interval with fuzz enabled to be at least one day more than the previous interval.

That is, `min_new_ivl ≥ prev_ivl + 1`

Obviously, this constraint should be applied only when the card was not lapsed.

**Comment by user1823** [comment]
By the way, the same fix needs to be applied to the helper (in both reschedule and disperse_siblings functions).

**Comment by L-M-Sherlock** [comment]
We have to consider more complex situation. For example, when user set the request retention to 70% and press `good`, the first interval could be 8 days (stability = 2.3 days). Then when the user set the request retention to 90% and press `good` in 8 days, the second interval could be 5 days (stability = 5 days). The second interval is shorter than the first, but it is rational.

**Comment by user1823** [comment]
> We have to consider more complex situation. For example, when user set the request retention to 70% and press `good`, the first interval could be 8 days (stability = 2.3 days). Then when the user set the request retention to 90% and press `good` in 8 days, the second interval could be 5 days (stability = 5 days). The second interval is shorter than the first, but it is rational.

Good point. But, we do need to find a way to solve the problem. Right?

**Comment by user1823** [comment]
> Then when the user set the request retention to 90% and press good in 8 days, the second interval could be 5 days (stability = 5 days).

By the way, if the user pressed good (or even hard) after 8 days, do you think it is possible that the stability would still be less than 8 days?

In other words, why should the new stability be less than the interval after the user reviews the card and gets it right?

**Comment by L-M-Sherlock** [comment]
> By the way, if the user pressed good (or even hard) after 8 days, do you think it is possible that the stability would still be less than 8 days?
> 
> In other words, why should the new stability be less than the interval after the user reviews the card and gets it right?

It is possible. A related research: https://controlaltbackspace.org/assets/attachments/overduecards.html

**Comment by L-M-Sherlock** [comment]
It is easy to ensure the new interval greater than the previous interval, because Anki custom scheduling provides the previous scheduled days:

![image](https://user-images.githubusercontent.com/32575846/236668076-ba1dc6b4-b8d3-46b3-8388-da6b81190105.png)

What we need to do is add a line of code:

`hard_interval = Math.min(hard_interval, scheduledDays);`

to the scheduler:

https://github.com/open-spaced-repetition/fsrs4anki/blob/e97e9cbf875367afbcc5d4131e9228aada4dd053/fsrs4anki_scheduler.js#L166-L168

**Comment by user1823** [comment]
> It is easy to ensure the new interval greater than the previous interval, because Anki custom scheduling provides the previous scheduled days:

I hope that the scheduledDays doesn't include the overdue delay so that we can avoid the problem highlighted by you above.

> What we need to do is add a line of code:
> 
> `hard_interval = Math.max(hard_interval, scheduledDays);`
> 
> to the scheduler:

I think that it should be something like

`min_ivl = Math.max(min_ivl, scheduledDays);`

**Comment by L-M-Sherlock** [comment]
> min_ivl = Math.max(min_ivl, scheduledDays + 1);

It could cause another problem. What if the max_ivl is smaller than `scheduledDays+1`?

**Comment by L-M-Sherlock** [comment]
Oh, my code would still exist problem. We also need to consider maximumInterval set by users.

**Comment by L-M-Sherlock** [comment]
> I hope that the scheduledDays doesn't include the overdue delay so that we can avoid the problem highlighted by you above.
> 
> >

It doesn't. Only the `elapsedDays` includes the overdue delay.

**Comment by user1823** [comment]
> > min_ivl = Math.max(min_ivl, scheduledDays + 1);
> 
> It could cause another problem. What if the max_ivl is smaller than `scheduledDays+1`?

In my opinion, `max_ivl` would never be smaller than `scheduledDays+1` except for the case where the user increases their `requestRetention`.

I can't think of a _good_ solution for this case. I hope that you can come up with one.

One solution I can come up with is:

`min_ivl = Math.min(Math.max(min_ivl, scheduledDays + 1), max_ivl);`

But, this would mean that there is no fuzz for such cases (where the user increased their requestRetention and it resulted in the max_ivl becoming smaller than the scheduledDays + 1).

**Comment by user1823** [comment]
> But, this would mean that there is no fuzz for such cases (where the new_ivl is less than the scheduledDays + 1).

I think that this is still better than the current condition where the user has to turn off fuzz altogether. But, I think that you can come up with a better solution.

**Comment by L-M-Sherlock** [comment]
Simple method:

```javascript
function next_interval(stability) {
  const new_interval = Math.max(apply_fuzz(stability * intervalModifier), scheduledDays + 1);
  return Math.min(Math.max(Math.round(new_interval), 1), maximumInterval);
}
```

> I can't think of a _good_ solution for this case (user increased the requestRetention). I hope that you can come up with one.

Unless user tell it to the scheduler, there is not a good solution for this case.

**Comment by user1823** [comment]
> Simple method:
> 
> ```js
> function next_interval(stability) {
>   const new_interval = Math.max(apply_fuzz(stability * intervalModifier), scheduledDays + 1);
>   return Math.min(Math.max(Math.round(new_interval), 1), maximumInterval);
> }
> ```

This solution doesn't handle the case where the `max_ivl` calculated during fuzz is smaller than the `scheduledDays + 1`.

In such conditions, my solution (reproduced below) sets the interval to `max_ivl`, which I think is better.

> I think that this line
> 
> https://github.com/open-spaced-repetition/fsrs4anki/blob/e97e9cbf875367afbcc5d4131e9228aada4dd053/fsrs4anki_scheduler.js#L187
> 
> should be replaced by
> 
> ```js
> const new_ivl = Math.floor(fuzz_factor * (max_ivl - min_ivl + 1) + min_ivl);
> 
> return Math.min(Math.max(new_ivl, scheduledDays + 1), max_ivl);
> ```

**Comment by L-M-Sherlock** [comment]
> This solution doesn't handle the case where the `max_ivl` calculated during fuzz is smaller than the `scheduledDays + 1`.

In my solution, if the `max_ivl` is smaller than `scheduledDays + 1`, the `new_interval` will be `scheduledDays + 1`.

**Comment by L-M-Sherlock** [comment]
Oh, maybe we both forget the case where the user presses `again`.

**Comment by user1823** [comment]
> In my solution, if the `max_ivl` is smaller than `scheduledDays + 1`, the `new_interval` will be `scheduledDays + 1`.

But, I think that it should be `max_ivl` because here fuzz is not responsible for causing the interval to be smaller than `scheduledDays + 1`. Here, the interval is smaller than `scheduledDays + 1` because of the working of the main FSRS algorithm.

Here is what I think about this fix.
> I think that the motive of this fix is to just prevent unwanted effects from fuzz and not to interfere with the working of the main algorithm.

> Oh, maybe we both forget the case where the user presses again.

I considered it. But, because you were talking so confidently about this approach, I thought that there was a separate formula for lapses.

**Comment by L-M-Sherlock** [comment]
When user presses `again`, the stability will decrease, but the `scheduledDays + 1` would not be affected. And the `apply_fuzz` is applied to all interval regardless of the `rating`.

**Comment by user1823** [comment]
By the way, after a lapse, the card first passes through the relearning steps (where I think that FSRS doesn't work).

Then, when the card is leaving the relearning steps (where FSRS begins to work again), is the value of scheduledDays the same as the interval before the lapse or it is changed to the interval of the last relearning step?

**Comment by L-M-Sherlock** [comment]
I need to do more research here. Because there is few documents about it in Anki.

**Comment by user1823** [comment]
> The `scheduledDays` will be set to 1 day (in my case).

If the `scheduledDays` is set to 1 day after a lapse, I think that my approach would well in the case of lapses also.

Explanation:
- If the `new_ivl` is greater than or equal to 2 days, it is used as it is and my formula doesn't change anything.
- If the `new_ivl` is 1 day, `scheduledDays + 1` (= 2) is used which also lies within the fuzz range. (`max_ivl` is at least 3.625 days because fuzz is only applied when ivl ≥ 2.5d)

But, I think that we need to add Math.floor to the second line of my formula. That is, it should look like
```js
return Math.floor(Math.min(Math.max(new_ivl, scheduledDays + 1), max_ivl));
```

**Comment by user1823** [comment]
After all the corrections, my suggestion is:

> I think that this line
> 
> https://github.com/open-spaced-repetition/fsrs4anki/blob/e97e9cbf875367afbcc5d4131e9228aada4dd053/fsrs4anki_scheduler.js#L187
> 
> should be replaced by
> 
> ```js
> const new_ivl = fuzz_factor * (max_ivl - min_ivl + 1) + min_ivl;
> 
> return Math.floor(Math.min(Math.max(new_ivl, scheduledDays + 1), max_ivl));
> ```

The only two conditions where my suggestion probably doesn't yield very good results are:
- The user changed the `requestRetention` and didn't reschedule all their cards using the Helper. (If all cards were rescheduled, `scheduledDays` decreases and no longer produces unexpected results.) Even if the cards were not rescheduled, the interval won't be more than max_ivl calculated by the fuzz.
- The user pressed again. But, I think that this is not a problem as I explained in https://github.com/open-spaced-repetition/fsrs4anki/issues/249#issuecomment-1537437801.

Note: This suggestion works for the scheduler.js. But, for the helper, the first point (if all cards were rescheduled, `scheduledDays` decreases and doesn't unwanted effects) doesn't hold true because the Helper acts after the card was studied while scheduler acts while the card is being studied.

**Comment by L-M-Sherlock** [comment]
According to the code of Anki's scheduler, `scheduledDays` is max(minimum_lapse_interval * lapse_multiplier, minimum_lapse_interval, 1) when user presses `again`.

**Comment by user1823** [comment]
Forget about all the solutions I proposed above. Just tell me whether we can add an `if` condition here:
https://github.com/open-spaced-repetition/fsrs4anki/blob/e97e9cbf875367afbcc5d4131e9228aada4dd053/fsrs4anki_scheduler.js#L182-L188
such that the middle portion something looks like:
```js
ivl = Math.round(ivl);
const min_ivl = Math.max(2, Math.round(ivl * 0.95 - 1));
const max_ivl = Math.round(ivl * 1.05 + 1);
if ivl > scheduledDays:
const min_ivl = Math.max(min_ivl, scheduledDays + 1)
```

In my opinion, this is the best solution for this issue and I don't think that it should have any undesirable effects.

**Comment by L-M-Sherlock** [comment]
There is a problem with relearning cards. For relearning cards, the scheduledDays is the interval set by Anki's built-in algorithm.

**Comment by user1823** [comment]
> There is a problem with relearning cards. For relearning cards, the scheduledDays is the interval set by Anki's built-in algorithm.

No problem. If the ivl (determined by FSRS) is not greater than the scheduledDays, this new rule does not apply. So, it wouldn't cause any undesirable effects.

By the way, does FSRS scheduler actually work on cards that are in the relearning phase?

**Comment by L-M-Sherlock** [comment]
> By the way, does FSRS scheduler actually work on cards that are in the relearning phase?

For relearning phase, the stability and difficulty will not be updated. FSRS only set the interval from the current stability and difficulty.

**Comment by user1823** [comment]
You might say that we should also deal with the cases where the `ivl` is smaller than the `scheduledDays`. But, consider what the purpose of this fix is:

> I think that the motive of this fix is to just prevent unwanted effects from fuzz and not to interfere with the working of the main algorithm.

So, if the `ivl` determined by FSRS is smaller than the `scheduledDays`, we don't change anything and let the scheduler work just like it was working till now.

**Comment by L-M-Sherlock** [comment]
You can track the process of FSRS scheduler. Here is the tutorial: https://github.com/open-spaced-repetition/fsrs4anki/wiki/How-does-the-scheduler-work%3F

**Comment by user1823** [comment]
Did you read my last comment (https://github.com/open-spaced-repetition/fsrs4anki/issues/249#issuecomment-1546628306) where I explain the purpose of this fix? Do you agree with it?

If you agree with it, do you think that my approach would work without any issues? I am very sure about it. But, I just want to know if you agree with it or not.

(I gave my explanation rebutting the concern about relearning cards here: https://github.com/open-spaced-repetition/fsrs4anki/issues/249#issuecomment-1546627382)

If you agree that this approach would work fine, I advise you to implement it soon.

Also, note that this fix needs to be applied to the scheduler.js and to the helper (reschedule + disperse_siblings).

**Comment by L-M-Sherlock** [comment]
> If you agree with it, do you think that my approach would work without any issues? I am very sure about it. But, I just want to know if you agree with it or not.

I will test it soon.

**Comment by L-M-Sherlock** [comment]
My implementation:
```
function apply_fuzz(ivl) {
  if (!enable_fuzz || ivl < 2.5) return ivl;
  ivl = Math.round(ivl);
  let min_ivl = Math.max(2, Math.round(ivl * 0.95 - 1));
  let max_ivl = Math.round(ivl * 1.05 + 1);
  if (is_review()) {
    const scheduledDays = states.current.normal?.review.scheduledDays ? states.current.normal.review.scheduledDays : states.current.filtered.rescheduling.originalState.review.scheduledDays;
    if (ivl > scheduledDays) {
      min_ivl = Math.max(min_ivl, scheduledDays + 1);
    }
  }
  return Math.floor(fuzz_factor * (max_ivl - min_ivl + 1) + min_ivl);
}
```

The new code only apply to review cards. So we can avoid the problem with lapse.

**Comment by user1823** [comment]
> My implementation:
> 
> ```js
> function apply_fuzz(ivl) {
>   if (!enable_fuzz || ivl < 2.5) return ivl;
>   ivl = Math.round(ivl);
>   let min_ivl = Math.max(2, Math.round(ivl * 0.95 - 1));
>   let max_ivl = Math.round(ivl * 1.05 + 1);
>   if (is_review()) {
>     const scheduledDays = states.current.normal?.review.scheduledDays ? states.current.normal.review.scheduledDays : states.current.filtered.rescheduling.originalState.review.scheduledDays;
>     if (ivl > scheduledDays) {
>       min_ivl = Math.max(min_ivl, scheduledDays + 1);
>     }
>   }
>   return Math.floor(fuzz_factor * (max_ivl - min_ivl + 1) + min_ivl);
> }
> ```
> 
> The new code only apply to review cards. So we can avoid the problem with lapse.

I have no problem with this implementation.

But, did you face any problem with the relearning cards? I don't think that there should be any problem.

Also, I don't think that your code skips the relearning cards because the relearning cards are also review cards.

To skip relearning cards, you should use the logic: is_not_learn

But, I think that skipping the learning or relearning cards is not necessary at all and it would only complicate the code.

**Comment by L-M-Sherlock** [comment]
> Also, I don't think that your code skips the relearning cards because the relearning cards are also review cards.

I write the functions `is_review()` and `is_learning()` to filter the relearning cards.

**Comment by L-M-Sherlock** [comment]
In my code, there are three states for cards: new, (re)learning, and review.

**Comment by L-M-Sherlock** [comment]
> But, did you face any problem with the relearning cards? I don't think that there should be any problem.

I just want to simplify the condition,  because the `scheduledDays` is stored in different location for different states.

**Comment by user1823** [comment]
> > Also, I don't think that your code skips the relearning cards because the relearning cards are also review cards.
> 
> I write the functions `is_review()` and `is_learning()` to filter the relearning cards.
>
> In my code, there are three states for cards: new, (re)learning, and review.

Ok. I get it now.

> > But, did you face any problem with the relearning cards? I don't think that there should be any problem.
>
> I just want to simplify the condition, because the `scheduledDays` is stored in different location for different states.

So, do you mean that if you didn't restrict this to the review cards, the following code would have been more complicated?
```js
const scheduledDays = states.current.normal?.review.scheduledDays ? states.current.normal.review.scheduledDays : states.current.filtered.rescheduling.originalState.review.scheduledDays;
```

If it is so, your implementation looks good to me.

**Comment by L-M-Sherlock** [comment]
> So, do you mean that if you didn't restrict this to the review cards, the following code would have been more complicated?

Yep, for relearning cards, `scheduledDays` is `states.current.normal.relearning.review.scheduledDays`.

**Comment by user1823** [comment]
Remember that this fix also needs to be applied to the helper (reschedule as well as disperse_siblings).

In the helper, scheduledDays can be replaced by the corresponding variable for previously scheduled interval (without the overdue delay).

**Comment by user1823** [comment]
@Leocadion, now that this feature has been implemented in the FSRS scheduler, you can turn on the fuzz (if you want) after updating to the latest version of the scheduler.

However, this feature is not yet implemented in the FSRS helper add-on (you can check the progress here: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/96). So, if you frequently reschedule your cards using the helper add-on, I would recommend you to hold on until the feature is implemented in the helper add-on too.
