### ISSUE TITLE
[Feature Request] A new google colab file to export the entire repetition history in .csv or .xlsx

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#251]
**Which module is related to your feature request?**
Scheduler/Optimizer

**Describe the solution you'd like**
First, the user will upload their deck/collection, just like in the Optimizer. Then he will specify a set of parameters (for example, copied from the optimizer), and then the entire history of repetitions will be generated. Here is roughly what it should like:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/2bd7631c-d744-4585-ab7b-226bfe86c19d)
Don't pay attention to the values, only to the overall data structure.

**Additional context**
I believe this can useful for analyzing strengths and weaknesses of the algorithm, as well as looking for correlations within data that could be used to further improve the accuracy.

**Comment by L-M-Sherlock** [comment]
<img width="343" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/5b13cbc7-06e3-4f4c-a228-b4813482d552">

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/dfe7292f-1cf7-4968-a48b-4a041b71dcda)
I can't download revlog_history for some reason. Oh well, I can jsut copy its contents into a different file.
It's not quite what I want though. I want D, S, R (predicted by FSRS), t and grades. And there is soem stuff that I don't understand, like `usn`, `ivl`, `last_lvl`, and `factor`.

**Comment by L-M-Sherlock** [comment]
<img width="1075" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/ea342e11-d2f3-4fa2-9191-9f89243f78f0">

Maybe what you need is `prediction.tsv`?

**Comment by Expertium** [comment]
That's closer to what I want, but I also need predicted R, grades and card IDs. So I need 6 things: ID, t, grade, D, S, R. Date and time is optional, I don't think I really need it because of t.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/1f2dc07a-3038-4119-946c-d4408597c507)

How about this?

**Comment by Expertium** [comment]
`r` is "rating", in other words grade, right? I don't see any 4s, but maybe you just don't use "Easy" very often. And `p` is predicted R?
Is so, then yes, this is what I want.

**Comment by L-M-Sherlock** [comment]
yes, `r` is `rating` and `p` is `P(recall)`. I will release this version tonight.
