### ISSUE TITLE
[BUG] List index out of range error in Section 3 of the Optimizer

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#252]
**Describe the bug**
![Optimizer](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/0a7cee39-e0f6-4685-b863-ced92df34708)

**To Reproduce**
1. Go to https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Expt/adaptive-grades/fsrs4anki_optimizer.ipynb.
2. See this error in Section 3 once the optimization has been finished.

**Environment**
 - Optimizer version: v3.17.1 (adaptive grades)

**Additional context**
I don't know if this is going to help, but here are my settings:
```
timezone = 'Europe/Moscow'
next_day_starts_at = 5
lr = 5e-3
n_epoch = 4
```
And the deck that I was using when I ran into this problem: https://drive.google.com/file/d/1WyYRkoZZLllbESz5eCXq7hxFaHAIfrAJ/view?usp=share_link

**Comment by L-M-Sherlock** [comment]
Replace `w[int((d - w[4]) / w[5] + 2)-1]` with `(d - w[4]) / w[5] + w[15] - w[13]`.

I'm re-implementing it based on mini-batch. So this issue will be close.
