### ISSUE TITLE
[BUG] Bad magic number for file header in optimizer v3.17.1

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#256]
**Describe the bug**
![1](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/aeec71ff-ec24-4add-afdb-fe807d2bd036)

**To Reproduce**
1. Go to https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v3.17.1/fsrs4anki_optimizer.ipynb#scrollTo=KD2js_wEr_Bs
3. See error in "1.1 Extract Anki collection & deck file" when running the optimizer

**Environment**
 - Optimizer version: v3.17.1

**Additional context**
This is the first time I'm having this problem. Yesterday I used this deck with no issues. Here's the deck: https://drive.google.com/file/d/1WyYRkoZZLllbESz5eCXq7hxFaHAIfrAJ/view?usp=share_link

**Comment by L-M-Sherlock** [comment]
Could you reproduce it? It could be network problem, where your browser doesn't upload complete file to colab.

**Comment by Expertium** [comment]
No, I can't reproduce it. Maybe it really was a connection problem.
