### ISSUE TITLE
[Question] How to calculate the series of intervals with input parameters?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#258]
Basically, I want to define the model and input my own parameters and then calculate the intervals that would be generated with a test rating sequence.

In other words, I want to skip the training in the optimizer and calculate the intervals (as in the Preview section of the optimizer) with my own input parameters.

**Comment by L-M-Sherlock** [comment]
You can copy the code from section (exclude 2.2).
