### ISSUE TITLE
[Feature Request] Implement B-W Metric Heatmap

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#260]
I have an idea how to analyze algorithm's performance even deeper and in greater detail than with the calibration graph.
Here is the B-W Metric Heatmap:
![B-W Heatmap (with an explanation), better colors](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/7f179bf9-779a-4fd7-afcd-8285b79f1260)

Here is how it's computed:
1. We will need 10 bins for D (column). I just split them into equal intervals.
2. We will need 10 bins for S (row). Note that the choice of values for bins is kind of arbitrary since S doesn't have an upper limit. I used percentiles, but they will be different for different users, so that's a problem.
3. For each D bin and each S bin (think like a "for" loop inside another "for" loop) calculate the average **predicted** R.
4. For each D bin and each S bin calculate the average **measured** R. Steps 3 and 4 are very similar to making a calibration graph.
5. For each D bin and each S bin calculate the number of data points (reviews).
6. Calculate `predicted_R - measured_R`. Note that we don't use `abs()` because we want to know not just the magnitude of the error, but also the direction. We want to know whether it's an overestimate or an underestimate.
7. Plot a heatmap with different colors. Exclude bins with <100 datapoints (reviews).
This was a nightmare to do in Excel, and I ended up typing 100 values (well, 300 actually, since I have to type predicted R, measured R and counts) manually. This was done using optimizer v3.17.1 with no new changes, but with `lr = 5e-3` and `n_epoch = 4`. 

As you can see, this can allow us to identify specific weaknesses of the algorithm. You can see that for D below 4.6 accuracy drops significantly, meaning that the algorithm doesn't accurately predict R for very easy cards. Although I can't know for sure whether other users will have the same issue.

Here's the calibration graph for this collection:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/8164f436-847b-4687-81c6-dfc1711aea5b)

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki/issues/239#issuecomment-1550102632_

I created a new issue for this so that the idea doesn't get buried in all the other messages. Another motive was to keep all the comments related to this feature in one place.

**Comment by user1823** [comment]
> I didn't see the definition of B-W.

Bet-win is just what Woz calls "prediction-reality". It's just predicted R minus measured R.
You can rename B-W Heatmap to Predicted R-Actual R Matrix or whatever

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki/issues/239#issuecomment-1551287197_

**Comment by L-M-Sherlock** [comment]
```python
B_W_Metric_raw = dataset[['difficulty', 'stability', 'p', 'y']].copy()
B_W_Metric_raw['s_bin'] = B_W_Metric_raw['stability'].map(lambda x: round(math.pow(1.4, math.floor(math.log(x, 1.4))), 2))
B_W_Metric_raw['d_bin'] = B_W_Metric_raw['difficulty'].map(int)
B_W_Metric = B_W_Metric_raw.groupby(by=['s_bin', 'd_bin']).agg('mean').reset_index()
B_W_Metric['B-W'] = B_W_Metric['p'] - B_W_Metric['y']
B_W_Metric.pivot(index="s_bin", columns='d_bin', values='B-W').style.format("{:.2%}")
```

<img width="886" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/13e046fd-4d0b-4084-9cc4-2313cfc394b6">

**Comment by Expertium** [comment]
Remove %nan (as well as bins with less than 200 reviews), add color (assuming it's possible in matplotlib), and this will be what I wanted. 
Thats surprisingly few lines of code, interesting. I thought the code will be much longer.

**Comment by Expertium** [comment]
@L-M-Sherlock I'm just reminding you to finish this, see my comment above

**Comment by user1823** [comment]
> ```python
> B_W_Metric_raw = dataset[['difficulty', 'stability', 'p', 'y']].copy()
> B_W_Metric_raw['s_bin'] = B_W_Metric_raw['stability'].map(lambda x: round(math.pow(1.4, math.floor(math.log(x, 1.4))), 2))
> B_W_Metric_raw['d_bin'] = B_W_Metric_raw['difficulty'].map(int)
> B_W_Metric = B_W_Metric_raw.groupby(by=['s_bin', 'd_bin']).agg('mean').reset_index()
> B_W_Metric['B-W'] = B_W_Metric['p'] - B_W_Metric['y']
> B_W_Metric.pivot(index="s_bin", columns='d_bin', values='B-W').style.format("{:.2%}")
> ```

@L-M-Sherlock, how should I use this? Just putting this at the end gives me the following error:

<img width=512px src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/b5883833-6a13-4eb0-aead-7a03a9b04a5a">

**Comment by L-M-Sherlock** [comment]
What about this?

<img width="880" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/3ca4dc36-fbb3-42b1-9dda-889fcc8ddaf4">

**Comment by L-M-Sherlock** [comment]
> @L-M-Sherlock, how should I use this? Just putting this at the end gives me the following error:

Please use this branch: https://github.com/open-spaced-repetition/fsrs4anki/tree/Expt/new-baseline

I plan to move all variants to this branch.

**Comment by Expertium** [comment]
The heatmap looks just like what I wanted, yes.
But Sherlock, I have a problem with this branch you suggest. Most of the code is hidden from the user. This is good for the average user, but for me and user1823 this is detrimental sicne we can't edit the code to do out own tests.

**Comment by user1823** [comment]
Expertium suggested to not display anything if a bin contained <100 reviews. It makes sense to implement this because we want our data to be statistically significant. @L-M-Sherlock, did you implement this? I couldn't find anything similar to this in the code.

But, I think that the number 100 is a bit arbitrary. Possibly, we should use a percentage.

Also, my B-W metric heatmap looks like the following:
<img width=256px src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/7081dc00-564f-49ea-b581-2c41241051db">

Why does the stability have so many trailing zeros?

**Comment by user1823** [comment]
> Please use this branch: https://github.com/open-spaced-repetition/fsrs4anki/tree/Expt/new-baseline
> I plan to move all variants to this branch.

By the way, why do we even need to use this branch? Can't we move all the variants to a new "experiment" folder on the main branch itself?

**Comment by L-M-Sherlock** [comment]
> Why does the stability have so many trailing zeros?

I don't know. It looks fine in my Jupyter notebook.

> Expertium suggested to not display anything if a bin contained <100 reviews. It makes sense to implement this because we want our data to be statistically significant. @L-M-Sherlock, did you implement this? I couldn't find anything similar to this in the code.

I didn't. If you have a good suggestion, I will implement it.

> By the way, why do we even need to use this branch? Can't we move all the variants to a new "experiment" folder on the main branch itself?

I don't want to pollute the commits history of the main branch.

**Comment by Expertium** [comment]
> I didn't. If you have a good suggestion, I will implement it.

Just make it so that if the B-W metric was calculated based on less than 100 reviews (in other words, if the average predicted p was calculated using less than 100 values), the bin will be displayed as empty.

Also add the following code to the calibration graph, between `plt.figure()` and` plt.plot(bin_prediction_means, bin_correct_means, label='Average actual retention')`:
```
    ax = plt.gca()
    #make the grid look nicer
    ax.set_xlim([0, 1])
    ax.set_ylim([0, 1])
```
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/2e6dd4da-b419-483a-ad75-af979c42a7f9)

**Comment by user1823** [comment]
> Just make it so that if the B-W metric was calculated based on less than 100 reviews, the bin will be displayed as empty.

But that doesn't take into account the differences in the total number of reviews between different collections. In other words, 100 reviews is proportionately much larger for a small collection (of say, 7000 reviews) than for a large collection (of say, 700,000 reviews).

That's why I think that we should use a fixed percentage rather a fixed number of reviews.

Probably, we should use 100/3n % where n is the total number of boxes in the table.

**Comment by Expertium** [comment]
> Probably, we should use 100/3n % where n is the total number of boxes in the table.
> 
> For example, the image posted by me above has 19 rows and 7 columns. So, the total number of boxes is 133.
> 
> Assuming that my collection has 90,000 reviews, the cutoff would be 100/(3 × 133) % of 90,000, which is equal to 226 reviews.

@L-M-Sherlock I like this idea, implement this, please. Also check my comment above about some small changes to the calibration graph.

**Comment by L-M-Sherlock** [comment]
```python
B_W_Metric_raw = dataset[['difficulty', 'stability', 'p', 'y']].copy()
B_W_Metric_raw['s_bin'] = B_W_Metric_raw['stability'].map(lambda x: round(math.pow(1.4, math.floor(math.log(x, 1.4))), 2))
B_W_Metric_raw['d_bin'] = B_W_Metric_raw['difficulty'].map(lambda x: int(round(x)))
B_W_Metric = B_W_Metric_raw.groupby(by=['s_bin', 'd_bin']).agg('mean').reset_index()
B_W_Metric_count = B_W_Metric_raw.groupby(by=['s_bin', 'd_bin']).agg('count').reset_index()
B_W_Metric['B-W'] = B_W_Metric['p'] - B_W_Metric['y']
n = len(dataset)
bins = len(B_W_Metric)
B_W_Metric = B_W_Metric[B_W_Metric_count['p'] > max(50, n / (3 * bins))]
B_W_Metric_pivot = B_W_Metric.pivot(index="s_bin", columns='d_bin', values='B-W')
B_W_Metric_pivot.apply(pd.to_numeric).style.background_gradient(cmap='seismic', axis=None, vmin=-0.2, vmax=0.2).format("{:.2%}", na_rep='')
```

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/28128ac1-a794-40a7-bf78-3144237e3e6e)

**Comment by Expertium** [comment]
> B_W_Metric = B_W_Metric[B_W_Metric_count['p'] > max(50, n / (3 * bins))]
Yep, looks good.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/68d47cf6-305b-40eb-b1e0-9bc3fa3daedf)
