### ISSUE TITLE
[BUG] Code erases itself and the V3 Scheduler Turns itself off on PC Restart

### ISSUE THREAD

**Issue by Kenljs** [open-spaced-repetition/fsrs4anki#263]
**Describe the bug**
Since I have installed FSRS4Anki and turned on the v3 scheduler the scheduler turns itself off randomly. At the same time the "code" is erased from settings. I believe it occurs when I turn off my PC.  

**Environment**
 - Anki version: Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0

**Debug info taken from anki**
    
    Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-05-18 13:37:57
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Color Confirmation ['1084228676', 2020-03-14T07:13, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
    Deck name in title 21 ['699175524', 2019-05-31T20:05, 'None', '']
    DrawingPad ['370778248', 2019-08-21T08:00, 'None', '']
    Edit Field During Review ['1020366288', 2022-08-29T14:38, 'None', '']
    FSRS4Anki Helper ['759844606', 2023-05-16T20:44, 'None', mod]
    Fast cards reposition ['544982740', 2021-09-19T08:51, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T06:57, 'None', '']
    ImageResizer ['1214357311', 2022-07-15T08:05, 'None', '']
    Puppy Reinforcement ['1722658993', 2020-03-02T14:23, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
    RuneScape-Gamification ['931346754', 2022-12-27T15:06, 'None', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T16:32, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1084228676 1210908941 1214357311 1722658993 1771074083 1906641654 370778248 544982740 699175524 742185195 759844606 931346754
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Anki Habitica for 21 ['1758045507', 2022-02-09T06:54, 'None', mod]
    Anki Killstreaks ['579111794', 2021-12-15T09:20, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T14:24, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T04:12, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-14T20:16, 'None', '']
    Leaderboard ['41708974', 2023-01-15T04:53, 'None', mod]
    Quizlet to Anki 21 Importer with audio support ['1362209126', 2023-05-18T01:57, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T05:24, 'None', '']

**Comment by Kenljs** [comment]
I do not know anything about programming. This issue makes FSRS4Anki unusable. I am not sure if the issue is with Anki or with FSRS4Anki.

**Comment by L-M-Sherlock** [comment]
Do you have other device? AnkiMobile or Ankidroid. Some users reported that the code was removed after sync.

**Comment by Kenljs** [comment]
Yes!

 

I do use Anki on android (Ankidroid). What is the best solution to this?

**Comment by L-M-Sherlock** [comment]
You can track this issue: https://github.com/ankidroid/Anki-Android/issues/12866

**Comment by L-M-Sherlock** [comment]
@Kenljs recently, AnkiDroid 2.16.x has been released in Google Play. Could you reproduce the bug in the latest version?

**Comment by Kenljs** [comment]
It works! I had to install everything and set up the v3 scheduler on android, but the bug seems to have been squashed. I am so thankful!
