### ISSUE TITLE
[BUG] Scheduler not working when card is in filtered deck

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#266]
The scheduler (js) is not working when the card is in a filtered deck. 

I have set the `display_memory_state` to `true`. The memory states are displayed when the card is reviewed in the parent deck. But, these are not displayed when the card is in a filtered deck.

**Environment**
 - Anki version: 2.1.63
 - OS: Windows
 - Scheduler version: v3.20.0 Qt6

**Comment by L-M-Sherlock** [comment]
How can I reproduce it? It works well in my anki.

**Comment by user1823** [comment]
Something strange is going on. I see the issue on my main profile but I don't see the issue on a test profile using the same decks and the same custom scheduling code.

**Comment by L-M-Sherlock** [comment]
Does the bug still exist?

**Comment by L-M-Sherlock** [comment]
Does it happen on all types of cards? I guess it depends on the template.

**Comment by L-M-Sherlock** [comment]
Is this issue still active? I need furthermore feedback.

**Comment by user1823** [comment]
Yes, it is still active. Also, I tested it on two different notetypes. It happens with both.

**Comment by L-M-Sherlock** [comment]
> Yes, it is still active. Also, I tested it on two different notetypes. It happens with both.

Could you send affected cards to me? And please include the scheduler code. I want to reproduce this bug.

**Comment by user1823** [comment]
I found out an interesting thing. The issue occurs only when I include the following code at the top of my custom scheduling code.
```js
// Upon each press of Good, move ease towards 2.5 by .05
if (
  states.good.normal &&
  states.good.normal.review &&
  states.current.normal.review
) {
  let oldEase = states.good.normal.review.easeFactor;
  let diff = 2.5 - oldEase;
  states.good.normal.review.easeFactor +=
    Math.sign(diff) * Math.min(0.05, Math.abs(diff));
}
```

But, I can't think of any reason why adding this to the custom scheduling code would cause the FSRS scheduler to stop working in filtered decks.

**Comment by L-M-Sherlock** [comment]
```
// Upon each press of Good, move ease towards 2.5 by .05
if (
  states.good.normal &&
  states.good.normal.review &&
  states.current.normal &&
  states.current.normal.review
) {
  let oldEase = states.good.normal.review.easeFactor;
  let diff = 2.5 - oldEase;
  states.good.normal.review.easeFactor +=
    Math.sign(diff) * Math.min(0.05, Math.abs(diff));
}
```

Please use this code and try again.

**Comment by user1823** [comment]
So, this would mean that this code won't work for cards in filtered decks. Am I right?

Can you help me rewrite it so that it works for all cards?

**Comment by L-M-Sherlock** [comment]
```javascript
// Upon each press of Good, move ease towards 2.5 by .05
if (is_review()) {
  let oldEase = states.good.normal.review.easeFactor;
  let diff = 2.5 - oldEase;
  states.good.normal.review.easeFactor +=
    Math.sign(diff) * Math.min(0.05, Math.abs(diff));
}
```

Note: `is_review()` is a function in the FSRS4Anki Scheduler.

```javascript
function is_review() {
  if (states.current.normal?.review !== undefined) {
    if (states.current.normal?.review !== null) {
      return true;
    }
  }
  if (states.current.filtered?.rescheduling?.originalState !== undefined) {
    if (Object.hasOwn(states.current.filtered?.rescheduling?.originalState, 'review')) {
      return true;
    }
  }
  return false;
}
```

**Comment by user1823** [comment]
This didn't modify the ease for a card I reviewed in a filtered deck. Probably, the `states.good.normal.review.easeFactor` part should be modified too.

**Comment by user1823** [comment]
By the way, if it is not easy to solve, you can just close this issue. This code is not very useful to me because
- I do most of my reviews on AnkiDroid, where this code doesn't get executed.
- I don't think that I will ever revert back to Anki scheduler. So, the value of the ease doesn't have any importance.

**Comment by L-M-Sherlock** [comment]
> This didn't modify the ease for a card I reviewed in a filtered deck. Probably, the `states.good.normal.review.easeFactor` part should be modified too.

Is the card's ease lower than 2.5?

**Comment by user1823** [comment]
> The code works for me.

Did you review the card in a filtered deck?

**Comment by user1823** [comment]
I am sorry. It is working fine. It seems that I forgot to save the custom scheduling code after updating it.

**Comment by L-M-Sherlock** [comment]
And please add the code before `// display if FSRS is enabled`.
