### ISSUE TITLE
[Question] Forget collection and restart from scratch - fsrs data won't erase

### ISSUE THREAD

**Issue by Diego-BR** [open-spaced-repetition/fsrs4anki#267]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**

Quite sometime ago, I was advised to forget some cards (long interval from past due date using FSRS). 

BUT... 
Browser > forget  OR
Export without schedule info > delete > import again

didn't work as intended. 

I think the FSRS use some custom data written in the cards and that isn't erased using the ordinary options above. 

My solution (to erase all the collection) was to: 

1) Debug Console 
2)  mw.col.db.execute("delete from revlog where id > 0")
     mw.col.mod_schema(False)
3) mw.col.db.execute("delete from cards where id > 0")
    mw.col.mod_schema(False)
4) check database. 
5) Manually set the initial due date for cards. 

As of now, FSRS returns for all cards when first reviewed: 
- D 6.56
- S 1
- R 100

Is it supposed to be done like this? Maybe have the option to start from scratch (or do so for specific cards only) in the add-on is a good idea. 

And if i may ask, are the FSRS numbers ok after the erase?

**Comment by L-M-Sherlock** [comment]
> Browser > forget OR Export without schedule info > delete > import again
> 
> didn't work as intended.

Did you use `forget` and `rescheduling` both? I guess it could solve your problem.

**Comment by Diego-BR** [comment]
> Did you use Browser > forget and Helper > reschedule both? I guess it could solve your problem.

Yep. That's what I did. 
The custom data is not erased. 
The first interval is reduced as manually set. 
The next one comes back to the old ones. 
Only way to avoid that I could find was to force through the debug terminal to erase all card data. 
This way, in my first review, FSRS code generated a new custom data and interval could be effectively reduced.

**Comment by L-M-Sherlock** [comment]
> The custom data is not erased.

You can use the `reset` feature in the Helper add-on.

**Comment by Diego-BR** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/31831366/92c07108-5f34-4926-a64f-ed33370ee3d3)
and where would that be? 
That's exactly what I was looking for.

**Comment by L-M-Sherlock** [comment]
Undo reschedulings in all cards

**Comment by Diego-BR** [comment]
Got that. Tks. 

Just a heads up. It doesn't work if you forget / export/ import the note first. 
It must be run before any procedure in the notes. 

But it worked flawlessly. 

Tks!
