### ISSUE TITLE
[Question] What has been changed in scheduler.js for version v3.20.1?

### ISSUE THREAD

**Issue by gcafepgdi** [open-spaced-repetition/fsrs4anki#272]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

# For the release v3.20.1, it mentions that **"Scheduler (updated): fsrs4anki_scheduler.js"** as shown in the screenshot:

![fsrs-q-01](https://github.com/open-spaced-repetition/fsrs4anki/assets/56123506/1834a155-c44c-4447-99c8-13686a6b2eb7)

# But when I checked the code, it still is **// FSRS4Anki v3.20.0 Scheduler Qt6** and was last updated two weeks ago:

![fsrs-q-02](https://github.com/open-spaced-repetition/fsrs4anki/assets/56123506/d0817d6f-06b4-4b50-b907-0b28d48ee7aa)

# What has been changed in scheduler.js for version v3.20.1?

**Comment by L-M-Sherlock** [comment]
These is not update in scheduler.js for version v3.20.1. I update it in 3.20.0. 3.20.1 is for the simulator.
