### ISSUE TITLE
[Feature Request] 3 answer buttons option

### ISSUE THREAD

**Issue by N3Q1E2** [open-spaced-repetition/fsrs4anki#281]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Some people find it easier and faster to decide between 3 answer buttons, instead of the default 4.

**Describe the solution you'd like**
Add option to enable only 3 buttons - Hard, Good, Easy
Or is it too hard to modify the algorithm to support this?

**Comment by L-M-Sherlock** [comment]
Do you mean that they never use `again`? I wonder when will the interval be shortened in their case.

**Comment by N3Q1E2** [comment]
The names are just an example, can be Again/Hard/Easy as well, or other combination that works best.

**Comment by L-M-Sherlock** [comment]
> Or is it too hard to modify the algorithm to support this?

I think it doesn't need to modify the algorithm for this. FSRS has supported two key mode.
