### ISSUE TITLE
[Question] apkg not uploading to colab? 

### ISSUE THREAD

**Issue by ooohweee80085** [open-spaced-repetition/fsrs4anki#294]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

Hi there, 

I am trying to upload my akpg to colab and it is not uploading. 
I have adequate storage on google. 
Can you pleace provide some advice as to how to fix this? 

Cheers
![Screenshot 2023-06-11 123231](https://github.com/open-spaced-repetition/fsrs4anki/assets/136206903/532d707c-35ca-45f3-991f-c5232ef8cb2e)

**Comment by ooohweee80085** [comment]
Update: I've used a different browser, and have been able to upload my package, however I'm now getting an error: Any further help would be great!! 

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/136206903/1d0b18bc-503e-4c30-8ed6-ca337fa15705)

**Comment by L-M-Sherlock** [comment]
I can't reproduce this bug. Could you reload the notebook and try it again?

**Comment by L-M-Sherlock** [comment]
https://stackoverflow.com/questions/54408973/name-c-is-not-defined-pytorchjupyter-notebook

Restarting the kernel will fix this error.
