### ISSUE TITLE
[Feature Request] A short description of each grade (Again, Hard, Good, Easy)

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#295]
**Which module is related to your feature request?**
Scheduler/Helper

**Is your feature request related to a problem? Please describe.**
I've used Anki for a long time, and I've heard many people asking things like "["Again" "Good" "Easy", What do they mean?](https://www.reddit.com/r/Anki/comments/d7ulgv/again_good_easy_what_do_they_mean/)", or "[Differences between Again, Hard, Good, and Easy](https://www.reddit.com/r/Anki/comments/zpfj74/differences_between_again_hard_good_and_easy/)".

**Describe the solution you'd like**
Make an icon right next to the answer buttons, like this:
![Question mark icon](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/360a8a1a-1245-4b00-b55a-83d9efa45f37)
Hovering the mouse over the icon should reveal the following message:

> Easy - you answered correctly with no hesitation.
> Good - you answered correctly with a little bit of hesitation.
> Hard - your answer was partially correct and/or you hesitated a lot.
> Again - your answer was completely incorrect.

**Additional context**
I understand that this feature is not directly related to FSRS and the core functionality that FSRS provides, so if you choose to close this issue as irrelevant, it will be perfectly understandable. However, I believe that it's a nice way to clear some confusion that many users have, and the chances that Anki devs themselves will implement it if I ask them are much lower than if I ask you.

**Comment by L-M-Sherlock** [comment]
I think it is the Anki's responsibility. And it should support multi-language.
