### ISSUE TITLE
[Question] When to use different parameters per deck?

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki#299]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I am not sure when it's better to use different parameters per deck and when train global ones.

My case - I have separate decks for learning German and French.

I've learned German in high school many years ago, so I am mainly re-learning material. If I get some card right it will probably stay in memory longer, as I knew this material some time ago.

French on the other hand is a new language for me. If I get some card right I will probably need to repeat it soon, as this is a very new piece of information for me.

Hence, those two decks should have different parameters trained separately? Or should I train optimizer on both combined to use more training data?

**Comment by L-M-Sherlock** [comment]
For example, when you use different setting with the default algorithm in these decks, I recommend you use different parameters with FSRS.

**Comment by szalejot** [comment]
> 

Thanks, I will go with that.

**Comment by Expertium** [comment]
I will add a little bit more - it depends on your _subjective_ feeling of difficutly (not FSRS difficulty). For example, if deck A makes you feel "Wow, this stuff is so easy!" and deck B makes you think "Damn, this stuff is so hard...", then it will likely be better for you to make 2 different sets of parameters for each deck.
