### ISSUE TITLE
The optimizer notebook seemed to fail on a SQL query

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#3]
I uploaded my deck to Collab notebook, but the file extension was `colpkg`, not sure if this is OK. I then ran all the code, but looks like the execution stopped at a SQL query statement. I've attached a screenshot for this. Thank you.
![2022-09-20_19-47](https://user-images.githubusercontent.com/742238/191352017-d0372db7-c3da-4cfa-8191-df2795eec517.png)

**Comment by L-M-Sherlock** [comment]
What's your Anki version? I see the collection.anki21b in the files. I never saw it before.

**Comment by L-M-Sherlock** [comment]
I got it. `anki21b` is the filename extension of the collection for the latest version of Anki. I have supported it in the newest version now. You can try it at https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb

**Comment by YorkZ** [comment]
Hi @L-M-Sherlock Thank you for the help. I'm using the Anki from git commit 5bf031f1e. I built this version a few days ago for the sake of trying out your amazing algorithm. I'll try your new notebook.

**Comment by L-M-Sherlock** [comment]
@YorkZ The problem still exists. Please export your collection file with `Support older Anki versions` and try it again.

**Comment by YorkZ** [comment]
Looks like it succeeded this time, thanks again. But I still have two questions:

1. Does the `.colpkg` file I exported include all my decks, or just one deck? If it includes all the decks, then how can I make it to include only one deck because I want to optimize each individual deck separately.
2. I still don't know how to use the results of running the notebook. My understanding is that the results would have to be copied back to my local computer because I run Anki on my local computer right? However, I wasn't able to find any document about how to incorporate the optimization results back into the local Anki system.

**Comment by L-M-Sherlock** [comment]
1. You can use `.apkg` file to optimize for each deck.
2. Copy the parameters in the notebook and replace the parameters in the custom scheduling of Anki deck options with them. The following output is an exmple.

```python3
print(f"const defaultDifficulty = {defaultDifficulty};")
print(f"const defaultStability = {defaultStability};")
print(f"const difficultyDecay = {difficultyDecay};")
print(f"const stabilityDecay = {stabilityDecay};")
print(f"const retrievabilityFactor = {retrievabilityFactor};")
print(f"const increaseFactor = {increaseFactor};")
print(f"const lapsesBase = {lapsesBase};")
```

**Comment by YorkZ** [comment]
Thank you so much. I would recommend that you document this step as well though. I'll try it out tomorrow.

**Comment by L-M-Sherlock** [comment]
OK, I've added some documentation to the notebook just now.

**Comment by YorkZ** [comment]
Sorry I still don't fully understand it. So should I copy the `print` statements in the `Result` section from running the notebook, to the `Custom scheduling` box in `Anki` deck option? But which line should I insert these `print` statement to? I don't see any `print` statement in that `javascript` file.

**Comment by L-M-Sherlock** [comment]
The default parameters in the `javascript` file:
![Snipaste_2022-09-21_11-47-29](https://user-images.githubusercontent.com/32575846/191410049-0f7de521-306e-40ba-8c18-2f78aa199e7b.png)

The output of the optimizer:
![Snipaste_2022-09-21_11-47-52](https://user-images.githubusercontent.com/32575846/191410066-b5c6eb5f-6fd1-431b-a9c1-01fec6d1b662.png)

You can replace the default parameters with the output of the optimizer.

**Comment by YorkZ** [comment]
I see. I also guessed this, but I did compare the defaults generated by the notebook with the defaults in that `javascript` file, and found them to be exactly the same. The following was copied from my results of the notebook, and as you can see they have no difference with the ones in that `javascript` file.

``` javascript
const defaultDifficulty = 4.6179;
const defaultStability = 2.5636;
const difficultyDecay = -0.5913;
const stabilityDecay = -0.1382;
const retrievabilityFactor = 1.1951;
const increaseFactor = 3.201;
const lapsesBase = -0.0562;
```

**Comment by L-M-Sherlock** [comment]
Maybe your code hasn't run there. The default output is generated from my revlog.

**Comment by YorkZ** [comment]
I uploaded only the exported file for the deck I was interested in (the `.apkg` file), and then ran the `notebook` again. This time it did produce the different parameters. So everything is ready for me to try it out tomorrow. Thanks again.

**Comment by L-M-Sherlock** [comment]
More feedback is welcome. You can share in the discussion: https://github.com/open-spaced-repetition/fsrs4anki/discussions

**Comment by YorkZ** [comment]
Sure. But I suppose it would like some time to know the results right? Or is there a way to know the results quicker?

**Comment by L-M-Sherlock** [comment]
Yes, it needs time. Maybe one month or more. Thanks for your test. And I will develop a simulator for predicting the review in the future.

**Comment by YorkZ** [comment]
What did you mean by "predicting the review"?

**Comment by L-M-Sherlock** [comment]
Like this add-on: [Anki Simulator](https://ankiweb.net/shared/info/817108664).

**Comment by YorkZ** [comment]
Sounds really cool!
