### ISSUE TITLE
[BUG] Optimizer not working anymore

### ISSUE THREAD

**Issue by parapluiie** [open-spaced-repetition/fsrs4anki#309]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/136634091/c5faa9f3-da03-4673-91e2-d927e5e68e2e)

Anybody else having this issue?

**Comment by L-M-Sherlock** [comment]
Could you share the setting with me?

timezone

next_day_starts_at

revlog_start_date

**Comment by parapluiie** [comment]
Europe/Zurich
19
2006-10-05

**Comment by L-M-Sherlock** [comment]
Could you share the related deck/collection file with me?

**Comment by parapluiie** [comment]
I've sent it to you. thank you very much

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/blob/v3.25.2/fsrs4anki_optimizer.ipynb

It would solve the bug.
