### ISSUE TITLE
[Question] I have a pretty new deck. Is it ok to use the default settings (parameters)?

### ISSUE THREAD

**Issue by Diego-BR** [open-spaced-repetition/fsrs4anki#313]
**Research**

*Enter an [x] character to confirm the points below:*

- [ X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X ] I have searched for similar existing questions here

**Question**

I have a pretty new deck. Is it ok to use the default settings (parameters)? Or should I use the FSRS algo only when it is mature enough to run the optimizer?

**Comment by L-M-Sherlock** [comment]
You can use the default parameters for a month. Then use the optimizer with your own review data to generate the parameters.

**Comment by Diego-BR** [comment]
tks
