### ISSUE TITLE
[Question] can I use Anki simulator addon instead of FSRS simulator?

### ISSUE THREAD

**Issue by superislam** [open-spaced-repetition/fsrs4anki#316]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
can I use Anki simulator addon instead of FSRS simulator? as I cant use FSRS simulator

**Comment by L-M-Sherlock** [comment]
You can use the Anki simulator, but it won't simulate your review accurately when you use FSRS.

**Comment by superislam** [comment]
> You can use the Anki simulator, but it won't simulate your review accurately when you use FSRS.

so how can I simulate accurately?

**Comment by L-M-Sherlock** [comment]
> so how can I simulate accurately?

Until now, there is not a way to simulate the reviews with FSRS accurately.

**Comment by superislam** [comment]
> > so how can I simulate accurately?
> 
> Until now, there is not a way to simulate the reviews with FSRS accurately.

OK if I use anki simulator I think the state of retention will be better than what appears in the add-on when using FSRS Isn't it?

**Comment by L-M-Sherlock** [comment]
> OK if I use anki simulator I think the state of retention will be better than what appears in the add-on when using FSRS Isn't it?

They are unrelated. Because Anki built-in algorithm doesn't promise a specific retention level.

**Comment by user1823** [comment]
@L-M-Sherlock, is it possible to add the FSRS simulator to the helper add-on?

I am not asking you to implement it. I am just asking about the possibility.

But, if it is not much time-consuming to implement, I would also suggest you to implement it. The reason being that simulation on Google Colab is much more difficult than simulation using an add-on.

**Comment by L-M-Sherlock** [comment]
> I am not asking you to implement it. I am just asking about the possibility.

It's possible, but requires much time to implement, especially the GUI module.

**Comment by user1823** [comment]
What about reusing the code from the Anki simulator add-on?

I think that the GUI should be similar.

**Comment by L-M-Sherlock** [comment]
I will take a look. By the way, my vacation has ended, so the development would be slow down.

**Comment by Expertium** [comment]
So, Sherlock, any plans to integrate the simulator into the add-on?

**Comment by L-M-Sherlock** [comment]
I haven't read the code of Anki Simulator. I will check it in this week.

**Comment by peter-moran** [comment]
+1. I'd love to be able to run a simulation within Anki, it is really helpful to get a rough estimate of my future workload based on performance, and to get a sense of when my reviews might start trailing off (at my current rate).

**Comment by Expertium** [comment]
If anyone wants to use a simulator with FSRS, use this: https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v4.10.2/fsrs4anki_simulator.ipynb
@L-M-Sherlock please close this issue
