### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ApprobationBW** [open-spaced-repetition/fsrs4anki#318]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**
Could you please kindly provide the scientific articles from your research ?

I would be happy to read them to better understand "FSRS4Anki" but they are behind a paywall. Unfortunately, the article is not available on "[Sci-Hub](https://en.wikipedia.org/wiki/Sci-Hub)" or "[Anna's Archive](https://en.wikipedia.org/wiki/Anna%27s_Archive)".

I am referring to the following articles:

https://dl.acm.org/doi/10.1145/3534678.3539081?cid=99660547150

https://ieeexplore.ieee.org/document/10059206/metrics#metrics

Thanks for your wonderful work.

**Comment by L-M-Sherlock** [comment]
Please read the README.md, where I have provided a free access link: [A Stochastic Shortest Path Algorithm for Optimizing Spaced Repetition Scheduling](https://www.maimemo.com/paper/).

For my another paper, you can request it in my research gate: https://www.researchgate.net/publication/369045947_Optimizing_Spaced_Repetition_Schedule_by_Capturing_the_Dynamics_of_Memory
