### ISSUE TITLE
[Data] Sharing my Japanese revlog (~19k young+mature cards learned)

### ISSUE THREAD

**Issue by kuroahna** [open-spaced-repetition/fsrs4anki#32]
**Data file**
I'd like to share my `revlog.csv` from my Japanese collection which has about ~19,000 young+mature cards learned. There's about 515296 entries in this CSV file. I hope this will be useful for future developments of fsrs4anki! Feel free to use however you'd like :) 

[revlog.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/9647754/revlog.zip)

Let me know if there's any other information you need

**Additional context**
- Timezone: `Canada/Eastern`
- The next day starts at: 8

**Comment by L-M-Sherlock** [comment]
Thanks!
