### ISSUE TITLE
[Question] group_cnt doesn't match card count in optimizer?

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki#323]
I'm confused about how the optimizer is extracting data from the deck.
I uploaded a deck and set the date range to include cards rated within the past year. This covers 8301 cards. But when I ran the optimizer, 1.2 gave me:
```
Retention calculated.
100%
13418/13418 [00:14<00:00, 634.17it/s]
Stability calculated.
analysis: 100%
316/316 [00:00<00:00, 435.76it/s]
Analysis saved!
1:again, 2:hard, 3:good, 4:easy
  r_history  avg_interval  avg_retention  stability  factor  group_cnt
          1           1.3          0.535        2.4     inf       2187
        1,3           3.8          0.731       17.2    7.17       1113
      1,3,3           9.3          0.796       13.1    0.76        778
    1,3,3,3          42.6          0.792       22.7    1.73        662
  1,3,3,3,3          97.1          0.766       31.4    1.38        494
1,3,3,3,3,3         113.6          0.816       31.4    1.00        170
          3           1.8          0.766       13.0     inf       2100
        3,3           5.1          0.835       37.4    2.88       1495
      3,3,3          11.8          0.882       25.7    0.69       1199
    3,3,3,3          66.0          0.866       61.2    2.38       1193
  3,3,3,3,3         111.5          0.826       64.7    1.06        812
3,3,3,3,3,3         122.4          0.792       32.4    0.50        215
```

Shouldn't the group count add up to the number of cards, since each card has one review log?
But here it adds up to 12418.
Also, what do 13418/13418 and 316/316 mean? Where are those numbers coming from?

**Comment by L-M-Sherlock** [comment]
> Also, what do 13418/13418 and 316/316 mean? Where are those numbers coming from?

13418 is the number of unique `rating history`. 316 is the number of unique `rating history` whose group count is higher than 10.

**Comment by L-M-Sherlock** [comment]
Here is the related code:

https://github.com/open-spaced-repetition/fsrs4anki/blob/3c037cb4068a43df92759f953dcb1783423ee7d5/package/fsrs4anki_optimizer/fsrs4anki_optimizer.py#L419-L426

**Comment by akavi1** [comment]
That still doesn't make sense. If there are only 8301 cards in the deck within the date range, how can there be 13418 unique rating histories? There's one history per card so at most there can only be 8301 unique rating histories right?

**Comment by L-M-Sherlock** [comment]
> If there are only 8301 cards in the deck within the date range, how can there be 13418 unique rating histories?

No. If a card has 10 reviews, it will have 10 review logs and 10 rating histories.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/75d24ccc-ede1-4823-a7d1-b00168b6659a)

**Comment by akavi1** [comment]
Ahh I see. So only a small fraction of the data is shown in the output. The full output would have 13418 rows. And if you were to add up the group_cnt from all 13418 rows, you would get the total number of review logs
