### ISSUE TITLE
[BUG] Strange intervals in revlog.csv from the optimizer

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#326]
I noticed some strange (negative) intervals in the revlog.csv obtained from the optimizer.

Screenshot:
<img width="782" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/46a62e6f-a836-4bf9-a40a-e21a611895b8">

This is not a new problem. It also exists in a revlog.csv that had been there in my Downloads folder since 6th May.

My deck: [Default.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/11311507/Default.zip) (Change extension to .apkg)

This deck file is from April 2023 but it should work because most of the abnormal revlogs are from 2022.

[revlog.xlsx](https://github.com/open-spaced-repetition/fsrs4anki/files/11907192/revlog.xlsx) (generated today)

timezone = 'Asia/Calcutta'
next_day_starts_at = 4
revlog_start_date = "2006-10-05"

**Comment by L-M-Sherlock** [comment]
They not strange.

>       -- interval (used in SRS algorithm). Negative = seconds, positive = days

Source: https://github.com/ankidroid/Anki-Android/wiki/Database-Structure

**Comment by user1823** [comment]
But still, why are some intervals negative and some positive?

**Comment by L-M-Sherlock** [comment]
> But still, why are some intervals negative and some positive?

You should ask Dae, the main developer of Anki. He designed the database like that.

**Comment by L-M-Sherlock** [comment]
In learning and relearning stages, the intervals are stored as seconds. In review stage, the intervals are stored as days.

**Comment by user1823** [comment]
> In learning and relearning stages, the intervals are stored in seconds. In review stage, the intervals are stored in days.

I think that this is something related to the v2 scheduler because this behaviour is not seen with the newer revlogs. (I am using the v3 scheduler since about August 2022.)
