### ISSUE TITLE
[Question] Unable to train the model on Colab - Cannot set a DataFrame with multiple columns to the single

### ISSUE THREAD

**Issue by lucatortiglione** [open-spaced-repetition/fsrs4anki#328]
Hi!
I was curious about optimizer but i'm not able to run all the steps

At the train model i get this error

ValueError                                Traceback (most recent call last)
[<ipython-input-44-c2c58482956d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 optimizer.train()

2 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py](https://localhost:8080/#) in _set_item_frame_value(self, key, value)
   4123 
   4124         if len(value.columns) != 1:
-> 4125             raise ValueError(
   4126                 "Cannot set a DataFrame with multiple columns to the single "
   4127                 f"column {key}"

ValueError: Cannot set a DataFrame with multiple columns to the single column tensor

How can i resolve ?

Thank you.

**Comment by L-M-Sherlock** [comment]
Do you upload a deck file with the scheduling information?

**Comment by lucatortiglione** [comment]
> Do you upload a deck file with the scheduling information?

Sure but i wonder how many times i have to study the deck before to upload it.

Another question, i have tried with another deck and i get "Training data is inadequate."

Do i have to reset the deck informations ? It's the first time i use your addon on Anki, copied and pasted your code into the deck options...tried to simulate some studies but i get "Cannot set a DataFrame with multiple columns to the single"

**Comment by L-M-Sherlock** [comment]
Could you share the affected deck file with me?

**Comment by lucatortiglione** [comment]
> Could you share the affected deck file with me?

Sure but by private way

**Comment by lucatortiglione** [comment]
> Could you share the affected deck file with me?

Sure but by private way.
Check your outlook mailbox

**Comment by lucatortiglione** [comment]
I have studied again 96 cards (so full deck) from the package where i got the error "training data is inadeguate" and now it's working. I don't know why.

**Comment by L-M-Sherlock** [comment]
> Another question, i have tried with another deck and i get "Training data is inadequate."

Because your deck file doesn't have enough review logs to train the model.

**Comment by L-M-Sherlock** [comment]
> 4127 f"column {key}"
> 
> ValueError: Cannot set a DataFrame with multiple columns to the single column tensor
> 
> How can i resolve ?

It is caused by the same problem. In you deck file, there are only review logs for the first learning. FSRS needs review data.

**Comment by lucatortiglione** [comment]
i'm happy to have helped you to improve your code a bit
