### ISSUE TITLE
Massive Intervals (400%+) for Just Learned Cards

### ISSUE THREAD

**Issue by slang19** [open-spaced-repetition/fsrs4anki#332]
**Research**
*Enter an [x] character to confirm the points below:*
- [ X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X ] I have searched for similar existing questions here
       → I found someone with a similar question but am unsure how to apply their fix to my situation
https://github.com/open-spaced-repetition/fsrs4anki/issues/113

**Question**
Hello,

Thank you for making this wonderful add-on and making the documentation so thorough!

I'm having an issue(?) thats giving me very large intervals when learning cards graduate thats caused my retention to tank from its usual ~85-90% to 60%. I applied this add-on a week or so ago, and am just now starting to seeing the cards that have exited the learning phase since I've added this add-on. And... its not going well. For most new cards after it finishes the learning stages (2m 1d 2d, grad 4d) it gives me a 8-10d interval instead of 4d, causing me to fail the majority of the cards. Weirdly enough for some cards its arbitrarily giving the expected 3-5d (the cards I'm comparing all have 3 3 3 ratings).

Essentially, my question is: how do I make sure newly graduated cards get a reasonable interval?

### Conditions of note
- I don't have a ton of revlog data, started Nov 2021
- I didn't touch Anki for a ~3 month period recently, possibly causing circumstantial data
- I did the training weights before I started and haven't changed them since (details at end)
- Attached are my .apkg files from 6/24/23 (date of installing FSRS) and today 7/2/23: [Archive.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/11930317/Archive.zip)
- I use "Set Added Date" addon to change the "Created Date" to the day I learned the card as I am using a premade deck. But this also changes the card ID, Anki somehow keeps track of this as all reviews pre and post change show up, but revlog doesn't retroactively modified. Maybe causes an issue?
- I have two main decks Listening and Speaking, I learn words through Listening cards 1st, then ~1 month later I introduce the Speaking card (of the same note). So the 1 note with 2 cards are split into 2 decks for this purpose. I tried to train the weights for each deck separately as my rates and how I approach them is very different, **_but training the export of my Listening deck and Speaking deck very unexpectedly gave me the exact same results_**. I suspect the Anki export exports the entire note's revlog not just the card's revlog, and I suspect the revlog of me breezing through cards on my Speaking deck (because the Listening counterpart is ~mature by that point) may be infecting what my actual training weights should be for my Listening Deck.

### 8-10d post learn interval
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/2716127f-c7d7-4efb-aaa6-c8fba67fccec)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/932d975a-36b3-4ac0-860d-6544ad48aa1d)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/1d6aa47c-67a2-41f9-b771-ba5f15ae7df6)

### Expected 3-5d post learn interval
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/77e6798a-ca98-4676-926f-9874180cf383)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/ef9b624c-cf86-4d23-b61a-96e1de0d7633)

### Training Output
from 6/24/23
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/1dde0614-aefd-499b-8d1b-b48df136fb00)
weights = [1.0102, 0.8987, 5.1168, -0.6363, -0.6888, 0.0528, 1.3007, -0.2766, 0.7057, 1.9952, -0.2162, 0.2971, 0.9]

**Comment by slang19** [comment]
Actually just confirmed the last bullet, it seems the model is misleadingly training on all _notes_ exported not just _cards_ in the deck exported.
I imported my export into a new profile, deleted the Speaking cards entirely and re-exported. This is the difference in results:

## Listening Deck (with listening cards included only) where note has Listening and Speaking card
[1.0184, 0.8122, 5.115, -0.5947, -0.6583, 0.0629, 1.291, -0.2894, 0.6967, 2.0033, -0.2053, 0.2562, 0.919]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/1376bf4c-1ea9-42f5-a0ed-76e740a5c6aa)

## Listening Deck (with listening cards included only) where note has only Listening
[0.713, 0.8709, 5.1592, -0.6371, -0.6464, 0.0669, 1.2396, -0.3439, 0.6406, 1.9368, -0.2629, 0.2037, 0.9441]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/111784386/efb6e734-8338-4526-b890-43c155b53109)
** for new words I review words a couple times outside of anki then 'learn' the listen card in anki, thus I've never rated a new listen card again/1. So when I see the fact that the previous export includes a "1" rating in the 1st slot, that confirms my suspicion that the training is seeing all cards of a note.

Pre and Post Delete Exports, [Archive.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/11930625/Archive.zip)

**Comment by L-M-Sherlock** [comment]
Could you provide your weights and requested retention?

**Comment by L-M-Sherlock** [comment]
> Actually just confirmed the last bullet, it seems the model is misleadingly training on all _notes_ exported not just _cards_ in the deck exported.

This problem has been solved in #324

**Comment by slang19** [comment]
Yes, but I've found a manual way to remedied it. The issue linked was about filtering out the revlog of cards that no longer exist, which works as intended once I manually delete the cards in other decks that unintentionally get pulled that I don't want for that specific optimization.

If I exporting my cards (which exports all associated notes, even though the associated cards that arn't in the same deck) and import it into a blank profile. Then for each card type, I can delete all other card types, leaving just the cards I want to be considered, and re-export. And repeat for each card type. I saw that you can filter out suspended cards, but I use the suspend function to hide new cards I haven't made mnemonics for yet, so I'd lose track of what cards I actually wanted to suspend.

I think its more an issue of how Anki exports cards, as the optimizer doesn't know which Deck I'm trying to optimize. It just sees the export of notes I give it, and thus doesn't filter out cards not in a specific deck.

**Comment by L-M-Sherlock** [comment]
> This issue is that Anki includes more cards in one's export than only just the ones in the deck you select to export.

Was it solved by https://github.com/open-spaced-repetition/fsrs4anki/pull/324?

**Comment by slang19** [comment]
#324 works as intended but doesn't address what I'm referencing. The issue is that I even need to delete cards in the first place, not whether or not they are successfully deleted.

It would be nice if I could just export the deck and tell the collab notebook the deck name and have it work. Instead of having to open a new profile in Anki to individually strip every card type of a note for every single deck, so that the collab notebook will read only the cards that are truly in the deck.

**Comment by L-M-Sherlock** [comment]
> * I tried to train the weights for each deck separately as my rates and how I approach them is very different, **_but training the export of my Listening deck and Speaking deck very unexpectedly gave me the exact same results_**.

I get it. You means Anki exports the deck based on note instead of card. Unfortunately, you are right. I haven't figure out a solution now.

> I saw that you can filter out suspended cards, but I use the suspend function to hide new cards I haven't made mnemonics for yet, so I'd lose track of what cards I actually wanted to suspend.

What if you can filter out cards with specific flag? Will it be helpful?

**Comment by slang19** [comment]
That would actually be really helpful, I could reserve a flag just for that purpose. And it would make it so I don't have to make a new profile and delete cards.

**Comment by L-M-Sherlock** [comment]
In v4.5.0, you can set the `filter_out_flags` in the optimizer notebook.

https://github.com/open-spaced-repetition/fsrs4anki/releases/tag/v4.5.0
