### ISSUE TITLE
[Question] When using FSRS on two key mode, do I need to do any special configuration to tell it that I'm in two key mode?

### ISSUE THREAD

**Issue by AkiraChisaka** [open-spaced-repetition/fsrs4anki#333]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I am using FSRS on two key mode. I prefer 2 key because making less decision when going though cards allows me to go though significantly more cards everyday.

But I am wondering, do I need to do any special configuration to tell FSRS that I am in two key mode? Or can FSRS just auto adjust and self calibrate to work as intended?

Also, algorithmically wise, would it be theoretically possible? Would FSRS knowing that "Easy" and "Hard" key being disabled help FSRS to function better?

Anyway, I have just finished setting up fsrs4anki and helper, and I think they are both working as intended. But this question is something that I just really want to figure out.

**Comment by L-M-Sherlock** [comment]
It doesn't require any extra configuration to use two-key mode with FSRS. If you have used two-key mode for a long time, the optimizer could learn it from your review logs automatically.

**Comment by AkiraChisaka** [comment]
> It doesn't require any extra configuration to use two-key mode with FSRS. If you have used two-key mode for a long time, the optimizer could learn it from your review logs automatically.

I see, thanks Jarrett!

Currently, I do most of my reviews on my PC, which is running Anki in two-key mode. I have also played around with Ankiweb in mobile browser, and have done some review on it too. And since it's vanilla Anki, it is on four-key mode.

This means I have a large amount of review logs where I have used only 1 and 3, with a few 2s and 4s scarcely scattered around.

I wonder, do you think FSRS likes this? I think I should just continue?

**Comment by L-M-Sherlock** [comment]
> And since it's vanilla Anki, it is on four-key mode.

But you could only use two-key, right?

**Comment by L-M-Sherlock** [comment]
> I wonder, do you think FSRS likes this? I think I should just continue?

It wouldn't make much trouble. Just feel free to go in your way.

**Comment by AkiraChisaka** [comment]
> But you could only use two-key, right?

I see, I was wondering if alternating between 2 key and 4 key mode was a terrible idea.

Sounds like it should be safe to do, thanks!
