### ISSUE TITLE
Review Intervals out of order

### ISSUE THREAD

**Issue by saddj001** [open-spaced-repetition/fsrs4anki#343]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**

Problem: Cards that have longer intervals for rating the card as more difficult doesn't make any sense to me. I have just started using FSRS for ~5 days and I am finding more and more cards that have this issue - see screenshot below:
<img width="1023" alt="Screenshot 2023-07-10 at 7 55 54 am" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48365667/9d32caf9-d526-4be8-bce9-aed854c0cb6a">

**For this card, I would have expected that the review intervals were as such: Again = <25m, Hard = 1d, Good = 2d, Easy = 4d.**

I have read FAQ#7 and have read multiple comments and threads that discuss this exact issue, the fact that if I rate the card as 'easy' I will see it more soon than if I took a long time to remember it and rated it 'hard'. **Is this a feature or a bug?**

The only answer I've seen to this issue is that 'learning steps of longer than 1 day are not recommended' - as in FAQ#7. Does this mean that if I use learning steps of 1d or more, this **_BREAKS_** the review intervals in the way I have described above? Or is it just the opinion that learning steps that large aren't good for retention? It would be good if this could be clarified in the FAQ as the answer provided isn't very clear.

Here is that cards info:
<img width="650" alt="Screenshot 2023-07-10 at 7 59 28 am" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48365667/9fb8ef07-1b73-47b9-a7a0-7bd212ba8b6c">

Here are the options settings for that subdeck:
<img width="1624" alt="Screenshot 2023-07-10 at 8 00 23 am" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48365667/d3543ac4-468a-4634-ba6c-80689e75d180">

Here are my numbers from the optimiser (trained on over 150k reviews over ~300 days of continuous reviews)
[0.5797, 1.4926, 4.6203, -1.9277, -2.3911, 0.0572, 1.743, -0.1684, 1.0841, 1.6952, -0.6052, 0.6027, 1.4804],
requested retention is set to 0.85

I am hoping someone can give me a full explanation regarding:
1. Why the ratings (with my current settings) don't give ascending review intervals and whether it has to do with my learning steps including 1d and above? For instance, the card example attached should be: Again = <25m, Hard = 1d, Good = 2d, Easy = 4d.
2. The recommendation to use learning steps below 1d, is this just a preference of whoever is recommending that? Or is it a requirement for FSRS to work as intended? i.e. using learning steps of 1d and above actually breaks something and results in these non-ascending review intervals?

I hope this makes sense. Thankyou.

**Comment by saddj001** [comment]
Another example for a card that has a strange review interval of a different kind. The first two times the card has been reviewed and rated with 'good' both times (3, 3...). Now if I were to rate the card as 'good' again, (3, 3, 3...) the review interval would be 1d, even though the last review interval was 4 days.

<img width="1021" alt="Screenshot 2023-07-10 at 11 11 03 am" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48365667/3522a1e1-67ef-4de9-a842-3467d47d9dd4">

**Comment by L-M-Sherlock** [comment]
Because you mix two algorithm in the long-term. When you set steps longer than one day, the long-term intervals will include the one given by steps and the one given by FSRS. FSRS doesn't know the interval given by steps, and steps also doesn't know the interval given by FSRS. So these intervals are out of order.

**Comment by L-M-Sherlock** [comment]
To solve this problem, please remove `4d` from your learning step.

**Comment by saddj001** [comment]
> Because you mix two algorithm in the long-term. When you set steps longer than one day, the long-term intervals will include the one given by steps and the one given by FSRS. FSRS doesn't know the interval given by steps, and steps also doesn't know the interval given by FSRS. So these intervals are out of order.

Thank you very much for responding, hoping to get this solved and keep learning! Your work is very much appreciated.

So from what you've said, it does sound like having learning steps larger than 1d actually BREAKS or 'overwrites' the function of FSRS? I feel like this should be more clear in the setup page, rather than making it sound like it's an optional change you would suggest as a matter of preference.

I will try your change, removing 4d. Though this is only in my new cards learning steps and not in the Lapses learning steps. Will this solve the issues I'm finding with review cards? Will it take a few more reviews for FSRS to 'solve' this, or should it immediately change these incorrect intervals?
Thank you again.

**Comment by L-M-Sherlock** [comment]
> I will try your change, removing 4d. Though this is only in my new cards learning steps and not in the Lapses learning steps. Will this solve the issues I'm finding with review cards? Will it take a few more reviews for FSRS to 'solve' this, or should it immediately change these incorrect intervals?

It happens in all steps. If you want to solve these issues in the reviewed cards, you should use FSRS4Anki Helper add-on to reschedule these cards.

**Comment by L-M-Sherlock** [comment]
> So from what you've said, it does sound like having learning steps larger than 1d actually BREAKS or 'overwrites' the function of FSRS? I feel like this should be more clear in the setup page, rather than making it sound like it's an optional change you would suggest as a matter of preference.

Some users want to control the learning intervals. And it's not `overwrite`. Learning step and review interval are not overlapped.

**Comment by L-M-Sherlock** [comment]
For example, what would happen if you set graduating interval shorter than learning steps? I think the same issue will happen.

**Comment by saddj001** [comment]
> Some users want to control the learning intervals. And it's not `overwrite`. Learning step and review interval are not overlapped.

"Overwrite" may have been the wrong word to use, but with my original learning steps settings FSRS is clearly not working as intended, right? It wasn't clear to me that if I kept my intervals including "4d" that it would create such strange results as in my original screenshots: (Again = <25m, Hard = 1d, Good = 2d, Easy = 4d).

**Comment by L-M-Sherlock** [comment]
> "Overwrite" may have been the wrong word to use, but with my original learning steps settings FSRS is clearly not working as intended, right? It wasn't clear to me that if I kept my intervals including "4d" that it would create such strange results as in my original screenshots: (Again = <25m, Hard = 1d, Good = 2d, Easy = 4d).

It's intended. Pressing `Hard` will keep your card in the learning stage, so it will use the interval given by learning steps. Pressing `Good` or `Easy` will move your card into `review` stage, so it will use the interval given by FSRS.

**Comment by saddj001** [comment]
Okay thank you, this makes more sense now. Appreciate your patience. I will close the question.

**Comment by L-M-Sherlock** [comment]
Related FAQ: https://faqs.ankiweb.net/hard-good-interval-longer-than-good-easy.html
