### ISSUE TITLE
[Question] When do I need to update FSRS?

### ISSUE THREAD

**Issue by AkiraChisaka** [open-spaced-repetition/fsrs4anki#344]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I was wondering, when do I need to update the core code of FSRS? I mean the part where you copy and paste the FSRS Scheduler Code.

Do I ever need to do so? And is there any system to alert me that a new stable update have come out and I should consider re-setting up FSRS again?

I am currenting using FSRS Scheduler Code, optimized with Optimizer, and using Helper on my PC. The Helper updates automatically with Anki's plugin system, and the Optimizer only needs to be ran when I feel like I need a re-optimize.

But I still can't figure out when should I update and get the new Scheduler Code. I think most updates on the FSRS project does not involve changing the Scheduler Code? For example, `v3.26.1` that happened 4 days ago.

I think currently, the easiest way is to just check the version number on top of the Code, which is `FSRS4Anki v3.20.0 Scheduler Qt6`. When that version number changed, it's time to update?

**Comment by L-M-Sherlock** [comment]
I recommend updating the scheduler code once it changes.

FSRS4Anki Scheduler has been stable for months, because it is simpler than Optimizer and Helper. If I update the scheduler, it would be a patch to solve serious bug or a major improvement to align with the new formula of FSRS4Anki Optimizer.

**Comment by AkiraChisaka** [comment]
I see, thanks for the info!
