### ISSUE TITLE
[Question] When the interval is 0, successful recall leads to stability becoming 0

### ISSUE THREAD

**Issue by vedang** [open-spaced-repetition/fsrs4anki#354]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**

I am implementing the `fsrs` algorithm from the lastest (v4) version into the Clojure language today. When testing, I noticed that once the card was in `:review` state, any successful recall would set the `stability` to 0. Looking at the formulae, this happens because:

1. The `interval` is 0 since `elapsed-days` is 0. 
2. In this situation `retrievability` becomes 1 (since `t = 0` in the formula `R(t,S) = (1 + \cfrac{t}{9 \cdot S})^{-1},)`
3. This leads to `(e^{w_{10}\cdot(1-R)}-1)`  factor becoming 0 in the `stability` formula and therefore the whole equation returning 0

So in this case, getting the answer right reduces the stability to 0, which does not seem right. My question is: *Is this because the implementation of the algorithm expects at least 1 day to have elapsed before review is allowed?* 

I can see that the `scheduled-days` property is a non-zero positive number, so that might be the expected answer. But I thought I'd check anyway.

**Comment by L-M-Sherlock** [comment]
The formula is:

$$S^\prime_r(D,S,R,G) = S\cdot(e^{w_8} \cdot (11-D) \cdot S^{-w_9} \cdot (e^{w_{10}\cdot(1-R)}-1) \cdot w_{15}(\textrm{if G = 2}) \cdot w_{16}(\textrm{if G = 4}) + 1).$$

When R = 1, $S^\prime_r(D,S,R,G) = S\cdot(0 + 1) = S$.

**Comment by vedang** [comment]
Thank you for the explanation. I missed the `+ 1` in my code. Sorry!
