### ISSUE TITLE
[Question] fsrs4anki-helper与fsrs4anki差别

### ISSUE THREAD

**Issue by xjqm-tao** [open-spaced-repetition/fsrs4anki#359]
你说过fsrs4anki-helper比fsrs4ank准确，我感觉确实这样。我对比了我忘记得厉害的卡，fsrs4ank计算的间隔比fsrs4anki-helper长一个月以上，这差距好大，感觉fsrs4ank的js脚本就像鸡肋一样。那么未来fsrs作为anki默认算法后是采用和fsrs4anki-helper一样的算法吗？

**Comment by L-M-Sherlock** [comment]
> 我对比了我忘记得厉害的卡，fsrs4ank计算的间隔比fsrs4anki-helper长一个月以上，这差距好大，感觉fsrs4ank的js脚本就像鸡肋一样。

FSRS4Anki-Helper 更准确，是在你的卡片已经用其他算法复习过很久的情况下。对于一开始就用 fsrs4anki.js 复习的卡片，两者是一样准确的。

**Comment by L-M-Sherlock** [comment]
fsrs4anki.js 不准确主要出在从旧卡片上计算稳定性的环节中。
