### ISSUE TITLE
[Hint] Similar project using Bayesian statistics

### ISSUE THREAD

**Issue by cryptocoinserver** [open-spaced-repetition/fsrs4anki#36]
This might be an interesting project to compare with? 
It's another algorithm based on Bayesian statistics.

[https://github.com/fasiha/ebisu-likelihood-analysis](https://github.com/fasiha/ebisu-likelihood-analysis)

[https://github.com/fasiha/ebisu](https://github.com/fasiha/ebisu)

**Comment by L-M-Sherlock** [comment]
Thanks for your recommendation!
