### ISSUE TITLE
[BUG] Optimizer generates empty revlog_history.tsv

### ISSUE THREAD

**Issue by ksuchodo** [open-spaced-repetition/fsrs4anki#370]
**Describe the bug**

Running *fsrs4anki_optimizer.ipynb* on either my *All.apkg* or *All.colpkg* file fails at step 2.1 with the error message *ValueError: Training data is inadequate*. In both cases, the *revlog.cvs* seems to be generated correctly but *revlog_history.cvs* is empty.

**To Reproduce**
1. Go to *fsrs4anki_optimizer.ipynb*
2. Import *All.apkg*
3. *Run all * under *Runtime*

**Screenshots**

<img width="1042" alt="Screenshot 2023-07-20 at 12 22 29" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/28412552/80654400-37ac-4f1f-910f-3830468ef2a9">

**Environment**
 - Anki version: 2.1.65
 - OS: iOS
 
[revlog.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/12104951/revlog.csv)

**Comment by L-M-Sherlock** [comment]
<img width="881" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/e7659a6e-cd3d-4e52-aca7-ae9cf012d85a">

I don't know why your revlogs don't include any reviews with type 0 (learn). FSRS filters out all reviews when the first learn review is missing.

**Comment by L-M-Sherlock** [comment]
Could you provide the colpkg file with me?

**Comment by ksuchodo** [comment]
Oh, I see. I think this is a quirk from an add-on I have been using to balance Anki by bypassing new cards completely and mixing them in as one-day reviews. Thank you very much!
