### ISSUE TITLE
[Question] Link redundancy?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#372]
**Question**

Now that version 4.2 is out, I see that there are 2 links to the files. Example:

https://github.com/open-spaced-repetition/fsrs4anki/blob/v4.2.0/fsrs4anki_scheduler.js
https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js

Wouldn't it be the case to remove one of them to avoid version "conflicts"?

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42243532/51d4e7c8-540a-484d-838c-18fae8c1e3cc)

**Comment by L-M-Sherlock** [comment]
The file in `main` will changes. The file in `v4.2.0` would never change.
