### ISSUE TITLE
[Feature Request] Apply tag specific scheduling parameters

### ISSUE THREAD

**Issue by patrickellis** [open-spaced-repetition/fsrs4anki#380]
Motivation
----------
> **Note**
> For cards within the same deck, it's currently impossible to apply different scheduling behaviours to them based on properties such as **tags** and **card type**. 

The ability to use tags as a target for scheduler parameters is desirable for finer-grained control of scheduler behaviour, without having to separate related cards into their own decks unnecessarily. 

Example
---------
In my case, I have some 'definition'-type and 'type-the-answer'-type cards within the same deck that I would like to see very often.
Many of those type-the-answer cards are programming syntax or one-liners that are important to have close to muscle memory, but regardless there are many reasons people would find themselves in similar situations. 

Solution
--------
Give FSRS users the option to add a `div` containing card tags (Using the built-in `{{Tags}}` field) that can be queried and matched against a novel `tagParameters` variable. 

**scheduler.js**
- [ ] Implement a `get_tags()` function that will query the DOM for a div with id / className "`FSRS-tags`" and fetch tags within as a list of strings.
- [ ] Match tags against elements in `tagParameters`, taking priority over `deckParameters`
- [ ] Edge case checks: If cards match multiple tags with FSRS parameters defined, ignore the parameters set for those tags.

**fsrs4anki-helper**
> Some refactoring is necessary here if we want to maintain correctness and keep behaviour consistent between the scheduler and the helper addon functions

  - [ ] Refactor calls to `mw.col.decks.all()` to instead call a `Mediator` class that queries cards in each deck and filters out those matching tags defined in [fsrs4anki_scheduler.js](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js). This class is responsible for managing interactions between cards and decks.
     - If we like, this class can also be responsible for creation and deletion of Cards and Decks - probably via an Abstract Factory so as not to bloat the code
- [ ] Abstract cards to their own datatype e.g. `FSRSCard` in order to associate **cards** with their own parameters. Those parameters should be inherited by **tags**, and **decks**, in that order of precedence. (Later, we can extend this to other sources if we wish, such as note types as mentioned in 'Motivation' above). Notice how in this model a Card and a Deck are starting to look very similar. Each has weights, scheduler options, etc. 

Following those final two steps, the implementations in each FSRS-helper utility will look far simpler. For instance, an FSRSCard object can implement `def reschedule(self) -> None:` and thanks to our pre-processing, all information for that reschedule is available as instance attributes. 

Rescheduler code might end up as something like this (ignoring the interruption check every X iterations for simplicity):
```Python
manager = FSRSManager(*args, **kwargs)
for card in manager.cards:
  card.reschedule()

Class FSRSCard(FSRSConfigurableItem):
  def __init__(self, *args, **kwargs) -> None:
    ...

  def reschedule(self, *args, **kwargs) -> None:
    ...

Class FSRSDeck(FSRSConfigurableItem):
  def __init__(self, *args, **kwargs) -> None:
    ...

Class FSRSConfigurableItem:
  mediator = Mediator()
  def __init__(self, *args, **kwargs) -> None:
    # Do things here common to both Cards and Decks

Class Mediator():
  def __init__(self, *args, **kwargs) -> None:
      ...

  def notify(sender: FSRSDeck | FSRSCard, event: str) -> None:
      ...
```

**Comment by L-M-Sherlock** [comment]
- #106

**Comment by cjdduarte** [comment]
I'm all for it, some people strictly classify their decks by tags and it opens up a lot of options.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42243532/d54821a5-4ba3-40ff-a979-fb80546eb0cc)

**Comment by L-M-Sherlock** [comment]
What if a card has several tags and each tag has its own parameters? Which parameters will be used to schedule the card?

**Comment by patrickellis** [comment]
Like this:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/74929696/4743d16d-5ff0-45ef-b9a0-e3f51fc63518)

**Comment by patrickellis** [comment]
You raise a good point, I don't think we should apply any parameters at all if the behaviour is unpredictable. 

I suggest that, in **scheduler.js**-land, we silently ignore cards that match more than one tag. 
In **FSRS helper**-land, we run a check in `__init__.py` to validate cards and trigger this warning if there's a conflict. 

Then document clearly that`tagParameters` is recommended to be used alongside the helper addon to avoid confusion.

Users are welcome to ignore the warning if they wish, they'll see it again the next time they boot up Anki which is a non-irritating way to remind people that there's an issue that needs their attention at some point.

**Comment by cjdduarte** [comment]
> You raise a good point, I don't think we should apply any parameters at all if the behaviour is unpredictable.
> 
> I suggest that, in **scheduler.js**-land, we silently ignore cards that match more than one tag - in this case we fall back to the matching deck parameters. In **FSRS helper**-land, we run a check in `__init__.py` to validate cards and trigger this warning if there's a conflict.
> 
> Then document clearly that`tagParameters` is recommended to be used alongside the helper addon to avoid confusion.
> 
> Users are welcome to ignore the warning if they wish, they'll see it again the next time they boot up Anki which is a non-irritating way to remind people that there's an issue that needs their attention at some point.

Excellent suggestion. Just a contribution.

Not everyone will use by tag. So I believe that the FSRS helper validation should only happen for the tags configured in scheduler.js
If the user does not use FSRS per tag or if the tags (I use more than 500 because I generate them automatically via a system) are not in scheduler.js they will be ignored in the analysis.

**Comment by patrickellis** [comment]
@L-M-Sherlock I forgot about this. I can still implement, but I see FSRS is in [beta in Anki itself](https://github.com/ankitects/anki/releases/tag/23.10beta4). What are the chances of this being able to be included into that codebase? Should I contribute over there instead? 

Also, is the FSRS helper due to remain a companion to FSRS after integration with Anki, or is it to be deprecated?
Thanks!

**Comment by L-M-Sherlock** [comment]
The built-in FSRS applies preset specific scheduling parameters. It's unlikely to support tag specific scheduling parameters, because it's a little complicate for average users.
