### ISSUE TITLE
[Question] What to do if I have forgotten a card that is not due yet?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#386]
Let's say that I am studying something (or reviewing some card), and I realize that I have forgotten a card, but the card is not due yet. What should I do in this case?

With time, I have realized that not doing anything in this case is not good. This is because of two reasons:
- Firstly, because I have told myself the correct answer, it is possible that when the card comes for review again, I may recall it. So, FSRS might think that I recalled the card after the whole interval but, in reality, I had forgotten the card in between and then relearnt it. This becomes even more important if the card has a long interval (say > 10 months) and I relearn it just a few days/weeks before it is due.
- Secondly, I don't get to review the card (which would help me to relearn it) until the card becomes due again.

I realize that this is a problem with flashcards in general and is not specific to FSRS. But finding a good answer to this issue is more important in FSRS because the optimizer might "learn" the incorrect results (success/failure rates), which would cause incorrect scheduling for all the cards.

You might think that this doesn't occur often. But, in my collection, it does occur very frequently. This is probably because my cards are very interlinked, which means that if I forget 1 fact, I may get 10 different cards wrong (which actually test different facts but are still related).

**Comment by L-M-Sherlock** [comment]
You can review the card in advance with filtered deck and rate it as `again`.

**Comment by nb9618** [comment]
There is an add-on which gives ability to grade a card from the card browser: [Learn now & Grade now](https://ankiweb.net/shared/info/1021636467). However I'm not sure if it is compatible with custom scheduling. Using it will probably require rescheduling with FSRS add-on.

**Comment by L-M-Sherlock** [comment]
> However I'm not sure if it is compatible with custom scheduling. Using it will probably require rescheduling with FSRS add-on.

I have tested it just now. It only uses the built-in algorithm without calling the custom scheduling code.

**Comment by user1823** [comment]
> You can review the card in advance with filtered deck and rate it as `again`.

This seems like a workable solution to me. I will leave this issue open for some time so that other people could share their ideas if they have some better solutions.

**Comment by user1823** [comment]
By the way, @L-M-Sherlock, how should I move just that particular card into a filtered deck?

**Comment by L-M-Sherlock** [comment]
> By the way, @L-M-Sherlock, how should I move just that particular card into a filtered deck?

You can put the cid:xxx in the filtered deck's query field.
