### ISSUE TITLE
[BUG] Error when using the optimizer

### ISSUE THREAD

**Issue by Zaldroc8** [open-spaced-repetition/fsrs4anki#391]
**Describe the bug**
When I use the optimizer, I encounter the error depicted in screenshot below. This is a recurring issue with different decks. This didn’t occur with the earlier versions of the optimizer (<v4.0). Any ideas what might be the issue? 

**Screenshots**
![chrome_8CwCuivukn](https://github.com/open-spaced-repetition/fsrs4anki/assets/107775308/8e07d662-6918-4a46-aebf-9cb829751f5d)

Settings within the optimizer
- timezone = 'Europe/Berlin'
- next_day_starts_at = 4
- revlog_start_date = "2006-10-05"
- filter_out_suspended_cards = False

**Environment**
 - Anki version: 2.1.64
 - OS: Windows 11
 - Optimizer version: v4.3.2

**Comment by L-M-Sherlock** [comment]
Could you share the affected deck file with me?

**Comment by Zaldroc8** [comment]
https://drive.google.com/file/d/1vNNgZ3dq4N-j6dELHjnLn0ad1rcRNt04/view?usp=sharing

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/179bf833-e158-4a2c-83ca-8fad8a014f4e)

I don't know why this card's rating is 0. Do you use any add-on that could induce this case?

**Comment by Zaldroc8** [comment]
Hm, I can’t think of one that might be responsible at the moment. Do you know whether this happened within the past few months as well? That might narrow down the possible cause. 
At first I thought about the manual rescheduling function or the former ReMemorize addon, however that should be shown within the „type“ column as „manual“.
