### ISSUE TITLE
[Question] ivl = -600

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#393]
`SELECT revlog.* 
FROM revlog
JOIN cards ON revlog.cid = cards.id
JOIN notes ON cards.nid = notes.id
WHERE revlog.ivl = -600`

I found out that some of my cards have ivl -600.
I'm analyzing if this occurs by FSR4-HELPER or another addon.
Is there any situation that the Helper does this?
And is the optimizer or FSR4 affected by this negative number?

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42243532/a1e98b42-eb3d-48c7-9f6b-728d474b2b35)

**Comment by L-M-Sherlock** [comment]
> I found out that some of my cards have ivl -600.

It means 600 seconds (10 min).

>     ivl             integer not null,
>       -- interval (used in SRS algorithm). Negative = seconds, positive = days

Source: https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#cards
