### ISSUE TITLE
Start testing V3 scheduler on AnkiDroid

### ISSUE THREAD

**Issue by MNastri** [open-spaced-repetition/fsrs4anki#395]
**Research**

*Enter an [x] character to confirm the points below:*

- [X] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [X] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [X] I have searched for similar existing questions here

**Question**

AnkiDroid can use the new backend and the V3 scheduler is available with it. Have you started doing any tests with this functionality?

**Comment by L-M-Sherlock** [comment]
I don't have Android device. You can track it here: https://github.com/ankidroid/Anki-Android/issues/12620

**Comment by user1823** [comment]
Let me clarify. The v3 scheduler is available in AnkiDroid since about a year (if you consider the alpha releases also). But, no version of AnkiDroid currently supports the custom scheduling feature of Anki. This means that FSRS can't work in AnkiDroid yet.

I think that the AnkiDroid team aims to implement most of the features from Anki (incl. custom scheduling) in v2.17.

**Comment by user1823** [comment]
@L-M-Sherlock, in the FAQ Q1, mention this:

> AnkiDroid currently supports the v3 scheduler, which can be enabled through an advanced setting. However, it doesn't support custom scheduling yet, which is required for FSRS to work. AnkiDroid is expected to support FSRS in v2.17.
>
> Till then, you can enable the "auto-reschedule after sync" option in the FSRS helper add-on. This way, when you sync your reviews from AnkiDroid to Desktop, they would be automatically rescheduled according to the FSRS algorithm. For best results, it is recommended to sync the reviews daily.
>
> However, if you only use AnkiDroid, you're out of luck.

Then, close this issue.

**Comment by L-M-Sherlock** [comment]
Done.
