### ISSUE TITLE
[Question] Test_rate_sequence está errado ou é minha configuração de reaprendizagem?

### ISSUE THREAD

**Issue by JeffersonCorreia32a** [open-spaced-repetition/fsrs4anki#404]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/138017463/32a74b35-bb45-4dcf-8188-ae12568fa6c5)

test_rating_sequence = "3,3,3,1,3,3,3,3,3,3"
requestRetention = 0.9  # recommended setting: 0.8 ~ 0.9

preview_sequence = optimizer.preview_sequence(test_rating_sequence, requestRetention)
print(preview_sequence)

rating history: 3,3,3,**1**,3,3,3,3,3,3
interval history: 0,7,25,82,**12**,32,82,197,449,980,2050
difficulty history: 0,4.8,4.8,4.8,6.7,6.7,6.7,6.7,6.7,6.7,6.7

Dear all,

As you can see in the image, I conducted a test in the optimizer where, after pressing button 3 three times, I would press button 1 once. In this test on Anki, whenever I press button 1, it goes back to 20 minutes, based on my relearning configuration with intervals set to 20 minutes and 1 day. Therefore, wouldn't it be appropriate to make an adjustment in this interval history? If, as in the example, clicking button 1 for the first time resulted in a 12-day interval, wouldn't that be incorrect due to the learning step? And wouldn't the entire subsequent sequence be wrong as a consequence?

Instead of the 12-day interval, it could have been indicated in the example as "RS," signifying a return to the relearning steps, and in the next step, report the interval determined by FSRS4.

In this case, I am considering that the user FSRS4 should have the option to set and choose their relearning steps. If the correct approach is to delete the relearning steps and leave them blank, then there would be no relearning steps used in conjunction with FSRS4, and the optimizer test would be correct. If I am wrong to use the relearning configuration I mentioned earlier with 20 minutes and 1 day, please let me know, as I haven't seen any information about it here. As previously stated, here are my relearning steps.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/138017463/1dbb9a3c-9b0d-4a00-ae0d-2c3c91e1ee41)

Please inform me of the appropriate relearning configuration to use with FSRS4.

**Comment by L-M-Sherlock** [comment]
> As you can see in the image, I ran a test in the optimizer where, after pressing button 3 three times, I would press button 1 once. In this test on Anki, whenever I press button 1, it goes back to 20 minutes, based on my relearning configuration with intervals set to 20 minutes and 1 day. Therefore, wouldn't it be appropriate to make an adjustment in this interval history? If, as in the example, clicking button 1 for the first time resulted in a 12-day interval, wouldn't that be incorrect due to the learning step? And wouldn't the entire subsequent sequence be wrong as a consequence?

The ratings in the relearning stage are ignored by the FSRS scheduler. The interval history only contains the long-term intervals.

**Comment by L-M-Sherlock** [comment]
The test rating sequence doesn't contain the ratings in relearning stage.

**Comment by L-M-Sherlock** [comment]
> Instead of the 12-day interval, it could have been indicated in the example as "RS," signifying a return to the relearning steps, and in the next step, report the interval determined by FSRS4.

Do you mean that the correct interval history should be "0,7,25,82,relearning steps,12,32,82,197,449,980,2050"?

Maybe the more correct version is "learning steps,7,25,82,relearning steps,12,32,82,197,449,980,2050". But the test rating sequence couldn't deal with ratings in (re)learning steps. Because it doesn't know anything about (re)learning steps.

**Comment by JeffersonCorreia32a** [comment]
> > Ao invés do intervalo de 12 dias, poderia ter sido indicado no exemplo como “RS”, significando um retorno às etapas de reaprendizagem e, na próxima etapa, relatar o intervalo determinado pelo FSRS4.
> 
> Você quer dizer que o histórico de intervalo correto deve ser "0,7,25,82,relearning steps,12,32,82,197,449,980,2050"?
> 
> Talvez a versão mais correta seja "etapas de aprendizado, 7,25,82, etapas de reaprendizado, 12,32,82,197,449,980,2050". Mas a sequência de classificação do teste não conseguiu lidar com as classificações nas etapas de (re)aprendizagem. Porque não sabe nada sobre passos de (re)aprendizagem.

Exato, acho que esse seria o correto

**Comment by L-M-Sherlock** [comment]
> Wouldn't there be some way to make the code run that way?

I think it doesn't exist. Because FSRS only consider the long-term memory.

**Comment by JeffersonCorreia32a** [comment]
> > Wouldn't there be some way to make the code run that way?
> 
> I think it doesn't exist. Because FSRS only considers the long-term memory.

The fact is that when we press button 1 the card goes back to relearning and pressing button 1 influences the stipulated deadlines. However, the new deadline outside the relearning stage will only be determined after exiting the relearning stage so I think there is no way to be different from what you mentioned before, learning stage and then on the exit depending on whether you press 3 or 4 to determine the new interval . That's how it should be, but if you have programming means to execute, then only you experts.
