### ISSUE TITLE
[BUG] Pressing "Again" throws cards into the future

### ISSUE THREAD

**Issue by WonderfulDeath** [open-spaced-repetition/fsrs4anki#406]
**Describe the bug**
When using certain parameters after pressing "Again" on a card it makes the time until the next review longer if you press "Good" on that card.

**To Reproduce**
1. Use these parameters [0.12, 0.35, 0.67, 3.87, 5.2909, 1.0745, 0.4474, 0.0029, 1.1521, 0.1635, 0.6593, 2.2137, 0.0184, 0.1958, 1.9556, 0.8888, 1.7788] and this retention rate .965 (I got these parameters from using my anki data in colab(except the retention rate))
2. Press "Again" on a card that has been gotten many "Good" reviews in the past.
3. Go to the card you pressed "Again" on and you can see now the "Good" option throws it much, much further into the future.
4. Keep in mind this only works after pressing "Again" once, subsequent "Again" inputs on the exact same card do not throw it further into the future, only the first "Again" and seeing it for the second time will show this.

**Expected behavior**
I expected "Again" to not keep throwing cards that i eventually press "Good" on further into the future considering i do my reviews quite quickly. (They even get thrown 97 years into the future when the latest i usually get is 1 year at most)

**Screenshots**
Before pressing "Again" ↓
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/141336555/a2e89545-0b88-4924-b7d7-c1f33ba7f098)
After pressing "Again" and seeing the card for the second time  ↓
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/141336555/ec16a83f-3f40-49b3-b73a-ce34f630b232)

Here is an even more drastic example.

Before pressing "Again" ↓
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/141336555/e35cf38a-6d37-4eb8-b706-332213f68fe1)
After pressing "Again" and seeing the card for the second time  ↓
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/141336555/466824b9-b2e7-4dfa-989b-fb183e1c2779)

**Environment**
 - Anki version: 2.1.65 Qt6
 - OS: Windows 10
 - Scheduler version: V3 scheduler
 - Optimizer version: v4.4.5
 - Simulator version: I didn't use a simulator for retention, i chose mine by trial and error (i think that's what this is asking?)

**Additional context**
Cards will get sent to 2048(and much, much further beyond) even though they shouldn't (i have no review cards outside of 2024).

The only way for me to mitigate this issue is for me to reschedule all cards every day and this has been happening every day (the reschedule all cards button, for some reason, refits all my cards back into a reasonable timeline like the card in this image from 2048 would be rescheduled to 2023 after rescheduling)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/141336555/aed183b6-0105-4207-b24e-2f8a8c359ef3)

**Comment by L-M-Sherlock** [comment]
<img width="1083" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/84282d8f-4c09-47d9-9d40-ab36883c26e0">

**Comment by WonderfulDeath** [comment]
> <img alt="image" width="1083" src="https://user-images.githubusercontent.com/32575846/258273901-84282d8f-4c09-47d9-9d40-ab36883c26e0.png">
> Here is the latest version: https://github.com/open-spaced-repetition/fsrs4anki/releases/latest

ah i see, my bad i didn't know, thanks for letting me know!
