### ISSUE TITLE
[Feature Request] Make graph in section 3 of the optimizer more useful

### ISSUE THREAD

**Issue by nb9618** [open-spaced-repetition/fsrs4anki#411]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
Currently, the result of finding optimal retention is the value of suggested retention and a graph which displays ten lines, each for every difficulty. Probably, the suggested retention alone is enough for many, if not most, users, however I think that the usefulness of this prediction can be improved. 

1. I think that it would be reasonable to suppose that some users will have a question: "My suggested target retention is X, but I'm not satisfied with that. I want my retention to be at least Y. How much extra effort would I need to put every day to achieve this?" The graph does not give answer to this, because each line represents only a fraction of user's collection, and that combined with the logarithmic scale makes it impossible to do visual analysis.
2. Previously, the terminal stability was fixed. This made possible to roughly compare estimated workload not only between different requested retention values, but also with different `w`. Now it is calculated dynamically, and this makes the expected time on the graph essentially abstract.

**Describe the solution you'd like**
1. Replace the ten lines (optionally, make them visible with `verbose=True` parameter) with a single one representing the total amount of reviews. This single line, if normalized to 1 at its minimum, should fit well on a linear scale graph, making it easy to estimate the amount of extra reviews compared to the recommended retention.
2. I don't know if this is possible, but ideally the results of analysis should be presented in terms of minutes or reviews _per day_ in the same manner as the add-on does for estimating burden.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by L-M-Sherlock** [comment]
> 1. I think that it would be reasonable to suppose that some users will have a question: "My suggested target retention is X, but I'm not satisfied with that. I want my retention to be at least Y. How much extra effort would I need to put every day to achieve this?"

For this case, I suggest using the simulator.

> 2. Now it is calculated dynamically, and this makes the expected time on the graph essentially abstract.

Because I find that the optimization of suggested retention could stick in endless loop if the user's memory is poor.

**Comment by brubsby** [comment]
> If it is so, I suggest removing that section from the optimizer.

Strong disagree, I think it is very useful to have in the HF optimizer, as it is much quicker and more user friendly than running the simulator completely for every deck one has.

**Comment by L-M-Sherlock** [comment]
Due to the complete refactor of finding optimal retention module, this issue has been out of date.
