### ISSUE TITLE
Massive good interval which is greater than easy when switching from v3 to v4 [Question]

### ISSUE THREAD

**Issue by oberblastmeister** [open-spaced-repetition/fsrs4anki#412]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

fsrs v3 generated
```
[1.1781, 1.1786, 4.9467, -0.4481, -0.4483, 0.2526, 1.4533, -0.15, 0.8533, 2.0533, -0.1467, 0.2533, 1.0501]
```
which causes these intervals:
```
1:again, 2:hard, 3:good, 4:easy

first rating: 1
rating history: 1,3,3,3,3,3,3,3,3,3,3
interval history: 0d,1d,3d,9d,23d,1.8m,4.0m,8.4m,1.4y,2.6y,4.7y
difficulty history: 0,5.8,5.6,5.4,5.3,5.2,5.2,5.1,5.1,5.0,5.0

first rating: 2
rating history: 2,3,3,3,3,3,3,3,3,3,3
interval history: 0d,2d,6d,16d,1.3m,3.1m,6.6m,1.1y,2.1y,3.9y,6.9y
difficulty history: 0,5.4,5.3,5.2,5.1,5.1,5.1,5.0,5.0,5.0,5.0

first rating: 3
rating history: 3,3,3,3,3,3,3,3,3,3,3
interval history: 0d,4d,11d,29d,2.3m,5.1m,10.7m,1.7y,3.2y,5.8y,10.1y
difficulty history: 0,4.9,4.9,4.9,4.9,4.9,4.9,4.9,4.9,4.9,4.9

first rating: 4
rating history: 4,3,3,3,3,3,3,3,3,3,3
interval history: 0d,5d,14d,1.2m,2.9m,6.5m,1.1y,2.1y,4.0y,7.1y,12.1y
difficulty history: 0,4.5,4.6,4.7,4.8,4.8,4.8,4.9,4.9,4.9,4.9
```

fsrs v4 generated
```
[1.08, 1.29, 19.58, 7.55, 4.8115, 0.8299, 0.7467, 0.1227, 1.6092, 0.1, 1.0587, 2.2983, 0.01, 0.4577, 1.3779, 0.4094, 2.7288]
```

```
1:again, 2:hard, 3:good, 4:easy

first rating: 1
rating history: 1,3,3,3,3,3,3,3,3,3,3
interval history: 0d,1d,4d,13d,1.4m,4.2m,11.9m,2.6y,6.7y,16.3y,38.0y
difficulty history: 0,6.5,6.3,6.1,5.9,5.8,5.7,5.6,5.5,5.4,5.3

first rating: 2
rating history: 2,3,3,3,3,3,3,3,3,3,3
interval history: 0d,1d,4d,15d,1.7m,5.3m,1.3y,3.5y,9.2y,22.7y,53.1y
difficulty history: 0,5.6,5.5,5.5,5.4,5.3,5.2,5.2,5.1,5.1,5.1

first rating: 3
rating history: 3,3,3,3,3,3,3,3,3,3,3
interval history: 0d,20d,2.4m,7.7m,1.9y,5.3y,13.9y,34.4y,80.7y,100.0y,100.0y
difficulty history: 0,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8

first rating: 4
rating history: 4,3,3,3,3,3,3,3,3,3,3
interval history: 0d,8d,1.1m,4.0m,1.1y,3.4y,9.5y,24.9y,61.3y,100.0y,100.0y
difficulty history: 0,4.0,4.1,4.2,4.3,4.3,4.4,4.4,4.5,4.5,4.6
```

This gives a massive interval of 20 days for a 3 rating which is even larger than the 4 rating! I am confused as to why this happens.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/5903cdf0-e8d5-4ea2-9690-e036bbec66bd)

Could you set this to True, try to optimize it again and provide the forgetting curves with me?

**Comment by L-M-Sherlock** [comment]
Or you can try v4.5.1, which may solve your problem: https://github.com/open-spaced-repetition/fsrs4anki/releases/tag/v4.5.1

**Comment by user1823** [comment]
> ![image](https://user-images.githubusercontent.com/32575846/258966383-5903cdf0-e8d5-4ea2-9690-e036bbec66bd.png)
> 
> Could you set this to True, try to optimize it again and provide the forgetting curves with me?

Instead of asking for this, I think that you should ask the user to share the `stability_for_pretrain.tsv` file from the left panel on Colab because this file contains more details than the graphs.

**Comment by L-M-Sherlock** [comment]
Fixed by https://github.com/open-spaced-repetition/fsrs-optimizer/pull/17
