### ISSUE TITLE
[Question] Regarding optimization and reverting to default

### ISSUE THREAD

**Issue by BEST8OY** [open-spaced-repetition/fsrs4anki#415]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Let's say I don't have a review log:

Can I use default parameters and accumulate a log over time and then use the optimizer and then reschedule based on new parameters? Is this the way it should be done for someone who has no backlog?

Now let's say I don't want to use FSRS after several months and I want to revert back to default algorithm:

In FAQ it's mentioned that I can do this but I'm not sure about the procedure.
1- First I empty the "Custom scheduling" section.
2- Now I’m puzzled, because, in the past several months, FSRS had scheduled my cards and had given their interval based on the algorithm; how can I reschedule cards based on the default algorithm? Is it even possible? I want to know what happens for studied cards when I stop using FSRS.

One more question about Optimizer

What's the impact of spent time on cards on the parameters? does it have a grand effect or it's not that much?
Because if it has a grand effect, it would be nice to have this feature in Anki.
https://forums.ankiweb.net/t/stop-timer-after-showing-answer/29937

**Comment by L-M-Sherlock** [comment]
The default algorithm will schedule your cards based on the interval scheduled by FSRS before.

**Comment by trooms** [comment]
I don't believe the first question, "Can I use default parameters and accumulate a log over time and then use the optimizer and then reschedule based on new parameters? Is this the way it should be done for someone who has no backlog?" was answered. 

Has any research been done / is there any information you can provide when it comes to how often you should run the optimizer?

**Comment by L-M-Sherlock** [comment]
I recommend running the optimizer once a month.

**Comment by trooms** [comment]
> I recommend running the optimizer once a month.

Is there any basis for this?

**Comment by L-M-Sherlock** [comment]
No. I just don't want the user waste too much time on optimization.
