### ISSUE TITLE
Optimizer error [BUG]

### ISSUE THREAD

**Issue by puckdoc** [open-spaced-repetition/fsrs4anki#417]
**Describe the bug**
Everything from section 2.1 and beyond does not work

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1081" alt="Screenshot 2023-08-09 at 1 36 17 PM" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/141874235/ba3b27c0-7057-452a-a064-8f482f40f6e8">

**Environment**
 - Anki version: [e.g. 2.1.64]
 - Scheduler version: [e.g. v]
 - Optimizer version: [e.g. v4.5.1]
 - Simulator version: [e.g. v1.1.0]

**Additional context**

**Comment by L-M-Sherlock** [comment]
Could you share the affected deck/collection with me? It seems to be caused by a lack of data.

**Comment by puckdoc** [comment]
Yes. I saw that and thought it was odd because I've been using the deck for consistently for 150 days now

https://drive.google.com/file/d/1deGuIzQ2KSlvWHmbAdymAwH33Efu76O-/view?usp=drive_link

**Comment by L-M-Sherlock** [comment]
I submit the access request. Do you receive it?

**Comment by puckdoc** [comment]
I didn't get anything but I just changed it to give access to everyone. Sorry about that

**Comment by L-M-Sherlock** [comment]
OK. I downloaded. Could you give me the info about timezone and next day start?

**Comment by L-M-Sherlock** [comment]
Oh, I think v4.5.2 has solved your problem. You can find it here: https://github.com/open-spaced-repetition/fsrs4anki/blob/v4.5.2/fsrs4anki_optimizer.ipynb

**Comment by puckdoc** [comment]
It still didn't work for me. Everything up to 2.1 works. EST, 4

**Comment by puckdoc** [comment]
It worked. Thank you
