### ISSUE TITLE
[BUG] Invalid argument when extracting .apkg file

### ISSUE THREAD

**Issue by yaoberh** [open-spaced-repetition/fsrs4anki#42]
**Describe the bug**
Error appears when extracting the apkg file. Doesn't happen when the **support older anki versions** export button is **checked**.

```
OSError                                   Traceback (most recent call last)

[<ipython-input-12-f1fb03115c22>](https://localhost:8080/#) in <module>
      2 # Extract the collection file or deck file to get the .anki21 database.
      3 with zipfile.ZipFile(f'./{filename}', 'r') as zip_ref:
----> 4     zip_ref.extractall('./')
      5     print("Extract successfully!")

3 frames

[/usr/lib/python3.7/zipfile.py](https://localhost:8080/#) in read(self, n)
    751                         "is an open writing handle on it. "
    752                         "Close the writing handle before trying to read.")
--> 753             self._file.seek(self._pos)
    754             data = self._file.read(n)
    755             self._pos = self._file.tell()

OSError: [Errno 22] Invalid argument
```

**To Reproduce**
1. Upload apkg file
2. Click on Runtime -> Run all
3. Extraction fails

**Expected behavior**

**Screenshots**

**Environment**
 - Anki version: [2.1.55]
 - OS: [Arch Linux]
 - Scheduler version: [v3]
 - Optimizer version: [v1.0.3]
 - Simulator version: [v1.1.0]

**Comment by L-M-Sherlock** [comment]
> Doesn't happen when the **support older anki versions** export button is **checked**.

It was caused by Anki. I have added this hint in the new version. You can use v2.0.3

**Comment by yaoberh** [comment]
Is it normal for it to show an reset these two values to 1 each time I try to modify them? My deck works correctly and my daily new cards are 50 as intended. I just can't change these values. Should I rerun the script each time I want to change this?
![image](https://user-images.githubusercontent.com/30667087/193058948-4b0b14b0-5f23-400d-bcf9-a8411e8e4346.png)

**Comment by L-M-Sherlock** [comment]
> Is it normal for it to show an reset these two values to 1 each time I try to modify them? My deck works correctly and my daily new cards are 50 as intended. I just can't change these values. Should I rerun the script each time I want to change this? ![image](https://user-images.githubusercontent.com/30667087/193058948-4b0b14b0-5f23-400d-bcf9-a8411e8e4346.png)

It is no caused by FSRS. Maybe you need to feedback in Anki 2.1.55 beta.

**Comment by yaoberh** [comment]
Thanks! Yes, seems to be a problem with the new beta :)
