### ISSUE TITLE
[Other] let's try to figure out the relationship between RMSE/MAE/other metrics and reviews per day

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#421]
Let's be honest, users don't care much about sophisticated metrics such as R-squared, RMSE, or MAE. What users do care about is how many reviews per day day they have to do.
Right now, the relationship between these two things is very elusive. The purpose of this issue is to invite people to share their ideas on how to figure this relationship out using formulas, simulations, or anything else.
The goal is to find some way to estimate how much an improvement in RMSE or some other metric will affect the workload aka the number of reviews per day.
If anyone has any ideas - share them here.

**Comment by Expertium** [comment]
So I came up with an idea how to relate average retention to reviews per day. It's not quite the same as relating accuracy to reviews/day though.
1) Take a user's collection, write down their average retention from True Retention add-on and their burden from FSRS stats.
2) Find the optimal parameters for that user
3) Reschedule all of their cards, with requested retention being exactly equal to their average retention in Anki
4) Write down the new burden
This will give us something like this:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/05a3ead9-74c9-40cc-a978-ac6e48733769)
The problem is that there is no way to automate it, and doing it manually would be extremely tedious.
@L-M-Sherlock @user1823 do you have any ideas?

**Comment by Expertium** [comment]
One more thing worth thinking about: currently "burden" decreases monotonically as you increase requested R. However, in reality there should be a minimum (if you plot burden as a function of requested R) because for very low R the user will press "Again" most of the time, which will lead to the intervals shortening rather than increasing most of the time. Burden doesn't account for that. Ideally, we need a new metric, like an improved burden.

**Comment by user1823** [comment]
> Ideally, we need a new metric, like an improved burden, that takes into account both factors:

This would probably require complex calculations. Also, it would likely be solved when the FSRS simulator is built into the helper  add-on. I suggested this to Sherlock here: https://github.com/open-spaced-repetition/fsrs4anki/issues/316#issuecomment-1605857344

**Comment by Expertium** [comment]
Not exactly the right issue for this, but I think it's worth mentioning how "mature" is defined.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/813de096-ae18-428e-8688-8fb0f99d26ee)

**Comment by L-M-Sherlock** [comment]
I think the relationship between RMSE/MAE/other metrics and reviews per day is uncertain. Even if the RMSE(bins) is zero, it is still possible that the number of reviews per day is not minimum.

**Comment by Expertium** [comment]
I think there might be a way to do this: https://github.com/open-spaced-repetition/fsrs4anki/issues/421#issuecomment-1675811971
We would need to test different versions of FSRS this way though, to see whether Burden converges to some value as RMSE decreases. Something like this:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/2c97b7d2-f7f6-4a76-a687-5105027eea04)

**Comment by L-M-Sherlock** [comment]
It would not works. Because the Burden depends on the retention. But RMSE doesn't relate the retention directly.

**Comment by Expertium** [comment]
Retention would be kept exactly the same each time, only the parameters and potentially the formulas would change.

**Comment by L-M-Sherlock** [comment]
> Retention would be kept exactly the same each time

It's impossible, because the user will deviate from the desired retention when the model is inaccurate (i.e., the RMSE is high).

**Comment by Expertium** [comment]
I meant desired retention. Just keep desired retention the same, reschedule all cards, record the value of Burden, repeat with the next version.
