### ISSUE TITLE
[Feature Request] do not ask for timezone, day start time multiple times

### ISSUE THREAD

**Issue by ilya-rusyanov** [open-spaced-repetition/fsrs4anki#423]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
When doing bulk optimization locally, e.g. `python -m fsrs_optimizer ./*.apkg` user is asked same questions (timezone, day start time, ignore suspended cards, generate graphs or not) for each deck file that is processed. When one has rather slow computer, user has to check it regularly if the optimizer has finished another deck and answer same questions he did before.

**Describe the solution you'd like**
Questions could be asked just one time after starting the optimizer and not for each deck.

**Describe alternatives you've considered**
User could have automated the process with some sort of script wrapper that would input the data automatically, but that requires quite some time to implement.

**Additional context**

![изображение](https://github.com/open-spaced-repetition/fsrs4anki/assets/1244545/cf15af77-9eab-4ede-bb01-e86460076d96)

**Comment by L-M-Sherlock** [comment]
Once you set the timezone, day start time, they are saved to a local file. You can run `python -m fsrs_optimizer ./*.apkg -y` to use the saved default values. Asking multiple times in the first time is necessary for me to run optimizer in a large dataset including many collections from different users in global.
