### ISSUE TITLE
[Question] What timezone should I use for the optimizer

### ISSUE THREAD

**Issue by jackbodine** [open-spaced-repetition/fsrs4anki#429]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I travel a lot since I am from the Chicago and study in Denmark, two very different time zones. Its probably a 50/50 of where most of my reviews have been done, but really impossible to tell.

Does the optimizer just need the time zone that of the machine when the deck is exported, or the time zone that the reviews have been compeleted in. Will it assume wrong dates for all the reviews i've done in Chicago if I set Copenhagen as my time zone?

**Comment by L-M-Sherlock** [comment]
Oh, it's a tricky problem. FSRS asks timezone and next_day_start to separate reviews by sleep. If you travel and do your reviews around the world, your sleep time will be very irregular.

**Comment by jackbodine** [comment]
Yeah thats what I was concerned about. Maybe the best thing to do is set revlog_start_date to when I've most recently changed timezones? How big would the impact be if I'm only using a couple months of reviews for training, when I've been using anki for years?

**Comment by L-M-Sherlock** [comment]
I haven't encountered this case. So I don't know how big the impact could be.

**Comment by Expertium** [comment]
> How big would the impact be if I'm only using a couple months of reviews for training, when I've been using anki for years?

Very big.

**Comment by nb9618** [comment]
Other day I was thinking that it might be worth to keep review intervals as floats, as opposed to calculating the day boundary and rounding them to days. Apart from helping those who travel a lot, it will remove necessity to enter timezone and day start, which is annoying an error prone, and also, it might improve accuracy for short interval reviews. Common sense suggests that if I learned a new card in evening and then reviewed it next day morning, I'll have better chance of remembering it if I was to learn it in morning and review it next day evening, however to the optimizer these two intervals are the same. I think this is also related to the spike on the stability to retention graph, which is at around 0.2 in my case. Despite this, I don't know if this change will bring any practical improvement.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/137687989/db3eb37e-2c24-4e9f-b706-b2fe8c89b354)

**Comment by L-M-Sherlock** [comment]
> keep review intervals as floats

You need to ask dae for this feature. In Anki, the interval is stored as integer.

**Comment by nb9618** [comment]
No, I mean `delta_t` and `t_history`. 
This obviously won't affect the scheduling as it is impossible to schedule a card at a specific time of a day, but it might improve accuracy of `w` and, if implemented in the add-on, accuracy of cards' memory states.

**Comment by L-M-Sherlock** [comment]
OK. I recommend opening an new issue for that feature.

**Comment by L-M-Sherlock** [comment]
This issue is outdated for the built-in FSRS.
