### ISSUE TITLE
[BUG] incompatibility with add-on Straight Reward

### ISSUE THREAD

**Issue by cocowash** [open-spaced-repetition/fsrs4anki#43]
**Describe the bug**
Straight Reward addon seems to crash instead of changing ease 

**To Reproduce**
1) install add-on
2) configure it to give certain ease after answering the same card X times. 
3). See error

**Expected behavior**
Add-on should not crash

debug
```
Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 553, in handler
File "aqt.reviewer", line 532, in _onAnswerButton
File "decorator", line 232, in fun
File "anki.hooks", line 89, in decorator_wrapper
File "anki.hooks", line 84, in repl
File "aqt.reviewer", line 431, in _answerCard
File "aqt.hooks_gen", line 3807, in __call__
File "[…]\AppData\Roaming\Anki2\addons21\957961234\src\lib\review_hook.py", line 101, in <lambda>
lambda ease_tuple, reviewer, card: on_will_answer_card(
File "[…]AppData\Roaming\Anki2\addons21\957961234\src\lib\review_hook.py", line 85, in on_will_answer_card
check_straight_reward(gains, reviewer, card, ease_tuple[1])
File "[…] \AppData\Roaming\Anki2\addons21\957961234\src\lib\review_hook.py", line 64, in check_straight_reward
next_states = reviewer.get_next_states()
AttributeError: 'Reviewer' object has no attribute 'get_next_states'
```

**Environment**
 - Anki version: [e.g. 2.1.55]
 - OS: [Windows 11]
 - Scheduler version: [v2.0.3]
 - Optimizer version: [v2.0.3]

**Comment by kuroahna** [comment]
@cocowash  I don't think this a bug with fsrs4anki. This is a bug for Straight Rewards addon. You should raise a bug on their [GitHub](https://github.com/hgiesel/anki_straight_reward). 

In Anki `2.1.54`, the [`reviewer.get_next_states()`](https://github.com/ankitects/anki/blob/2.1.54/qt/aqt/reviewer.py#L259) method exists, but in [2.1.55 beta 1](https://github.com/ankitects/anki/blob/5bf031f1e33c51034c31cec359ae62e621e115a6/qt/aqt/reviewer.py), this method no longer exists.

In other words, Straight Rewards addon is incompatible with Anki 2.1.55, and hgiesel will need to update his addon for it to work again.

Although, if you're using fsrs4anki, you shouldn't worry about ease anymore as that is no longer used in its scheduling algorithm. It is only used for [converting an existing card to fsrs memory states](https://github.com/open-spaced-repetition/fsrs4anki/blob/5e318bd2e6824041928a89aa00b1a3c76d311a7a/fsrs4anki_scheduler.js#L149). You can safely disable straight rewards addon and use fsrs4anki without any issue.

**Comment by cocowash** [comment]
@kuroahna, ty for the time for explaining why straight reward broke, since 2.1.55 still in beta I just going to deactivate the addon. Also, my reasoning behind leaving it on before this report was just for safety if one day I just decided to stop using fsrs4anki. Maybe it's just too soon to be concerned about it. 
I'm closing the thread.
