### ISSUE TITLE
[Feature Request] Make "fuzz" a little smarter

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#430]
**Which module is related to your feature request?**
Scheduler

**Describe the solution you'd like**
Currently fuzz just adds a random number to the interval. However, there is a better way of doing this. Look ahead n days, choose the day with the lowest number of due cards, and schedule the card that has been just reviewed to appear on that day.
Sherlock, if you remember our conversation about "Dilute", this is conceptually similar. The idea is that scheduling the review to happen on the day with the lowest workload should make the workload more consistent than just adding a random number to the interval.

**Comment by L-M-Sherlock** [comment]
The scheduler doesn't have the access to these information. So it's impossible in technology. The custom scheduling framework only pass the information of the current card to FSRS scheduler. So it's impossible to implement load balance in the scheduler.

**Comment by Expertium** [comment]
Ah, that's unfortuante.
