### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FEI352** [open-spaced-repetition/fsrs4anki#431]
**Describe the bug**
[FSRS4Anki 使用指北 - 知乎 (zhihu.com)](https://zhuanlan.zhihu.com/p/636564830)这个教程的调度器，是3.20版本，但是优化器却是最新的版本。你releases 说过V3和V4的的数据是不兼容的，但是在中文教程中并没有指出这一点，跟着教程走很容易犯错，得出一个错误的结果。

**Expected behavior**
希望希望能够更新中文教程。

**Comment by L-M-Sherlock** [comment]
已经更新中文教程中的代码。
