### ISSUE TITLE
[Feature Request] README/Docs: advice on how to choose an answer grade

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki#432]
> Ideally, the user shouldn't rate the card based on the displayed interval. But we can't prevent the user doing that.

I have definitely done this myself, especially when I had an exam deadline, but also when the initial easy interval was longer than I liked it. Also, there was a time when I used [the pass/fail two-button system](https://ankiweb.net/shared/info/876946123).

This reminds me that Anki has, in fact, a setting to turn on/off the next intervals display (default: on).

Perhaps it should be mentioned in the Wiki/FAQ:

<details>
<summary>Draft</summary>

# Grading your answer

The grade should be chosen based only on how easy it was to answer the card, not how long you want to wait until you see it again.

For example, if you habitually avoid the easy button because it shows long intervals, you can end up in a negative cycle: You'd be making the "easy" situations even rarer and easy grade's intervals longer and longer.

This means you should ignore the intervals shown above the answer buttons and instead focus on how well you recall the information. To help you, you can hide the intervals in the Anki preferences:

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/52420923/438754bb-d3df-46cd-85cb-b0d56084d9df)

If you still want to see a deck sooner rather than later, for example because you have an exam coming up, you can use the _Advance_ function of the Helper add-on. _Advance_ is the preferable method because it doesn't skew the grading history of the cards.

</details>

_Originally posted by @galantra in https://github.com/open-spaced-repetition/fsrs-optimizer/issues/23#issuecomment-1680325727_

**Comment by L-M-Sherlock** [comment]
Should we add a new page of wiki for this doc or add a new FAQ? @Expertium and @user1823, what do you think of this issue?

**Comment by user1823** [comment]
Making a new Wiki page seems to be an overkill. I suggest adding a new FAQ.

**Comment by Expertium** [comment]
> Making a new Wiki page seems to be an overkill. I suggest adding a new FAQ.
I agree. 
Here's how (IMO) users should grade themselves:

Easy - you answered correctly with no hesitation.
Good - you answered correctly with a little bit of hesitation.
Hard - your answer was only partially correct, and/or you hesitated a lot.
Again - your answer was completely incorrect.

Unrelated, but @user1823, do you mind helping with editing this? https://github.com/open-spaced-repetition/fsrs4anki/issues/472

**Comment by cjdduarte** [comment]
> > Here's how (IMO) users should grade themselves:
> > Easy - you answered correctly with no hesitation.
> > Good - you answered correctly with a little bit of hesitation.
> > Hard - your answer was only partially correct, and/or you hesitated a lot.
> > Again - your answer was completely incorrect.
> 
> This is something where preferences vary. Many people (including me) mostly use the Again and Good buttons because choosing between the 4 buttons can be difficult in many situations. It is not that I never use the Hard and Easy buttons. But, this happens very rarely.
> 
> > Unrelated, but @user1823, do you mind helping with editing this? #472
> 
> I will have a look when I have sufficient time.

It's my case. I simplified the process;

Again: I don’t know
Good: I got it right

**Comment by Expertium** [comment]
I mean, that works, but 4 grades allow you to grade yourself more precisely and convey more information to FSRS, which, in turn, allows FSRS to calculate optimal intervals more accurately.

**Comment by user1823** [comment]
> I mean, that works, but 4 grades allow you to grade yourself more precisely and convey more information to FSRS, which, in turn, allows FSRS to calculate optimal intervals more accurately.

Though it seems to be logically correct, the data seems to say something else.

I mostly use Good and Again and still the RMSE for my collection (1.2%) is among the lowest.

**Comment by Expertium** [comment]
> I mostly use Good and Again and still the RMSE for my collection (1.2%) is among the lowest RMSEs.

RMSE varies a lot from one user to another, so we would need to analyze lots of colelctions to determien whether RMSE is correlated with only using 2 buttons.

> You will say that a statistical significance test must be conducted to confirm this claim; I agree.

Lol, good prediction.
Also, @L-M-Sherlock, I just realized that if the user only uses 2 buttons, he won't be able to utilize the full range of values of D, 1-10 or 0-1 in the beta. Right now the only way to achieve the lowest value of D is by using "Easy", this is a bit of a problem for those who don't use "Easy".

**Comment by L-M-Sherlock** [comment]
> I just realized that if the user only uses 2 buttons, he won't be able to utilize the full range of values of D, 1-10 or 0-1 in the beta. Right now the only way to achieve the lowest value of D is by using "Easy", this is a bit of a problem for those who don't use "Easy".

But we don't know how it is beneficial to utilize the full range of values of D. And the difficulty is a relative value instead of an absolute value.

**Comment by L-M-Sherlock** [comment]
Added in 11th [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ).
