### ISSUE TITLE
How to better prepare for upcoming exams

### ISSUE THREAD

**Issue by archive-r** [open-spaced-repetition/fsrs4anki#434]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question 

- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused 

- [x] I have searched for similar existing questions here

**Question**

Hi,
Could I set a specific deadline (a date) and drive retention up to that deadline?
I have a very important exam coming up in about 30 days, and I don't mind forgetting everything I've learned once it's over.
Is there anything I can set in FSRS for such a case?
I'm not sure if increasing the requestedRetention will help, sorry for the stupid question, but I really need it.

**Comment by L-M-Sherlock** [comment]
You can use the helper add-on: https://ankiweb.net/shared/info/759844606

It allows you to review cards in advance:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/d2f8d972-b4ad-408a-baa4-0fdecb1938ff)

**Comment by archive-r** [comment]
Thank you, I think this will help me a lot
