### ISSUE TITLE
[Question] Still confused regarding how the scheduler handles "(re)learning" cards

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#435]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
FAQ says "Due to technical limitations, the FSRS scheduler doesn't know about the reviews that occur in the learning steps". But the optimizer does use data from when the card was in the "learning" stage. This means that the data that the optimizer is using and the data that the scheduler will be using are different, which, in turn, means that the "optimal" parameters aren't actually optimal. Am I missing something?

**Comment by nb9618** [comment]
As far as I understand, while the scheduler itself won't consider learning steps, the helper add-on will, so rescheduling manually from time to time will correct memory states for such cards.

**Comment by Expertium** [comment]
That would be a major problem, since that would mean that if users don't regularly reschedule all cards, the error (the difference between how the scheduler schedules cards and how they are actually supposed to be scheduled) will accumulate.

**Comment by L-M-Sherlock** [comment]
If the user doesn't have learning steps longer than one day, the error doesn't exist.

**Comment by Expertium** [comment]
Ok, so suppose the repetition history looks like this:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/5f9e0940-2772-4360-99f6-6609e34223af)
Will the scheduler see 1 review or 2 reviews?

**Comment by L-M-Sherlock** [comment]
> Will the scheduler see 1 review or 2 reviews?

2 reviews. Scheduler can see the first review in the learning stage.

**Comment by Expertium** [comment]
Ah, ok. I'll close this issue, but I may leave more comments here in the future, if I get confused again.

**Comment by extr15** [comment]
Hi @L-M-Sherlock , Is there any future plan to support the `(re)learning phase more than 1 day` on both FSRS and Anki sides?
Even if you have a maximum learning step which is less than 1 day, say `6h`, you may start to learn some cards in the middle night and finish the learning phase the next day morning. For these cards, their learning phase is more than 1 day.

**Comment by L-M-Sherlock** [comment]
> Is there any future plan to support the `(re)learning phase more than 1 day` on both FSRS and Anki sides?

The helper has supported it. Please use the feature named `auto reschedule after review`.

**Comment by Expertium** [comment]
@extr15 it's worth mentioning that enabling this feature and using longer learning steps will lead to a different issue - the intervals displayed above the answer buttons won't be equal to real intervals anymore. Unfortunately, right now there is no way to have displayed intervals match actual intervals *and* use learning steps longer than 1d.

**Comment by extr15** [comment]
Thanks for your reply. It is a little sad to know that. Sometimes I may choose `hard` or `good` according to the predicted intervals.
It seems Anki or FSRS are focusing on the long time memorization and the way Anki handles learning cards with multiple days is a little tricky.
Anyway, it's good enough now, and many thanks for all your work!
