### ISSUE TITLE
[Feature Request] A tool to compare the FSRS parameters

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#436]
Whenever the user re-generates the parameters using the optimizer, he might think how the new parameters differ from the previous ones. To answer this query, it might be reasonable to develop a tool to compare the two series of the parameters.

The [previewer](https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_previewer) developed by you recently is a useful tool. It can be made even more useful by adding the above requested feature.

I implemented a very crude version of this feature in Excel. Do check it out: [Compare FSRS w.xlsx](https://github.com/open-spaced-repetition/fsrs4anki/files/12385807/Compare.FSRS.w.xlsx)

**Comment by L-M-Sherlock** [comment]
There are so many formulas in that Excel. I guess most users don't understand that complicated panel.
