### ISSUE TITLE
[Question] Does "Disperse siblings" change the interval or the value of S?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#439]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
When a sibling gets dispersed, does it affect the interval without affecting S? If that's so, then I think it should be changed. I believe that seeing a sibling increases the stability of all related cards, hence the value of S must be changed, not just the interval length.

**Comment by L-M-Sherlock** [comment]
It's pretty hard to quantity the effect of seeing a sibling on other related cards.

**Comment by Expertium** [comment]
I know, but I still think that changing S makes more sense than only changing the interval.

**Comment by Expertium** [comment]
Now that I think about it, it would make rescheduling really complicated because the add-on would have to go not just through the card's own history but through the histories of all of its siblings too.

**Comment by filipenanclarez** [comment]
My data have 6 cards for each word ... I've already share with @L-M-Sherlock 

I think this decks is useful to help this. This improvement is much relevant for languages learners ...

Also this data have many post-due study history.

My cards, in the front side, have:

1 - Word in target language
2 - Audio in target language
3 - Word in native language
4 - Sentence with this word in target language
5 - Audio of sentence in target language
6 - Sentence in native language

This is the reason behind https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/232 to know retention by notes.

Maybe, the relationship between itens is the key for https://github.com/open-spaced-repetition/fsrs4anki/issues/352

The relationship between itens can affect D or make a new component of memory: The Quality of Item

The Quality of item can be 'how many connections this item have in the memory'. We know if the information have context, this is more easy to remember. This is why we need create a good flashcards with images, sounds etc.

Just an "out of the box" idea to help

**Comment by Expertium** [comment]
> The Quality of item can be 'how many connections this item have in the memory'.

How would we quantify it though? I can't think of any way to put a number on it.

**Comment by filipenanclarez** [comment]
> > The Quality of item can be 'how many connections this item have in the memory'.
> 
> How would we quantify it though? I can't think of any way to put a number on it.

Every time you answer a sibling, you is saying to system, the relationship between them. This is connections measure. The R or S or D between them maybe a new variable in this equation.

**Comment by Expertium** [comment]
Well, maybe in the future we'll try to take siblings into account when calculating S.

**Comment by Expertium** [comment]
@L-M-Sherlock if you don't plan to include a new variable and/or parameter to account for the effect of reviewing a sibling, you can close this issue. I assume taking that into account would require completely changing the optimizer, since it will have to go not only through the history of the card itself (liek right now) but also through the history of all of its siblings in order to calculate DSR values.

**Comment by filipenanclarez** [comment]
> @L-M-Sherlock if you don't plan to include a new variable and/or parameter to account for the effect of reviewing a sibling, you can close this issue. I assume taking that into account would require completely changing the optimizer, since it will have to go not only through the history of the card itself (liek right now) but also through the history of all of its siblings in order to calculate DSR values.

I think this is a important issue. 

Now days, i'm in a like Easy Hell problem with my decks. More than 1000 reviews to do. This deck only use FSRS.

I don't know how can optimize this, but siblings is the most reasonable way to me.

**Comment by Expertium** [comment]
Does every single one of your cards have multiple siblings? Because otherwise I doubt that it would be _that_ much of an issue.

**Comment by filipenanclarez** [comment]
> Does every single one of your cards have multiple siblings? Because otherwise I doubt that it would be _that_ much of an issue.

Yes, every single card have 8 siblings 😣

**Comment by L-M-Sherlock** [comment]
> Yes, every single card have 8 siblings 😣

Could share some contents of them?

**Comment by filipenanclarez** [comment]
> > Yes, every single card have 8 siblings 😣
> 
> Could you share some contents of them?

Yes, off course ... 

Here the all deck, with all the revision history:

[HSK2021-issue-439.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/13450560/HSK2021-issue-439.zip)

**Comment by filipenanclarez** [comment]
@L-M-Sherlock you made any change about this? Or close because we have no solution at this point?

**Comment by L-M-Sherlock** [comment]
I close this issue because I haven't any solution at this point. And the current architecture of FSRS doesn't support updating siblings' stability.
