### ISSUE TITLE
[Question] Learning cards keep getting pushed to Review Queue 

### ISSUE THREAD

**Issue by ArcticBlack23** [open-spaced-repetition/fsrs4anki#443]
Why does the system keep progressing learning cards to the review (green) phase despite them still being in the learning phase and having short intervals. 
![IMG_0191](https://github.com/open-spaced-repetition/fsrs4anki/assets/130110958/4c348ee1-873f-4ae6-95d0-802d14f4d151)
![IMG_0192](https://github.com/open-spaced-repetition/fsrs4anki/assets/130110958/1b2edb9a-795d-4e9f-8be4-f8bae9547637)

**Comment by L-M-Sherlock** [comment]
The card in your screenshot is in reviewing stage, right?

**Comment by ArcticBlack23** [comment]
No it’s currently in the learning stage which is why I’m confused that it’s
getting pushed to the reviewing stage.

**Comment by L-M-Sherlock** [comment]
FSRS doesn't modify the stage of card. So I don't know what happened your cards. Could you reproduce this case?

**Comment by ArcticBlack23** [comment]
Just wanted to confirm. How many times do you have to answer good on a new
card for it to move from a learning to a review card?

**Comment by L-M-Sherlock** [comment]
> Good moves the card to the [next step](https://docs.ankiweb.net/deck-options.html#learning-steps). If the card was on the final step, the card is converted into a review card (it 'graduates').

Source: https://docs.ankiweb.net/studying.html#learningrelearning-cards

So if you have two steps, you need to press good two times.

**Comment by ArcticBlack23** [comment]
That makes sense. I guess I messed up my Anki settings without realizing
it. That’s my fault. There is nothing wrong with the system.
