### ISSUE TITLE
How to disable fsrs4anki for all decks except the specific ones?

### ISSUE THREAD

**Issue by ImKamyar** [open-spaced-repetition/fsrs4anki#444]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Hello, I am using fsrs4anki to improve my spaced repetition scheduling. I really appreciate your work on this project.
However, I have a question about how I can turn off the global functionality of fsrs4anki and make it so that only the specific decks that I mention are enabled for it. As of right now, the only way to turn off the scheduler is to add all of my Anki decks into the skip function, but if I have too many decks it will be a long process.
Is there a way to make fsrs4anki apply only to certain decks, instead of having to exclude all the other decks?

**Comment by L-M-Sherlock** [comment]
You can create a parent deck for all your decks except for the certain deck. Then you can add the parent deck's name into skip deck.

**Comment by ImKamyar** [comment]
Thanks for the helpful answer. I made a parent deck for all my decks except the one I want to use fsrs4anki on. It’s working great now.
