### ISSUE TITLE
First interval for Hard too small

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#446]
In my Anki, the first interval for the "Hard" rating (23m) doesn't seem to be related to the S0 for Hard. Is this normal?

<img width="302" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/13ebcd03-2ed8-48c7-91c9-aebd459ab2d8">

w: [1.1211, 1.4881, 18.5946, 37.4614, 4.5476, 1.6884, 1.9914, 0.0, 1.7468, 0.1402, 1.1844, 1.5592, 0.1902, 0.6935, 0.0106, 0.0, 6.5664]
requestRetention: 0.94

Learning steps & Graduating interval:
<img width="543" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/55f9724d-9a07-415d-9f11-19c5924d3e45">

**Environment**
 - Anki version: [e.g. 2.1.66]
 - OS: [e.g. Windows]
 - Scheduler version: [e.g. v4.0.0]

**Comment by L-M-Sherlock** [comment]
- Hard repeats the current step.
  - If the card is on the first step, the delay will be the average of Again and Good.
  - After the first step, Hard repeats the previous delay.

https://docs.ankiweb.net/studying.html#learningrelearning-cards

**Comment by L-M-Sherlock** [comment]
> if there are 2+ steps, it is the average of the previous step and next step. When you only have a single step, it’s 50% larger than the single step

https://forums.ankiweb.net/t/interval-for-hard-is-longer-than-intervals-for-good-and-easy/24860/7?u=l.m.sherlock

**Comment by L-M-Sherlock** [comment]
So it's controlled by Anki's short-term algorithm, not by FSRS.

**Comment by user1823** [comment]
But, is it not possible to modify the interval after the first `Hard` rating using custom scheduling?

**Comment by L-M-Sherlock** [comment]
The custom scheduling couldn't control the stage of cards.

**Comment by user1823** [comment]
Closing this issue because you can't do anything to solve it.
