### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by filipenanclarez** [open-spaced-repetition/fsrs4anki#450]
**Data file**
If you use FSRS4Anki optimizer, it will extract the data of your review and save it as `revlog.csv`. You can download it from Colab. Then drag and drop the `revlog.csv` file here:
[revlog.csv](https://github.com/open-spaced-repetition/fsrs4anki/files/12515294/revlog.csv)

**Additional context**
- Timezone: America/Sao_Paulo
- The next day starts at: 4

I have a lot of overdue data. Now i'm restart my study routine, with a new deck of words an phrases.

But when i perform optimization based on my pass history, in some cases my **new cards** show me **4 months for good button**. My configs is 0.8 for desired retention rate. Is this right?

**Comment by L-M-Sherlock** [comment]
Thanks for your contribution!
