### ISSUE TITLE
[Question] option to disable fuzz

### ISSUE THREAD

**Issue by omega3** [open-spaced-repetition/fsrs4anki#454]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

> Currently fuzz just adds a random number to the interval.

Following 
https://github.com/open-spaced-repetition/fsrs4anki/issues/430

1. Doesn't it defeat the purpose of all this fancy math if in the end there is random rescheduling added? Doesn't it make math less precise?

2. I agree with the proposed solution but if it is technically impossible, is it possible to disable fuzz completely? I balance my workload by adding more or less new cards. When they are in review I'd like to take full advantage of the fancy math. Yes, I understand the function of fuzz in Anki, but I just don't find it a good solution that should be imposed on me. In my opinion it should be optional.

As FSRS is going to be implemented in Anki by default maybe we should suggest to Damien to add option to disable fuzz?

3. Can disable fuzz be done by adding some lines to the scheduling code pasted to Anki?

**Comment by L-M-Sherlock** [comment]
You can disable fuzz here:

https://github.com/open-spaced-repetition/fsrs4anki/blob/9cf7e2c381783790257ec5e539466ab7ac900b2a/fsrs4anki_scheduler.js#L43
