### ISSUE TITLE
[Question] Is it expected behaviour that the custom scheduling code get reseted?

### ISSUE THREAD

**Issue by wang1zhen** [open-spaced-repetition/fsrs4anki#459]
**Research**

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I have generated deck-specific FSRS parameters via google colab and pasted these data into the custom scheduling code, and it worked. When I wished to add more deck-specific scheduling codes, I found that the former deck-specific FSRS parameters were gone. Is that expected behaviour?

**Comment by L-M-Sherlock** [comment]
Absolutely not. Did you have any other operations during setting parameters? Such as sync?

**Comment by wang1zhen** [comment]
Yes, the sync was done between anki PC (Windows QT6 version) and ankidroid.

**Comment by L-M-Sherlock** [comment]
This issue may be helpful to you:
- https://github.com/ankidroid/Anki-Android/issues/12866
