### ISSUE TITLE
Changing easyBonus and hardInterval doesn't affect intervals

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#46]
**Describe the bug**
Changing easyBonus and hardInterval in fsrs4anki_scheduler.js v2.0.3 doesn't affect intervals. To be fair, I don't understand why they even _should_ affect intervals in the first place, I thought the new algorithm handles it on its own, based on it's own calculations of D and other stuff.

**To Reproduce**
1. Copy and paste code from fsrs4anki_scheduler.js v2.0.3 into the window in deck options
2. Try changing the values of easyBonus and/or hardInterval 
3. See if it affects intervals

**Expected behavior**
Different values should correspond to different intervals.

**Screenshots**
https://i.imgur.com/rqaLLAo.png

**Environment**
 - Anki version: ⁨2.1.55 (6944210f)⁩ Python 3.9.7 Qt 6.3.2 PyQt 6.3.1 
 - OS: Windows 10
 - Scheduler version: 2.0.3

**Comment by L-M-Sherlock** [comment]
I know the problem. You use the advanced button bar add-on, which is incompatible to fsrs.

You can see it in #23

**Comment by Expertium** [comment]
I disabled "The KING of Button Add-ons", but changes to easyBonus and hardInterval still have no effect on interval length.
![image](https://user-images.githubusercontent.com/83031600/193016638-b5f376a7-135a-4329-b7f3-c27b3c155027.png)

**Comment by L-M-Sherlock** [comment]
I will check it later.

And the easyBonus and hardInterval are set for people who want to modify the schedule in their own way. And Anki’s built-in schedule supports it.

**Comment by L-M-Sherlock** [comment]
Is it the same as #41?

**Comment by Expertium** [comment]
Seems like it, yeah.
