### ISSUE TITLE
[Question] bad weight parameters of the optimizer?

### ISSUE THREAD

**Issue by extr15** [open-spaced-repetition/fsrs4anki#463]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Hi everyone, I use the provided `huggingface tool` to optimize my parameters, but the result weight seems bad.
I got: `[1.641, 5.7421, 17.5701, 17.5701, 4.5881, 0.446, 1.442, 0.0002, 2.0623, 0.1016, 1.498, 2.0929, 0.1427, 0.5133, 1.3107, 0.3341, 4.4343]`, while the original default parameters are `"w": [0.4, 0.6, 2.4, 5.8, 4.93, 0.94, 0.86, 0.01, 1.49, 0.14, 0.94, 2.18, 0.05, 0.34, 1.26, 0.29, 2.61],`. 
**The two parameter sets look so different! Is there anything wrong with my training?**
Here are the settings when training:
<img width="1224" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/af44dfa3-12c2-4254-8342-bfca5a727c80">
And the output:
```
Suggested Retention: 0.88
Loss Information
Loss before training: 0.15412410344644048

Loss after training: 0.14211003149976192

Difficulty Distribution
difficulty

3 0.004590

4 0.008964

5 0.333414

6 0.049629

7 0.136033

8 0.131470

9 0.020089

10 0.315809

Ratings
1:again, 2:hard, 3:good, 4:easy

first rating: 1

rating history: 1,3,3,3,3,3,3,3,3,3,3

interval history: 0d,2d,15d,3.2m,1.4y,6.7y,27.8y,100.0y,100.0y,100.0y,100.0y

difficulty history: 0,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5

first rating: 2

rating history: 2,3,3,3,3,3,3,3,3,3,3

interval history: 0d,6d,1.5m,9.0m,3.9y,18.2y,74.5y,100.0y,100.0y,100.0y,100.0y

difficulty history: 0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

first rating: 3

rating history: 3,3,3,3,3,3,3,3,3,3,3

interval history: 0d,18d,4.2m,2.1y,10.7y,48.5y,100.0y,100.0y,100.0y,100.0y,100.0y

difficulty history: 0,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6

first rating: 4

rating history: 4,3,3,3,3,3,3,3,3,3,3

interval history: 0d,18d,4.5m,2.3y,12.6y,59.0y,100.0y,100.0y,100.0y,100.0y,100.0y

difficulty history: 0,4.1,4.1,4.1,4.1,4.1,4.1,4.1,4.1,4.1,4.1

```

If I use the trained parameters and reschedule all my cards (by `fsrs4anki helper`), I only get hundreds of reviews each day in the future, which is too little for me.
<img width="733" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/f30ee05f-e667-4c59-b388-2fd032fb1b6e">

If I use the default parameters, I will get thousands of reviews each day in the future, just like what I did in the past month.
Thus I think the optimizer's result weight is bad...

I found that the card ease distribution looks strange. It is not the normal distribution but lacks too much in 180% and 210% ease. **Is this distribution right** or maybe related to the upper weight problem?
<img width="679" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/9e4e039d-45dc-4992-9847-9d96b9a52a78">

Some additional info:
I have about 70k reviews, which is enough.
I only use AnkiDroid to learn and review. The v3 scheduler in Ankidroid was off as default in the past months.
I synchronized my deck between Ankidroid and Anki Desktop every day. In Anki Desktop, I enabled the v3 scheduler and installed FSRS with the default parameters about two or three weeks ago (I didn't reschedule my cards until today).
> Actually, I am not sure which scheduler took effect...All my fsrs settings were default in the past, thus the `"auto-reschedule after sync" option` was off. I was not familiar with anki and fsrs, thus some settings were not reasonable probably. Now I know the `"auto-reschedule after sync" option` should turn on in order to use the fsrs scheduler in AnkiDroid.

The learning step is `1m 16m 12h`. Note I may start to learn at night, thus some cards with a `12h` learning interval will span to the next day. 
> You suggest finishing learning in the same day. But it is OK if I synchronize and reschedule every day, right? Also, the upper problem is the optimizer's, not the scheduler's.

In fsrs, "requestRetention": 0.9

**Comment by L-M-Sherlock** [comment]
Could you share your retention stats?

**Comment by extr15** [comment]
@L-M-Sherlock , thank for your reply.
I am not sure what's retention stats, and I attached the files from huggingface including:
evaluation.tsv             revlog_history.tsv
prediction.tsv             stability_for_analysis.tsv
revlog.csv
Are them what you want?
[Analysis Files.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/12619134/Analysis.Files.zip)

**Comment by extr15** [comment]
@L-M-Sherlock , You mean the apkg file exported from anki? Here: 
[word_upload.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/12619222/word_upload.zip)

**Comment by L-M-Sherlock** [comment]
<img width="590" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/518e0373-21c2-4716-94e8-5949f048dca8">

You retention is pretty high. So the parameters fit your memory.

**Comment by extr15** [comment]
@L-M-Sherlock , so what's your suggestion? Should I use the calculated parameters?
I modify fsrs's js with `"requestRetention": 0.95` and reschedule, now the number of due cards is about 700. So should I use this configuration?
I worry if I don't review enough cards each day, I'll forget some of them soon.

**Comment by L-M-Sherlock** [comment]
Yeah. You can set a high retention like 0.95 with the calculated parameters.

**Comment by extr15** [comment]
@L-M-Sherlock Thanks, I'll have a try.
Btw, do you know if the figure of `card ease distribution` in my first comment is normal or not?
>I found that the card ease distribution looks strange. It is not the normal distribution but lacks too much in 180% and 210% ease.

**Comment by L-M-Sherlock** [comment]
It would be unrelated. FSRS doesn't use ease to optimize the parameters.

**Comment by Expertium** [comment]
@extr15 FSRS doesn't use ease. Instead, you can Shift + Left Click on "Stats" and scroll all the way down to see the distribution of difficulty.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/e4d43377-6a7a-479a-b14a-45cd7faa4fb3)

**Comment by extr15** [comment]
@Expertium , Thanks for the `Shift + Left Mouse Click on "Stats"`.
My difficult distribution:

<img width="837" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/aa0fce03-5fd8-4312-a025-77e3bb36cf62">

FSRS is complex and confused me a little.
In my first comment, 
```
Loss before training: 0.15412410344644048
Loss after training: 0.14211003149976192
```

It seems the `Loss` only changed a little, and is it normal? 

** Does this mean even if I use the calculated parameters, the actual memory effect is almost the same? **

The optimizer also outputs a difficulty distribution, which differs much from Anki's stats.
Note the `5 0.333414` is pretty high, which does not correspond with the last figure. Is it OK?


```
Difficulty Distribution
difficulty

3 0.004590

4 0.008964

5 0.333414  --------- pretty high

6 0.049629

7 0.136033

8 0.131470

9 0.020089

10 0.315809
```

**Comment by extr15** [comment]
> I found that the card ease distribution looks strange. It is not the normal distribution but lacks too much in 180% and 210% ease.

As for the Anki's card ease distribution, [here](https://forums.ankiweb.net/t/wrong-card-ease-statistics/5039/6) says it's just caused by the size of the statistical buckets.

**Comment by L-M-Sherlock** [comment]
> It seems the `Loss` only changed a little, and is it normal?

It's normal. The minimal changes in the loss would induce a huge impact in the schedule.

> The optimizer also outputs a difficulty distribution, which differs much from Anki's stats.

Because it's calculated from the entire history of all cards. The Anki's stats only consider the latest memory states.

**Comment by extr15** [comment]
Thanks for your clarification.
