### ISSUE TITLE
[Question] learning steps Settings and How Learning Step Settings Schedule Cards After the Addon's Initial Use

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#464]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

hello,I'm a medical student and I'd like to use the fsrs4anki tool.

My current settings are:

Learning steps: 30m, 1d
Graduating interval: 3
Easy interval: 4
Relearning steps: 30m
Retention rate: 75%

i unsuspend daily 100-150 new cards 

I'm aiming for a retention rate of 85% to 90%. I've heard it's not recommended to use learning steps with a 1-day duration. I'm unsure of how to adjust my settings. Can anyone provide guidance on this?

Furthermore, once I use the addon for the first time, will my cards be scheduled according to the deck's settings (learning and relearning steps) or will they follow the fsrs4anki parameters?

**Comment by L-M-Sherlock** [comment]
Just modify these setting:
- Learning steps: 30m
- Retention rate: 85%

**Comment by eagleftw023** [comment]
Thanks for your response 
i should do that before adding the code in the advanced tab and before rescheduling?

When i remove 1d 
It will effect the performance?

after i do this the first time and then i use the deck as usual it ,the new schedule will depend on anki setting or the addon parameters?

**Comment by L-M-Sherlock** [comment]
It doesn't matter when you change the setting. When you remove 1d, FSRS will take over all long-term schedule for you. It would improve the performance.

**Comment by eagleftw023** [comment]
After rescheduling all the cards
Once  i start to use the cards when i click again the card will get new schedule it will depend on the anki settings not fsrs right?

should i do rescheduling with the add-on every month ?

auto reschedule the card after each review should be off?

**Comment by eagleftw023** [comment]
> It doesn't matter when you change the setting. When you remove 1d, FSRS will take over all long-term schedule for you. It would improve the performance.

After rescheduling all the cards
Once i start to use the cards when i click again the card will get new schedule it will depend on the anki settings not fsrs right?

should i do rescheduling with the add-on every month ?

auto reschedule the card after each review should be off?

**Comment by L-M-Sherlock** [comment]
> Once i start to use the cards when i click again the card will get new schedule it will depend on the anki settings not fsrs right?

Yeah. When you press again, the built-in short-term scheduler will take over.

> should i do rescheduling with the add-on every month ?

I recommend rescheduling only when you update the parameters.

> auto reschedule the card after each review should be off?

If you don't want to reschedule all cards in one time, you can enable it.

**Comment by eagleftw023** [comment]
> > Once i start to use the cards when i click again the card will get new schedule it will depend on the anki settings not fsrs right?
> 
> Yeah. When you press again, the built-in short-term scheduler will take over.
> 
> > should i do rescheduling with the add-on every month ?
> 
> I recommend rescheduling only when you update the parameters.
> 
> > auto reschedule the card after each review should be off?
> 
> If you don't want to reschedule all cards in one time, you can enable it.

Thanks alot,there is one  thing that i didnt understand till now

After rescheduling all the cards ,now because i removed 1d from learning step, cards aren't given that additional 1-day buffer before graduating ,how this will not affect the performance,i didnt understand how fsrs will improve the performance

**Comment by L-M-Sherlock** [comment]
Because 1d could be not optimal for you. FSRS would schedule 2d or 5d for you, which relies on your request retention.

**Comment by eagleftw023** [comment]
> Because 1d could be not optimal for you. FSRS would schedule 2d or 5d for you, which relies on your request retention.



You mean that the algorithm of fsrs work when each day i review cards and clicking again or good and decide how to schedule the card,independently to learning steps ??

i thought that fsrs just work in the first time when rescheduling the cards and then the anki setting what will decide the schedule

**Comment by eagleftw023** [comment]
> Because 1d could be not optimal for you. FSRS would schedule 2d or 5d for you, which relies on your request retention.

You mean that the algorithm of fsrs work when each day i review cards and clicking again or good and decide how to schedule the card,independently to learning steps ??

Again button and good button will be calculated through fsrs algorithm?

**Comment by user1823** [comment]
> You mean that the algorithm of fsrs work when each day i review cards and clicking again or good and decide how to schedule the card,independently to learning steps ??

Yes, FSRS replaces Anki's built-in scheduler.

For short-term scheduling (when intervals are shorter than 1 day), Anki's built-in scheduler schedules the cards. This is the phase where learning steps matter.

In the long-term (when the cards has passed through all its learning steps), the FSRS scheduler takes over and Anki's built-in scheduler has no role in controlling when the card will be shown next.

After you press Again, the card enters the relearning phase, where Anki's scheduler takes over until the card passes through all its relearning steps. After that FSRS scheduler takes over.

The role of rescheduling (in the add-on) is to schedule the cards that were previously scheduled by the Anki's scheduler according to the FSRS algorithm.

**Comment by eagleftw023** [comment]
now i 

> > You mean that the algorithm of fsrs work when each day i review cards and clicking again or good and decide how to schedule the card,independently to learning steps ??
> 
> For short-term scheduling (when intervals are shorter than 1 day), Anki's built-in scheduler schedules the cards. This is the phase where learning steps matter.
> 
> In the long-term (when the cards has passed through all its learning steps), the FSRS scheduler takes over and Anki's built-in scheduler has no role in controlling when the card will be shown next.
> 
> After you press Again, the card enters the relearning phase, where Anki's scheduler takes over until the card passes through all its relearning steps. After that FSRS scheduler takes over.
> 
> The role of rescheduling (in the add-on) is to schedule the cards that were previously scheduled by the Anki's scheduler according to the FSRS algorithm.

Thank you for the detailed explanation,It's much clearer now

**Comment by extr15** [comment]
`Graduating interval: 3`, I think you'd better modify it to 1 day.

**Comment by L-M-Sherlock** [comment]
> `Graduating interval: 3`, I think you'd better modify it to 1 day.

It doesn't matter, because FSRS overrides this setting.

**Comment by extr15** [comment]
> > `Graduating interval: 3`, I think you'd better modify it to 1 day.
> 
> It doesn't matter, because FSRS overrides this setting.

OK, I get it.

**Comment by eagleftw023** [comment]
hi, i have anki on pc and iphone (both are updated to the last version and fsrs is enabled on both)

should i enable this "Auto reschedule cards reviewed on other devices after sync" in fsrs addon or not?

**Comment by L-M-Sherlock** [comment]
> should i enable this "Auto reschedule cards reviewed on other devices after sync" in fsrs addon or not?

If you don't want to use load balance and easy days, you can disable "Auto reschedule cards reviewed on other devices after sync".

**Comment by eagleftw023** [comment]
> > should i enable this "Auto reschedule cards reviewed on other devices after sync" in fsrs addon or not?
> 
> If you don't want to use load balance and easy days, you can disable "Auto reschedule cards reviewed on other devices after sync".

i didnt use easy days now,but i have enabled load balancer,should i keep it enabled??
if i can enabled it what is the benefit of it(without easy days)

**Comment by L-M-Sherlock** [comment]
> i didnt use easy days now,but i have enabled load balancer,should i keep it enabled??

Yeah. You need to keep it enabled because load balance only works when rescheduling.

**Comment by eagleftw023** [comment]
> > i didnt use easy days now,but i have enabled load balancer,should i keep it enabled??
> 
> Yeah. You need to keep it enabled because load balance only works when rescheduling.

What is the benefit of load balancer(it works without easy days?)

**Comment by L-M-Sherlock** [comment]
It can make the workload more smooth.
