### ISSUE TITLE
Can FSRS schedule reviews for the same day if learning steps are blank?

### ISSUE THREAD

**Issue by brubsby** [open-spaced-repetition/fsrs4anki#465]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

Rather than fine tune learning steps per deck, I'd like it if they could be autoregressively learned, like long term review timing is learned with FSRS. If I completely delete the learning steps on the settings of a rather difficult deck I have, it shows the learning steps for new cards as 1m (again) 1d (hard) 2d (good) and 4d (easy). and after hitting "again", it then shows 1m (again) 1d (hard) 1d (good) 2d (easy).

Will it ever learn to show me less than 1d for an affirmative answer on a new card? Or is this a shortcoming of the current implementation of FSRS? I searched for discussion of this, and found mostly Sherlock chiding people for having >= 1d in their learning steps, and asking them to remove it. But I wouldn't be surprised if there is a limitation of the algorithm or Anki that it is only limited to dates and not datetimes for interval length.

**Comment by L-M-Sherlock** [comment]
The minimum of interval scheduled by FSRS is 1d.
