### ISSUE TITLE
[BUG] scheduler seems to miss some part review history of some learning cards

### ISSUE THREAD

**Issue by extr15** [open-spaced-repetition/fsrs4anki#466]
**Describe the bug**
Review count and review history are not consistent for some learning cards.
In the following card info, `reviews`  is 3, while there are actually 5 review items.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/3e4d37b1-713e-41f3-a1b7-25c4f7585de9)

**To Reproduce**
My learning step for new cards is `1m 16m 10h`, and I learned 100 cards in 10:00~14:00, thus they will be due about 10 hours later.
But there are **a few** cards (8 cards, and they are at the end of today's learning queue) due at about 15:00, so I checked their card info, and the screenshot is upper. It seems the scheduler or anki does not see all my review history?
I reschedule all my cards, but the problem still exists.
Note only 8 cards are abnormal, which means most of the cards are normal.
My ~~`learn ahead limit` is 1h~~`learn ahead limit` is 5 minutes( sometimes 65 minutes temporarily), and I do my reviews on AnkiDroid, and only use the Anki desktop to sync and reschedule.

**Environment**
 - Anki version:Version ⁨2.1.66 (70506aeb)⁩
    Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
 - OS: macOS
 - Scheduler version:// FSRS4Anki v4.5.6 Scheduler Qt6
 - Optimizer version:  
 - Simulator version:

**Comment by extr15** [comment]
My fsrs4anki helper's settings:
<img width="414" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/ab7ed747-e959-40b5-92e7-bcd82f1bc780">

**Comment by user1823** [comment]
This seems to a bug in AnkiDroid/ Anki.

Can you share your AnkiDroid debug info by following the steps below:

AnkiDroid 2.16+
- Open the navigation drawer by tapping the button on the top left of the screen
- Tap "Settings"
- Tap "About"
- Tap the "Copy debug info" button at the bottom (which copies "debug info" to the clipboard)

If filling out the bug report on your mobile device, paste the contents of the clipboard directly to the issue. Alternatively, you can paste the contents of the clipboard into a new email, send it to yourself, then copy and paste that into the bug report from your computer.

AnkiDroid 2.15 and below
- Open the navigation drawer by tapping the button on the top left of the screen
- Tap "Settings"
- Tap "Advanced"
- Tap "About AnkiDroid" at the bottom
- Tap the "Copy debug info" button at the bottom (which copies "debug info" to the clipboard)

If filling out the bug report on your mobile device, paste the contents of the clipboard directly to the issue. Alternatively, you can paste the contents of the clipboard into a new email, send it to yourself, then copy and paste that into the bug report from your computer.

**Comment by extr15** [comment]
Hi @user1823 , I use Ankidroid 2.16.5 and enable the v3 scheduler.
The copied debug info:
```
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = OnePlus

Model = LE2100

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; LE2100 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 4ca296c6-9c06-442a-89ac-e43327eb3352

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by extr15** [comment]
Also, the Anki debug info here:
```
    
    Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-12.6-x86_64-i386-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-09-17 09:13:18
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2023-07-02T03:55, 'None', mod]
    AnkiWebView Inspector ['31746032', 2023-06-28T03:26, 'None', '']
    Edit Field During Review Cloze ['385888438', 2023-07-31T21:21, '6.15', mod]
    FSRS4Anki Helper ['759844606', 2023-09-15T12:15, 'None', mod]
    Review in Created Order Fix ['252796796', 2022-06-03T10:51, 'None', '']
    Set Added Date ['1124670306', 2023-07-17T01:31, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', '']
    Templates Import  Export ['712027367', 2022-04-13T23:26, '0.2', '']
    rebuildempty some or all filtered decks ['104518886', 2023-05-17T06:33, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    104518886 1046608507 1124670306 252796796 31746032 385888438 712027367 759844606 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T11:10, 'None', '']
    custom sync server redirector ['358444159', 2022-10-06T07:29, 'None', mod]
```

**Comment by L-M-Sherlock** [comment]
I recommend reporting this bug in https://github.com/ankidroid/Anki-Android

**Comment by user1823** [comment]
> I use Ankidroid 2.16.5 and enable the v3 scheduler.

I thought that you might be using the legacy backend in AnkiDroid, which might be causing the issue. But, you are using the new backend. So, I think that you should report this issue on forums.ankiweb.net

**Comment by extr15** [comment]
> > I use Ankidroid 2.16.5 and enable the v3 scheduler.
> 
> I thought that you might be using the legacy backend in AnkiDroid, which might be causing the issue. But, you are using the new backend. So, I think that you should report this issue on forums.ankiweb.net

OK, I'll report.
