### ISSUE TITLE
[Question] Will burying a card affect the schedule?

### ISSUE THREAD

**Issue by extr15** [open-spaced-repetition/fsrs4anki#468]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Sometimes I am not sure about a card (choose `again` or `hard`?) and I may bury it, thus I can review it tomorrow. In this way, I think I can increase retention for that card or make a better choice tomorrow. But since the original last interval of that card is `n` days (e.g. `n`>5 days) and If I bury it, the passed interval will be `n+1` tomorrow, so **will this change affects the schedule of that card?**
I think the answer is yes, since the FSRS will think you forget or still remember that card after a longer interval.

And what's your suggestion? Should I not bury a card even if I want to see it one more time tomorrow to remember it better?

**Comment by L-M-Sherlock** [comment]
It doesn't affect the schedule of that card directly. `Bury` operation isn't recorded in review logs, so FSRS doesn't consider it in the rescheduling. But `Bury` would increase the elapsed days, so the retrievability will decay. In DSR model, the next interval will increase when you recall that card with lower retrievability.

**Comment by extr15** [comment]
Thanks for your reply. It may be hard to judge which one is better. `Bury` makes you see this card on a successive day but also makes future interval a little longer.
