### ISSUE TITLE
[Question]Setting up Custom Scheduling for Anki on PC and iPhone?

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#469]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**

If I want to use Anki on both PC and iPhone, do I need to add the code to the 'Custom Scheduling' within the Anki app on the iPhone?

**Comment by L-M-Sherlock** [comment]
First, you need to enable v3 scheduler on both PC and iPhone. Then, you need to add the code to the 'Custom Scheduling' in Anki (PC or iPhone). Finally, just sync your device.
