### ISSUE TITLE
[Feature Request] Two Button Mode

### ISSUE THREAD

**Issue by AdmerStroh** [open-spaced-repetition/fsrs4anki#47]
**Which module is related to your feature request?**
Scheduler, Optimizer

**Is your feature request related to a problem? Please describe.**
I am only using Answer 1 (Again) or 3 (Good) since that is way more natural for me. Will this effect the efficency of fsrs4anki? Will the Optimizer give valid data for my past reviews?

**Describe the solution you'd like**
Implement a dedicated option in the scheduler and optimizer that accounts for the behavior of only using the buttons Again & Good.

Thank You!

**Comment by kuroahna** [comment]
> I am only using Answer 1 (Again) or 3 (Good) since that is way more natural for me. Will this effect the efficency of fsrs4anki? Will the Optimizer give valid data for my past reviews?

You can use the Again and Good buttons only perfectly fine. Here's a related discussion about this: https://github.com/open-spaced-repetition/fsrs4anki/issues/33

**Comment by AdmerStroh** [comment]
Ah, I missed this one! Thank you :)
