### ISSUE TITLE
[BUG] Deck name not found

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs4anki#470]
I get the following message after enabling "display_memory_state"  
FSRS enabled Deck name not found

**Comment by L-M-Sherlock** [comment]
What's your Anki's version?

**Comment by Vilhelm-Ian** [comment]
2.1.56

**Comment by Vilhelm-Ian** [comment]
I installed a new version. It fixed the problem tahnks
