### ISSUE TITLE
[BUG] Sudden trouble with FSRS sync from desktop

### ISSUE THREAD

**Issue by aedoncassiel** [open-spaced-repetition/fsrs4anki#471]
Getting an error message when I start Anki, and randomly when I try to react to a card. 
The latter seemingly happens more when I click "again." The code says:

> Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
> Platform: Windows-10-10.0.19045
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-09-20 21:29:00
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "aqt.sync", line 117, in on_future_done
>   File "aqt.main", line 1027, in on_collection_sync_finished
>   File "_aqt.hooks", line 4878, in __call__
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 57, in <lambda>
>     sync_did_finish.append(lambda: auto_reschedule(local_rids))
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 50, in auto_reschedule
>     return fut.result()
>   File "concurrent.futures._base", line 446, in result
>   File "concurrent.futures._base", line 391, in __get_result
>   File "concurrent.futures.thread", line 58, in run
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 259, in <lambda>
>     lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 278, in reschedule_background
>     deck_parameters = get_deck_parameters(custom_scheduler)
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 199, in get_deck_parameters
>     weights = _get_weights(version, w_str_matches)
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 121, in _get_weights
>     return [list(map(float, w.split(", "))) for w in str_matches]
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 121, in <listcomp>
>     return [list(map(float, w.split(", "))) for w in str_matches]
> ValueError: could not convert string to float: '0.00 07'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 238, in on_done
>     tooltip(future.result())
>   File "concurrent.futures._base", line 439, in result
>   File "concurrent.futures._base", line 391, in __get_result
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "aqt.sync", line 117, in on_future_done
>   File "aqt.main", line 1027, in on_collection_sync_finished
>   File "_aqt.hooks", line 4878, in __call__
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 57, in <lambda>
>     sync_did_finish.append(lambda: auto_reschedule(local_rids))
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 50, in auto_reschedule
>     return fut.result()
>   File "concurrent.futures._base", line 446, in result
>   File "concurrent.futures._base", line 391, in __get_result
>   File "concurrent.futures.thread", line 58, in run
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 259, in <lambda>
>     lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 278, in reschedule_background
>     deck_parameters = get_deck_parameters(custom_scheduler)
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 199, in get_deck_parameters
>     weights = _get_weights(version, w_str_matches)
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 121, in _get_weights
>     return [list(map(float, w.split(", "))) for w in str_matches]
>   File "C:\Users\aedon\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 121, in <listcomp>
>     return [list(map(float, w.split(", "))) for w in str_matches]
> ValueError: could not convert string to float: '0.00 07'

I'm running FSRS with a personal/optimized code even though I haven't been using Anki for long. I've had FSRS going for a week or so though, and it worked incredibly and I felt like it was an improvement right away. 

I randomly started getting a sync error last night, before touching the settings, so I can't be sure what I'm about to say actually caused it. However, it went away and seemed to work fine this morning. Then a few minutes ago I tried running the optimizer again, and changed my settings, and immediately got the error above. You might also be able to tell me if these numbers are just absurd to use, so I'll add that my original settings were: 

>[1.1856, 1.4674, 6.9493, 12.4234, 5.4214, 1.5095, 1.2161, 0.0036, 1.5271, 0.1506, 0.9876, 2.7173, 0.0114, 0.3121, 0.4112, 0.0, 1.9997] 

and I just tried to "optimize" to: 

> [0.6789, 0.9687, 3.9883, 6.8986, 5.3849, 1.3969, 1.083, 0.0712, 1.061, 0.2108, 0.5044, 2.172, 0.0583, 0.3411, 1.3546, 0.00 07, 2.0971]

 - Anki version: 10
 - FSRS4Anki v4.5.6 Scheduler Qt6
 - Optimizer version: 4.7.1

**Comment by L-M-Sherlock** [comment]
> 0.00 07

Please remove the extra blank in the parameter.

**Comment by aedoncassiel** [comment]
Strange. Fixed it, of course. If you or someone else can give me more info on what exactly these numbers do and how to judge how reasonable they are (honestly, my Anki account is probably too young for this to make sense, and this looks like a pretty big change for such a short period of time between the two "optimizations"), please message me?

Thank you!

**Comment by L-M-Sherlock** [comment]
The parameters are correct. But the blank made it invalid.

**Comment by L-M-Sherlock** [comment]
If you want to know the details about these parameters, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm

**Comment by aedoncassiel** [comment]
Well, the first problem is that I'm innumerate. What I gather from the page is that each number is just plotting the next point on the curve before the card is shown again. The second is that even if I found a good Anki deck for calculus (is that even the right branch of math?) and grinded until I fully understood the page, I'm not sure it answers my question, which is how to judge how my curve looks within the parameters expected by FSRS's design philosophy, and how best to manage (if I even should be) using personal optimization with a very young Anki account (would it be best to optimize every day? What changes in the numbers/graph would give the strongest indication that there was some unique outlier altering my results unnecessarily? etc.)

**Comment by L-M-Sherlock** [comment]
For a very young Anki account, I recommend using the default parameters for a month, then optimize the model for yourself.
