### ISSUE TITLE
[Question] Are the default settings optimized on vocabulary? What to do with the dormant decks?

### ISSUE THREAD

**Issue by wadid** [open-spaced-repetition/fsrs4anki#473]
I have some decks that I use for remembering knowledge other than vocabulary but I dont have enough reviews for generating revies. I can imagine that vocabulary would have another need another profile of settings. I wanted to ask what the default settings are optimized for? 

Another thing I didn't understand yet is if a deck that is dormant would affect the results somehow negatively? I read the FAQ but I am not sure about the answer to my question.

**Comment by L-M-Sherlock** [comment]
No. The default settings are optimized from various materials and users.

**Comment by L-M-Sherlock** [comment]
You can set different parameters for different decks.

**Comment by wadid** [comment]
yes I saw that. but for some I have not the 2000 reviews yet. I will just go with the standard settings. do you have any value ranges in terms of efficiency differences when you customize the settings compared to the standard settings? if it is small then it wouldnt matter to me anyways.

how about the dormant decks, do they skew the results in any way?

**Comment by L-M-Sherlock** [comment]
The default weights has been better than SM-2, so you can use it without optimization when you don't have enough data to train the model.

For the dormant deck, if its content is very different from the materials that you are learning now, I recommend excluding them in optimization.

**Comment by wadid** [comment]
is there any data on how much difference the retention rate settings do? I set it to .85. Wondering how much effect on the amount of daily reviews these settings have. I understood it right, its not a linear curve?

**Comment by L-M-Sherlock** [comment]
https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_simulator

You can use this simulator.
