### ISSUE TITLE
[Question]postpone cards

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#476]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**
Hi, I have a deck with 720 unsuspended cards in Anki and missed a week of review. Today, I have 490 cards to review, but I don’t have time to review them all.

The add-on suggests that it is relatively safe to postpone up to 47 cards. If I postpone 200 cards, how will it affect my retention, and when will these cards be scheduled?

**Comment by eagleftw023** [comment]
@L-M-Sherlock

**Comment by L-M-Sherlock** [comment]
If you postpone cards, your real retention will be lower than your request retention. To respect the safe cnt, the decrease will be limited in 3%.

**Comment by eagleftw023** [comment]
If I postpone 200 cards, will I achieve the target retention in the long term? I am considering postponing 200 cards to make the deck more manageable, as I believe this is better than not reviewing any cards and ceasing to use the deck altogether.

> If you postpone cards, your real retention will be lower than your request retention. To respect the safe cnt, the decrease will be limited in 3%.

**Comment by L-M-Sherlock** [comment]
If you don't postpone cards frequently, you could achieve the target retention in the long term.
