### ISSUE TITLE
[BUG] Missing attribute for argparse in package

### ISSUE THREAD

**Issue by alig1882** [open-spaced-repetition/fsrs4anki#478]
**Describe the bug**

After local installation of the optimizer, I tried running it on an exported Anki deck. I then get the error "AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'".

**To Reproduce**
1. Do a command line installation per these [instructions](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Advanced-methods-of-optimization)
2. Run this command `python -m fsrs_optimizer "package.(colpkg/apkg)"`
3. See error

**Expected behavior**
It should produce the weights to upload into Anki

**Screenshots**
<img width="1012" alt="Screen Shot 2023-09-25 at 6 09 36 PM" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/30926326/e28cfe91-9806-4715-b1e3-f9e824715a75">

**Environment**
 - Anki version: ⁨2.1.65
 - OS: macOS Monterey 12.0.1
 - Scheduler version: v3
 - Optimizer version: 4.5.5

**Additional context**
None

**Comment by L-M-Sherlock** [comment]
Upgrade your python to 3.9.

**Comment by L-M-Sherlock** [comment]
https://stackoverflow.com/questions/70242395/run-capital-gains-command-and-get-erro-attributeerror-module-argparse-has-no

**Comment by alig1882** [comment]
Thank you it worked!
