### ISSUE TITLE
Research on spaced repetition that might be useful

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#481]
I was messaged by a person on Reddit who wrote a thesis on spaced repetition, and also developed his own algorithm.

Full: https://www.politesi.polimi.it/retrieve/b39227dd-0963-40f2-a44b-624f205cb224/2022_4_Randazzo_01.pdf
Summary: https://www.politesi.polimi.it/retrieve/278cbc9b-de06-4230-8daf-9202b17fb3e4/2022_4_Randazzo_02.pdf
Code: https://github.com/giacomoran/memory-models

This could potentially be useful. The metric that he uses, ICI (Integrated Calibration Index), seems to be conceptually similar to our MAE(bins), but with smoothing.

**Comment by L-M-Sherlock** [comment]
> This repository has been archived by the owner on Sep 26, 2023. It is now read-only.

Seems the project is not active now.
