### ISSUE TITLE
[Question] Should the stability's distribution always be a normal distribution?

### ISSUE THREAD

**Issue by extr15** [open-spaced-repetition/fsrs4anki#484]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I get the following 'calibration_2.png' from 'fsrs_optimizer', and the distribution is not like a normal distribution( there is a high pole in about 2 days of the X axis), is it OK?
Actually, I am not sure about the meaning of the 'number of predictions'. Does it mean something like review counts?

![calibration_2](https://github.com/open-spaced-repetition/fsrs4anki/assets/19777236/aeb951ad-f451-483d-a98f-0dec1fcce13d)

PS: In the first half part of my review history, many cards' learning steps spanned 2 days and I modified the learning steps to one day after starting to use FSRS. Does this relate to the above problem?

**Comment by Expertium** [comment]
It's not a normal distribution, the x-axis is logarithmic.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/6f1237bb-42c5-4479-887d-1d4a4cf6cf87)

> there is a high pole in about 2 days of the X axis), is it OK?

Probably ok.

> I am not sure about the meaning of the 'number of predictions'. Does it mean something like review counts?

Yes.

**Comment by extr15** [comment]
Thanks for your reply, I indeed didn't notice the x-axis is logarithmic.
