### ISSUE TITLE
[Question] Scheduler keeps resetting to 3.0.0 afterupdating and rescheduling cards

### ISSUE THREAD

**Issue by ooohweee80085** [open-spaced-repetition/fsrs4anki#487]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

I have tried a few times now to copy and paste the updated scheduler code into the box in the 'options' tag for a deck. I have then run the optimiser and rescheduled cards. Every time I do this i'll notice shortly afterwards (usually the next day) that the scheduler code always defaults back to v.3.20.0. 

My helper add on is up to date, I have the V3 scheduler enabled, relevant add ons disabled and anki itself is also up to date. 

Any thoughts on how to fix this?

**Comment by L-M-Sherlock** [comment]
Do you use AnkiDroid?

**Comment by L-M-Sherlock** [comment]
Do you use AnkiDroid?

**Comment by ooohweee80085** [comment]
Yes I do

**Comment by L-M-Sherlock** [comment]
I guess it is caused by synchronization.

- https://github.com/ankidroid/Anki-Android/issues/13009

I recommend updating your ankidroid.
