### ISSUE TITLE
[Question] Is each card always scheduled separately (not affected by review state of other cards)?

### ISSUE THREAD

**Issue by extr15** [open-spaced-repetition/fsrs4anki#488]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I use `fsrs4anki helper` to re-schedule my cards every day. Say I set the `requestRetention` to `0.9` and I have 100 cards to review today. If I click `again` for 50 cards among these 100 cards, will each card only be scheduled by its own review history and won't be affected by other cards or something global?
Maybe this is a silly question, but I just want to make sure that FSRS won't think like this: oh he forgot too many cards today, I should reduce the review interval for **all** the cards in order to keep the `requestRetention`.

**Comment by L-M-Sherlock** [comment]
Of course, FSRS reschedules all cards based on their own review history independently.

**Comment by Expertium** [comment]
Yes and no. Strictly speaking, cards do not affect each other _directly_, so each card is scheduled independently. However, their review history does affect the values of the parameters. If you review 50 cards and then 50 cards without re-optimizing parameters, then the first 50 reviews won't have any effect on the last 50 reviews. But if you do 50 reviews, then re-optimize parameters, and then do another 50 reviews, they will be affected, albeit marginally.

**Comment by extr15** [comment]
Thanks for your replies, I get it now. @Expertium , thanks for reminding me of that case.
