### ISSUE TITLE
Incorrect graduating interval for new cards

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#49]
**Describe the bug**
The interval that corresponds to "Easy" (aka graduating for new cards) during the first review doesn't match the learning step I set in the deck options. See screenshots.

**To Reproduce**
1. Go to deck options and set learning steps and the graduating interval
2. Review a new card for the first time
3. Check if the "Easy" interval (aka graduating interval) with this FSRS corresponds to the "Easy" (graduating) interval without FSRS

**Expected behavior**
Since FSRS isn't supposed to affect learning steps and graduating intervals, both intervals should be the same, with or without FSRS

**Screenshots**
![1](https://user-images.githubusercontent.com/83031600/193310133-94e8ab84-961c-40b6-9538-518da6b074b2.png)

**Environment**
 - Anki version: 2.1.55
 - OS: Windows 10
 - Scheduler version: v.2.1.0

**Comment by L-M-Sherlock** [comment]
`graduating interval` and `easy interval` become irrelevant in FSRS. You can see the Q7 in [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ).

**Comment by Expertium** [comment]
Ok, I'll close this issue then
