### ISSUE TITLE
[BUG]  Issue with HELPER Addon and Native FSRS in Anki 23.10

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#490]
**Describe the bug**

Anki 23.10 beta4

'm encountering an issue with Anki version 23.10. Despite having the native FSRS properly configured, the HELPER addon is still requesting the JavaScript code from the old FSRS.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42243532/95c6150f-cded-49ac-9fd1-6549e613b6fc)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42243532/4744c185-06f4-495d-8e39-00e47b39cd7b)

**Comment by L-M-Sherlock** [comment]
Do you update the helper add-on？Reinstall the helper and try again.

**Comment by L-M-Sherlock** [comment]
It could be a problem of AnkiWeb. I also noticed this bug, but failed to reproduce it.
