### ISSUE TITLE
[Other] Research the relationship between RMSE and how often users use "Hard" and "Easy"

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#498]
Right now it's unclear whether using only two buttons is detrimental to accuracy or no. The simplest way to investigate it is this:
1) Run FSRS on all collections, record RMSE for each
2) Record how often (in %) user presses "Hard" for each collection
3) Record how often (in %) user presses "Easy" for each collection
4) Calculate the correlation coefficient between RMSE and values calculated in steps 3 and 4 (so there will be two values of the correl. coeff., one for % of Hard and RMSE, one for % of Easy and RMSE)

This is pretty crude, but I don't have a better idea right now.

**Comment by user1823** [comment]
The first step is already done (in the benchmark repo).

Doing the rest of the steps should be pretty easy (for a developer).

**Comment by L-M-Sherlock** [comment]
I made an initial analysis:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/cc8f9b1f-a583-4b52-9de6-da12ce04b775)

**Comment by Expertium** [comment]
Now that I think about it, you should do the same for Again and Good too, to see the full picture

**Comment by L-M-Sherlock** [comment]
Again usage correlation:  0.5072757150803998
Hard usage correlation:  -0.1556013522657226
Good usage correlation:  -0.3534940241621264
Easy usage correlation:  0.12450313870827061

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/5b705833-1559-49c6-a396-b6219b878cd1)

**Comment by Expertium** [comment]
Interesting. Again is correlated the most with RMSE, this suggests that we may need to work on the formula for post-lapse stability.

**Comment by Expertium** [comment]
@L-M-Sherlock can you send me these collections? I'll try to think of some way to improve the formulas.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/45410f34-bf4c-469a-a8e7-f6795b40e05e)

**Comment by user1823** [comment]
I have another idea to test whether not using some of the buttons affects the RMSE (bins).

- Use an arbitrary cutoff to decide if a user uses a particular button or not. I think that if a particular button is used in less than 10% of the reviews, we can assume that the user doesn't use the button. Note: This approach won't work for `Again`. So, we can skip Again in this test.
- For each button, divide the total dataset into two parts, one part consisting of collections that use a particular button and the second part consisting of collections that don't use a particular button.
- For each button, calculate the average RMSE (bins) of the two parts and calculate statistical significance. I am not sure which test would be most appropriate. Probably t-test or Wilcoxon Rank Sum Test?

**Comment by Expertium** [comment]
Wilcoxon rank sum test for non-paired data would be good, yes. Sherlock, I recommend doing what user1823 suggested
`scipy.stats.ranksums(list1, list1).pvalue`
Also, note that since this is a test for non-paired data, neither the length of lists nor the order of values in lists matters.

**Comment by L-M-Sherlock** [comment]
> this suggests that we may need to work on the formula for post-lapse stability.

I have tested some ideas to improve the post-lapse stability prediction. However, they also increased the total RMSE(bins).

**Comment by L-M-Sherlock** [comment]
By the way, I don't want to intervene the button usage habit of users. Ideally, FSRS should fit users with various habits. Only one case should be banned: some users press `hard` when they forget the card. It will confuse FSRS and let FSRS overestimate the user's retention.

**Comment by user1823** [comment]
> By the way, I don't want to intervene the button usage habit of users. Ideally, FSRS should fit users with various habits.

Yes, but we want to know whether FSRS is able to adjust to users' rating habits effectively or not.

**Comment by AnKingMed** [comment]
> By the way, I don't want to intervene the button usage habit of users. Ideally, FSRS should fit users with various habits. Only one case should be banned: some users press hard when they forget the card. It will confuse FSRS and let FSRS overestimate the user's retention.

What if there were only two buttons for the user but FSRS learned habits over time and used the time to answer as a guide, then you could implement hard, good, and easy intervals (or more) based on the amount of time per answer. You'd have to allow the user to turn this on and off and probably require it be off initially so that you could learn the user's habits?

**Comment by L-M-Sherlock** [comment]
> turn this on and off

What's this? Is it the interval displayed above the button? You can read Q11: https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ

**Comment by AnKingMed** [comment]
No I'm suggesting adding a new "auto" feature that the user could turn on and off.  If turned on, it would make it so there are only two buttons, "again" and "good". If the user selected "good", it would then use the time taken to answer to decide whether to use "hard", "good", or "easy"

This may not always be great as length of cards may vary, etc.   It's just a proposal to look into. I'm not sure how effective it would be. I just know many people out there only use again and good, so automating it for them may help to better schedule their cards

**Comment by Expertium** [comment]
Basically, Anking is suggesting that we look into the relationship between grades and answer time to see if we could estimate the former from the latter.

**Comment by Expertium** [comment]
@L-M-Sherlock a reminder to do what user1823 suggested https://github.com/open-spaced-repetition/fsrs4anki/issues/498#issuecomment-1766296905

**Comment by L-M-Sherlock** [comment]
I'm still not interested in the relationship between RMSE and button usage. The dataset is open-source, so I recommend analyzing it by yourselves.

By the way, what if the results showed that using four buttons is better than two buttons? Will it persuade more users to shift from two buttons to four buttons?

**Comment by Expertium** [comment]
> The dataset is open-source, so I recommend analyzing it by yourselves.

Would you provide it in .csv format?

**Comment by L-M-Sherlock** [comment]
https://huggingface.co/datasets/open-spaced-repetition/fsrs-dataset

**Comment by Expertium** [comment]
I need RMSE, or at least predicted R so I can calculate RMSE on my own.

**Comment by L-M-Sherlock** [comment]
Do you mean the evaluation.tsv generated by optimizer?

**Comment by Expertium** [comment]
That would work, yes. I need either RMSE or raw values of R to calculate RMSE, and I also need the review history to calculate the % of Again/Hard/Good/Easy.

**Comment by L-M-Sherlock** [comment]
https://drive.google.com/file/d/10FZgXAI7zdAOGTFuvsuKDRLF4vUv6vr_/view?usp=drive_link

**Comment by Expertium** [comment]
That was a good pandas excercise for me, I wrote code that calculates everything I need for every file and the saves the result as a new .xlsx file.
Anyway, I decided to separate all collections into 2 group. The first groupis where % of Hard+ % of Easy <= threshold%, in other words, Again and Good are used (1-threshold)% of the time or more. The second group consists of all the remaining collections.
There was no statistically significant difference, regardless of the threshold chosen. I'd say this is good news. I will edit FAQ (I recently added an answer to the question about 2 buttons).
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/7910f965-d8a2-445b-a337-f46a318d88ea)
@user1823 you might be interested

**Comment by AnKingMed** [comment]
So basically it doesn't matter if users use 2 vs 4 buttons (vs 6 with Supermemo?). Should I still recommend users try to use all 4 buttons?

**Comment by Expertium** [comment]
Well, idk about Supermemo, but Anki data suggests that FSRS is equally accurate both for people who rarely use "Hard" and "Easy" and for people who use them a lot. So it really doesn't matter either way.

**Comment by AnKingMed** [comment]
Good to know! Thank you for exploring!
