### ISSUE TITLE
[Feature Request] Less than a day interval

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs4anki#503]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Some cards are so hard. They achieve interval of 1 day and I still get them wrong afetwards

**Describe the solution you'd like**
For cards that already have interval of 1 day to achieve an interval less than 1 day. Maybe 12 hours

**Comment by L-M-Sherlock** [comment]
Why not use learning/relearning steps?

**Comment by Vilhelm-Ian** [comment]
Not everycard is that difficult. If I use relearning steps I would have to see a card less than one day for every card that I fail

**Comment by L-M-Sherlock** [comment]
But FSRS doesn't affect the short-term schedule. It would be impossible to schedule a interval less than a day for a review card.
