### ISSUE TITLE
[Question] The doc mention `FSRS has been integrated into Anki 23.10 or newer`, What would be the stable version value?

### ISSUE THREAD

**Issue by KAGEYAM4** [open-spaced-repetition/fsrs4anki#504]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Readme mention FSRS being integrated in Anki with version `23.10` but this isn't the scheme followed by stable release. First i was confused wether it was some mistake, then after sometime figured it out that it was reffering to beta version.

It would be nice to mention that this is reffering to beta version and if possible to add information about which stable version will have FSRS integrated.

**Comment by Vilhelm-Ian** [comment]
Anki is changing it's version number. The next release will be 23.10

**Comment by KAGEYAM4** [comment]
Thank you.
