### ISSUE TITLE
[Feature Request] Reschedule X cards

### ISSUE THREAD

**Issue by ankiuser01** [open-spaced-repetition/fsrs4anki#506]
**Which module is related to your feature request?**
Scheduler, Optimizer, or Simulator?
Scheduler

**Is your feature request related to a problem? Please describe.**
When I Reschedule all cards, I get a huge 7800 card due backlog. I know that we can slowly chip away at it by doing reviews every day, but I would like to have my old cards get rescheduled faster.

**Describe the solution you'd like**
It would be nice to have a Reschedule __ cards option where the user can choose how many cards to reschedule. I think this would be a nice mid-way point between reschedule all or nothing.

**Comment by Vilhelm-Ian** [comment]
There already exists a feature Reschedule Recently Reviewed cards

**Comment by ankiuser01** [comment]
> There already exists a feature Reschedule Recently Reviewed cards

That feature doesn't give me any due cards because I have been using FSRS for a month now. I believe it only reschedules the last 7 days.

**Comment by L-M-Sherlock** [comment]
> I believe it only reschedules the last 7 days.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/dca3bb7f-649a-473d-93bc-ba43bb4631cf)

You can configure the `days_to_reschedule`.

**Comment by ankiuser01** [comment]
Sorry I didn't know this was an option. This was exactly what I was looking for thank you
