### ISSUE TITLE
[BUG] tutorial.md not found

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#508]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/9fdd5165-6f9b-4196-823f-8a08e877fb83)

**Comment by L-M-Sherlock** [comment]
It's a bug of GitHub: https://github.com/github/markup/issues/1734

**Comment by FEI352** [comment]
> It's a bug of GitHub: [github/markup#1734](https://github.com/github/markup/issues/1734)这是 GitHub 的一个错误：github/markup#1734

现在有啥办法办法能看吗？

**Comment by FEI352** [comment]
另外新版的Ankidroid能不能直接用（教程，救我），会不会对旧版的桌面的Anki的自定义排程有影响。
