### ISSUE TITLE
In optimizer v.2.2.0 "import zipfile" doesn't work properly

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#51]
**Describe the bug**
`import zipfile` produces an error. For some reason it only affects certain decks, not every deck

**To Reproduce**
1. Enter the name of your deck in `filename`, then enter your timezone and `next_day_starts_at`
2. Run that code
3. Run the next piece of code, the one that starts with `import zipfile`

**Expected behavior**
There should be no error.

**Screenshots**
![1](https://user-images.githubusercontent.com/83031600/193417233-e3ffcb25-17a3-46bd-8473-fc89e12ab128.png)

**Environment**
 - OS: Windows 10
 - Optimizer version: v2.2.0

**Comment by L-M-Sherlock** [comment]
Do you enable `support order Anki version` when you export the Anki deck file?

<img width="649" alt="image" src="https://user-images.githubusercontent.com/32575846/193417693-6c5cde63-9c87-456a-8c99-87311e051d2d.png">

**Comment by Expertium** [comment]
Yes. I tested if a bit more - it has something to do with the name of the .apkg file. Some names cause this error, some don't.

**Comment by L-M-Sherlock** [comment]
> Yes. I tested it a bit more - it has something to do with the name of the .apkg file. Some names cause this error, some don't. EDIT: nevermind, it's not the name of the file. I can't even reproduce this error anymore, and yes, I'm 100% sure "support older versions" was always enabled on all of my decks.

Maybe it is caused by Colab's file system. Sometimes the Colab can't read the uploaded file immediately.
