### ISSUE TITLE
[Documentation] A short and concise wiki entry for complete newcomers

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#512]
The wiki has a lot of info. Too much, perhaps. If someone is completely new to FSRS, they will have to read a lot of pages, which is probably not what they're looking for. I would like to write a short wiki page that explains the basics of FSRS. It would be a single page that provides all the info necessary to have a basic, minimal understanding of FSRS.
Sherlock, if you don't mind, please create a new wiki page and let me edit it.

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/wiki/ABC-for-FSRS

**Comment by Expertium** [comment]
I'm done. @L-M-Sherlock @user1823 feel free to edit it further.

**Comment by Expertium** [comment]
Btw, Sherlock, it seems that [this page](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-mechanism-of-optimization) hasn't been updated after FSRS v4 was released, it still describes FSRS v3.

**Comment by Expertium** [comment]
@user1823 since 23,10, I think it's time to make final edits to this page. Your help would be appreciated.

**Comment by user1823** [comment]
I have made some edits to make the page more readable. However, I feel that it is currently very disjointed. Alas, I don't have enough time at the moment to make the page better.

**Comment by Expertium** [comment]
Ok. Btw, I prefer to use the word "parameters" rather than "weights", for 2 reasons:
1) Weights is usually used in the context of neural networks, where weights represent the strength of connection between nodes
2) The word parameter is less likely to create confusion among people who are not familiar with ML

**Comment by L-M-Sherlock** [comment]
I agree with user1823. It would be great to make it more organized.

**Comment by dae** [comment]
Re: the retention graph with the red/green bars, what do you think about increasing the y axis to better reflect how high the workload grows as you approach R=1, if doing so still makes the left hand side legible? Currently the truncation makes high R values look only ~3x larger than 0.9.

**Comment by Expertium** [comment]
Coloring is pretty straightforward. @L-M-Sherlock, I suggest re-running the simulator, but this time from 0.999 to 0.60. Last time I had to kinda guess the value for 0.99, since it wasn't in the data your provided.

**Comment by Expertium** [comment]
> would be to color the 0.7-0.85 and 0.95-0.97

Slightly disagree on the range. I think 0.8-0.95 should be green, not 0.85-0.95.

**Comment by L-M-Sherlock** [comment]
If 0.8-0.95 is green, should we set the default desired retention to 0.87 or 0.88 instead of 0.9?

**Comment by dae** [comment]
My vote would be to keep it at 0.9 - it doesn't have to be symmetrical.

**Comment by Expertium** [comment]
I decided to add vertical lines to indicate the range of allowed values of desired retention, and there is a problem: it shows that values in the red area are allowed. This will inevitably lead to users asking "If this area is red, why is it allowed to set the desired retention so high?". Plus, it's inconsistent: the lower boundary is right inbetween the orange and red areas, but the upper boundary is entirely in the red.
![Figure_1](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/a81f5b0b-3f28-48ea-bf20-3c826ae2d6f2)

Then there is another issue: the limit. If I set it low, the graph will demonstrate that there is a big difference between workloads at 0.8 and 0.95, but it won't demonstrate just how much workload grows for R>0.97. If I set y lim high, I get the opposite issue. Now it's clear how quickly workload grows, but workload at 0.7 and 0.95 looks too similar, which can (and probably will) mislead users.
![111](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/94c54d42-edca-4fab-a53e-49cb3c78ea73)

@dae @L-M-Sherlock @user1823 what's your opinion regarding these issues?

**Comment by dae** [comment]
Personally, I'd keep the lines out of the graph, as it allows the user to focus on what's important, and avoids presenting too much information at once. What about setting xmax to 0.99 instead of 1.0 instead? And xmin to 0.67 or similar. 

Regarding the y-axis, one possible approach you could use is to add ticks to the y axis (1x, 2x, 3x) and maybe faint horizontal bars, which would make it easier to see that 0.95 is approximately 2x. If you're not keen on that, maybe we could reach some sort of middle ground on the y axis between those two graphs?

**Comment by L-M-Sherlock** [comment]
> Coloring is pretty straightforward. @L-M-Sherlock, I suggest re-running the simulator, but this time from 0.999 to 0.60, or even to 0.5, to show that workload increases for very low retention rates. Last time I had to kinda guess the values for R>0.97, since it wasn't in the data your provided.

I re-run the simulator with retention from 0.5 to 0.99:

```
[128.42718521043832,
 126.10586350257151,
 123.86323100419062,
 124.48763889725619,
 123.55646271045798,
 123.43303721331742,
 122.30497451348332,
 122.15259019671615,
 120.66356182499598,
 120.71766095900323,
 118.46067691245344,
 117.996435848432,
 116.9026381695129,
 116.90439453733136,
 117.0676543398416,
 116.87291721228723,
 116.31486268004336,
 115.85366389346582,
 116.4216439101658,
 115.19567302651005,
 114.87530852659273,
 113.53655325213391,
 115.13691533864515,
 115.62138703770871,
 114.76960076774199,
 115.40369340768487,
 115.82480378468483,
 114.9575330411633,
 116.94736342126731,
 117.58531651606509,
 117.36775574433011,
 119.32339071100732,
 120.45015145509191,
 122.19685831432899,
 124.6350740547518,
 126.99968537807649,
 129.70336675687713,
 132.41933601503496,
 136.80095507331478,
 142.44879085247103,
 148.0477921109703,
 157.41139358191,
 167.33382956745544,
 181.09913246821685,
 199.26041948396235,
 225.03989356583492,
 264.3108002037564,
 337.1411969520337,
 464.03994714120853,
 825.7770012538409]
```

**Comment by Expertium** [comment]
> Regarding the y-axis, one possible approach you could use is to add ticks to the y axis (1x, 2x, 3x)

I'm not sure how to make that understandable. Currently, the y axis says "Workload (minutes of study per day)". If I add ticks like 1, 2, 3, it will indicate *relative* workload (unitless), not minutes. I'm not sure what to call the y axis then. Calling it "Relative workload" is weird.

**Comment by dae** [comment]
What if the graph were the output interval for a stability of 100 days, like in the deck options?

**Comment by dae** [comment]
Nevermind, that doesn't account for the graph including the extra reviews for forgotten cards.

**Comment by Expertium** [comment]
It will change what the curve looks like for low retention. It won't show that the time spent on Anki actually increases due to having to relearn a lot of forgotten cards. It will just show a monotonic curve.

**Comment by Expertium** [comment]
How about this? The first horizontal line corresponds to the minimum workload. The second is 2x the minimum, etc.
![Figure_1](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/8a19a4ea-2d9f-49cb-b389-fbaceee1b67d)

**Comment by dae** [comment]
Thanks, I think that's a lot clearer. My only remaining suggestion would be to shrink the x axis a bit so it looks less like 1.0 is 4.5x instead of infinity. :-)

**Comment by Expertium** [comment]
I'm not sure what you mean. Do you want the x axis to only extend up to 0.99?

**Comment by dae** [comment]
Preferably, around the point that the line reaches the graph bounds, so it doesn't imply that it levels off.

**Comment by Expertium** [comment]
Like this?
![Uploading Figure_1.png…]()

**Comment by dae** [comment]
Yep! Or even stopping exactly as it hits the top, so users can see what exact DR will give the ~4.3x that the graph is showing. But up to you.

**Comment by user1823** [comment]
I think that the x-axis should extend till 1 but there should be no color in the region between the vertical line corresponding to the point where the curve meets the upper limit of the graph and the vertical line corresponding to DR = 1.

**Comment by Expertium** [comment]
But then there will be empty white space, that's confusing

**Comment by Expertium** [comment]
I fixed some minor coloring issues in photoshop. @L-M-Sherlock, I suggest using this as the final version
![Workload and retention, again](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/79b59813-bd95-4a42-a0a9-025070be8b99)

**Comment by dae** [comment]
Only if the ticks have to be equal length - if the last tick came earlier, there'd be no need. But if that's tricky to do, no problem.

**Comment by Expertium** [comment]
> Only if the ticks have to be equal length

Ticks don't have to be of equal length, in fact, that's how I made the graph above. The distance between ticks is 0.05, excpet for the last one

**Comment by user1823** [comment]
By the way, did you not plot the value for 0.99? In the data shared by Sherlock, the value for 0.99 is roughly 7× the minimum value.

**Comment by Expertium** [comment]
> By the way, did you not plot the value for 0.99?

It's plotted, it's just too far up.
Also, I removed lots of white space, here's a smaller image
![Workload and retention, again (small)](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/f1971d87-e649-426b-9303-33d0f6cf64a9)

**Comment by Expertium** [comment]
@L-M-Sherlock I don't plan to work on this wiki entry anymore, so I recommend making it so that other users cannot edit it anymore.

**Comment by L-M-Sherlock** [comment]
OK
