### ISSUE TITLE
[Question] Can I use this solely for load balance without the other features?

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [open-spaced-repetition/fsrs4anki#515]
My question is simple -- I do not want to change my Anki's general scheduler as I find it cumbersome (I still think the addon is awesome, just too involved for me). However, this is the only addon I've seen that is up to date that features a load balancer. 

If I install this addon, but do NOT:
1) activate scheduler v3 (am on v2)
2) install the custom js advanced deck options
3) tick everything off EXCEPT load balancing in settings

will the load balancer function with everything else disabled, or will this not work?

**Comment by L-M-Sherlock** [comment]
It's impossible. Load balance is based on fuzz range. And Anki removed the fuzz range API in v3. So the add-on has to calculate the fuzz range via FSRS memory state.

**Comment by aboose-aboose-aboose** [comment]
I see, thanks for the prompt reply. I will have to decide if I want to go all in on this add-on. it seems good but the most daunting parts to me: 

1) I have 5 different decks I use with likely very different review history going back years. I think I need to run the training algorithm on these each separately and maintain separate deck logics for each one is that right? 
2) then on top of that I need to retrain them monthly?

**Comment by user1823** [comment]
Yes. But, all of this will become very simple in a matter of days. The next version of Anki (v23.10) has built-in FSRS scheduler and optimizer (as an optional feature).

**Comment by aboose-aboose-aboose** [comment]
fantastic. thanks maybe I'll just wait for that
