### ISSUE TITLE
[BUG] Optimization button doesnt work until you hit "save" and reopen

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [open-spaced-repetition/fsrs4anki#516]
**Describe the bug**
On first time setup, I have created a new deck options preset for each of my decks as they have wildly differing difficulty. These decks all have tens of thousands of review history. When I set FSRS to on and hit optimize, it says "insufficient history to perform". When I hit save, then reopen deck options and hit optimize, then it runs.

**To Reproduce**
See video:

https://github.com/open-spaced-repetition/fsrs4anki/assets/42923683/3b3a2786-1cee-44ff-a6a8-8eed5c25e40a

**Expected behavior**
Hit optimize and run without needing to reopen the window.

**Screenshots**
See above

**Environment**
 - Anki version: 23.10
 - Scheduler version: 3

**Additional context**
Just want to say this is obivously not a big deal but was a bit confusing at first. and I anticipate you may say this is due to how anki handles deck option states and can't be resolved unless Anki itself is fixed, to which I say probably true. Just wanted to give a heads up.

**Comment by L-M-Sherlock** [comment]
I recommend reporting it in https://forums.ankiweb.net

@dae, could open an issue in the repo of Anki?

**Comment by dae** [comment]
Done: https://github.com/ankitects/anki/issues/2797
