### ISSUE TITLE
[Question]fsrs update 

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#518]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**
Hello,
I recently updated Anki with the integrated FSRs feature and I'm curious about any necessary adjustments in the settings. I use Anki on both my iPhone and PC, with the code in custom scheduling.

Also, I have a question regarding the parameters: Is it recommended to change them monthly? If changes are made, will I need to reschedule the cards, or are these two aspects not related?

**Comment by L-M-Sherlock** [comment]
If you have previously used FSRS, please delete the text in the custom scheduling section before enabling FSRS, and ensure the helper add-on has been updated to the 23.10 version if you are using it.

For re-optimizing parameters, it's enough to do that once a month. Regarding rescheduling, it depends. If you want a smooth transition over the re-optimizing, you shouldn't reschedule all cards. If you want an accurate schedule, you need to reschedule all cards.

**Comment by eagleftw023** [comment]
thanks,i have another 2 questions

if i want to use different parameters to different deck how i can do that

how can i enable this after the update?

const display_memory_state = true;

**Comment by Vilhelm-Ian** [comment]
you need to create different deck options
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/81630959/087aad43-a47b-472b-9652-c8eb2ee84400)
The parameters run on per deck

**Comment by eagleftw023** [comment]
> you need to create different deck options
> ![image](https://user-images.githubusercontent.com/81630959/280352727-087aad43-a47b-472b-9652-c8eb2ee84400.png)
> The parameters run on per deck option group

Thanks i have to add the parameters without [] right?
And do you know how to enable const display_memory_state = true;

**Comment by Vilhelm-Ian** [comment]
In the new version of anki you don't have to add the parameters manually. You have to press the button to calculate parameters
