### ISSUE TITLE
[BUG] Simulator not working properly for large decks and long histories

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#525]
**Describe the bug**
I tried simulating 100 years of Anki with a deck that has 100 000 cards.
```
w = [0.2627, 0.2627, 0.8254, 19.0325, 4.8190, 1.1621, 0.7919, 0.0144, 1.6035, 0.1643, 1.0286, 2.5704, 0.0571, 0.2480, 1.1562, 0.2359, 4.6902]
requestRetention = 0.9

maximumInterval = 36500
new_cards_limits = 20
review_limits = 400
max_time_limts = 10000
learn_days = 36500
deck_size = 100_000
```
Here are the graphs that I got:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/223ccc8b-4210-4489-a732-c0935dfd32f3)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/d85c620f-661e-449c-aa1d-8de614319dd7)

**To Reproduce**
1. Go to https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v4.8.3/fsrs4anki_simulator.ipynb
2. Set the parameters specified above
3. See strange curves on the charts

**Expected behavior**
It's hard to tell what exactly went wrong, but charts definitely don't look normal to me.

**Comment by L-M-Sherlock** [comment]
Could you provide other charts?

**Comment by L-M-Sherlock** [comment]
> review_limits = 400

I guess this setting caused the weird graphs. You need to increase this value.

**Comment by Expertium** [comment]
Thank you, I'll increase it and report back. By the way, the simulator is pretty slow for 100 years + 100k cards, can you take a look at the code to see if it could be optimized?

**Comment by L-M-Sherlock** [comment]
The performance has been optimized several times. I don't have any other idea to improve it now.

**Comment by Expertium** [comment]
I see, thank you.

**Comment by L-M-Sherlock** [comment]
It takes 2 minutes for the Rust-based simulator to simulate the review process in FSRS with your configuration. So I think the python version couldn't be faster than that.

**Comment by Expertium** [comment]
Then maybe you could upload the Rust version to Google colab?

**Comment by L-M-Sherlock** [comment]
It's impossible. Because Google colab couldn't run the Rust code. Maybe someday we can integrate the simulator into Anki. But I don't know how to design the GUI for that.
