### ISSUE TITLE
[Question]how to postpone cards in specific deck

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#530]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

Hi,how can i postpone cards in specific deck,not from all decks because there are deck im currently not using

**Comment by L-M-Sherlock** [comment]
Did you install the FSRS4Anki Helper add-on? You can postpone cards of a specific deck in the gear menu of decks.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/4ca4d2b4-aab4-4b38-be45-b1a3c4ce4ed0)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/5b83f7c1-caa8-4be7-9137-4f1ea3ce6b13)
