### ISSUE TITLE
[Question] What is a recommended/standard desired retention for FSRS?

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [open-spaced-repetition/fsrs4anki#531]
FSRS gives us the option to define our desired retention. However, as a new user of this feature I don't really know what to use. Is there a "gold standard" to start out with? I have mine set to .90 but I do not remember if this is the default or if I just input that randomly.

**Comment by L-M-Sherlock** [comment]
0.9 is the default setting. SuperMemo also suggests 0.9.

**Comment by aboose-aboose-aboose** [comment]
thanks for the speedy reply. it might help to add a note in the setting saying that is the default and recommended
