### ISSUE TITLE
Query Regarding FSRS4 Configuration for Specific Exam Dates in Anki 23.10.1

### ISSUE THREAD

**Issue by medicino** [open-spaced-repetition/fsrs4anki#532]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Good morning,

It would be very useful to be able to configure FSRS4 in Anki version 23.10.1 in such a way that we can set a specific exam date. Thus, FSRS4 would automatically configure the cards taking that date into account.

- Is this possibility currently available or in development?
- Is there any add-on compatible with FSRS4 that offers this functionality?
- If the answer to the above questions is negative, could you please explain in detail how to configure FSRS4 to set it up for a specific exam date?

This concern is shared by many students, and we would be very interested in its development.

Thank you very much for your help and dedication.

**Comment by L-M-Sherlock** [comment]
FSRS has been integrated into Anki in 23.10. You can take the exam date into account via this feature:

https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#step-5-optional-compute-optimal-retention

**Comment by Expertium** [comment]
The simplest way is to just set your desired retention high and set yor max. interval in such a way that it's less than the number of days until the exam. For example, if the exam is in 3 months, set max. interval to 1 month. You can use what Sherlock suggested above to choose desired retention.
Additionally, you can use the "Advance" button in the Helper add-on to study cards ahead of time.
