### ISSUE TITLE
[Question] Can you please clarify wht are the right settings of Learning Steps (New Card) and Relearning Steps ?

### ISSUE THREAD

**Issue by lucatortiglione** [open-spaced-repetition/fsrs4anki#534]
Hi,
actually I use latest version of Anki and i have readed somewhere the right settings are 15m 1d but by default i see 1m 10m for new card
and 10m for relearning steps.

Can you please clarify ?

**Comment by L-M-Sherlock** [comment]
I recommend using the default steps. 1d is not recommended if you are using FSRS.

**Comment by Expertium** [comment]
Please read this: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#learning-and-re-learning-steps

**Comment by lucatortiglione** [comment]
> Please read this: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#learning-and-re-learning-steps

ok but there i see 15m 1d

**Comment by Expertium** [comment]
And it says "When FSRS is enabled, learning steps over 1 day are not recommended". Though I suppose it's a little misleading, it makes it sound like 2d is not ok, but 1d is ok. 1d is also suboptimal.
Anyway, make sure that:
1) You don't have too many short learning steps, it's not going to help much with long-term memory
2) Make sure that all your steps can be completed within the same day
In practice, that means use steps like "15m" or "15m 30m".
