### ISSUE TITLE
Does the Optimizer Give More Weight to Recent Data? [Question]

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#535]
*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**

I've noticed an increase in my retention rate from 88% in 2022 to 92% in 2023. I'd like to understand how the FSRS4Anki optimizer handles these changes over time. Does it give more weight to the most recent data, or does it use an average for optimizing the study schedule?

**Comment by Expertium** [comment]
All reviews have the same weight.

**Comment by L-M-Sherlock** [comment]
It doesn't.
