### ISSUE TITLE
[Question] how can i enable this after the update?  const display_memory_state = true;

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#539]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**
hi,
how can i enable this after the update?

const display_memory_state = true;

thanks

**Comment by L-M-Sherlock** [comment]
The bulit-in FSRS doesn't support to display memory state in cards during review. You can submit feature request at https://forums.ankiweb.net/
