### ISSUE TITLE
[Question] How the optimizer so fast now?

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki#542]
Just curious, how is the built-in optimizer significantly faster than the one on colab/huggingface? Is the previous optimizer more accurate than the built-in optimizer?

**Comment by akavi1** [comment]
I did find that using the weights from colab results in a slightly lower RMSE than using the built-in optimizer

**Comment by L-M-Sherlock** [comment]
Because your CPU must be better than the CPU provided by Google Colab.

**Comment by L-M-Sherlock** [comment]
By the way, the python optimizer is very fast in my local device, too.

**Comment by aly-k** [comment]
> Is the previous optimizer more accurate than the built-in optimizer?

@L-M-Sherlock Comments please?
