### ISSUE TITLE
Wiki page A Three Day Journey from Novice to Expert has missing images

### ISSUE THREAD

**Issue by cepera-ang** [open-spaced-repetition/fsrs4anki#549]
**Describe the bug**
Wiki page has missing images https://github.com/open-spaced-repetition/fsrs4anki/wiki/Spaced-Repetition-Algorithm:-A-Three%E2%80%90Day-Journey-from-Novice-to-Expert

**To Reproduce**
1. Go to ['...'](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Spaced-Repetition-Algorithm:-A-Three%E2%80%90Day-Journey-from-Novice-to-Expert)
2. See some images missing (maybe open in private tab, maybe missing images are rendered for author because they private or something?)

**Comment by L-M-Sherlock** [comment]
It's a bug of GitHub: https://github.com/orgs/community/discussions/77236

**Comment by L-M-Sherlock** [comment]
Solved.

**Comment by cepera-ang** [comment]
I can't see images still

**Comment by L-M-Sherlock** [comment]
I can see the images even when using InPrivate mode. It's a bug related to GitHub. I couldn't solve it by myself. I recommend reporting this bug to GitHub official.

**Comment by cepera-ang** [comment]
Ok, sorry for nagging you. I see almost all the images except couple in the
beginning and couple in the middle and thought that maybe quick reupload or
something like that will fix the problem.
