### ISSUE TITLE
[BUG] Optimizing After Small Amount Of Reviews

### ISSUE THREAD

**Issue by Neilord** [open-spaced-repetition/fsrs4anki#550]
**Describe the bug**
Optimizing the FSRS parameters after studying as little as 10 cards, result in lots of changes in the load.

**To Reproduce**
1. Import my Anki collection (it should look like on the screenshot) - download [here](https://drive.google.com/file/d/1vNbZQgRJkzXb6ksV0duvuIeeFxDZC-GL/view?usp=sharing).
2. Fail 10 (shortcut: [enter, 1] * 10) cards in the "Core" deck with the Vocabulary preset.
3. Optimize the FSRS parameters using the setting in the preset options.
5. You will get 489 due cards instead of 628 as it was before (139 LESS after failing!)

**FSRS Settings**
 - SM2 retention: 0.90
 - Desired retention: 0.81

**Expected behavior**
Should it not rely on such an amount of review in that way?)

**Screenshots**
<img width="784" alt="Screenshot 2023-12-04 at 22 40 31" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/65029782/4bbedef6-ec8c-455f-86e6-d1d8e213ceb5">
 
**Environment**
 - Anki version: ⁨23.10.1
 - OS: macOS Ventura (13.0 22A380)
 - Scheduler version: latest probably (sorry not sure where to find it, so I use the one that is build-in into Anki)
 - Optimizer version: latest (sorry not sure where to find it, see "Updated 2023-11-30" on the addon page)
 - Simulator version: _not using it I guess_

**Comment by L-M-Sherlock** [comment]
> result in lots of changes in the load.

Could you compare the future due graphs before and after the optimizing and rescheduling?

**Comment by Neilord** [comment]
Thanks, sure, here it is.

Before:
<img width="740" alt="Screenshot 2023-12-05 at 08 14 05" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/65029782/2cfa8cc7-7310-4121-821a-524e2822d04a">

After:
<img width="741" alt="Screenshot 2023-12-05 at 08 15 41" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/65029782/53d1a94e-3001-4bd4-b335-0213974d73a8">

All stats:
[anki-stats-before.pdf](https://github.com/open-spaced-repetition/fsrs4anki/files/13556443/anki-stats-before.pdf)
[anki-stats-after.pdf](https://github.com/open-spaced-repetition/fsrs4anki/files/13556445/anki-stats-after.pdf)

**Comment by L-M-Sherlock** [comment]
> 4\. You will get 489 due cards instead of 628 as it was before (139 LESS after failing!)

I find that it's due to the backlog. You have 10 days backlog. So the minute difference accumulates. To compare the total reviews in a month, it is 1289 vs 1286, whose difference is insignificant.

**Comment by Neilord** [comment]
That sounds right, thank you for taking a look at it!
