### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#552]
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**
Hi, 

If I unsuspend 100 new cards to my deck every day, how many cards will I approximately need to review each day after a certain period? I understand that the actual number may vary based on individual performance and memory retention, but an approximate figure or a method to calculate this would be greatly helpful.

**Comment by Vilhelm-Ian** [comment]
you can us eth eoptimizer in this repo. To see how many cards you will per day for different retention settings and different new card amount. Based on that you can make your decision

**Comment by L-M-Sherlock** [comment]
You can use the simulator: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb
