### ISSUE TITLE
[Question] Should we deprecate FAQ?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#553]
I mean this: https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ
First of all, some of it is outdated. But more importantly, most people will never see it. People who are new to FSRS will be directed to [this guide](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md), which has its own FAQ, specifically for questions about the built-in version of FSRS, without mentioning questions related to the standalone version.
The standalone version is practically irrelevant as of today: people who have known about FSRS for a long time have already switched to using the desktop version, and people who are new will be told to install the newest desktop version of Anki with built-in FSRS. At this point, the number of people who are using the standalone version is probably in single digits. So the FAQ doesn't help anyone, and the guide has its own FAQ. Thus, I suggest removing it.

@L-M-Sherlock @user1823 thoughts?

**Comment by user1823** [comment]
I think that it doesn't hurt to keep this FAQ page. But, you can remove it if you feel that is better.

The only suggestion I have:
There are some questions in the old FAQ that are relevant for the built-in version too but are not included in the new FAQs. So, those questions should be added to the new FAQs also.

**Comment by Expertium** [comment]
> There are some questions in the old FAQ that are relevant for the built-in version too but are not included in the new FAQs. So, those questions should be added to the new FAQs also.

Which ones, exactly?

**Comment by L-M-Sherlock** [comment]
I plan to move the old FAQs to https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial2.md

**Comment by user1823** [comment]
> Which ones, exactly?

Q1 (about AnkiDroid), Q6, Q11 are missing in the new FAQs. The answer for Q1 needs to be updated though.

In Q6 of new FAQs, it would be nice to mention (briefly) about Ease Hell as in Q3 of old FAQs.

The A4 in new FAQs can be expanded using the text from A10 in the old FAQs. Also, the question should not mention the `Easy` button (the users can also feel the same for Good or even Hard).

**Comment by Expertium** [comment]
Ok, I'll submit a PR later.

**Comment by user1823** [comment]
@L-M-Sherlock, you need to update the link in the issue template (Question) too.
