### ISSUE TITLE
FSRS seems way too conservative with overdue cards that are missing learning steps?

### ISSUE THREAD

**Issue by jcznk** [open-spaced-repetition/fsrs4anki#557]
EDIT: I would like to change the label from 'bug' to 'enhancement', but I'm not sure how to do it.

I'm testing on Anki 23.12 beta 2, qt6.6.1, Windows 10. 
Default FSRS parameters. 
Desired retention: 80%
Already run the rescheduler.

This seems to be at least in part caused by a very hight estimated difficulty.

Cards with no learning steps (introduced by rescheduling):

<img src="https://github.com/open-spaced-repetition/fsrs4anki/assets/60730312/51475bf3-35e2-4bcb-9c5a-acd620f3ecc9" height="400">
<img src="https://github.com/open-spaced-repetition/fsrs4anki/assets/60730312/30831d28-8c82-4982-af07-af469ac7b930" height="400">

Cards introduced by "normal" means, for comparison:

<img src="https://github.com/open-spaced-repetition/fsrs4anki/assets/60730312/c5644c30-67ff-4c08-bd0c-d8c7b8c4047a" height="400">
<img src="https://github.com/open-spaced-repetition/fsrs4anki/assets/60730312/11d1c25e-ab66-4136-a054-bbbcb1fe0862" height="400">
<img src="https://github.com/open-spaced-repetition/fsrs4anki/assets/60730312/c6848a52-c5ac-43e9-9eaf-56db260a3844" height="400">

**Comment by user1823** [comment]
This case is being discussed in https://github.com/open-spaced-repetition/fsrs4anki/issues/540. I have proposed a solution. Let's see if Damien agrees to it.

**Comment by user1823** [comment]
This case is being discussed in https://github.com/open-spaced-repetition/fsrs4anki/issues/540. I have proposed a solution. Let's see if Damien agrees to it.

**Comment by dae** [comment]
From the first example card:

```
[rslib/src/scheduler/fsrs/memory_state.rs:295] first_review.ease_factor = 2.5
[rslib/src/scheduler/fsrs/memory_state.rs:296] first_review.interval = 2.0
[rslib/src/scheduler/fsrs/memory_state.rs:297] sm2_retention = 0.73
[rslib/src/scheduler/fsrs/memory_state.rs:294] fsrs.memory_state_from_sm2(dbg!(first_review.ease_factor),
    dbg!(first_review.interval), dbg!(sm2_retention)) = Ok(
    MemoryState {
        stability: 0.600823,
        difficulty: 10.0,
    },
)
```

Anki treats this like cards with truncated revlogs: difficulty is inferred from the SM2 data on the first non-manual review. In this case we can look into treating it like regular learning instead, but that would not change things for cards with truncated revlogs. I think we should be asking ourselves if a difficulty of 10 is reasonable for those inputs. If not, memory_state_from_sm2 in fsrs-rs may need tweaking.

**Comment by siraben** [comment]
I think it depends on how the user is treating manual scheduling. This basically assumes that manual scheduling is equivalent to having the card as "New" on that day, and that the user hadn't seen it before. For my usage pattern it's better to assume I don't know that manual card than to schedule a longer interval which is what the current FSRS is doing.

**Comment by user1823** [comment]
> that would not change things for cards with truncated revlogs. I think we should be asking ourselves if a difficulty of 10 is reasonable for those inputs. 

The problem with truncated revlogs is that we don't know the previous review history of the card. So, we need to be conservative.

Even with a difficulty of 10, the card will still have a 2.5 (or whatever the Ease is) times increase in the interval. So, it is atleast not worse as compared to SM-2.

Also, the D will decrease with further reviews. So, it won't be high forever.

In addition, most cases of actually truncated revlogs would not have such a small interval (because people would only delete the revlogs when the card is somewhat mature). So, in those cases, the D will not be so high. Rather, if the interval is too high, D would be very low (if the Ease is still 2.5).

By the way, I saw that you made this commit: https://github.com/ankitects/anki/commit/db93939ded947d74bb25bd8552a2b2356a096509
Are you sure that this change doesn't include such cards in the trainset?

**Comment by user1823** [comment]
> I think it depends on how the user is treating manual scheduling.

@siraben

Yes, you are right. That's also why I have proposed adding a new setting to control this. But, it won't be implemented soon.

**Comment by dae** [comment]
> Are you sure that this change doesn't include such cards in the trainset?

Yes, there is no change to the training path.

**Comment by user1823** [comment]
@jcznk, this should be fixed in 23.12.

**Comment by siraben** [comment]
Will this properly handle filtered reviews as well? e.g.
<img width="747" alt="Screenshot 2024-01-03 at 12 04 55" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/8219659/d23b32bc-45e0-4a08-9ada-deee4ab3cde7">

**Comment by L-M-Sherlock** [comment]
> Will this properly handle filtered reviews as well? e.g.

What do you mean "properly"? In that case, FSRS just ignores those filtered reviews.

**Comment by siraben** [comment]
I meant if FSRS would ignore them during eval, I wasn't sure if FSRS uses the review type or rating. Thanks!

**Comment by L-M-Sherlock** [comment]
> I meant if FSRS would ignore them during eval, I wasn't sure if FSRS uses the review type or rating. Thanks!

FSRS doesn't use these reviews in training and eval.
