### ISSUE TITLE
[BUG] AnkiMobile error message

### ISSUE THREAD

**Issue by asb8718** [open-spaced-repetition/fsrs4anki#558]
Getting this error on AnkiMobile (iPhone and iPad) when reviewing with FSRS. Seems to happen somewhat randomly on grading a card. Happens to maybe 10-20% of all cards. Happens on both new and review cards.

```
Error
card was modified: Normal (
Review(
ReviewState {
scheduled_days: 54, elapsed_days: 54, ease_factor: 2.3, lapses: 1, leeched: false, memory_state: Some(
FsrsMemoryState {
stability: 23.2, difficulty: 6.599,
},
) Normal(
Review(
ReviewState {
scheduled_days: 13, elapsed_days: 13, ease_factor: 2.3, lapses: 1, leeched: false, memory_state: Some(
FsrsMemoryState {
stability: 4.9, difficulty: 6.616,},
),
},
),
)
```

I can't tell if it affects anything. The cards are successfully graded

Running the FSRS Helper on Mac which is fully up to date, Anki 23.10, AnkiMobile 23.10.

**Comment by dae** [comment]
Yes, please use the forum or other support site: https://docs.ankimobile.net/support.html

When you post there, please mention whether you're using taps on the screen, or an external keyboard or game controller.
