### ISSUE TITLE
Compatibility - Straight Reward?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki#56]
You could check if there is compatibility with the add-on: **Straight Reward**
https://ankiweb.net/shared/info/957961234

https://github.com/open-spaced-repetition/fsrs4anki/wiki/Compatibility

**Comment by L-M-Sherlock** [comment]
It isn't compatible with Anki 2.1.55. So I can't test whether it is compatible with FSRS.

**Comment by L-M-Sherlock** [comment]
Straight Rward updated at 2022-12-12. I test its compatibility. FSRS4Anki is compatibility with Straight Rward. Because Stratight Reward only modify the `ease` of card and FSRS4Anki doesn't use `ease` in scheduling.
