### ISSUE TITLE
[Question] How does it determine DSR after "Forget Card"?

### ISSUE THREAD

**Issue by hsseek** [open-spaced-repetition/fsrs4anki#562]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
How does it determine DSR after "Forget Card"?

For example,I have cards with a long history. 

1. After months of Anki, a card has large stability(just before an annual exam)
2. Then the card has been put away after the exam.
3. I didn't pass the exam. I reset the card by "Forget Card" to prepare the next year's exam.

Here's an example of such a card.
![Screenshot from 2023-12-16 11-33-16](https://github.com/open-spaced-repetition/fsrs4anki/assets/24645593/0bb662d0-2fe1-47ee-81b4-f50a915cf6c9)

In that case, considering the history before the previous exam would result in rather inaccurate DSR values. I wonder how such casss are dealt with.

**Comment by L-M-Sherlock** [comment]
The history before the `Forget` is ignored by FSRS.
