### ISSUE TITLE
[Question] How does reschedule all cards work?

### ISSUE THREAD

**Issue by ratman-codes** [open-spaced-repetition/fsrs4anki#563]
I have a deck of about 2000 cards that I've had for 5 years or so with a low pass rate (70%). Normally there are raound 20-30 cards due a day.

I hit reschedule for the first time to test it and see what would happen. Because my pass rate is so low, it dumped 900 cards due (this was yesterday). I didn't mind this, I went ahead and did all the reviews. The forecast looked "normal" (30-40 cards per day).

Next day (today) I have 600 cards to review. Once again, I don't mind this and did the reviews, but once again I see tomorrow there will only be 30 reviews. I have a suspicion it won't be 30 but probably something like 300-400 if the pattern keeps up. 

Does rescheduler not actually change the due date in Anki but rather force the cards to appear on a certain time instead? I find it puzzling and want to know why I cannot see what my review load will be now that I've hit this button. It makes me hesitant to use it on other decks.

**Comment by L-M-Sherlock** [comment]
> The forecast looked "normal" (30-40 cards per day).
> 
> Next day (today) I have 600 cards to review.

It's really weird. Which graph do you check? Could you share the screenshot with me?

**Comment by ratman-codes** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42923683/1c2d2506-b6fd-408f-aa96-db7f44442719)
^ the standard stats page graph, though I prefer the legacy format for visibility reasons:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/42923683/c559038c-66e9-48d0-a366-360b27a1930e)

**Comment by ratman-codes** [comment]
As you can see in the graphs above, I wil have 22 cards "due tomorrow" though I suspect that won't be the real amount due, because it looked similar yesterday.

**Comment by L-M-Sherlock** [comment]
Did you check the `backlog`? I guess you set a review limit.

**Comment by ratman-codes** [comment]
Yes, turns out you were right. I did my reviews first (~32) on day 1 then when I rescheduled, it showed 967 cards becuase my review limit is 999. I didn't notice this because I have never hit the review limit and if I did I would expect it to be 999, but it counted the 32 I did earlier. Then the remaining 600 came the next day. I do have 22 as expected due today so it resolved itself. Thank you!
