### ISSUE TITLE
[Question]Unable to clone FSRS4Anki wiki locally

### ISSUE THREAD

**Issue by ChuckieChen945** [open-spaced-repetition/fsrs4anki#565]
**Describe the bug**

Unable to clone FSRS4Anki wiki locally.

**To Reproduce**

Run `git clone https://github.com/open-spaced-repetition/fsrs4anki.wiki.git` locally.

**Expected behavior**

Successfully cloned to local.

**Error message**

```
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Additional context**

The default filenames `How-does-the-scheduler-work?.md` and `Spaced-Repetition-Algorithm:-A-Three‐Day-Journey-from-Novice-to-Expert.md` generated by the wiki are invalid due to the presence of illegal characters `:` and `?`.

**Comment by L-M-Sherlock** [comment]
https://dev.to/jumbo02/how-to-fix-error-invalid-path-when-working-with-git-on-windows-16kf

**Comment by L-M-Sherlock** [comment]
It's not a bug. The path is valid in Mac and Linux. I don't want to modify the filenames because it will change the URL, which has been posted in many places.

**Comment by ChuckieChen945** [comment]
I agree with you. 

The method of setting `git config --global core.protectNTFS false` is ineffective. This issue with Git on Windows seems to have not been properly addressed yet. If any Windows users encounter this problem, they will need to obtain the raw files of the two documents through the following links:

<https://raw.githubusercontent.com/wiki/open-spaced-repetition/fsrs4anki/How-does-the-scheduler-work%3F.md>

<https://raw.githubusercontent.com/wiki/open-spaced-repetition/fsrs4anki/Spaced-Repetition-Algorithm:-A-Three%E2%80%90Day-Journey-from-Novice-to-Expert.md>
