### ISSUE TITLE
[Question] A due manually set by 'Set Due Date' , how does it tkae it into account?

### ISSUE THREAD

**Issue by hsseek** [open-spaced-repetition/fsrs4anki#566]
- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I suppose a due date manually set by `Set Due Date`is not taken into account into FSRS algorithm. If not, what is the best action if I would like an interval shorter than the `Hard` interval?
![Screenshot from 2023-12-20 16-40-30](https://github.com/open-spaced-repetition/fsrs4anki/assets/24645593/d035447d-4da6-4eaa-b4d1-1a6dbe90aa17)

**Comment by L-M-Sherlock** [comment]
FSRS doesn't consider `Set Due Date` in computing the memory state. And I don't recommend rating based on the interval.
