### ISSUE TITLE
[Question] Starting parameters for the optimizer?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#567]
When optimization starts, some initial parameters have to be chosen for the first epoch. In the current Anki implementation, which parameters are used as initial?
1) The default parameters
2) The old parameters (as long as the user has run the optimizer at least once before)

If it's 1, then perhaps we should switch to 2. My reasoning is that they are likely much closer to the optimum for this particular user than the default parameters, so 2 should improve convergence. This shouldn't be difficult to implement, and could potentially fix (or at least alleviate) the problem when users sometimes get worse parameters after another optimization.

**Comment by Expertium** [comment]
@L-M-Sherlock what do you think? This is quite simple to implement, and could improve convergence.

**Comment by L-M-Sherlock** [comment]
Optimizing from default parameters:
<img width="725" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/21cc6f63-cdbf-4008-ab0c-a739d65716c6">

Optimizing from the previous parameters:
<img width="725" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/107c0058-9224-44e1-8d70-fc06f3f70e43">

They have the similar performance and can't fix the issue that the new parameters are worse than the old one in some cases.

**Comment by Expertium** [comment]
I see. Do you have any ideas how to fix this problem, aside from my idea to evaluate both sets of parameters and keep whichever result in lower RMSE? We might have to resort to that.

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/issues/572#issuecomment-1872845869

A easy method is not to re-optimize frequently.
