### ISSUE TITLE
[Question] Any alternate method to achieve `Learn now` effect of `Learn Now & Grade Now` addon as currently `Lean now is incompatible`.

### ISSUE THREAD

**Issue by KAGEYAM4** [open-spaced-repetition/fsrs4anki#569]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

As the title says, what my method of using this `learn now` was to go into `browse` section of anki, select `added` filter, and for all the new cards add them into learn queue.

Can you please suggest any altnernate method to achieve this.

**Comment by L-M-Sherlock** [comment]
`Learn now` is compatible in 23.12. I will update the README.
