### ISSUE TITLE
Questons about FSRS

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#571]
Hi. I have a new collection and I don't have any reviews before and I use Anki 23.12 and FSRS, do I need a FSRS add-on? Also I didn't understand something about how to optimize fsrs parameters. What is the difference between "present:deck name" and "present:deck name" -is:suspended. What do -is:suspended do?

**Comment by L-M-Sherlock** [comment]
FSRS has been integrated into Anki. So you don't need an add-on to schedule your reviews with FSRS. If you need more useful features, you can take a look at the helper add-on: https://ankiweb.net/shared/info/759844606

`-is:suspended` will filter out those reviews from your suspended cards.
