### ISSUE TITLE
Large backlog after update to FSRS v4.5

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#572]
I updated to Anki 23.12.1 and reoptimized my FSRS parameters. It gave me the following parameters:

- 1.2469, 3.8350, 22.0402, 45.3525, 4.7622, 1.4381, 1.5550, 0.0088, 1.7277, 0.1756, 1.0779, 1.8094, 0.1014, 0.5958, 0.5417, 0.0004, 4.0000
- Log loss: 0.2120, RMSE(bins): 1.19%.

(The actual value of w[3] was 35 but I increased it to 45 manually. This decreased the log loss and RMSE. Anyway, it doesn't explain the following observations.)

Then, I rescheduled all my cards and got a backlog of 2300+ cards!

Future Due Graph:
<img width="525" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/17e12931-d783-43c3-b870-6419f32a3044">

Then, I decided to download Anki 23.10.1 and see what parameters it produces. It gave me the following parameters:

- 1.2452, 1.8249, 19.2423, 61.2210, 4.7892, 1.3961, 1.9008, 0.0193, 1.7643, 0.1371, 1.1227, 1.9802, 0.1377, 0.6087, 0.3046, 0.0093, 6.1882
- Log loss: 0.2127, RMSE(bins): 1.31%. 

Then, I rescheduled all my cards and only about 830 cards were due (out of which 400 were already due, even before I started doing any of the above).

Future Due Graph:
<img width="455" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/704769e9-813b-47d5-a712-1231c1481f60">

So, FSRS v4.5 decreased the log loss and RMSE. However, it gave me a huge backlog (FSRS has never given me such a huge backlog till now; even when I switched to FSRS from SM-2, it gave me a backlog of about 900 cards.)

Also, my true retention has not been very different from my desired retention (0.94).
<img width="523" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/c32a0eae-0761-4c6a-8d04-a618b4d649bf">
<img width="556" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/e6135b9f-8ec3-4b7f-9493-54dcff3833e7">

So, is it possible that there is some issue with the new algorithm?

If you need my deck, here it is: [Test.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/13785867/Test.zip) (change file extension to .apkg)

**Comment by L-M-Sherlock** [comment]
My guess is that the forgetting curve's shape is changed in FSRS-4.5. The new curve is sharper for R > 90% and flatter for R < 90%. In your case, the desired retention is 94%, which is higher than 90%, so FSRS-4.5 will schedule a shorter interval than before.

**Comment by user1823** [comment]
But, if the true retention was close to 0.94 earlier, this means that the new curve should calculate a higher stability than before.

So, the effects should cancel each other and the intervals should be roughly the same.

**Comment by L-M-Sherlock** [comment]
> The actual value of w[3] was 35 but I increased it to 45 manually.

What about tuning it to 60? And did you press `easy` frequently? The `w[16]` seems to reach its upper limit.

**Comment by user1823** [comment]
> And did you press easy frequently?

- At first ratings, I have used `Easy` in about 300 cards.
- In the learning phase, I have used it about 500 times.
- In young cards, 7 times.
- In mature cards, never used Easy.

The total number of reviews is greater than 100k. So, I don't think that this explains the situation.

> What about tuning it to 60? 

Changing the w[3] to 60 and w[16] to 7 decreased the total number of due cards by only about 10 cards.

**Comment by user1823** [comment]
I have a strong feeling that the new algorithm is less accurate for me.

As I said earlier, re-optimizing the parameters with the 23.10.1 also gave me a backlog, though not as big as 23.12.1 gave me. So, I decided to work through the backlog given by reoptimizing with 23.10.1. As I was working through the backlog, I noted that I was getting almost every card correct (with Review Sort Order set to "Relative Overdueness"). So, this meant that the new parameters were suboptimal.

After doing >200 reviews, I optimized again in 23.10.1 and my due count fell from 1000 to 100. However, reoptimizing with 23.12.1 is still giving me 2000+ due cards. So, I think that it is less accurate for me. As for the log loss and RMSE, they change so much between the optimizations that I don't think we should rely on them for my collection.

**Comment by L-M-Sherlock** [comment]
According my analysis of the benchmark results, FSRS-4.5 is more accurate than FSRSv4 for 81.7% collections.

**Comment by user1823** [comment]
Then, maybe some other change like https://github.com/open-spaced-repetition/fsrs-rs/commit/a9cc36a207e8861a4b7a383b9d3fae4b9d74c2b8 is the cause.

**Comment by L-M-Sherlock** [comment]
In the comparison between FSRS-rs and FSRS v4, the percentage is 71.3%.

**Comment by user1823** [comment]
I think that you need to analyse things more deeply in order to find the issue. If you don't have enough time to do so now, it's fine. But, it would be great if you perform a proper analysis whenever you have the time.

**Comment by L-M-Sherlock** [comment]
Do you try the python optimizer? It's only related to the Rust optimizer?

**Comment by user1823** [comment]
Py Optimizer v19.2 | Py Optimizer v20.4
-- | --
w = 1.2187, 1.8588, 18.5804, 65.7669, 4.3881, 1.7984, 2.0913, 0.0, 1.7866, 0.1608, 1.2135, 1.4601, 0.1772, 0.6982, 0.0114, 0.0, 4.0 | w = 1.2109, 2.0110, 21.5144, 35.2091, 4.4859, 1.7484, 2.1434, 0.0, 1.8002, 0.1564, 1.1763, 1.3683, 0.1759, 0.7184, 0.0118, 0.0, 4.0
Log loss: 0.2110, RMSE(bins): 0.99%. | Log loss: 0.2110, RMSE(bins): 0.94%
Loss after training: 0.2119, RMSE: 0.0123 | Loss after training: 0.2119, RMSE: 0.0115
Due = 1363 cards | Due = 1388 cards

So, they are quite similar to each other, but in between the Rust Optimizer in 23.12.1 and 23.10.1

I am not happy with these results either. The reason: As I mentioned above, when I started completing the backlog given by the optimizer, I was getting almost all cards correct. So, I think that I should not have any backlog (or a very small backlog).

**Comment by user1823** [comment]
I guess that I have found the issue.

In some cards, I rated `Again` in a Filtered deck (with rescheduling) only a few days after I rated them `Good`. In my opinion, the `Good` rating was because of interference from other related cards that I reviewed on the same day or adjacent days. This seems to have confused FSRS even though such ratings were present in only 8 cards.

You can find such cards in the deck file shared in the first post of this issue by using the following search query in the Browser: 
```
cid:1700673098704,1691514827314,1689521450583,1684167598943,1672238572726,1661483066910,1661483683057,1664457812204
```

I used the following in the Anki Debug Console to delete those unexpected `Good` ratings:
```py
mw.col.db.execute("DELETE from revlog where cid = 1700673098704 and id > 1701801000000 and id < 1702233000000")
mw.col.db.execute("DELETE from revlog where cid = 1691514827314 and id > 1697740200000 and id < 1699122600000")
mw.col.db.execute("DELETE from revlog where cid = 1689521450583 and id > 1701369000000 and id < 1701714600000")
mw.col.db.execute("DELETE from revlog where cid = 1684167598943 and id > 1690223400000 and id < 1690569000000")
mw.col.db.execute("DELETE from revlog where cid = 1672238572726 and id > 1690223400000 and id < 1691173800000")
mw.col.db.execute("DELETE from revlog where cid = 1661483066910 and id > 1692729000000 and id < 1693247400000")
mw.col.db.execute("DELETE from revlog where cid = 1661483683057 and id > 1688149800000 and id < 1688495400000")
mw.col.db.execute("DELETE from revlog where cid = 1664457812204 and id > 1689359400000 and id < 1689791400000")
```

Then, on re-optimizing and rescheduling, Anki 23.12.1 gave me 597 due cards which is much better than the previous 2300+.

**Comment by L-M-Sherlock** [comment]
Thanks for the report. Sounds like the optimizer is sensitive to these reviews? Did you forget them completely? Maybe the better solution is just burying them instead of pressing again.

**Comment by user1823** [comment]
> Did you forget them completely? Maybe the better solution is just burying them instead of pressing again.

Yes, I forgot them. Also, they were not due. I reviewed them in a filtered deck, just to tell Anki that I have forgotten them.

**Comment by L-M-Sherlock** [comment]
By the way, according my recent analysis, it's not a good idea to re-optimizer frequently.
- https://github.com/open-spaced-repetition/fsrs-benchmark/issues/25

<img width="717" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/b136cb82-c24e-4933-9d6a-cd4b281ef505">

<img width="717" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/4d558f7d-72c3-4f12-91c1-d4ba2aba402e">

Based on the experiments, if we re-optimizer every 2000 reviews, the new parameters are better than the old one in 70% cases. But if we do that every 1000 reviews, the percentage drops down to 60%.

**Comment by user1823** [comment]
By the way, I have performed the above-mentioned deletion of revlogs in my main profile as well as my test profile.

Optimization on my main profile still gives me 2000+ cards.
Parameters: 1.2517, 3.9538, 22.1976, 35.3524, 4.9177, 1.4497, 1.5342, 0.0114, 1.8261, 0.1589, 1.1108, 1.6823, 0.1184, 0.6283, 0.4755, 0.0207, 4.0000

Optimization on my test profile (which contains yesterday's collection + above-mentioned change) gives me 587 cards when applied to my main profile.
Parameters: 1.2502, 3.9521, 22.2139, 35.3634, 5.1795, 1.3051, 1.3681, 0.0108, 1.7835, 0.1059, 1.0901, 2.1143, 0.1215, 0.5364, 0.3711, 0.0060, 4.0000

**Comment by L-M-Sherlock** [comment]
<img width="717" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/844a3b3b-68aa-4c93-8bff-a6d9b48582c4">

If we re-optimize for every 4000 reviews, the new parameters are better in 85% cases.

**Comment by Litong18** [comment]
> <img alt="image" width="717" src="https://private-user-images.githubusercontent.com/32575846/293496393-844a3b3b-68aa-4c93-8bff-a6d9b48582c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODAxMjAsIm5iZiI6MTcwNDE3OTgyMCwicGF0aCI6Ii8zMjU3NTg0Ni8yOTM0OTYzOTMtODQ0YTNiM2ItNjhhYS00YzkzLThiZmYtYTZkOWI0ODU4MmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODYzMjllNzkxZmMxMjVmZDgyODRlN2QxODJiZTEzZGZhMGVjYmI1YTYzY2ZmZjczZTRlNTBiZjIwNTZiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wSj3Qe8C8poV9dG8-DmpcAUiptKZOshPnpxLWYbOsbQ">
> 
> If we re-optimize for every 4000 reviews, the new parameters are better in 85% cases.

If frequent optimization can lead to adverse effect on user's parameter, shouldn't FSRS then prevent user for doing this, similar to how there is a 1000 reviews limit for the initial optimization?

**Comment by Vilhelm-Ian** [comment]
That's an anki decision. Not an issue with the algorithm
