### ISSUE TITLE
[Feature Request] calculate new parameters automatically

### ISSUE THREAD

**Issue by Ankilli** [open-spaced-repetition/fsrs4anki#575]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At the moment the user has to calculate their individual parameters manually (e.g. once a month as recommended by the creator).
I often forget when I calculated my parameters the last time.

**Describe alternatives you've considered**
I would appreciate an option in the Deck options to see when I changed parameters the last time like "parameters where changed on 5th of January" or "two weeks ago". Additionally a useful setting would be to automatically calculate parameters (e.g. once a month / once a week / never / etc.).
Then people wouldn't have to bother it anymore once they have set it all up :)

regards :)

**Comment by Vilhelm-Ian** [comment]
That is a problem with anki not the scheduler. Post on the ankiforum so dae can see that there is demand for the feature

**Comment by L-M-Sherlock** [comment]
Yeah. Please report this feature request in https://forums.ankiweb.net/
