### ISSUE TITLE
[BUG] No matter what FSRS parameters I set, the default parameters are being used for calculate next stability

### ISSUE THREAD

**Issue by hugomarins** [open-spaced-repetition/fsrs4anki#576]
**Describe the bug**
No matter what FSRS parameters I set (for w8, w9 and w10), the default parameters are being used for calculate next stability.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/54500828/d3146149-2105-43d3-bb0b-b0c423707a30)

**Expected behavior**
For some reason, the user chosen weights (parameters) are not being used, but the default parameters.

**Screenshots**

**Environment**
 - Anki version: ⁨23.12.1 (1a1d4d54)⁩
 - OS: Windows

**Comment by L-M-Sherlock** [comment]
Could you provide the parameters that you have tried?

**Comment by hugomarins** [comment]
0.5614, 1.2546, 3.5878, 7.9731, 5.1043, 1.1303, 0.8230, 0.0465, 4, 0.1350, 0.1, 2.1320, 0.0839, 0.3204, 1.3547, 0.2190, 2.7849

**Comment by L-M-Sherlock** [comment]
> the default parameters are being used for calculate next stability.

How do you know that? Could you provide some cases?

**Comment by hugomarins** [comment]
I changed some parameters and the intervals provided (next stability) were always the same. And were not according to the formula (they were still using the default weights). Could you test if changing w8, w9 and w10 (parameters used for calculating the next stability in case of sucsessful recall) would change the calculated next interval (next stability)?

**Comment by hugomarins** [comment]
I changed some parameters and the intervals provided (next stability) were always the same. And were not according to the formula (they were still using the default weights). Could you test if changing w8, w9 and w10 (parameters used for calculating the next stability in case of sucsess recall) would change the calculated next interval (next stability)?
