### ISSUE TITLE
Load balancer not working + large backlog [Question]

### ISSUE THREAD

**Issue by bonedoc1** [open-spaced-repetition/fsrs4anki#577]
Hi everyone,

I switched to FSRS about a week ago but did not select reschedule cards on change because I'd prefer to ease into the new algorithm over time as I do cards. 
When I hit " reschedule all cards" via FSRS add-on and have load balancer checked, the amount of future cards due varies tremendously day-to-day and i also get a large backlog of cards. It seems that loadbalancer is maybe not working correctly? Any help would be greatly appreciate, thanks. I'm using the AnKing deck, and my max interval is set to 90 days because thats how often I want to see matured cards.

Before rescheduling:
<img width="926" alt="Screenshot 2024-01-06 at 1 43 16 AM" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/155923339/36cb2282-b556-42b3-9178-f651313c7344">

After rescheduling:
<img width="835" alt="Screenshot 2024-01-06 at 2 00 25 AM" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/155923339/fee17e2e-9378-4fb1-b75d-932e8861a27e">

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Comment by L-M-Sherlock** [comment]
> my max interval is set to 90 days

It causes that most mature cards cannot be load balance because their intervals are limited.

**Comment by bonedoc1** [comment]
> > my max interval is set to 90 days
> 
> It causes that most mature cards cannot be load balance because their intervals are limited.

So it looks like 3100/5700 active cards are at an interval of 2.9months+, when my max interval is 3 months. The reason I chose this max interval is to see the cards more frequently because I'm studying medicine and I don't really trust myself to remember the card after 3 months of not seeing it. Do you have any suggestions? Would changing max interval to 3.5 months or 4 months work?

**Comment by L-M-Sherlock** [comment]
Just trust the algorithm. If you're afraid that you forget too much, just increase the desired retention.
