### ISSUE TITLE
Quick Question re: Optimization and Presets

### ISSUE THREAD

**Issue by embosphere** [open-spaced-repetition/fsrs4anki#578]
I hope this isn't a redundant question - tried searching for it in the past. 

First question is if the algorithm for FSRS takes into account the status of a card when computing intervals - for instance, if retention rates vary from new to mature cards; in an exaggerated sense, what if retention for new cards was 80% and mature was 100%? Will FSRS just average the two to get a total retention as reported in the stats and develop one universal interval schedule for all cards, or will it minimize intervals in the beginning and extend it as cards become matured to adapt to the aforementioned intervals?

Second: When stating that the same preset should be used for all decks within a subdeck. I find this impossible if doing cards with differing number of news where a different max new card limit would be needed for individual decks. Am I misunderstanding this limitation? The only way my presets differ for a given large deck is number of news. All other parameters are consistent across the differing options. 

Thank you, appreciate all the help.

**Comment by L-M-Sherlock** [comment]
> if the algorithm for FSRS takes into account the status of a card when computing intervals

It doesn't. But FSRS also doesn't average any cards. FSRS is optimized in each review.

> I find this impossible if doing cards with differing number of news where a different max new card limit would be needed for individual decks

<img width="549" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/83eaa5f6-41a7-40e8-995b-76d7a1412adf">
