### ISSUE TITLE
[Question] Does it take into account delays

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs4anki#579]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [ ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**

Does the algorithm factor in delayed reviews. For example if I had a card due on the 10th. And if I answered it correct it would show me in five days. What would happn if I review the card on the 30th would it still show it me in 5 days or will it take into account that I was able to answer it even though there was a large delay.

also can you add an answer to this in the faq

**Comment by L-M-Sherlock** [comment]
> Does the algorithm factor in delayed reviews.

Of course. FSRS take into account delays via the retrievability of card when you review it.
