### ISSUE TITLE
[BUG] FSRS young vs mature retention % difference

### ISSUE THREAD

**Issue by BingThosser** [open-spaced-repetition/fsrs4anki#581]
**Describe the bug**
Set retention to 90%, after about a month, some decks have around 90% on mature cards and in the 70s% on young cards.

**Expected behavior**
They should all be at around 90%

**Screenshots**
<img width="1470" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/156291196/b452829b-1df4-459f-89bb-91a467f3db7f">
Main deck ("Master Japanese")

<img width="1470" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/156291196/6b7256d4-de7c-48b0-bfc5-3238b8c59aed">
Problem subdeck 1 ("Core 2000")

<img width="1470" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/156291196/5258c489-58b5-47f7-b856-f0db71fbd0da">
Problem subdeck 2 ("Sentence Mining")

**Environment**
 - Anki version: 23.12.1
 - OS: macOS Ventura 13.0.1
 - Scheduler version: [e.g. v1.0.0]
 - Optimizer version: [e.g. v1.0.3]
 - Simulator version: [e.g. v1.1.0]

**Additional context**
The rest of the subdecks seem fine. Collection file too big for github, here's a dropbox link: 
https://www.dropbox.com/scl/fi/qe68i9olbjs17euckv6bd/collection-2024-01-10-23-13-45.colpkg?rlkey=c1te3hedcepqef5sm0z4e09yf&dl=0

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/fc4a85ea-b02d-4ca5-922d-5e85b881b4a3)

The problem is the stability is too low for those cards that you press `again` in the first learning stage. Even if FSRS scheduled them in 1 day, the retention still couldn't reach 90%.

**Comment by L-M-Sherlock** [comment]
If you still want to achieve 90% retention for these cards, I suggest add an extra learning step.

**Comment by BingThosser** [comment]
How would I go about increasing stability for the learning stage in the long run? Just learn the material better before reviewing it for the first time in Anki as to not press again?
>If you still want to achieve 90% retention for these cards, I suggest add an extra learning step.

Close to 90% would be ideal. Would something like 15 min, 30 min be better or should there be more time between steps?

**Comment by L-M-Sherlock** [comment]
> How would I go about increasing stability for the learning stage in the long run?

You can improve the formulation of your cards.

> Close to 90% would be ideal. Would something like 15 min, 30 min be better or should there be more time between steps?

It depends. I recommend doing experiments by yourself.
