### ISSUE TITLE
[Question] Best practice to deal with huge backlog

### ISSUE THREAD

**Issue by FiniTea** [open-spaced-repetition/fsrs4anki#585]
So i have a huge backlog in several decks from times before FSRS and now i wanna tackle them again with FSRS. I have different presets for the decks, i optimized them. 

Is it best to leave the review per day option uncapped and just review as much as i manage to do each day?

What review sort order is best for backlogs in FSRS? Ascending intervals?

I installed the FSRS helper addon. 

Shall now use the postpone cards in all decks feature or wouldnt that do much as it only effects cards scheduled with FSRS? I didnt quite understand that. Would you then maybe recommend use the "reschedule all cards on change" (in the deck options) to then postpone? Or shall i just review normally as much as i manage to do?

Or would it maybe even be better to just bite the bullet and forget the cards and learn them again?

Thanks for answers!

**Comment by L-M-Sherlock** [comment]
> Is it best to leave the review per day option uncapped and just review as much as i manage to do each day?

If you don't introduce new cards, it's OK.
