### ISSUE TITLE
[Feature Request] FSRS does not support Easy Interval

### ISSUE THREAD

**Issue by kerrickstaley** [open-spaced-repetition/fsrs4anki#586]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Two months ago I started using Anki to learn Chinese again after a break of over 2 years. I wanted to focus on vocabulary related to a game I'm playing, using my [Chinese Prestudy](https://github.com/kerrickstaley/Chinese-Prestudy) plugin. My review was filled with irrelevant words so I decided to delete my entire collection and start over.

Since I deleted all my review history, I set the Easy Interval for new cards to 30 days so that if a word I already knew came up I could quickly set it to a higher review interval, and thus make it faster to get Anki's state back in sync with what I know.

**Describe the solution you'd like**
I wish the Easy button's behavior were configurable in FSRS like it is in the default scheduler.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by L-M-Sherlock** [comment]
If you want to control the easy interval, please modify the 4th value in your parameters of FSRS.
