### ISSUE TITLE
Interesting finding about leeches 

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki#590]
I am not sure where to share this finding. So, I am creating this issue.

In my collection, I suspended the most difficult cards, which I found using the following search query. These were just 48 cards out of a total of 12,000+ cards in my collection.

The query:
```
prop:lapses>5 or prop:reps>50
```

After suspending them, I clicked `Evaluate` and the RMSE dropped from 1.05% to just 0.70% and that is **without** re-optimizing the parameters.

So, "leeches" seem to have a considerable effect.

@Expertium, you might also be interested.

**Comment by Expertium** [comment]
Interesting. I remember trying to add a new parameter to further adjust SInc if a card had a lot of lapses, but it barely affected RMSE.

**Comment by Expertium** [comment]
One of my decks before suspending cards with `prop:lapses>8 or prop:reps>50`:
log loss=0.4564
RMSE (bins)=4.13%

After suspending cards with `prop:lapses>8 or prop:reps>50`:
logloss=0.4485
RMSE (bins)=4.38%

Nope, didn't help.
