### ISSUE TITLE
[Question] Do optimized FSRS parameters synchronize across multiple devices?

### ISSUE THREAD

**Issue by leolulu** [open-spaced-repetition/fsrs4anki#591]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I am currently using Anki version 23.12.1 on two Windows devices. 
After optimizing and saving the FSRS parameters on one of the devices, I synchronized both devices with AnkiWeb. 
However, I noticed that the FSRS parameters on the second device did not update accordingly. 
I am wondering if this is a deliberate design feature, or if there might be an issue with how I am conducting the synchronization process. 
Any insights or assistance on this matter would be greatly appreciated. Thank you in advance.

**Comment by L-M-Sherlock** [comment]
It should be synced. And I recommend asking questions about FSRS in https://forums.ankiweb.net because FSRS has been integrated into Anki.

**Comment by leolulu** [comment]
Understood, I'll go check it out over there.

**Comment by leolulu** [comment]
Understood, I'll go check it out over there.
