### ISSUE TITLE
[Question] Pressing `Again` on a card causes a reschedule where `Good` becomes 100y, after upgrade to anki 23.12 and reoptimizing

### ISSUE THREAD

**Issue by gamagoat** [open-spaced-repetition/fsrs4anki#594]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I have used FSRS for about a year now.  Recently, I upgraded anki to 23.12 (on Mac with intel chip) and decided to re-optimize my FSRS settings.  My parameters came out as follows:

```
[0.4873, 1.083, 3.5878, 7.9731, 5.3797, 2.4396, 0.9191, 0.2165, 1.4245, 0.3689, 0.8408, 2.2769, 0.0465, 0.4059, 1.4799, 1.0, 4.0]
```

I input them directly into the `Custom Scheduling` script, as shown in the screen shot.

<img width="707" alt="Screenshot 2024-01-20 at 11 12 52 AM" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/35706274/b7e76ad5-665a-48dd-8ce2-e1d3fc6ba5e0">

Then I chose to `Reschedule all cards` using the fsrs4anki helper.

I had a decent backlog of items, about ~600 reviews to go through.   Most of the cards had `Good` intervals of 14+ years.  For the cards I pressed `Again` on, when they showed back up in the review, they had `Good` intervals of 100y.  I would have to click the `Reschedule all cards` button again to give them an interval of 2d or 3d.  This has to be done every time a review is marked with `Again`.

This problem is persisting after having gone through the ~600 reviews.

Is this expected behavior, or something I can fix?  Will monthly re-optimizing prevent this issue?

**Comment by L-M-Sherlock** [comment]
Please remove the custom scheduling code. Because it overrides the built-in FSRS.

**Comment by gamagoat** [comment]
@L-M-Sherlock I have done so, and instead pasted the values into `FSRS paramters`.  Do I need to perform another reschedule?

Also, is that information written in a README somewhere?  I had some trouble finding info on this topic.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/b91612e7-ea67-4443-8d52-61bcb644740d)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/2706f669-cc36-42f3-94db-67e1082b890c)

**Comment by gamagoat** [comment]
I missed it, thank you.
