### ISSUE TITLE
[Question] Initial Parameters for new Deck

### ISSUE THREAD

**Issue by lfmelchiades** [open-spaced-repetition/fsrs4anki#595]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

Hello, I'm starting a new deck without any cards. I use version 23.12.1 of anki and the "default parameters" settings are blank. I would like to know what default value to start with.

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/123755028/e5e253bb-7961-477b-952e-e6c2769a24e7)

**Comment by L-M-Sherlock** [comment]
The set of parameters pointed by your green arrow is the default parameters.
