### ISSUE TITLE
[Feature Request] Produce workload graph for an individual 

### ISSUE THREAD

**Issue by Xemorr** [open-spaced-repetition/fsrs4anki#596]
**Which module is related to your feature request?**
Scheduler, Optimizer, or Simulator?
Simulator I guess?

**Is your feature request related to a problem? Please describe.**
The optimal retention calculator spits out a single number, mine being 0.75/0.76 depending on how parameters are varied. I'm preparing for exams so can't afford a retention that low but would still be interested in a graph of how my workload goes up as desired retention is varied.

**Describe the solution you'd like**
The ideal solution would be a button under compute optimal retention that pops up with a graph.

**Describe alternatives you've considered**
Maybe instead of purely minimising workload, (ie finding the minimum point on that graph), it takes into account retention. For example, if 90% retention is only 5% more work than 75% retention, but you get questions wrong 2/5ths as often, then that is much better. I think it's possible to write an equation that also optimises while considering that.

**Additional context**
![281365800-e2b95037-593a-4633-8774-dd16cba5f48e](https://github.com/open-spaced-repetition/fsrs4anki/assets/31805746/f667d7b8-00ac-49fd-9bf3-f11904b6759c)
The graph in the tutorial I'm referencing

**Comment by L-M-Sherlock** [comment]
@Expertium, do you have the code to draw the workload graph?

**Comment by Expertium** [comment]
I do, but beware that it would take a lot of time to generate the graph, even if we limit the range to 0.7-0.99 instead of 0.5-0.99.
[Plotting a graph from Sherlock's data.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/14036991/Plotting.a.graph.from.Sherlock.s.data.zip)

**Comment by Expertium** [comment]
[Plotting a graph from Sherlock's data.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/14039238/Plotting.a.graph.from.Sherlock.s.data.zip)

Here's the code. However, with the way I defined the green area, it may be possible for the output of "Compute optimal retention" to fall within the yellow area.

![Figure_1](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/c9da88df-3769-4a0e-88f6-a3db65422460)

**Comment by Xemorr** [comment]
> > For example, if 90% retention is only 5% more work than 75% retention, but you get questions wrong 2/5ths as often, then that is much better.
> 
> By the way, "Compute optimal retention" doesn't minimize the workload, rather, it maximizes the sum of all probabilities of recall of all cards. In simple terms, it maximizes knowledge acquisition within given time constraints.

ah thank you, I took that understanding from what someone said on reddit. That sounds more sensible. I've realised the values I'm getting from compute optimal retention were because I had a large deck size (explaining the difference between what I'm managing to do, and what the algorithm spit out). I was entering a deck size figure by what I'd expect my deck size to be by the time of exams, as it can't account for a varying deck size. Maybe I'm more interested in having the compute optimal retention feature gain like a linear interpolation feature where there is the option to linearly interpolate between current deck size, end deck size using the number of days of study.

**Comment by L-M-Sherlock** [comment]
Added in the optimizer:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/f544ed27-762e-442b-aa03-780abdf0b567)

**Comment by aleksejrs** [comment]
My arithmetic decks (where I fail a card if I didn't answer it quick enough) got a graph where 98-99% is best, so the whole graph is red.

**Comment by Expertium** [comment]
Can you show that graph here?

**Comment by aleksejrs** [comment]
imp 0 veryimp mathbas 12%.apkg
[3.1008, 3.1008, 8.3177, 25.1118, 5.3022, 1.7371, 1.1355, 0.0697, 1.6848, 0.1068, 1.1423, 1.5057, 0.1995, 0.4903, 0.5435, 0.0127, 3.9198]
Loss before training: 0.2054
Loss after training: 0.2014
![imp 0 veryimp mathbas 12% apkg](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/ded8d6f1-8491-4d99-96f2-313df8b0275d)



imp post math-bas 14%.apkg
[1.1157, 2.5695, 8.9803, 20.0419, 4.9463, 0.7911, 0.7905, 0.0424, 1.6001, 0.1579, 1.0157, 2.0435, 0.1945, 0.3917, 1.3053, 0.1832, 3.161]

![imp post math-bas 14% apkg](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/6b3a4351-80f2-4a40-845a-02afa843f036)

**Comment by Expertium** [comment]
Huh. I guess the default values of "Days to simulate" and other stuff just aren't very good for you.
@L-M-Sherlock what are the defaults? 365 days, 10 000 cards, 30 minutes of study per day?

**Comment by aleksejrs** [comment]
>  @L-M-Sherlock what are the defaults? 365 days, 10 000 cards, 30 minutes of study per day?

So it still depends on those choices like time of study?

Past year:

imp 0 veryimp mathbas 12%.apkg:
Days studied:	77% (281 of 364)
Total:	2508 reviews
Average for days studied:	8.9 reviews/day
If you studied every day:	6.9 reviews/day
Total:	2 hours
Average for days studied:	0.5 minutes/day
If you studied every day:	0.4 minutes/day
Average answer time:	⁨3.2⁩s (⁨18.74⁩ cards/minute)

imp post math-bas 14%.apkg:
Days studied:	65% (237 of 364)
Total:	1099 reviews
Average for days studied:	4.6 reviews/day
If you studied every day:	3.0 reviews/day
Total:	1 hours
Average for days studied:	0.3 minutes/day
If you studied every day:	0.2 minutes/day
Average answer time:	⁨4.03⁩s (⁨14.88⁩ cards/minute)

**Comment by Xemorr** [comment]
> Huh. I guess the default values of "Days to simulate" and other stuff just aren't very good for you. @L-M-Sherlock what are the defaults? 365 days, 10 000 cards, 30 minutes of study per day? Maybe you should add an option to configure all of that, just like in "Compute optimal retention" in Anki itself

Would it be possible to set the default number of cards, to the number of cards the user currently has in their deck? I imagine that might be a _more_ sensible default than 10k.

**Comment by L-M-Sherlock** [comment]
> Maybe you should add an option to configure all of that, just like in "Compute optimal retention" in Anki itself

Actually, the current implementation is configurable: https://github.com/open-spaced-repetition/fsrs-optimizer/blob/bddc4fe67184fdcfaf79284b0e5430a11fcb3c31/src/fsrs_optimizer/fsrs_optimizer.py#L1220-L1227

**Comment by Expertium** [comment]
But I don't see those options in fsrs4anki_optimizer.ipynb.

**Comment by L-M-Sherlock** [comment]
You can pass the arguments into the function in fsrs4anki_optimizer.ipynb.

**Comment by Expertium** [comment]
That's not obvious. Maybe you should add text explaining that, and an example? You can't expect most people to know that.

**Comment by L-M-Sherlock** [comment]
I will do it tomorrow.

**Comment by aleksejrs** [comment]
So this graph is much better than trying different values to get individual numbers and then thinking about them, but it suffers from all the other problems of Evaluate.

I opened the stats for "imp 0 veryimp mathbas 12%.apkg"', "deck:current introduced:100", and it shows that there have been 3 reviews per day (2 with -rated:1), which is about 8.7 seconds.
There are 569 new cards.

figs = optimizer.find_optimal_retention(deck_size=569, learn_span=365, max_cost_perday=9)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/cc38cde4-bb09-4d1f-884b-e1c6c3f0dba7)


figs = optimizer.find_optimal_retention(deck_size=569, learn_span=365, max_cost_perday=6)
Just over 140 cards memorized in the year.
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/3595c213-aeda-4241-bb80-f915f7674306)


I introduce only 1 card per day, so it should be 569 days. And I will probably have backlogs again, so I try changing 6s to 5s.
figs = optimizer.find_optimal_retention(deck_size=569, learn_span=569, max_cost_perday=5)

But apparently 6s was already not enough, so I can learn a new card less often than every other day if I am to fit in 5s?
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/aa459d3f-c50f-4020-b399-d36319a01f33)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/d40e9f3b-e405-41da-863c-9520dc0f0281)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/30752a2b-a4af-4c6a-852c-82c006547c55)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/b52b884f-a383-486f-a356-67e774e2e34c)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/4bc30036-e7b7-41e3-bbc7-f2cfa8ce0b56)

**Comment by Expertium** [comment]
> And I will probably have backlogs again, so I try changing 6s to 5s.

`max_cost_perday` is in minutes, and it's not per card, it's per all cards of that day.

**Comment by aleksejrs** [comment]
> `max_cost_perday` is in minutes, and it's not per card, it's per all cards of that day.

Then why

```
ValueError                                Traceback (most recent call last)

<ipython-input-35-c34ca6615495> in <cell line: 1>()
----> 1 figs = optimizer.find_optimal_retention(deck_size=569, learn_span=590, max_cost_perday=2)

5 frames

/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py in _validate_converted_limits(self, limit, convert)
   3568             if (isinstance(converted_limit, Real)
   3569                     and not np.isfinite(converted_limit)):
-> 3570                 raise ValueError("Axis limits cannot be NaN or Inf")
   3571             return converted_limit
   3572 

ValueError: Axis limits cannot be NaN or Inf
```

**Comment by aleksejrs** [comment]
1800 seconds = 30 minutes, 1800 minutes won't fit in a day.

**Comment by Expertium** [comment]
Ok, my bad. I looked at the code again, and it appears to be in seconds. But I'm still pretty sure that it's per all cards, not just one card.
This would've been much easier if only it was properly documented in the .ipynb itself.

**Comment by aleksejrs** [comment]
I was talking about the time per review that I multiplied by the number of reviews (since Anki rounds per-day stats down to 0).

**Comment by Expertium** [comment]
Ah, so you're plotting a graph for a "What if I only learn 1 card per day?" scenario? I don't think this feature is intended to be used that way, but ok.

**Comment by aleksejrs** [comment]
> Ah, so you're plotting a graph for a "What if I only learn 1 card per day?" scenario? I don't think this feature is intended to be used that way, but ok.

I introduce 1 new card per day.

As I understand it,
* Optimizer limits overall repetitions. It introduces as many new cards as it can fit in max_cost_perday. It doesn't support new_cards_limits, but it can't review overtime.
* Simulator limits overall repetitions + obeys new_cards_limits. It can't review overtime.
* Anki can limit overall repetitions and obey new_cards_limits. You can review overtime. But the only built-in way to get a dynamic new card limit like with Cardistry is to limit reviews and review overtime by choice.

**Comment by Expertium** [comment]
> * Optimizer limits overall repetitions. It introduces as many new cards as it can fit in max_cost_perday. It doesn't support new_cards_limits, but it can't review overtime.
> * Simulator limits overall repetitions + obeys new_cards_limits. It can't review overtime.

I don't think simulator obeys new card's limits, actually. But I'm not sure.

**Comment by aleksejrs** [comment]
> I don't think simulator obeys new card's limits, actually. But I'm not sure.

Then why is the setting there?

**Comment by Expertium** [comment]
Where? I don't see it in https://github.com/open-spaced-repetition/fsrs-optimizer/blob/bddc4fe67184fdcfaf79284b0e5430a11fcb3c31/src/fsrs_optimizer/fsrs_optimizer.py

**Comment by aleksejrs** [comment]
You are looking at Optimizer.

**Comment by Expertium** [comment]
I'm looking at the simulator too
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/be575d43-92f1-491b-bc5d-726f6d4e49a1)

**Comment by aleksejrs** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb

**Comment by Expertium** [comment]
Ah, that one. Yeah, I was looking at the one that is used for calculating optimal retention

**Comment by aleksejrs** [comment]
Simulator needs a switch to disable Anki simulation.
Optimizer needs to support a new card limit.

Still not sure what to do about the existing review cards, since they are causing the most workload in the decks where I am not learning new cards.

With 1 new card/day and pretty much no review limits (100 reps, 60 seconds), I got
DR, time, remembered cards, time per rememberedcard:
0.83 115.2 535 0.22
0.84 569 113.9 535 0.21
0.85 569 114.0 539 0.21
0.85 569 116.7 536 0.22 — with the FSRS values I had before today
0.86 569 117.4 540 0.22, 1 leech
0.87 569 119.2 540 0.22, 1 leech
0.88 569 119.2 542 0.22
0.89 569 118.1 543 0.22

114/600=
 0.19 min/day avg
 11.4 seconds
 11.4/4=2.85
 11.4/3=3.8

**Comment by L-M-Sherlock** [comment]
> Simulator needs a switch to disable Anki simulation. Optimizer needs to support a new card limit.

Please open a new issue to submit feature request.
