### ISSUE TITLE
[Feature Request] Make it easier to disable SM2 ("anki") simulation in Simulator

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki#601]
**Which module is related to your feature request?**
Simulator?

**Is your feature request related to a problem? Please describe.**
Simulator simulates "anki" and "fsrs".

```python
for scheduler_name in ("anki", "fsrs"):
```

When you want to check various settings of FSRS against each other, "anki" simulation is a waste of time.

**Describe the solution you'd like**
Add a switch.

**Describe alternatives you've considered**
Change tuple to list, so that users can simply remove `"anki", ` , especially if they are not familiar with single-element tuples in Python.

**Comment by L-M-Sherlock** [comment]
Implemented in #603
