### ISSUE TITLE
[BUG] Give Simulator's graphs titles to distinguish them

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki#602]
**Describe the bug**
Simulator creates 4 graphs where the text on top is like "new cards limits:4-learn days:730".
The distinguishing text of each graph is the description of the vertical axis, positioned vertically on the left.
The text on top is bigger and looks like the title of the graph, and it is difficult to read the vertical text.

This composition does not direct my attention to the distinguishing text, and no more than two graphs fit on one page of Simulator, so I confuse the graphs.

**Expected behavior**
There is a title on top that is bigger than the data text.

**Screenshots**
(anki simulation was disabled)
![Untitled1](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/57f980c7-3e0d-43b5-9f23-b421724c1277)
![Untitled2](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/09220bf5-66ca-47f8-af79-33624642ac83)
![Untitled3](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/54b1f4d0-b591-4686-b4d3-9a270132e3eb)
![Untitled4](https://github.com/open-spaced-repetition/fsrs4anki/assets/1025861/e24240ce-0ea5-4fb8-b80b-deb45091a1d7)

**Environment**
 - Simulator version: 4.11

**Comment by L-M-Sherlock** [comment]
> There is a title on top that is bigger than the data text.

Do you have an expected title for each graph?

**Comment by aleksejrs** [comment]
The vertical text seems like a good title.

**Comment by L-M-Sherlock** [comment]
How about these:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/3085e012-df34-4407-9835-a9dc9e404f10)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/9c29b971-b541-436d-bed0-f0efc1cf4776)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/8e6930bd-e8e2-491b-86fa-d6f90512dc38)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/df0d4b38-d27d-4e86-b434-889cd1e3eb51)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/3e463be4-2ffd-4092-857a-dde3cda0af52)

**Comment by aleksejrs** [comment]
Seems fine.
