### ISSUE TITLE
[Feature Request] Improve Learning/Relearning Scheduling

### ISSUE THREAD

**Issue by brishtibheja** [open-spaced-repetition/fsrs4anki#606]
I've recently noticed that with FSRS, say I have a card on learning/relearning phase today; I review it through all the steps except the last one. So it's not graduated yet but it's been through the learning/relearning steps; now if I have a backlog of such cards from a week back and review it today I should expect FSRS assigning them a interval > or = to 7 days. I have seen this not happening with learning/relearning cards. My reasoning is **if I'm able to actively recall something after two weeks, the stability should increase not decrease!**

My personal situation was that I had a large backlog of Kanji writing cards especially a lot of relearning cards and after I started reviewing them I see FSRS giving most of them an interval of 3/4 days even though some of the cards haven't been reviewed in two weeks!

![Screenshot_2024-02-02-04-23-20-05_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/open-spaced-repetition/fsrs4anki/assets/136738526/c2269e2e-c2ef-4573-96b2-55749438eb7a)

I have attached data from one of my cards.

**Comment by aleksejrs** [comment]
Yeah, even if all learning steps are a couple of minutes, learning or failing a card at the end of the day probably misleads FSRS.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/c0726ce3-93f6-456f-808b-874a5b63416a)

The stability is 37 days. But the interval is 4 days. I guess you set a very high desired retention, or use multi-days relearning steps.

**Comment by user1823** [comment]
> Yeah, even if all learning steps are a few minutes, not graduating a card on the same day probably misleads FSRS.

I think that this is the problem. The revlog doesn't show multi-day relearning steps.

**Comment by L-M-Sherlock** [comment]
> The revlog in the screenshot doesn't show multi-day relearning steps.

The screenshot doesn't display the info about review kind, so it's unclear.

**Comment by user1823** [comment]
After pressing the `Easy`, the further relearning steps are skipped. So, the card is in Review state now with a 4 day interval.

**Comment by L-M-Sherlock** [comment]
Yeah. You're right. The interval is weird. Maybe it's a bug related to Ank-Android? @brishtibheja which version do you use? And what's your desired retention?

**Comment by brishtibheja** [comment]
@L-M-Sherlock I use the alpha17 version now but before that I was in the last stable version of ankidroid. So all the reviews except the latest happened in the last stable 2.16 version.
 As for the desired retention, it is 84 per cent.

@user1823 You're right, it is in review phase. I dont generally use Easy but I'm graduating the card in 2nd of Feb and the last review was 17th of Jan so even having 4 days interval is too much imho.
  I agree with @aleksejrs that it's related to graduating the card after a 2 week period when it was actually supposed to graduate the same day. But to expand on that I think FSRS doesn't handle backlog even with "some" review cards.

Here is one extreme example from a different deck of mine. 
![Screenshot_2024-02-03-02-04-41-66_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/open-spaced-repetition/fsrs4anki/assets/136738526/36b46b35-1041-4d1c-a54d-fb8bea361f8c)

This is actually a review card of mine. The interesting part is the interval at which I reviewed them. The last review in this card was last year almost 1.5 months back; and the current interval assigned by FSRS is even lower than that. It's a mere 14 days interval. Although this is something I haven't seen with every card of mine.

**Comment by L-M-Sherlock** [comment]
> the current interval assigned by FSRS is even lower than that. It's a mere 14 days interval

Compared with the last interval which is 2 days, 14 days interval has considered the delay.

**Comment by brishtibheja** [comment]
Given that my other cards in this deck didn't have a similar low interval assigned I would guess you're right that the delay was taken into account then. But my logic was, I will not forget something after a month that I was able to recall after 1.5 months. I failed a ton of stuff but imo that card was easy so I remembered it from last December. Anyways, review cards are a different case so I will not prolong the discussion; though can you tell me if manually resheduling cards is okay?

**Comment by user1823** [comment]
You can reschedule all cards using the add-on on the Desktop. It will fix the intervals of all cards.
