### ISSUE TITLE
[BUG] Hard interval is longer than Good interval, and longer than Max interval

### ISSUE THREAD

**Issue by alexbowe** [open-spaced-repetition/fsrs4anki#607]
**Describe the bug**

One item of mine showed a longer hard interval than the good interval. It is my understanding that when I mark a card as "Hard" I should review it sooner (as I need more practice).

Besides that, the Hard interval is 12.1 months. I set FSRS's maximum duration to 365 days, which is an underestimate of days in a year, so it should not be more than 12 months. This might be a sign that something is estimating a month as 30 days, or somewhre a min() function isn't being applied but should. (Although this could be in Anki rather than FSRS).

**To Reproduce**

This may be hard to reproduce without a specific review history. I attached a screenshot below, but please let me know if some logs might help reproduce this (I didn't use FSRS for the whole lifetime of this card, but I did reschedule everything using it).

**Expected behavior**

- The hard interval should be shorter than the Good interval (probably always shorter, and never equal).
- All intervals should be less than the maximum interval.

**Screenshots**

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/208211/12d9acca-8a4a-4ec1-85e3-6039e340aa4d)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/208211/48988b61-9c42-4f1d-a077-1fea04c4c79c)

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/208211/208d146a-e63d-43fb-9938-be3976fdc780)

**Environment**
 - Anki version: 23.12.1 (1a1d4d54)⁩
 - OS: Mac OS X Sonoma 14.1.1 (23B2082)
 - Scheduler version: Whatever FSRS versio is built into this Anki version.
 - Optimizer version: as above
 - Simulator version: as above

**Additional context**

**Comment by L-M-Sherlock** [comment]
I recommend reporting this bug in https://forums.ankiweb.net/c/fsrs/
