### ISSUE TITLE
[Feature Request] Add fuzz to new intervals

### ISSUE THREAD

**Issue by dawrom** [open-spaced-repetition/fsrs4anki#61]
**Which module is related to your feature request?**
Scheduler.

**Is your feature request related to a problem? Please describe.**
If I rate cards the same they will stick together forever and always come up for review on the same day. This can negatively affect learning.

This issue is addressed by Anki here:
https://docs.ankiweb.net/studying.html#fuzz-factor

**Describe the solution you'd like**
Add a small random delay to new intervals.

I wrote a simple function and use it myself, however, I don't know if it won't mess up the algorithm:
```js
function fuzz(interval) {
  let delta;
  if (interval < 2.5) {
    delta = 0;
  } else if (interval < 10) {
    delta = 1;
  } else if (interval < 30) {
    delta = 2;
  } else if (interval < 50) {
    delta = 3;
  } else {
    delta = 4;
  }

  function random_in_range(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  const min_interval = Math.round(interval - delta);
  const max_interval = Math.round(interval + delta);

  return random_in_range(min_interval, max_interval);
}
```

Also, I edited this part of the code:
```js
const hard_interval = constrain_interval(fuzz(last_s * hardInterval));
const good_interval = Math.max(constrain_interval(fuzz(customData.good.s)), hard_interval + 1);
const easy_interval = Math.max(constrain_interval(fuzz(customData.easy.s * easyBonus)), good_interval + 1);
```

It seems to work as intended.

**Describe alternatives you've considered**
I believe that here is the original solution of Anki:
https://github.com/ankitects/anki/blob/72b08cb7d51ddf6a3f51653b678fa0475b8cd0bb/rslib/src/scheduler/states/fuzz.rs

Maybe there is a way to use Anki's original solution?

**Comment by L-M-Sherlock** [comment]
It's a little complicated. I prefer to give a simple implementation.
