### ISSUE TITLE
FSRS Simulator File Not a Zip File [BUG]

### ISSUE THREAD

**Issue by rikr0x** [open-spaced-repetition/fsrs4anki#613]
**Describe the bug**
On [this simulator](https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v4.10.2/fsrs4anki_simulator.ipynb), I followed the instructions attached [here on imgur](https://imgur.com/a/k9XhF3t), but each time the second code block fails with the error "BadZipFile"

``` 
BadZipFile                               Traceback (most recent call last)

[<ipython-input-15-a0aa78290750>](https://localhost:8080/#) in <cell line: 13>()
     11 
     12 optimizer = optimizer.Optimizer()
---> 13 optimizer.anki_extract(filename, filter_out_suspended_cards, filter_out_flags)
     14 
     15 New = 0

2 frames

[/usr/local/lib/python3.10/dist-packages/fsrs_optimizer/fsrs_optimizer.py](https://localhost:8080/#) in anki_extract(self, filename, filter_out_suspended_cards, filter_out_flags)
    416         """Step 1"""
    417         # Extract the collection file or deck file to get the .anki21 database.
--> 418         with zipfile.ZipFile(f"{filename}", "r") as zip_ref:
    419             zip_ref.extractall("./")
    420             tqdm.write("Deck file extracted successfully!")

[/usr/lib/python3.10/zipfile.py](https://localhost:8080/#) in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1267         try:
   1268             if mode == 'r':
-> 1269                 self._RealGetContents()
   1270             elif mode in ('w', 'x'):
   1271                 # set the modified flag so central directory gets written

[/usr/lib/python3.10/zipfile.py](https://localhost:8080/#) in _RealGetContents(self)
   1334             raise BadZipFile("File is not a zip file")
   1335         if not endrec:
-> 1336             raise BadZipFile("File is not a zip file")
   1337         if self.debug > 1:
   1338             print(endrec)

BadZipFile: File is not a zip file 
```

**To Reproduce**
1. [Go here](https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v4.10.2/fsrs4anki_simulator.ipynb)
2. Follow [these instructions](https://imgur.com/a/k9XhF3t), including uploading the file and copying the name. My deck was an .apkg file. 
3. Press Run all. Scroll down to the bottom of the second code block. 

**Expected behavior**
The code should run and simulate. I'm looking for a FSRS accurate and compatible version of the Anki Simulator [add-on](https://ankiweb.net/shared/info/817108664). Not to calculate optimal retention, but to get an idea of what my review load might look like for the next month on different amounts of new cards per day. 

**Screenshots**
<img width="1027" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/160676743/fc0c0c9d-58d1-4508-b17c-ba90cb3233aa">
<img width="663" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/160676743/ae40ec27-12d3-44f6-88c4-cef8b736ce2a">
<img width="728" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/160676743/1b0844d6-8d9c-40c3-a1b1-5f38adef132f">
<img width="944" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/160676743/a59439c0-4494-40d0-a066-ae2a550c2b33">

**Environment**
 - Anki version: Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3

**Comment by L-M-Sherlock** [comment]
Which browser do you use?

**Comment by aleksejrs** [comment]
IIRC, it's when you export the deck without checking the "Support older Anki versions (slower/larger files)" box.

**Comment by aleksejrs** [comment]
Is the apkg file a ZIP file? Is it readable by the browser, so it uploads with a non-zero size?

**Comment by rikr0x** [comment]
Firefox **122.0.1 (64-bit)**

**Comment by L-M-Sherlock** [comment]
I recommend using Chrome because colab is a product of Google. Some firefox users also reported that the file is uploaded incorrectly.

**Comment by aleksejrs** [comment]
If my comments reached anybody: neither exporting in the new format nor uploading an unreadable file causes this error on Firefox.

**Comment by rikr0x** [comment]
> I recommend using Chrome because colab is a product of Google. Some firefox users also reported that the file is uploaded incorrectly.

I’ll try it out in chrome and let you know how that works!

**Comment by L-M-Sherlock** [comment]
> I’ll try it out in chrome and let you know how that works!

Have you tried?

**Comment by rikr0x** [comment]
Worked like a charm, thank you!
