### ISSUE TITLE
[Question]only use "Again" or "Hard"

### ISSUE THREAD

**Issue by aimator** [open-spaced-repetition/fsrs4anki#614]
When I used to use Anki's legacy SuperMemo 2 (SM2) scheduler, I never used "Good" and "Easy". I have only used two-key mode ("Again or Hard") for a long time. 

I recently switched to using FSRS, should I make any changes? Can I continue to use only "Hard" and "Again"? do I need to use "Good" instead of "Hard"?

**Comment by L-M-Sherlock** [comment]
Could you provide the parameters optimized from your data? I need to check whether they are normal.

**Comment by aimator** [comment]
Sure. The parameters optimized from my data is:
0.4266, 1.4061, 3.4739, 7.9731, 5.6550, 1.2496, 0.3940, 0.0772, 1.8506, 0.1539, 0.7332, 2.2107, 0.0872, 0.3368, 1.1233, 0.2859, 4.0000

**Comment by aimator** [comment]
Does this mean that I need to repeat it more times in the same amount of time, and how does this affect the memorization effect? What's the best thing I can do?

**Comment by L-M-Sherlock** [comment]
> Does this mean that I need to repeat it more times in the same amount of time, and how does this affect the memorization effect? What's the best thing I can do?

I recommend checking your true retention and set the desired retention at the same level.

**Comment by aimator** [comment]
> > Does this mean that I need to repeat it more times in the same amount of time, and how does this affect the memorization effect? What's the best thing I can do?
> 
> I recommend checking your true retention and set the desired retention at the same level.

![FB2D3297-3904-4AE2-968B-BE9E3BD40886](https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/07656100-459a-4d1a-8205-e79fb904a21a)
![ADFECBA2-AE07-4D5D-A743-D9FA4E7B0F87](https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/b81fef38-d27a-486b-91f5-d4f5a202424c)
![72D82095-0345-45B6-956B-BB4A2C485E1B](https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/00c1a9e1-16ac-4661-9eb1-072c6175ff30)

I found my average retrievability is 91%, should I set the desired retention to 0.91?

**Comment by user1823** [comment]
> I found my average retrievability is 91%

This is not what L-M-Sherlock asked you to check.

Ideally, you should check the true retention in the stats on the Desktop Anki with the FSRS Helper add-on installed by holding Shift when you click the Stats button.

If you don't use the Desktop version, you can use a value close to the values written after Young and Mature in the following graph.

<img width=300 src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/a6900635-0f1d-438c-bc43-aecc627fafc6">

**Comment by aimator** [comment]
> > I found my average retrievability is 91%
> 
> This is not what L-M-Sherlock asked you to check.
> 
> Ideally, you should check the true retention in the stats on the Desktop Anki with the FSRS Helper add-on installed by holding Shift when you click the Stats button.
> 
> If you don't use the Desktop version, you can use a value close to the values written after Young and Mature in the following graph.
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/92206575/307308258-a6900635-0f1d-438c-bc43-aecc627fafc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDExOTYsIm5iZiI6MTcwODc0MDg5NiwicGF0aCI6Ii85MjIwNjU3NS8zMDczMDgyNTgtYTY5MDA2MzUtMGYxZC00MzhjLWJjNDMtYWVjYzYyN2ZhZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDAyMTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmI3ZTMxM2FhOTc5ZjM1N2ZiZjhjYmY3Y2NkYjM3OTk3MmE2MGQ1MDlkZGFkMTVmZDVlZDM1NjgxOWIyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kGpT8FqSgdwLA2y3GnOprdrCt_gzbug0KGR3IYwgL0s">

Thanks for your help.  I checked the true retention in the stats on the Desktop Anki with the FSRS Helper add-on:

<img width="797" alt="true retention" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/d9c98849-893d-443c-93a7-9b55fe8fab02">

It seems to be close to 90%, it is the same as my current desired retention (0.90).

Should I continue to use only “Hard" and "Again"? Do I need to use "Good" instead of "Hard"? 

How will the shorter interval affect my retention?

**Comment by user1823** [comment]
> Should I continue to use only “Hard" and "Again"?

Generally, I recommend sticking to the old rating habits because FSRS uses your old review history to learn your memory patterns and uses them to schedule new reviews.

But, using "Hard" instead of "Good" even when you recall the card easily can confuse FSRS because when you press "Hard", FSRS assumes that the card is difficult and increases its difficulty. This causes the intervals to grow more slowly.

> How will the shorter interval affect my retention?

It will tend to increase your retention but I feel that the intervals are too small. So, I think that you will mostly be wasting your time if you review them this frequently.

You have three options: (the last one is probably the most effective but also the most difficult)
- Keeping using "Hard" and set a lower desired retention (say, 0.85)
- Start using "Good" and set a desired retention of, say, 0.90
- Convert your old "Hard" ratings into "Good" and then re-optimize.
   - Do this ONLY IF you are sure that each time you pressed "Hard", you actually meant "Good" and you didn't use "Good" for the cards that were easier than those that you pressed "Hard" on.
  - Before doing this, SYNC all your devices and create a BACKUP.
  - On the Desktop version of Anki, press Ctrl+Shift+; (the control key, shift key, and semi-colon key at the same time) to open up the debug console.
  - Paste the following code into it.
  ```
  mw.col.db.execute("update revlog set ease=3 where ease=2")
  mw.col.mod_schema(False)
  ```
  - Press Ctrl + Enter to run the code. The message shown by Anki gives the impression that the code failed to execute. But, it does get executed.
  - Close the Debug Console. Click check database and finally upload your collection to AnkiWeb at the next sync.
  - Re-optimize your parameters and start using "Good" and "Again" from now onwards.

**Comment by aimator** [comment]
> > Should I continue to use only “Hard" and "Again"?
> 
> Generally, I recommend sticking to the old rating habits because FSRS uses your old review history to learn your memory patterns and uses them to schedule new reviews.
> 
> But, using "Hard" instead of "Good" even when you recall the card easily can confuse FSRS because when you press "Hard", FSRS assumes that the card is difficult and increases its difficulty. This causes the intervals to grow more slowly.
> 
> > How will the shorter interval affect my retention?
> 
> It will tend to increase your retention but I feel that the intervals are too small. So, I think that you will mostly be wasting your time if you review them this frequently.
> 
> You have three options: (the last one is probably the most effective but also the most difficult)
> 
> * Keeping using "Hard" and set a lower desired retention (say, 0.85 or 0.80)
> * Start using "Good" and set a desired retention of, say, 0.90
> * Convert your old "Hard" ratings into "Good" and then re-optimize.
>   
>   * Do this ONLY IF you are sure that each time you pressed "Hard", you actually meant "Good" and you didn't use "Good" for the cards that were easier than those that you pressed "Hard" on.
>   * Before doing this, SYNC all your devices and create a BACKUP.
>   * On the Desktop version of Anki, press Ctrl+Shift+; (the control key, shift key, and semi-colon key at the same time) to open up the debug console.
>   * Paste the following code into it.
>   
>   ```
>   mw.col.db.execute("update revlog set ease=3 where ease=2")
>   mw.col.mod_schema(False)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * Press Ctrl + Enter to run the code. The message shown by Anki gives the impression that the code failed to execute. But, it does get executed.
>   * Close the Debug Console. Click check database and finally upload your collection to AnkiWeb at the next sync.
>   * Re-optimize your parameters and start using "Good" and "Again" from now onwards.

Thank you for providing detailed answers, I followed the last option, looks like everything is going well. Here are my new parameters:
0.4265, 0.8556, 2.4316, 7.9731, 5.6787, 1.0437, 0.5065, 0.0523, 1.1659, 0.2704, 0.3670, 2.5389, 0.0767, 0.2754, 1.6863, 0.2190, 4.0000

I preview the intervals :
<img width="1100" alt="new intervals" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/34d93e79-0675-443f-a24f-77019711029d">

Is that all right? I start using "Good" and "Again" from now onwards.

**Comment by aimator** [comment]
> > Should I continue to use only “Hard" and "Again"?
> 
> Generally, I recommend sticking to the old rating habits because FSRS uses your old review history to learn your memory patterns and uses them to schedule new reviews.
> 
> But, using "Hard" instead of "Good" even when you recall the card easily can confuse FSRS because when you press "Hard", FSRS assumes that the card is difficult and increases its difficulty. This causes the intervals to grow more slowly.
> 
> > How will the shorter interval affect my retention?
> 
> It will tend to increase your retention but I feel that the intervals are too small. So, I think that you will mostly be wasting your time if you review them this frequently.
> 
> You have three options: (the last one is probably the most effective but also the most difficult)
> 
> * Keeping using "Hard" and set a lower desired retention (say, 0.85 or 0.80)
> * Start using "Good" and set a desired retention of, say, 0.90
> * Convert your old "Hard" ratings into "Good" and then re-optimize.
>   
>   * Do this ONLY IF you are sure that each time you pressed "Hard", you actually meant "Good" and you didn't use "Good" for the cards that were easier than those that you pressed "Hard" on.
>   * Before doing this, SYNC all your devices and create a BACKUP.
>   * On the Desktop version of Anki, press Ctrl+Shift+; (the control key, shift key, and semi-colon key at the same time) to open up the debug console.
>   * Paste the following code into it.
>   
>   ```
>   mw.col.db.execute("update revlog set ease=3 where ease=2")
>   mw.col.mod_schema(False)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * Press Ctrl + Enter to run the code. The message shown by Anki gives the impression that the code failed to execute. But, it does get executed.
>   * Close the Debug Console. Click check database and finally upload your collection to AnkiWeb at the next sync.
>   * Re-optimize your parameters and start using "Good" and "Again" from now onwards.

Thank you for providing detailed answers, I followed the last option, looks like everything is going well. Here are my new parameters:
0.4265, 0.8556, 2.4316, 7.9731, 5.6787, 1.0437, 0.5065, 0.0523, 1.1659, 0.2704, 0.3670, 2.5389, 0.0767, 0.2754, 1.6863, 0.2190, 4.0000

I preview the intervals :
<img width="1100" alt="new intervals" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/db68202b-61c7-4939-828f-3c6f58d75312">

I've noticed that the “Again" intervals are shorter than before. Is that all right? I start using "Good" and "Again" from now onwards.

**Comment by aimator** [comment]
> > Should I continue to use only “Hard" and "Again"?
> 
> Generally, I recommend sticking to the old rating habits because FSRS uses your old review history to learn your memory patterns and uses them to schedule new reviews.
> 
> But, using "Hard" instead of "Good" even when you recall the card easily can confuse FSRS because when you press "Hard", FSRS assumes that the card is difficult and increases its difficulty. This causes the intervals to grow more slowly.
> 
> > How will the shorter interval affect my retention?
> 
> It will tend to increase your retention but I feel that the intervals are too small. So, I think that you will mostly be wasting your time if you review them this frequently.
> 
> You have three options: (the last one is probably the most effective but also the most difficult)
> 
> * Keeping using "Hard" and set a lower desired retention (say, 0.85 or 0.80)
> * Start using "Good" and set a desired retention of, say, 0.90
> * Convert your old "Hard" ratings into "Good" and then re-optimize.
>   
>   * Do this ONLY IF you are sure that each time you pressed "Hard", you actually meant "Good" and you didn't use "Good" for the cards that were easier than those that you pressed "Hard" on.
>   * Before doing this, SYNC all your devices and create a BACKUP.
>   * On the Desktop version of Anki, press Ctrl+Shift+; (the control key, shift key, and semi-colon key at the same time) to open up the debug console.
>   * Paste the following code into it.
>   
>   ```
>   mw.col.db.execute("update revlog set ease=3 where ease=2")
>   mw.col.mod_schema(False)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * Press Ctrl + Enter to run the code. The message shown by Anki gives the impression that the code failed to execute. But, it does get executed.
>   * Close the Debug Console. Click check database and finally upload your collection to AnkiWeb at the next sync.
>   * Re-optimize your parameters and start using "Good" and "Again" from now onwards.

Thank you for providing detailed answers, I followed the last option, looks like everything is going well. Here are my new parameters:
0.4265, 0.8556, 2.4316, 7.9731, 5.6787, 1.0437, 0.5065, 0.0523, 1.1659, 0.2704, 0.3670, 2.5389, 0.0767, 0.2754, 1.6863, 0.2190, 4.0000

I preview the intervals :
<img width="1100" alt="new intervals" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/d92b8b7d-c64f-4635-ad55-4bc857ca911f">

Is that all right? I start using "Good" and "Again" from now onwards.

**Comment by user1823** [comment]
I think that your true retention earlier was less than 90%.

To get a more accurate value of True Retention, select All history or 1 year in the Stats screen (after opening it while holding Shift).

**Comment by aimator** [comment]
> I think that your true retention earlier was less than 90%.
> 
> To get a more accurate value of True Retention, select All history or 1 year in the Stats screen (after opening it while holding Shift).
> 
> According to my guess, it would be close to 80%.

Here is my Stats screen, I select All history:

<img width="835" alt="true retention1" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/b1c27a73-3559-4d13-b63b-66e673f2e269">

<img width="835" alt="true retention2" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/16689877/ab5f4aed-5504-44d6-9907-4450046f8f84">

Are the parameters correct?

**Comment by user1823** [comment]
There is no easy way to see if the parameters are good or not. What's the RMSE, by the way? You can check it by clicking Evaluate, next to Optimize
 in the Deck Options.

But, they don't look strange to me. You have to decide for yourself: Are you comfortable with such short intervals (as seen in the previewer)? If not, you can decrease the desired retention slightly (to say, 0.88 or 0.86).

**Comment by aimator** [comment]
RMSE is 2.10%, Log loss is 0.4049.

Maybe I should try it for a while.

**Comment by user1823** [comment]
> RMSE is 2.10%

This is in the Good range. So, I think that the parameters should be fine.

Now, you just need to decide a value of desired retention based on your needs / expectations. So, I think that you can close this issue now.

**Comment by aimator** [comment]
OK, thanks for your help.
