### ISSUE TITLE
[Question] Does review records affecte the parameters when I reset old cards to new cards

### ISSUE THREAD

**Issue by aimator** [open-spaced-repetition/fsrs4anki#625]
I added about 5000 cards to Anki in Dec 2020 and spent about half a year (Dec 2020-May 2021) studying and reviewing them, but then I stopped, and 2 years later, in June 2023, I reset them to new cards (I had forgotten all of them) and restarted studying them again up to the present time.

By checking the details of these cards, I can see a lot of review records for 2020-2021, I would like to know if these review records will affecte the parameters when I use Anki's "Optimize FSRS Parameters"? Should I use the plugin to delete the 2020-2021 review records from these cards?

**Comment by L-M-Sherlock** [comment]
If you reset these cards to new cards, their previous review record will be filtered out in the optimization of parameters.

**Comment by aimator** [comment]
> If you reset these cards to new cards, their previous review record will be filtered out in the optimization of parameters.

Thanks for your help.

**Comment by aimator** [comment]
Thanks for your help.
