### ISSUE TITLE
[Feature Request] Change to difficulty on new cards 

### ISSUE THREAD

**Issue by Nightdkz** [open-spaced-repetition/fsrs4anki#627]
New card difficulty is always the first button you press. This makes me just press again every time. I had an idea for a potential change that would at least add a bit of variety to the difficulty of new cards and spread them better. 
Maybe this could even help with data collection. 
This would add better support for multiple learning steps within the same day too, but even a 1 learning step could benefit. 

Let's say new cards get D:83% for again, D:66% for hard, D:50% for good, D:33% for easy

If a card is reviewed 4 times within the first day, I would like a feature to make the difficulty the average. If I hit 1, 1, 2, 3 it would have the final difficulty of 70.5
I have a second possible distribution that accounts for the danger of setting the difficulty lower than it should be. 
If the first was a 1 (or maybe regardless of it) do the average of all but the last difficulty. This is a more conservative approach that considers the fact you had to press several buttons as a sign your actual difficulty is probably closer to the first than the last. Putting a higher weight on the first is also a possibility. In the example, it would be 77.3

New cards have a completely different ecology from review cards, and I imagine finding a good approach to be hard for the people developing it. This option doesn't have any data behind it, but it follows a simple assumption. if you are doing more than one or two reviews on the same card on the first day, the first button you press is, by definition, not the real difficulty. The real difficulty must be somewhere in between the buttons you did press. Anything in-between is likely better than just the first, especially if you discount the last.

**Comment by L-M-Sherlock** [comment]
Due to technical limitation, FSRS cannot take the short-term schedule into account. If a card is reviewed 4 times, the last 3 reviews are invisible to FSRS.

**Comment by L-M-Sherlock** [comment]
The helper add-on doesn't include FSRS model. It just calls the FSRS API which is built in Anki.
