### ISSUE TITLE
[Question] Not graduating cards the same day affects scheduling?

### ISSUE THREAD

**Issue by brishtibheja** [open-spaced-repetition/fsrs4anki#628]
Somewhere recently Expertium said FSRS would take into account the first review of a card *at a given day*. So if I don't graduate a learning/relearning card the same day it got lapsed/got into learning queue, can that affect scheduling for those cards, for better or for worse?

In my case, I sometimes have cards in learning for multiple days before I'm able to graduate them.

**Comment by L-M-Sherlock** [comment]
Yes, it affects scheduling in your case for better. The reason why FSRS only takes into account the first review of a card at a given day is that FSRS only considers long-term memory which is mainly related with sleeping.

**Comment by brishtibheja** [comment]
> for better.

That was unexpected. I thought learning steps should be less then 1 day so I may be worsening my scheduling. That was iirc a technical limitation probably. 

Thank you for your response.

**Comment by L-M-Sherlock** [comment]
I want to make it more clear: learning steps longer than 1 day is not recommended because it prevents FSRS controlling the long-term schedule as soon as possible. But FSRS could consider this case to alleviate this negative effect.
