### ISSUE TITLE
v3版本是否提升了与AnkiDroid的兼容性

### ISSUE THREAD

**Issue by hEzoooo** [open-spaced-repetition/fsrs4anki#63]
v3版本后，是不是在AnkiDroid复习然后在pc端重新调度就和在pc端复习完全一样

**Comment by L-M-Sherlock** [comment]
不太完全一致，js调度器是支持easyBonus和hard Interval的，重新调度插件并不支持。

**Comment by L-M-Sherlock** [comment]
现在支持 easyBonus 和 hardInterval 了
https://github.com/open-spaced-repetition/fsrs4anki-helper
