### ISSUE TITLE
[Question] I haven't used Anki for a while

### ISSUE THREAD

**Issue by eagleftw023** [open-spaced-repetition/fsrs4anki#633]
Do you have a doubt about using FSRS in Anki? If so, please post on https://forums.ankiweb.net/ instead.

This issue tracker is primarily intended for questions and suggestions about the algorithm itself, rather than its usage in Anki. In addition, a larger community can provide support on the Anki Forums.

Before posting, please read the following:

**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

hi

I haven't used Anki for a while, and I want to get back to using it. I have 1,400 cards due today. What is the best way to resume using the deck and complete the cards? Should I postpone a large number of cards, or what is the best approach?

**Comment by L-M-Sherlock** [comment]
It's irrelated to FSRS. If you just want to deal with the backlog, please see this tutorial: https://refold.la/roadmap/stage-1/c/srs-best-practices#Falling-Behind
