### ISSUE TITLE
[Question] Date change

### ISSUE THREAD

**Issue by JustJustArtem** [open-spaced-repetition/fsrs4anki#636]
Should I, when using the FSRS algorithm, change the date to the date it was last run. That is, if I ran it in 01.01, then when optimizing the data, should I restrict the data to start from 01.01? The algorithm performs optimization over the entire history of anki cards, so it will take into account the work with other parameters. That is, it may turn out that the history of the card 3,2,2,2,2,1,3,4,4,4,4.... where 3,2,2,2,2,2,1 is the work of the algorithm with Retention rate 90, and the rest with Retention rate 97, respectively, and the time intervals between them were different. I don't really understand how the algorithm works, so I'd be glad if you could help me!

(It could also be that 1 card worked only with one setting and didn't show up after changing it, because it had too long a break to repeat. How much would this all affect the algorithm?)

((Will the algorithm even work correctly, because when you connect it to Anki, it will look at the entire history of the card, which were with the previous settings?))

**Comment by aleksejrs** [comment]
I think the restriction is for when you change your rating or studying habits, so cards start to appear easier or harder to FSRS.

**Comment by L-M-Sherlock** [comment]
I don't know which date you mean. Could you provide a sreechshot?

**Comment by JustJustArtem** [comment]
> I don't know which date you mean. Could you provide a screenshot?

![изображение_2024-04-11_130341955](https://github.com/open-spaced-repetition/fsrs4anki/assets/166639603/6ac1858f-36d5-4c63-a86e-0601332a0b3a)
this one. in the code that is responsible for optimizing the "weights" for the cards

**Comment by L-M-Sherlock** [comment]
The date can be useful if you imported someone else's scheduling data, or have changed the way you use the answer buttons. If not, please keep it as the default.

**Comment by JustJustArtem** [comment]
> Retention rate

Ok, so the code will take into account the changes related to Retention rate and the deck settings themselves?

**Comment by JustJustArtem** [comment]
> It doesn't matter.
okey, thank you very much
