### ISSUE TITLE
[Question]: Questions regarding Optimisation

### ISSUE THREAD

**Issue by brishtibheja** [open-spaced-repetition/fsrs4anki#646]
Hey Sherlock, I have a few questions to ask,

1. Why is `-is:suspended` used in optimisation by default? Is that for a purpose? I tried removing that and it improved my RMSE(bins)/log loss. Is there a way to know whether to include suspended cards or no? For perspective, all my suspended cards come from a backlog I had a few months back, I thought it would be unwise to spend too much time in those so I simply suspended everything that was due.

2. What makes different parameters necessary? I imagine it is not a simple difference in difficulty for such differences exist even between cards of the same note. I struggle to arrive at a logical conclusion. On one hand I may think all my Japanese cards need a single preset in Anki. But I may also divide them into further categories. 

*Addendum:* I tried my hands at a little test to see how different parameters I get for the same deck and the same material. I study a writing deck for the 漢字検定試験 where the material is divided according to different levels (now that I think about it I sent you that file before). I tried creating a seperate preset for the highest levels and upon optimisation w1 changed from .4 to around .16; the next one from around .7 to .41; then 1.5 to 1.1; 2.7 to 3.1.

**Comment by L-M-Sherlock** [comment]
1. Please see this discussion: https://forums.ankiweb.net/t/anki-23-12-beta/37771/155
2. I haven't found out an objective method. Here is an initial experiment: https://github.com/open-spaced-repetition/fsrs-when-to-separate-presets

**Comment by brishtibheja** [comment]
> then that card is no longer representative of what kind of material the user is learning. 

But in my case, because these are cards I suspended *only because they were due*, using them shouldn't be an issue right? I do observe a reduction in RMSE(bins)/log loss but Evaluation then happens across all cards...
I tested one thing just now, I optimised my parameters after removing the `-is:suspended` part from search. My parameters have seemed to improve. Now I put the `-is:suspended` part back in to the search bar; do an Evaluation and I find my RMSE(bins)/log loss to have decreased.

I just want to confirm that this a valid way of evaluation right?

**Comment by L-M-Sherlock** [comment]
> But in my case, because these are cards I suspended _only because they were due_, using them shouldn't be an issue right?

For your case, it's better to include those suspended cards.

> Once again, I can just experiment with different levels of optimisation and check what comes up in the evaluation right?

Yes.
