### ISSUE TITLE
[Question] Should I use a low value produced by optimal retention (75%)？

### ISSUE THREAD

**Issue by siraben** [open-spaced-repetition/fsrs4anki#649]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I have been using FSRS for around 8 months now to study Mandarin vocabulary (> 1.5k words), but the target retention it has been giving me in both the Anki app and the notebook is 75%, according to the following workload graph. I have been setting my desired retention to 85%, since I feel that getting the local minimum that is in the model for best retention/workload is not possible when my workload graph looks monotonically increasing. Is this OK or should I actually be using the 75% value?

![output3](https://github.com/open-spaced-repetition/fsrs4anki/assets/8219659/fd86919d-f498-470a-9e82-fddc3548e353)

I also travel across time zones quite frequently, so I think it might be affecting the day cutoff used when calibrating the algorithm (as seen by the dips in the graphs below), if necessary I can provide my data and open a separate issue.

Calibration:
![output2](https://github.com/open-spaced-repetition/fsrs4anki/assets/8219659/0c6ae8b1-0af8-44fe-95e3-badf865febf4)

![output](https://github.com/open-spaced-repetition/fsrs4anki/assets/8219659/926b3960-a91d-4591-b5fa-b1343fa075d6)

**Comment by brishtibheja** [comment]
I'll not comment on how changing timezones can affect FSRS because that has been a concern for even me although I was thinking of changing `Next day starts at` setting a lot. I'll just say that 75% is normal. People have got a number around that. I have got one for me Kanji writing deck. Also, if you change the number of days you'll get results that differ by 2-3% so as a rule of thumb I use slightly higher values *just in case I'm spending more time to learn less*. Spending a bit more time to learn a bit more doesn't sound bad. If it were me I'd set desired retention at around 78-80%.

Note: I used to mess around my `Next day starts at` setting a lot while doing my Kanji writing deck.

**Comment by siraben** [comment]
@brishtibheja for me it looks like I hit that lower bound with difficult material that I tend to lapse a lot, such as Mandarin hanzi (similar difficulty to your Kanji deck probably). Also, the 75% comes from what looks like a golden section method used in the Brent algorithm for finding optimal retention. So it seems arbitrary, would it be even lower if the limit wasn't in place? Hm.

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/91b9fc70d69753fb86392f6d319ca8916473f243/src/fsrs_optimizer/fsrs_simulator.py#L233

**Comment by L-M-Sherlock** [comment]
You can use a low desired retention if you feel current workload to heavy for you.

**Comment by siraben** [comment]
@L-M-Sherlock but is 75% too low? If the intervals are too long could it cause more lapses?

**Comment by brishtibheja** [comment]
> @L-M-Sherlock but is 75% too low? If the intervals are too long could it cause more lapses?

Ideally, around 25% would be lapse. What that feature tells you is basically that the `knowledge acquisition rate` is maximum around that point. So you're spending less time learning something than you'll be with other retention rates. So even though you'll learn less you'll also spend much less time doing that learning.

**Comment by L-M-Sherlock** [comment]
> but is 75% too low? If the intervals are too long could it cause more lapses?

It's not too low. In MaiMemo app (a language learning app), the average retention is ~77%.
