### ISSUE TITLE
[Question] Can FSRS schedule intervals shorter than a day?

### ISSUE THREAD

**Issue by mattcoleanderson** [open-spaced-repetition/fsrs4anki#651]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I've noticed that cards with a stability of less than a day, are always scheduled for 1 day upon hitting Good.

This means that FSRS is ignoring the target retrievability when stability is less than a day. This tends to lead a spiral of never learning the card. Each day hitting again because it has been forgotten again.

Is FSRS not capable of scheduling intervals shorter than a day or must we rely on manual relearning/learning steps for these situations?

**Comment by L-M-Sherlock** [comment]
Anki cannot schedule intervals shorter than a day. Most SRS cannot, too. In theory, FSRS is capable for that.

**Comment by mattcoleanderson** [comment]
@L-M-Sherlock thanks for confirming this for me. Seems like an odd limitation though. Do you know more about why? I assume it's an opinionated choice rather than a true limitation.

**Comment by L-M-Sherlock** [comment]
Because Anki stores interval as an integer:

```
    ivl             integer not null,
      -- interval (used in SRS algorithm). Negative = seconds, positive = days
```

Source: https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#cards

**Comment by brishtibheja** [comment]
For more context, the lead developer, dae is against this feature. He doesn't think it's worthwhile to try to integrate this.

**Comment by mattcoleanderson** [comment]
@brishtibheja So it is an opinionated decision. I can see it being less useful in the previous schedulers. With the move toward ML models for scheduling, I would think the scheduler would be more affective with granular control of intervals. Do y'all agree?

**Comment by L-M-Sherlock** [comment]
Most users prefer to review at a specific time block, instead of the entire day, so granular control of intervals may be useless. And it's also annoying if I finished a lot of review in the morning and saw a pile of reviews again before sleeping.

**Comment by mattcoleanderson** [comment]
Fair point. However many users also make ample use of intraday new/relearning steps which also result in multiple reviews in the same day. My suggestion is to merely offload this to FSRS for automatic stability based intraday scheduling.

It would affectively be the same as new/learning steps because you would only have intraday intervals in the case of failures.

**Comment by L-M-Sherlock** [comment]
It requires a big refactor in the Anki's part. So I recommend submitting this feature request in https://forums.ankiweb.net/
