### ISSUE TITLE
[Question] What is the correct way to determine the card state (New, Learning, Review, Relearning) when implementing the algorythm separately from Anki?

### ISSUE THREAD

**Issue by Chebotarev-Alexey** [open-spaced-repetition/fsrs4anki#652]
What is the correct way to determine the card state (New, Learning, Review, Relearning) when implementing the algorythm separately from Anki? I need to know this state to use the optimizer later.

**Comment by Chebotarev-Alexey** [comment]
I just foun this and it made me less confused. But is there any place where I can read the same things as in this code but in documentation?
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/66257265/a82f7cf5-8730-4215-a56d-a9a1918f2af6)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/66257265/6c03a7b9-ec90-4837-9cac-195cac2419c6)

**Comment by L-M-Sherlock** [comment]
You can refer to ts-fsrs-demo: https://github.com/ishiko732/ts-fsrs-demo

Here is a helpful chart:

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/5c69fa2e-ec72-40ac-9780-a925ad2a29e6)
