### ISSUE TITLE
[Question] Wiki—post-lapse stability example parameter inconsistency?

### ISSUE THREAD

**Issue by djliden** [open-spaced-repetition/fsrs4anki#662]
Do you have a doubt about using FSRS in Anki? If so, please post on https://forums.ankiweb.net/ instead.

This issue tracker is primarily intended for questions and suggestions about the algorithm itself, rather than its usage in Anki. In addition, a larger community can provide support on the Anki Forums.

Before posting, please read the following:

**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

**Question**

The post-lapse stability example under the FSRS v4 header appears to use the default parameters from the FSRS v3 section, not those from the v4 section.

e.g. $S^\prime_f(S=100) = 2\cdot 2^{-0.2} \cdot ((100+1)^{0.2}-1) \cdot e^{1(1-0.9)} \approx 3$

corresponds to the params in this list from v3: `var w = [1, 1, 5, -1, -1, 0.1, 1.5, -0.2, 0.8, 2, -0.2, 0.2, 1];`

where I'd have expected to use w_11–w_14 = `2.18, 0.05, 0.34, 1.26`.

Is this an error in the wiki, or am I understanding this incorrectly? Thank you!

**Comment by L-M-Sherlock** [comment]
The parameters are selected arbitrarily.
