### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sineptic** [open-spaced-repetition/fsrs4anki#666]
**Research**

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I don't use anki.
Why it need retrievability to calculate new stability (in 4 version)? and why it needed second time to calculate next_review if it already used?

**Comment by L-M-Sherlock** [comment]
The user may not review the card in the scheduled date.

**Comment by sineptic** [comment]
but new stability calculated when user complete card. algorithm use predicted R at this moment?

**Comment by L-M-Sherlock** [comment]
Yes. FSRS is based on DSR model. You can read this for details: https://supermemo.guru/wiki/SuperMemo_Algorithm:_30-year-long_labor#Increase_in_memory_stability_with_rehearsal

**Comment by YukiNagat0** [comment]
1
