### ISSUE TITLE
[BUG] Seeing different intervals for the same card on different computers.

### ISSUE THREAD

**Issue by Vitorvlv** [open-spaced-repetition/fsrs4anki#67]
**Describe the bug**
Hi! I'm seeing different intervals for the same card on anki on different computers. Both are synced correctly, using the same settings.

**Expected behavior**
I believe they should present the same intervals, right?

**Screenshots**
On my pc
![Captura de tela de 2022-10-10 01-20-02](https://user-images.githubusercontent.com/26132870/194798889-7b44dcd7-8ed8-465a-8469-6bd573ba85c9.png)

On my notebook
![Captura de tela de 2022-10-10 01-19-09](https://user-images.githubusercontent.com/26132870/194798938-730fcc56-274b-4a0e-a04e-ba5054fa8e88.png)

**Environment**
 - Anki version: 2.1.55
 - OS: Fedora and Manjaro
 - Scheduler version: 3.20
 - Optimizer version: 3.20

**Comment by L-M-Sherlock** [comment]
So weird. I don't have two PC to test it. Could you use the Anki Web inspector?

**Comment by Vitorvlv** [comment]
I also believe this is due to fuzz. I'll close the issue for now, unless L-M-Sherlock thinks this merits a more thorough investigation.
