### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#676]
Hi. I have a few questions. If I only use Anki on my PC, do I need an add-on? If I take a break, will it affect the future reviews and intervals? For example, can I take a break once a month and then do my reviews in one day? Will it work properly?

**Comment by L-M-Sherlock** [comment]
1. not need
2. yes, it will

**Comment by L-M-Sherlock** [comment]
Yes. When you leave the field empty, Anki will autofill it with preset: "Preset name".
