### ISSUE TITLE
[Question] Very long initial intervals when using multiple card types

### ISSUE THREAD

**Issue by janispritzkau** [open-spaced-repetition/fsrs4anki#677]
Before posting, please read the following:

**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

In one of my vocabulary decks I have two card types, one for recognition and one for reproduction (fill in the blank). I have been using FSRS pretty much from the beginning (4 months). Since I added the other card type, the initial interval has increased significantly, to the point that I had to manually adjust the first 4 parameters to prevent the interval from going straight to 3-4 months when pressing good or easy. I suspect the problem is that the second card type is usually shown shortly after the first one, and so there is a knowledge transfer that FSRS is not aware of.

I've been trying FSRS v5 for a few days, it seems to have exaggerated the problem even more. I wonder if I am using it wrong or if this is just something that has not been considered yet. These are the parameters (v4.5) which I get when optimizing on the entire history:

```
0.1199, 4.0416, 47.4006, 47.4006, 5.2316, 1.0248, 1.1100, 0.0237, 1.5355, 0.0861, 0.8713, 2.1731, 0.1224, 0.4543, 1.7320, 0.0507, 4.5753
```

It gets slightly worse if I only optimize on the last 3 months:

```
0.1165, 7.4696, 56.2787, 56.2787, 5.3593, 1.1345, 1.0915, 0.0374, 1.4406, 0.2686, 0.8374, 2.1669, 0.1097, 0.4095, 1.8324, 0.0323, 4.0354
```

Additionally, I use "again", "hard", and "good" pretty consistently. However, I tend to choose between "good" and "easy" a bit arbitrarily, to nudge the next interval in a certain direction. I'll be happy to answer any follow-up questions.

**Comment by L-M-Sherlock** [comment]
I recommend using two decks with different presets: one for recognition, one for reproduction. The initial interval will be longer in your recognition deck, and shorter in your reproduction deck.

**Comment by janispritzkau** [comment]
I'm gonna try that. Are there things to consider when pulling in new cards? Like

- Which card type should come first? Or randomize?
- Intentionally keeping a gap between learned notes of one card type? (To avoid the other card type coming up the next day after burying.)
