### ISSUE TITLE
这样是不是可以使用v5了？

### ISSUE THREAD

**Issue by keen0309** [open-spaced-repetition/fsrs4anki#681]
![8b3fdd281ce3591e4985850aae890274](https://github.com/user-attachments/assets/4176aac6-4539-47d7-9ce3-99a5d2a90214)
填好是不是就可以用了

**Comment by L-M-Sherlock** [comment]
并非如此。目前使用 v5 只有两种方法：

1. 拉取 Anki 源代码在本机编译
2. 使用自定义排程脚本

以上两种方法都不建议对代码不了解的用户尝试。请等待 Anki 正式发布下个版本。
