### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kurkasr** [open-spaced-repetition/fsrs4anki#682]
Hi. How can I use Anki Desktop and AnkiDroid (Android) properly? Where can I find a manual? Do I need an add-on? Do I need to reschedule my cards?

**Comment by L-M-Sherlock** [comment]
Yes. AnkiDroid has supported FSRS in 2.17+.

The manual: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md

Nope.

It's unnecessary.
