### ISSUE TITLE
[Question] Does formula for Retrievability and next interval changes from FSRS v4 and FSRS v5 ?

### ISSUE THREAD

**Issue by MrAnyx** [open-spaced-repetition/fsrs4anki#683]
**Question**

I was using FSRS v4 for a personal project and i implemented successfully and recently, i saw that the version 4.5 and version 5 of the FSRS algorithm was released and i wanted to update my project.

In the version 4, the formula for retrievability(`R`), the next interval (`I`), new difficulty value `D'`, the `DECAY` and `FACTOR` was explained but not for version 5. Is it because it's same formula as for the version 4.5 or is it something different ?

**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Comment by Expertium** [comment]
Same formula.

**Comment by MrAnyx** [comment]
Ok, great, thanks for your quick answer :+1:
