### ISSUE TITLE
[Question] Unexpected Stability and Difficulty for Overdue Mature Cards Remembered after Long Hiatus

### ISSUE THREAD

**Issue by slang19** [open-spaced-repetition/fsrs4anki#691]
Do you have a doubt about using FSRS in Anki? If so, please post on https://forums.ankiweb.net/ instead.

This issue tracker is primarily intended for questions and suggestions about the algorithm itself, rather than its usage in Anki. In addition, a larger community can provide support on the Anki Forums.

Before posting, please read the following:

**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Hello,

Both the Wiki and question #579 note that the algorithm should take into account relative overdueness. But I'm seeing some pretty extreme values in my Stability, Difficulty, and Intervals for cards I *did* remembered after coming back from a year long hiatus. Why is it pitching this low? (examples below)

The only things I can think of are: a) my parameters for this particular content are pretty 'bad' (as in its difficult for me to remember) so maybe its hitting some kind of pre-predicted limit. and b) I also haven't taken a hiatus this long before so maybe it lacks data to make an accurate projection at extreme overdue intervals like this.

I saw this in the wiki: "In FSRS, a delay in reviewing (i.e., overdue reviews) affects the next interval as follows:
As the delay increases, retention (R) decreases. If the review was successful, the subsequent stability (S) would be higher, according to point 3 above. However, instead of increasing linearly with the delay like the SM-2/Anki algorithm, the subsequent stability converges to an upper limit, which depends on your FSRS parameters." Which leads me to think (a) is the main contributer. But I have a hard time believing my parameters are so bad that it would give me a 1.7m interval for a mature card I remembered after a 12m.

**--Settings--**
T2 (verbs + adj vocab) deck parameters = [0.0846, 0.2431, 0.6448, 2.3990, 5.6223, 1.2298, 1.2385, 0.0060, 1.3181, 0.3935, 0.7168, 2.1524, 0.0216, 0.2786, 1.5440, 0.2424, 2.3609]
85% desired retention
Optimizer claims N = 4,055 reviews

T1 (all other vocab) deck parameters = [0.7278, 0.7744, 0.8499, 2.3810, 5.5973, 1.3540, 0.7974, 0.1037, 1.2126, 0.3526, 0.6106, 2.2320, 0.0149, 0.4003, 1.6091, 0.0120, 2.2626]
87% desired retention
Optimizer claims N = 6,763 reviews

- Hiatus was 1 year. Currently about a month into clearing the large backlog, I suspended all cards and am slowly adding them back in from greatest to lowest interval.
- Can't find any files to timestamp when but I has been using FSRS for while before my hiatus.
- Answer methodology I've used from pretty much the start: <6s Easy, <15s Good, <30s Hard, else Again

**--Example of Problem Cards--**
T2 card 위험하다 - Mature card, one miss while learning, (2 prev hards, 1 prev easy). I remembered it after an entire year (at hard), which looking at the data, I presume was longer than the intended interval. (I find the interval Anki reports in the log isn't accurate so not sure what the previous interval actually was). Yet D = 99%, S = 28d, IVL = 1.7m. Interval of 1.7m on a card I remembered after a 12m? :(
![image](https://github.com/user-attachments/assets/ff9b3e4f-19ef-4b14-91bb-6575ef909f6b)

T2 card 불가능하다 - Mature card, one misses (entirely 3 history otherwise). Remembered after a year at *good* and D = 78% S = 2m, IVL = 3.5m. Again really low interval for a 13m interval I rated as 'good'. And it made the difficulty go up too; after I out performed its exception for that card by a huge margin, shouldn't the difficulty go down (log says was 71% previously)?
<img width="718" alt="image" src="https://github.com/user-attachments/assets/ee5f32f2-87fd-4cd0-ad53-70c9cc7f7c35">

T1 card (easier deck) 아홉 - mature card w 1 previous lapse, answered hard after a year. Only has D = 62% and S = 26d, IVL = 1.33. Difficulty seems more in line with what I'd expect, but interval of 1.3m is still a super low.
![image](https://github.com/user-attachments/assets/2692ed5b-434e-4c65-aca4-20ce56d4e3e1)

T2 card 쓰다 - Mature card, with perfect 3 history otherwise. Missed on overdue review. D = 72% S = new reviews since lapse so not sure at the time but current = 15d, IVL = 24d. Interval expected to be low bc of the miss. However, cards that are straight 3s have D = 50% in my deck, yet one missed review that was a year late (expected to miss at that point) makes the difficulty jump 22%? And answering 3 a month later at the expected review date made D jump to 79%? I get why it would effect the current stability but why would that increase the difficulty?
<img width="722" alt="image" src="https://github.com/user-attachments/assets/29f9315a-48e2-4cbe-91d0-6953391424b8">

**--Comparison Cards with (more) Expected Values--**
vs T2 card 기대하다 - mature, no misses, similar learned date as 1st two. Remembered after a year at *hard* and D = 65% S = 2.8m, IVL = 4.9m.
<img width="721" alt="image" src="https://github.com/user-attachments/assets/d78456dc-9e10-4334-9e60-34e969ae83cd">

vs T2 card 마르다 - mature, no misses, similar learned date as 1st two. Remembered after a year at *good* and D = 65% S = 4m, IVL = 7m.
<img width="723" alt="image" src="https://github.com/user-attachments/assets/88050e09-d0a1-4688-82cc-d96207421ca1">

**Comment by brishtibheja** [comment]
> But I'm seeing some pretty extreme values in my Stability, Difficulty, and Intervals for cards I did remembered after coming back from a year long hiatus. Why is it pitching this low?

From someone else:

> In FSRS, the next stability of overdue cards doesn't increase linearly with the delay like the SM-2/Anki algorithm. Rather, the next stability converges to an upper limit, which depends on your FSRS parameters.

**Comment by L-M-Sherlock** [comment]
What's your true retention? If it's lower than the desired retention, I think it could explain most of those issues.

For difficulty, the overdueness doesn't affect difficulty. If you press again or hard, the difficulty always increases.

**Comment by slang19** [comment]
Since I'm adding in very overdue cards everyday, its incredibly low at the moment → 63% overall the past month, 50% for mature cards (via the 'true retention' add on). I usually keep desired retention set to the mid 80s so thats a pretty big gap right now. 

Thank you for your insight! If I'm interpreting this correctly, does that mean the intervals for a card is in some part calculated by the retention gap at that moment (desired-current), meaning it will rectify itself once my true retention starts to even out once I get all my cards back in?

**Comment by L-M-Sherlock** [comment]
I mean the true retention before you switch to FSRS. What's you true retention when you used SM-2? If it's lower than 85%, the current interval scheduled by FSRS is intended.

As for the interval of 1.7m on a card you remembered after a 12m, I find that you press `hard` in that card. So the interval is also intended.
