### ISSUE TITLE
我尝试使用FSRS4Anki v5.0.2 Scheduler Qt6排程到anki中出现参数疑问

### ISSUE THREAD

**Issue by jjy1000** [open-spaced-repetition/fsrs4anki#693]
Do you have a doubt about using FSRS in Anki? If so, please post on https://forums.ankiweb.net/ instead.

This issue tracker is primarily intended for questions and suggestions about the algorithm itself, rather than its usage in Anki. In addition, a larger community can provide support on the Anki Forums.

Before posting, please read the following:

**Research**

*Enter an [x] character to confirm the points below:*

- [ ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#faq) and could not find an answer to my question
- [ ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ ] I have searched for similar existing questions here

**Question**
- 我尝试将我的anki中FSRS参数填入到FSRS4Anki v5.0.2 Scheduler Qt6中，但是我的参数只有17个和FSRS4Anki v5.0.2 Scheduler Qt6的w数值有19个值？
- 如果我仍然填入17个参数，原代码中function next_short_term_stability(s, rating) {
  return +(s * Math.exp(w[17] * (rating - 3 + w[18]))).toFixed(2);
}
是否要移除了w[17] 和 w[18] 的引用？
function next_short_term_stability(s, rating) {
  // 保持短期稳定性不变
  return +s.toFixed(2);
}

望大佬解答一下🙏

**Comment by L-M-Sherlock** [comment]
因为 FSRS4Anki v5.0.2 Scheduler 用的是 FSRS-5 算法，Anki 目前尚未更新到该版本，所以你从 Anki FSRS 参数复制出来的还是 FSRS-4.5 的参数。两者是不兼容的。

**Comment by jjy1000** [comment]
> 因为 FSRS4Anki v5.0.2 Scheduler 用的是 FSRS-5 算法，Anki 目前尚未更新到该版本，所以你从 Anki FSRS 参数复制出来的还是 FSRS-4.5 的参数。两者是不兼容的。

请问我需要用优化器进行数据优化吗？我并没有完全搞明白这个18个参数代表什么，在Visualize your FSRS schedule打开倒是看见18个参数，我是否可以直接填入里面呢？

**Comment by ishiko732** [comment]
> 在Visualize your FSRS schedule打开倒是看见18个参数

现在https://open-spaced-repetition.github.io/anki_fsrs_visualizer/ 已更新，使用的也是FSRS-5算法；在Visualizer填入17个参数会触发ts-fsrs自动填充[0.0, 0.0]到`w[17..18]`
