### ISSUE TITLE
Large discrepancy in interval between native and custom scheduling version of FSRS

### ISSUE THREAD

**Issue by jcznk** [open-spaced-repetition/fsrs4anki#701]
Hi! I am not sure if the following behavior is expected. I am using Anki 24.10 beta 4. 

FSRS parameters: `2.8481, 4.8042, 6.3959, 35.0206, 9.2963, 0.7195, 1.3503, 0.0207, 1.5680, 0.2701, 1.0538, 1.8377, 0.1651, 0.3927, 1.2660, 0.0553, 5.6456, 0.4597, 0.7716`
Desired retention: `87`

Using the native implementation of FSRS 5, pressing "Good" would yield a 2.5 months interval for a card I last reviewed in January and was due in August. I recall that FSRS 4 often behaved in a similar way.
<img src="https://github.com/user-attachments/assets/459a9b18-4346-440b-b682-36ed3780943a" height="500">

Using the javascript version of FSRS ([fsrs4anki_scheduler.js](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js)), with the same parameters and desired retention, I get these intervals, which I personally find more reasonable:
<img src="https://github.com/user-attachments/assets/3f6ea8cd-d68a-4aa5-8bfb-882b45700f1b" height="530">

**Comment by Expertium** [comment]
I don't see any difference in intervals on these two pictures?

**Comment by jcznk** [comment]
The card is yet to be rated. The intervals I am referring to are the ones above the Again/Hard/Good/Easy buttons.

**Comment by brishtibheja** [comment]
The Javascript version was last updated 3 months ago.

**Comment by jcznk** [comment]
True. However, I find the current behavior of the native version of FSRS 5 a bit strange and, personally, undesirable, so I’m left wondering whether this is actually expected.

**Comment by L-M-Sherlock** [comment]
[fsrs4anki_scheduler.js](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js) is based on custom data. In your case, the card doesn't have custom data, so the js version converted the card's interval and ease factor to custom data:

https://github.com/open-spaced-repetition/fsrs4anki/blob/aee45cadd4cab3fb6fec068b08867679369d1af8/fsrs4anki_scheduler.js#L244-L257

So the result is different.
