### ISSUE TITLE
[Question] Will release candidate 24.10 implement load balancing automatically?

### ISSUE THREAD

**Issue by ratman-codes** [open-spaced-repetition/fsrs4anki#704]
Right now, I have to manually "reschedule all cards reviewed in past X days" (I use 3 for X) using fsrs-helper to get load balancing.

Will passive load balancing be added to release candidate? Is this an upcoming feature? Just curious if this is on the roadmap.

Thank you for all the hard work.

**Comment by L-M-Sherlock** [comment]
Yes. For details, please see:
- https://github.com/ankitects/anki/pull/3230
