### ISSUE TITLE
FSRS and reviewing ahead of schedule

### ISSUE THREAD

**Issue by jcznk** [open-spaced-repetition/fsrs4anki#707]
I noticed that if I use a filtered deck (rescheduling enabled) to perform multiple same day reviews that are ahead of schedule, FSRS-5 intervals grow very fast. 
I am using Anki 24.11 rc.

SM-2:

![image](https://github.com/user-attachments/assets/6493cf3b-fe9f-4f13-9e0d-1c7cec31b8f1)

Another card, using FSRS-5 (default parameters, 90% desired retention)

![image](https://github.com/user-attachments/assets/bdb8cf71-c667-455e-b7fe-358d8e3c47c5)

**Comment by L-M-Sherlock** [comment]
Because FSRS-5 takes the same-day reviews into account.

**Comment by jcznk** [comment]
I understand that. What I'm wondering is if the behavior I described regarding "not yet due" cards is actually desirable. 

The one above is an extreme example for testing purposes. My personal use case is that I would like to use a filtered deck to review ~25 random cards each day, independently of their due state, in addition to scheduled reviews.  
This is to maximize interleaving, and to counteract the fact that sometimes I am able to guess the answer to a card based on my knowledge of which cards might or might not be due. 

I would like to enable rescheduling for this filtered deck so that my answers will influence the normal scheduling. E.g., if I fail a card, I definitely want to see it sooner than previously scheduled. I would also like to give a slight boost to cards that I answer correctly. But, given the above testing, I'm worried this will lead to intervals that grow too fast.

Admittedly, I'm not a FSRS expert and my testing is limited to the example above. Is there any "dampening" to the growth of the interval/change of memory state when a card is reviewed ahead of schedule?

**Comment by jcznk** [comment]
I'm personally mostly concerned about very mature cards (>1 year interval). Especially since there is a good chance they will come up 2+ times in the filtered deck before their due date is reached.
Sticking to the above example, going from 2.8 months to 4.27 months, or from 4.27 to 5.67 months, seems to me like a pretty significant leap for a "same day" review.

**Comment by L-M-Sherlock** [comment]
Ideally, multiple reviews of the same cards only happens when you learn a new card or forget a card. And in these cases, the number of same-day reviews are limited.

For your case, I don't recommend review the same card in the same day too many times. If you insist doing that, please set these two parameters to zeros:

<img width="648" alt="image" src="https://github.com/user-attachments/assets/ef62e75b-c3b8-42d4-82a7-7e93f3f29617">

**Comment by L-M-Sherlock** [comment]
> The focus is actually not on "same-day" reviews but on all reviews performed before the actual due date. Same-day reviews are simply an extreme example of this.

So it's not a specific issue related to FSRS-5, right?

For reviews performed before the actual due data, the interval increases slower:

<img width="992" alt="image" src="https://github.com/user-attachments/assets/ad5cc825-f50c-4e01-99c8-63b188eaf0ef">

https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm

**Comment by L-M-Sherlock** [comment]
> It also seems that same-day reviews might yield longer intervals compared to reviews spread across multiple days, as the stability growth is not constrained by R.

Yes, because I haven't figured out the short-term memory model to deal with it. And Anki also cannot let FSRS know how long the time elapses since the last same-day review. So I uses different formula to deal with the same-day reviews and other reviews.

> By the way, would it make sense to use the same-day review formula for stability only for "learning" and "re-learning" cards, and apply the standard formula for "review" cards, even when they are reviewed multiple times in a single day?

FSRS cannot distinguish whether a review is from in "learning" and "re-learning" card or a "review" card. It only knows the intervals and ratings.

**Comment by Expertium** [comment]
Yes, this is one of the three edge cases where this formula doesn't work well.
![image](https://github.com/user-attachments/assets/fae5fb1c-d563-4084-8bf7-250662bc92e4)

1) If the user had one or two learning steps, but then switched to something like `30s 2m 5m 15m 30m 1h 2h 4h 6h 8h`, then his stability will be overestimated.
2) If the user uses a filtered deck to do an unlimited number of same-day reviews (your case).
3) If the user is in a Good - Again - Good - Again loop (during the same day), stability will either explode or fall to near 0. This is possible if his learning steps are, for example, `10m 30m`.

There is no solution as of today, so all 3 of these will remain troublesome for the foreseeable future.

**Comment by jcznk** [comment]
Thank you both for the explanation.

I’m curious why FSRS cannot distinguish between learn/re-learn and review cards. Is there anywhere I can read more about this?

**Comment by L-M-Sherlock** [comment]
> I’m curious why FSRS cannot distinguish between learn/re-learn and review cards. Is there anywhere I can read more about this?

Because I don't want to consider card types in FSRS. FSRS is based on DSR model, where the card type doesn't have its place.

**Comment by L-M-Sherlock** [comment]
It's a philosophy choice. Many SRS apps don't have the concept of card type, so I don't want to support it in FSRS.
