### ISSUE TITLE
Add a check to ensure that hard intervals cannot be longer than good intervals.

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#71]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Sometimes I see cards with hard intervals longer than good intervals. However, it doesn't seem like a problem with FSRS itself, but rather a problem of how it interacts with user-specified learning steps. If one of the learning steps is greater than 1 day this sometimes happens (I don't have a screenshot right now, unfortunately), so for now I have to set all my learning steps across almost all decks to 1 day to avoid this.

**Describe the solution you'd like**
Add something like this to the scheduler:
```
if NewInterval.hard > NewInterval.good:
    NewInterval.hard = NewInterval.good
else:
    NewInterval.hard
```

**Comment by L-M-Sherlock** [comment]
FSRS didn't deal with the learning steps. And I recommend not to use steps bigger than one day.

**Comment by L-M-Sherlock** [comment]
By the way, why do people use learning steps that are longer than one day? Could you tell me the reason?

**Comment by Expertium** [comment]
> By the way, why do people use learning steps that are longer than one day? Could you tell me the reason?

It depends on how difficult in your opinion the material is. If it's easy then why not make learning steps longer?

**Comment by L-M-Sherlock** [comment]
> It depends on how difficult in your opinion the material is. If it's easy then why not make learning steps longer?

Why not skip to the review stage earlier with a longer graduate interval? I think they are similar.

**Comment by Expertium** [comment]
That's a good point, I haven't thought about that.

So anyway, will you implement the fix I suggested above, if possible?

**Comment by L-M-Sherlock** [comment]
> So anyway, will you implement the fix I suggested above, if possible?

I found that the built-in schedule also has this problem, if you set a leaning step longer than graduate interval or easy interval. So I don't think it's a bug for FSRS.

**Comment by kuroahna** [comment]
> It depends on how difficult in your opinion the material is. If it's easy then why not make learning steps longer?
This makes no sense lmao. If it's easy, then why not just quickly graduate it and move it out of the learning stage? You're just doing unnecessary reviews. Why make more work for yourself?

**Comment by galantra** [comment]
> By the way, why do people use learning steps that are longer than one day? Could you tell me the reason?

Here is one possible explanation:

https://eshapard.github.io/anki/what-anki-learning-steps-to-use.html

https://eshapard.github.io/anki/anki-learning-steps-with-feedback.html
