### ISSUE TITLE
[Question] Does FSRS bias weight of optimization curve to recent reviews?

### ISSUE THREAD

**Issue by ratman-codes** [open-spaced-repetition/fsrs4anki#714]
I have decks with hundreds of thousands of reviews. that are 5+ years old.  Due to how flawed ankis base algorithm was, my real retrievability was probably only around 50% even though I had review intervals of 1-3+ years.

Before using FSRS my typical retention was around 80% when reviewing. Then with FSRS, I did a one time optimize and it shuffled basically all my cards into my review (say 2000 of them) within a month or two's time. I failed a ton of cards over a short period of time and the algorithm sorted me out. Now with FSRS I am achieving a target 90% and like it. However, during that transition period I failed tons of cards as mentioned.

I am wondering, if I now start to see success with cards maintaining 90%, will the optimization algorithm primarily look at my most recent reviews to start determing a new curve? I assume yes, but not sure how it works. I imagine that if it didnt, it wouldnt be able to give an accurate reading since I have so many years of old history that would throw it off.

**Comment by L-M-Sherlock** [comment]
FSRS treats all reviews equally.  To assign more weights on recent reviews is still in my todo list:

- https://github.com/open-spaced-repetition/fsrs-rs/issues/256
