### ISSUE TITLE
Wiki - The Optimal Retention: 'learning span' is not defined

### ISSUE THREAD

**Issue by joshdavham** [open-spaced-repetition/fsrs4anki#715]
I'm reading this repo's wiki article on [The Optimal Retention](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Optimal-Retention) and it talks about something called the 'learning span' and I'm not sure what this means.

What is the 'learning span'? And could we get a definition in the article?

Also, how do I suggest changes to the wiki? I haven't found a way to fork, make changes and open a pr like most things on github. I guess wikis are different? I'm also not seeing any kind of edit button.

**Comment by L-M-Sherlock** [comment]
The learning span is the number of days to simulate.

**Comment by joshdavham** [comment]
> I can give you push access.

Sure, sounds good.

**Comment by L-M-Sherlock** [comment]
Added

**Comment by joshdavham** [comment]
Sick. Thanks
