### ISSUE TITLE
[BUG] Latest fsrs4anki helper error

### ISSUE THREAD

**Issue by Willz7** [open-spaced-repetition/fsrs4anki#74]
**Describe the bug**
I updated the fsrs4anki helper to the latest version, and then I got an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Updated fsrs4anki helper to the latest version
2. updated an individual deck 
3. Tools -> Reschedule all cards 
4. error

**Expected behaviour**
Should update the entire collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/5053219/195673200-26928024-55d2-4f4f-be07-fcaece80d28e.png)

**Environment**
 - Anki version: [e.g. 2.1.55]
 - OS: Window 10
 - Scheduler version: [v3.4.0]
 - Optimizer version: [v3.2.1]
 - Simulator version: [v3.3.2]

**Comment by L-M-Sherlock** [comment]
I update it now. Could you try again?

**Comment by Willz7** [comment]
> I update it now. Could you try again?

I tried the new update and it is working like normal!

Thank you for fixing the bug!
