### ISSUE TITLE
执行FSRS4Anki v3.5.0 Optimizer的1.2步骤时出现"KeyError"[BUG]

### ISSUE THREAD

**Issue by 5mdld** [open-spaced-repetition/fsrs4anki#78]
**Describe the bug**
使用Anki v2.1.55 beta 2导出的.apkg文件（已经勾选了兼容旧版本），
执行FSRS4Anki v3.5.0 Optimizer的1.2步骤时出现"KeyError"
如有需要，可以邮件发您使用的.apkg文件

KeyError                                  Traceback (most recent call last)
[<ipython-input-61-c88f9fa42baf>](https://localhost:8080/#) in <module>
     66     return group
     67 
---> 68 df = df.groupby(by=['r_history', 'delta_t']).progress_apply(cal_retention)
     69 print("Retention calculated.")
     70 df = df.drop(columns=['id', 'cid', 'usn', 'ivl', 'last_lvl', 'factor', 'time', 'type', 'create_date', 'review_date', 'real_days', 'r', 't_history'])

9 frames
[/usr/local/lib/python3.7/dist-packages/tqdm/std.py](https://localhost:8080/#) in inner(df, func, *args, **kwargs)
    812                 # on the df using our wrapper (which provides bar updating)
    813                 try:
--> 814                     return getattr(df, df_function)(wrapper, **kwargs)
    815                 finally:
    816                     t.close()

[/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py](https://localhost:8080/#) in apply(self, func, *args, **kwargs)
   1273         with option_context("mode.chained_assignment", None):
   1274             try:
-> 1275                 result = self._python_apply_general(f, self._selected_obj)
   1276             except TypeError:
   1277                 # gh-20949

[/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py](https://localhost:8080/#) in _python_apply_general(self, f, data)
   1307             data after applying f
   1308         """
-> 1309         keys, values, mutated = self.grouper.apply(f, data, self.axis)
   1310 
   1311         return self._wrap_applied_output(

[/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/ops.py](https://localhost:8080/#) in apply(self, f, data, axis)
    850             # group might be modified
    851             group_axes = group.axes
--> 852             res = f(group)
    853             if not _is_indexed_like(res, group_axes, axis):
    854                 mutated = True

[/usr/local/lib/python3.7/dist-packages/tqdm/std.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    807                     # take a fast or slow code path; so stop when t.total==t.n
    808                     t.update(n=1 if not t.total or t.n < t.total else 0)
--> 809                     return func(*args, **kwargs)
    810 
    811                 # Apply the provided function (in **kwargs)

[<ipython-input-61-c88f9fa42baf>](https://localhost:8080/#) in cal_retention(group)
     62 
     63 def cal_retention(group: pd.DataFrame) -> pd.DataFrame:
---> 64     group['retention'] = round(group['r'].map(lambda x: {1: 0, 2: 1, 3: 1, 4: 1}[x]).mean(), 4)
     65     group['total_cnt'] = group.shape[0]
     66     return group

[/usr/local/lib/python3.7/dist-packages/pandas/core/series.py](https://localhost:8080/#) in map(self, arg, na_action)
   4159         dtype: object
   4160         """
-> 4161         new_values = super()._map_values(arg, na_action=na_action)
   4162         return self._constructor(new_values, index=self.index).__finalize__(
   4163             self, method="map"

[/usr/local/lib/python3.7/dist-packages/pandas/core/base.py](https://localhost:8080/#) in _map_values(self, mapper, na_action)
    868 
    869         # mapper is a function
--> 870         new_values = map_f(values, mapper)
    871 
    872         return new_values

/usr/local/lib/python3.7/dist-packages/pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

[<ipython-input-61-c88f9fa42baf>](https://localhost:8080/#) in <lambda>(x)
     62 
     63 def cal_retention(group: pd.DataFrame) -> pd.DataFrame:
---> 64     group['retention'] = round(group['r'].map(lambda x: {1: 0, 2: 1, 3: 1, 4: 1}[x]).mean(), 4)
     65     group['total_cnt'] = group.shape[0]
     66     return group

KeyError: 0

**Environment**
 - Anki version: [2.1.55 beta 2]
 - OS: [macOS 13 beta (22A5373b)]

**Comment by 5mdld** [comment]
感觉好像文件太大就会出现该问题？选取了部分卡（两千个左右）打包执行的时候一切正常

**Comment by L-M-Sherlock** [comment]
看起来是异常数据，理论上反馈只有 1 2 3 4 四种，我会在下个版本修复。

**Comment by 5mdld** [comment]
谢谢，等待修复

**Comment by L-M-Sherlock** [comment]
试一下最新版

https://github.com/open-spaced-repetition/fsrs4anki/blob/v3.7.0/fsrs4anki_optimizer.ipynb

**Comment by 5mdld** [comment]
谢谢，已可以正常使用
