### ISSUE TITLE
[Feature Request] Provide instruction for installing and running the optimizer locally

### ISSUE THREAD

**Issue by YorkZ** [open-spaced-repetition/fsrs4anki#8]
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**

I'm more efficient and productive when doing things locally compared with doing remotely. In this case, I would prefer running the optimizer locally on my system instead of having to run it in Google Colab. Being able to run the optimizer on my local system would, to the very least, eliminate from having to upload the exported deck, changing the `.apkg` file name and the time zone every time. Also, I use Linux, so I guess that setting it up on Linux would be a bit easier.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by L-M-Sherlock** [comment]
You can run it locally through jupyter notebook. I will export the requirements of dependencies.

**Comment by YorkZ** [comment]
Yep, I had Jupyter Notebook installed, but I suppose there are quite a few dependencies to install as well.

**Comment by YorkZ** [comment]
Thank you so much @L-M-Sherlock, you are so fast :+1:

**Comment by L-M-Sherlock** [comment]
You are welcome. And I am looking forward to your reply if you encounter any problems.

**Comment by YorkZ** [comment]
Just noticed in the [requiremets.txt](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/requirements.txt) file that all the packages are pinned to specific versions. Do I have to install those exact versions? Are newer versions than those pinned ones OK?

**Comment by L-M-Sherlock** [comment]
I just used pip freeze > requirements.txt. You can use other versions. But it will make replication hard if you meet some bugs caused by a specific version of dependencies.

**Comment by L-M-Sherlock** [comment]
Do you run it in local successfully? I think it is better to create a new virtual venv to run it. You can install the dependencies via `pip install -r requirements.txt`.

**Comment by YorkZ** [comment]
Yep, I agree that creating a virtualenv dedicated for it might be better. I haven't got the time to do this yet.

**Comment by L-M-Sherlock** [comment]
Thanks for your testing anyway. And waiting for your good news.
