### ISSUE TITLE
[BUG] Error when using optimizer 3.7.2

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#84]
**Describe the bug**
An error occurs when optimizer is trying to calculate suggested retention.

**To Reproduce**
1. Go to optimizer v.3.7.2
2. Run it (I use Ctrl+F9)
3. Wait until it gets to calculating suggested retention

**Screenshots**
![1](https://user-images.githubusercontent.com/83031600/197328415-b65dd6ee-c883-4b37-8816-8edaeac37868.png)

**Environment**
 - OS: Windows 10
 - Optimizer version: v3.7.2

**Comment by kuroahna** [comment]
[Duplicate issue](https://github.com/open-spaced-repetition/fsrs4anki/issues/82) Already fixed in 3.7.2

**Comment by Expertium** [comment]
> [Duplicate issue](https://github.com/open-spaced-repetition/fsrs4anki/issues/82) Already fixed in 3.7.3

Ok, thank you. I'll close this issue then.
