### ISSUE TITLE
[Feature Request] Adaption to exam learning

### ISSUE THREAD

**Issue by cryptocoinserver** [open-spaced-repetition/fsrs4anki#86]
**Which module is related to your feature request?**
Scheduler & Optimizer

Besides long-term learning like languages, Anki often is used for exams. The difference would be that an exam is only 4 weeks, 3 months or something like that in the future. In case of university, normally the maximum is one semester = 6 months. 

Is there a way to adapt your algorithm to this use case? If I understood it right, currently the use case is more long-term / language learning. This would be a real game changer, as often one is limited regarding available total learning time.

I'm thinking about something like a field in the optimizer where one can add the total available learning time additionally to the daily reviews.

Nevertheless thank you for this already incredible work!

**Comment by L-M-Sherlock** [comment]
If we can set a clear goal for the short-term learning, it is possible to design a new algorithm for optimization. I need the goal to be formulated in math.

**Comment by L-M-Sherlock** [comment]
Need more constructive advice.

**Comment by cryptocoinserver** [comment]
After giving it some thoughts, it shouldn't differ for exam learning? The memory functions the same way when learning for exams, so your formulas don't need modification. Lowering requestRetention and (maybe) lowering maximumInterval should be enough. Maybe you want to add that to the FAQ or simulate it.

**Comment by galantra** [comment]
Just an idea: The parameter that you might want to adjust is requestRetention. The FSRS4Anki Optimizer suggests the optimal target retention for you; this is the most time-saving target. However, on the date you write the exam, you might want a higher probability of recall.

What you could do is use the suggested requestRetention (e.g., 0.85) up until a short time (like, a week) before the exam. At this point you change the requestRetention value to something higher, e.g. 0.9. Then you reschedule all cards with the FSRS4Anki Helper add-on.

I imagine (haven't simulated it) that this could result in a lot more reviews shortly before the exams – however, these will be exactly those cards where your probability of recall is the lowest (i.e. 0.85, 0.86, 0.87, 0.88, and 0.89).

**Comment by L-M-Sherlock** [comment]
> What you could do is use the suggested requestRetention (e.g., 0.85) up until a short time (like, a week) before the exam. At this point you change the requestRetention value to something higher, e.g. 0.9. Then you reschedule all cards with the FSRS4Anki Helper add-on.

Thanks for your solution! It inspired me to develop the Postpone & Advance features for the Helper add-on: https://ankiweb.net/shared/info/759844606
