### ISSUE TITLE
[BUG] An error when using scheduler v.3.4.0

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#87]
**Describe the bug**
I noticed that my intervals were off, so I checked whetehr the code was running properly using AnkiWeb Inspector, and found the error in the screenshot.

**To Reproduce**
1. Copy code from https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js
2. Paste it in the window for custom code, in deck options
3. Use AnkiWeb Inspector to check for errors
4. See error at line 40

**Screenshots**
![1](https://user-images.githubusercontent.com/83031600/198071833-f14b37be-1640-43ec-89a7-9b6564678dae.png)

**Environment**
 - Anki version: ⁨2.1.55 (6944210f)⁩, Python 3.9.7 Qt 6.3.2 PyQt 6.3.1
 - OS: Windows 10
 - Scheduler version: v3.4.0

**Additional context**
Originally I thought I messed up the code while adding more `else if` statements, but it seems like this problem still remains even with the code directly copied from fsrs4anki_scheduler.js without any modifications. I also made sure that all cards have `<div id=deck deck_name="{{Deck}}"></div>` on the front side, so that's not what's causing the problem.

**Comment by L-M-Sherlock** [comment]
Could you show me the value of `deck_name`?

**Comment by Expertium** [comment]
![image](https://user-images.githubusercontent.com/83031600/198075684-9a1f97f0-2b0a-4727-bc82-45ddca61b6ed.png)
Is this what you mean?

**Comment by L-M-Sherlock** [comment]
Can you switch to the `element` tab of the inspector? I want to check the `div` element in the front.

**Comment by Expertium** [comment]
I checked some other decks and it seems like they are fine, so something is wrong either with this deck or with the cards in it.
Here's the screenshot, `deck_name` in `Elements` is correct, but when I get to line 32 and check code in the `Sources` tab it still says `deck_name=null`.
![image](https://user-images.githubusercontent.com/83031600/198083896-bedf2c6f-f293-4c81-85ad-5da2f5cebb33.png)

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/198086720-21643f8d-455c-47b8-b080-46cbd1c718b7.png)

I find that an another element also has id=deck.

**Comment by Expertium** [comment]
Ah, I guess there might be a problem with the card template.
Here's the code from the front of the card:

```
<div id="items">
	<div id="path"></div>
	<div id="deck">{{Deck}}</div>
	<div id="front">{{Front}}</div>
</div>
<script>
	deck = document.getElementById("deck");
	dName = deck.innerText.split("::")
	deck.innerHTML = dName[dName.length-1];
	document.getElementById("path").innerHTML = dName.join(" > ")
	function addTitle(id=false, title="") {
		let el = document.getElementById(id);
		if (el.innerText) {
			let t = document.createElement("div");
			t.classList.add("title");
			t.innerHTML = title;

			let b = document.createElement("div");
			b.classList.add("body");
			b.innerHTML = el.innerHTML;

			while(el.firstChild) {
				el.removeChild(el.firstChild);
			}
			el.append(t, b);
		} 
	}
	addTitle("front", "Q. ");
</script>

<div id=deck deck_name="{{Deck}}"></div>
```

**Comment by L-M-Sherlock** [comment]
Remove the line 3. It will solve the problem.
