### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs4anki#90]
**Describe the bug**

**To Reproduce**
1. Go to simulator
2.  Upload exported deck
3. start the simulator

ValueError                                Traceback (most recent call last)
[<ipython-input-4-ee361e34c1f5>](https://localhost:8080/#) in <module>
    128                 card.iat[idx, field_map['repetitions']] += recall_repetitions
    129 
--> 130                 delta_t, factor = scheduler(scheduler_name, (stability, new_stability, rating),(due-last_date, ivl, factor, rating))
    131                 card.iat[idx, field_map['factor']] = factor
    132                 card.iat[idx, field_map['due']] = day + delta_t

2 frames
[<ipython-input-4-ee361e34c1f5>](https://localhost:8080/#) in constrain_interval(stability)
     21 def fsrs4anki_scheduler(last_stability, stability, rating):
     22     def constrain_interval(stability):
---> 23         return min(max(1, round(stability * np.log(requestRetention) / np.log(0.9))), maximumInterval)
     24     if last_stability is None:
     25         return constrain_interval(stability)

ValueError: cannot convert float NaN to integer

**Screenshots**

**Environment**
 - Anki version: [e.g. 2.1.55]
 - OS: linux
 - Simulator version: 1.8.0

**Additional context**

**Comment by L-M-Sherlock** [comment]
Could you share your deck with me? I need it to reproduce the bug.

**Comment by Vilhelm-Ian** [comment]
Where can I share it

**Comment by L-M-Sherlock** [comment]
> Where can I share it

You can use zip to pack the deck file and upload it by dragging & dropping at GitHub's comment area.

**Comment by Vilhelm-Ian** [comment]
[language.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/9910746/language.zip)

**Comment by L-M-Sherlock** [comment]
Thanks, I will check it tomorrow.

**Comment by L-M-Sherlock** [comment]
The bug doesn't occur in v3.8.0. Could you update to the latest version?

**Comment by Vilhelm-Ian** [comment]
I still got the error in 3.8.0 . 

return min(max(1, round(stability * np.log(requestRetention) / np.log(0.9))), maximumInterval)

this is the line that gives the error

**Comment by L-M-Sherlock** [comment]
I run it on colab. Here is the screenshot:

![image](https://user-images.githubusercontent.com/32575846/199467176-e67256af-5b44-45b7-a7f1-be569f69b557.png)

**Comment by L-M-Sherlock** [comment]
Did you modify the code?

**Comment by Vilhelm-Ian** [comment]
I only change the name of the deck in the code. 

filename = "ALL__Learning.apkg" to filename = "language.apkg"

**Comment by L-M-Sherlock** [comment]
I am sorry but I can't reproduce this bug.
