### ISSUE TITLE
[Feature Request] fix for the bug I had

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs4anki#92]
```
notroundnumber = stability * np.log(requestRetention) / np.log(0.9)
        if math.isnan(roundnumber):
          roundnumber = 0
        return min(max(1, round(notroundnumber)), maximumInterval)
```

**Comment by L-M-Sherlock** [comment]
Could you help me test the fix version?

**Comment by Vilhelm-Ian** [comment]
```
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
[<ipython-input-4-80db87752951>](https://localhost:8080/#) in <module>
     14 # Extract the collection file or deck file to get the .anki21 database.
     15 with zipfile.ZipFile(f'./{filename}', 'r') as zip_ref:
---> 16     zip_ref.extractall('./')
     17     print("Extract successfully!")
     18 if os.path.isfile("collection.anki21b"):

2 frames
[/usr/lib/python3.7/zipfile.py](https://localhost:8080/#) in open(self, name, mode, pwd, force_zip64)
   1522             fheader = struct.unpack(structFileHeader, fheader)
   1523             if fheader[_FH_SIGNATURE] != stringFileHeader:
-> 1524                 raise BadZipFile("Bad magic number for file header")
   1525 
   1526             fname = zef_file.read(fheader[_FH_FILENAME_LENGTH])

BadZipFile: Bad magic number for file header
```

when trying with an .apkg file I got the above error


BadZipFile: File is not a zip file

when I tried witth .colpkg file I got the above error

**Comment by L-M-Sherlock** [comment]
Please use the older version of Anki to export the .colpkg file.

**Comment by L-M-Sherlock** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/32575846/201594010-5b88f963-9363-4cce-98ee-4ebae443cd49.png">

**Comment by L-M-Sherlock** [comment]
> > Please use the older version of Anki to export the .colpkg file.
> 
> 
> 
> I get the error with apkg also. And I marked that option

Could you share the apkg file with me? I assume it was caused by some new features in the latest version of Anki. By the way, which version did you use?

**Comment by Vilhelm-Ian** [comment]
[language.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/10006623/language.zip)
I am not using an official anki version I compiled it from source when you released the first version of fsrs4anki. I am happy with the algorithm I have less reviews now

**Comment by L-M-Sherlock** [comment]
So weird. I use google colab to execute the optimizer with your language deck file. It works well. I don't know what caused the error in your case. I assume the colab is the same for us?

![image](https://user-images.githubusercontent.com/32575846/201805478-28e97130-e091-40a6-9ca8-fabb7884e07b.png)

**Comment by Vilhelm-Ian** [comment]
it should. I now this shouldn't affect the result maybe because I am using linux

**Comment by Vilhelm-Ian** [comment]
I tried with a different browser it worked. Look how few reviews I will have with fsrs4anki 
![image](https://user-images.githubusercontent.com/81630959/201940438-719f4814-253d-4bb9-903f-a17fc5aaee90.png)

**Comment by L-M-Sherlock** [comment]
> I tried with a different browser it worked. Look how few reviews I will have with fsrs4anki 

Good news! And the figure shows that FSRS reduces the reviews nearly 30% than Anki.

**Comment by tjbrn** [comment]
Had same error. Tried with a different browser and worked.

**Comment by L-M-Sherlock** [comment]
> Had same error.

Which browser did you use?

**Comment by tjbrn** [comment]
> > Had same error.
> 
> Which browser did you use?

FIrefox. Maybe some addon is the source of the error.
