### ISSUE TITLE
Compatibility - autoLapseNewInterval?

### ISSUE THREAD

**Issue by onebigchildren** [open-spaced-repetition/fsrs4anki#96]
Hi, is this compatible with autoLapseNewInterval?

https://ankiweb.net/shared/info/372281481

**Comment by L-M-Sherlock** [comment]
I tested it. This add-on will modify the `New Interval` in deck options, changing the post-lapse interval. But it happens before FSRS work. So the final new interval is given by FSRS.

**Comment by L-M-Sherlock** [comment]
So FSRS overrides the autoLapseNewInterval add-on. I record it [here](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Compatibility).
